// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit call/emit/subscribe.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// Low-level publish/reply-topic helpers are intentionally not generated; use
// the generic SDK protocol primitives directly when testing transport behavior.
//
// Regenerate with cmd/sdkgen from this repository.
package tracingmsg

import (
	"context"

	bkmodule "github.com/brainlet/brainkit/module"
	"github.com/brainlet/brainkit/sdk"
)

// CallTraceGet issues a synchronous request-response Call for TraceGetMsg.
func CallTraceGet(rt sdk.CallerRuntime, ctx context.Context, msg TraceGetMsg, opts ...sdk.CallOption) (TraceGetResp, error) {
	return sdk.Call[TraceGetMsg, TraceGetResp](rt, ctx, msg, opts...)
}

// CallTraceGetWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallTraceGetWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg TraceGetMsg, opts ...sdk.CallOption) (TraceGetResp, error) {
	return sdk.CallWithCaller[TraceGetMsg, TraceGetResp](caller, ctx, msg, opts...)
}

// CallTraceList issues a synchronous request-response Call for TraceListMsg.
func CallTraceList(rt sdk.CallerRuntime, ctx context.Context, msg TraceListMsg, opts ...sdk.CallOption) (TraceListResp, error) {
	return sdk.Call[TraceListMsg, TraceListResp](rt, ctx, msg, opts...)
}

// CallTraceListWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallTraceListWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg TraceListMsg, opts ...sdk.CallOption) (TraceListResp, error) {
	return sdk.CallWithCaller[TraceListMsg, TraceListResp](caller, ctx, msg, opts...)
}

