// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit publish/subscribe/call/emit.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// The underlying generic publish/call patterns are unchanged. These wrappers
// just add type safety.
//
// Regenerate with cmd/sdkgen from this repository.
package tracingmsg

import (
	"context"

	"github.com/brainlet/brainkit/sdk"
)

// PublishTraceGet publishes a TraceGetMsg and returns routing info for the response.
func PublishTraceGet(rt sdk.Runtime, ctx context.Context, msg TraceGetMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeTraceGetResp subscribes to the response topic for a TraceGetMsg command.
func SubscribeTraceGetResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(TraceGetResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[TraceGetResp](rt, ctx, topic, handler)
}

// CallTraceGet issues a synchronous request-response Call for TraceGetMsg.
func CallTraceGet(rt sdk.CallerRuntime, ctx context.Context, msg TraceGetMsg, opts ...sdk.CallOption) (TraceGetResp, error) {
	return sdk.Call[TraceGetMsg, TraceGetResp](rt, ctx, msg, opts...)
}

// PublishTraceList publishes a TraceListMsg and returns routing info for the response.
func PublishTraceList(rt sdk.Runtime, ctx context.Context, msg TraceListMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeTraceListResp subscribes to the response topic for a TraceListMsg command.
func SubscribeTraceListResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(TraceListResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[TraceListResp](rt, ctx, topic, handler)
}

// CallTraceList issues a synchronous request-response Call for TraceListMsg.
func CallTraceList(rt sdk.CallerRuntime, ctx context.Context, msg TraceListMsg, opts ...sdk.CallOption) (TraceListResp, error) {
	return sdk.Call[TraceListMsg, TraceListResp](rt, ctx, msg, opts...)
}

