package common

// BuiltinNames contains compiler-generated and standard library names.
// These string constants are used by the compiler and builtins packages.
// Ported from: assemblyscript/src/builtins.ts BuiltinNames namespace (lines 122-774).

const (
	// Compiler-generated names.
	BuiltinNameStart              = "~start"
	BuiltinNameStarted            = "~started"
	BuiltinNameArgumentsLength    = "~argumentsLength"
	BuiltinNameSetArgumentsLength = "~setArgumentsLength"

	// std/builtins.ts
	BuiltinNameAbort = "~lib/builtins/abort"
	BuiltinNameTrace = "~lib/builtins/trace"
	BuiltinNameSeed  = "~lib/builtins/seed"

	BuiltinNameIsBoolean   = "~lib/builtins/isBoolean"
	BuiltinNameIsInteger   = "~lib/builtins/isInteger"
	BuiltinNameIsSigned    = "~lib/builtins/isSigned"
	BuiltinNameIsFloat     = "~lib/builtins/isFloat"
	BuiltinNameIsVector    = "~lib/builtins/isVector"
	BuiltinNameIsReference = "~lib/builtins/isReference"
	BuiltinNameIsString    = "~lib/builtins/isString"
	BuiltinNameIsArray     = "~lib/builtins/isArray"
	BuiltinNameIsArrayLike = "~lib/builtins/isArrayLike"
	BuiltinNameIsFunction  = "~lib/builtins/isFunction"
	BuiltinNameIsNullable  = "~lib/builtins/isNullable"
	BuiltinNameIsDefined   = "~lib/builtins/isDefined"
	BuiltinNameIsConstant  = "~lib/builtins/isConstant"
	BuiltinNameIsManaged   = "~lib/builtins/isManaged"
	BuiltinNameIsVoid      = "~lib/builtins/isVoid"

	BuiltinNameAdd    = "~lib/builtins/add"
	BuiltinNameSub    = "~lib/builtins/sub"
	BuiltinNameMul    = "~lib/builtins/mul"
	BuiltinNameDiv    = "~lib/builtins/div"
	BuiltinNameClz    = "~lib/builtins/clz"
	BuiltinNameCtz    = "~lib/builtins/ctz"
	BuiltinNamePopcnt = "~lib/builtins/popcnt"
	BuiltinNameRotl   = "~lib/builtins/rotl"
	BuiltinNameRotr   = "~lib/builtins/rotr"
	BuiltinNameAbs    = "~lib/builtins/abs"
	BuiltinNameMax    = "~lib/builtins/max"
	BuiltinNameMin    = "~lib/builtins/min"
	BuiltinNameCeil   = "~lib/builtins/ceil"
	BuiltinNameFloor  = "~lib/builtins/floor"

	BuiltinNameCopysign    = "~lib/builtins/copysign"
	BuiltinNameNearest     = "~lib/builtins/nearest"
	BuiltinNameReinterpret = "~lib/builtins/reinterpret"
	BuiltinNameSqrt        = "~lib/builtins/sqrt"
	BuiltinNameTrunc       = "~lib/builtins/trunc"
	BuiltinNameEq          = "~lib/builtins/eq"
	BuiltinNameNe          = "~lib/builtins/ne"
	BuiltinNameRem         = "~lib/builtins/rem"

	BuiltinNameLoad  = "~lib/builtins/load"
	BuiltinNameStore = "~lib/builtins/store"

	BuiltinNameAtomicLoad    = "~lib/builtins/atomic.load"
	BuiltinNameAtomicStore   = "~lib/builtins/atomic.store"
	BuiltinNameAtomicAdd     = "~lib/builtins/atomic.add"
	BuiltinNameAtomicSub     = "~lib/builtins/atomic.sub"
	BuiltinNameAtomicAnd     = "~lib/builtins/atomic.and"
	BuiltinNameAtomicOr      = "~lib/builtins/atomic.or"
	BuiltinNameAtomicXor     = "~lib/builtins/atomic.xor"
	BuiltinNameAtomicXchg    = "~lib/builtins/atomic.xchg"
	BuiltinNameAtomicCmpxchg = "~lib/builtins/atomic.cmpxchg"
	BuiltinNameAtomicWait    = "~lib/builtins/atomic.wait"
	BuiltinNameAtomicNotify  = "~lib/builtins/atomic.notify"
	BuiltinNameAtomicFence   = "~lib/builtins/atomic.fence"

	BuiltinNameSizeof       = "~lib/builtins/sizeof"
	BuiltinNameAlignof      = "~lib/builtins/alignof"
	BuiltinNameOffsetof     = "~lib/builtins/offsetof"
	BuiltinNameNameof       = "~lib/builtins/nameof"
	BuiltinNameLengthof     = "~lib/builtins/lengthof"
	BuiltinNameSelect       = "~lib/builtins/select"
	BuiltinNameUnreachable  = "~lib/builtins/unreachable"
	BuiltinNameChangetype   = "~lib/builtins/changetype"
	BuiltinNameAssert       = "~lib/builtins/assert"
	BuiltinNameCallIndirect = "~lib/builtins/call_indirect"
	BuiltinNameUnchecked    = "~lib/builtins/unchecked"
	BuiltinNameInlineAlways = "~lib/builtins/inline.always"
	BuiltinNameInstantiate  = "~lib/builtins/instantiate"
	BuiltinNameIdof         = "~lib/builtins/idof"

	// Primitive type builtins.
	BuiltinNameI8    = "~lib/builtins/i8"
	BuiltinNameI16   = "~lib/builtins/i16"
	BuiltinNameI32   = "~lib/builtins/i32"
	BuiltinNameI64   = "~lib/builtins/i64"
	BuiltinNameIsize = "~lib/builtins/isize"
	BuiltinNameU8    = "~lib/builtins/u8"
	BuiltinNameU16   = "~lib/builtins/u16"
	BuiltinNameU32   = "~lib/builtins/u32"
	BuiltinNameU64   = "~lib/builtins/u64"
	BuiltinNameUsize = "~lib/builtins/usize"
	BuiltinNameBool  = "~lib/builtins/bool"
	BuiltinNameF32   = "~lib/builtins/f32"
	BuiltinNameF64   = "~lib/builtins/f64"
	BuiltinNameV128  = "~lib/builtins/v128"

	// i32/i64 bit operations.
	BuiltinNameI32Clz    = "~lib/builtins/i32.clz"
	BuiltinNameI64Clz    = "~lib/builtins/i64.clz"
	BuiltinNameI32Ctz    = "~lib/builtins/i32.ctz"
	BuiltinNameI64Ctz    = "~lib/builtins/i64.ctz"
	BuiltinNameI32Popcnt = "~lib/builtins/i32.popcnt"
	BuiltinNameI64Popcnt = "~lib/builtins/i64.popcnt"
	BuiltinNameI32Rotl   = "~lib/builtins/i32.rotl"
	BuiltinNameI64Rotl   = "~lib/builtins/i64.rotl"
	BuiltinNameI32Rotr   = "~lib/builtins/i32.rotr"
	BuiltinNameI64Rotr   = "~lib/builtins/i64.rotr"

	// f32/f64 math operations.
	BuiltinNameF32Abs             = "~lib/builtins/f32.abs"
	BuiltinNameF64Abs             = "~lib/builtins/f64.abs"
	BuiltinNameF32Max             = "~lib/builtins/f32.max"
	BuiltinNameF64Max             = "~lib/builtins/f64.max"
	BuiltinNameF32Min             = "~lib/builtins/f32.min"
	BuiltinNameF64Min             = "~lib/builtins/f64.min"
	BuiltinNameF32Ceil            = "~lib/builtins/f32.ceil"
	BuiltinNameF64Ceil            = "~lib/builtins/f64.ceil"
	BuiltinNameF32Floor           = "~lib/builtins/f32.floor"
	BuiltinNameF64Floor           = "~lib/builtins/f64.floor"
	BuiltinNameF32Copysign        = "~lib/builtins/f32.copysign"
	BuiltinNameF64Copysign        = "~lib/builtins/f64.copysign"
	BuiltinNameF32Nearest         = "~lib/builtins/f32.nearest"
	BuiltinNameF64Nearest         = "~lib/builtins/f64.nearest"
	BuiltinNameI32ReinterpretF32  = "~lib/builtins/i32.reinterpret_f32"
	BuiltinNameI64ReinterpretF64  = "~lib/builtins/i64.reinterpret_f64"
	BuiltinNameF32ReinterpretI32  = "~lib/builtins/f32.reinterpret_i32"
	BuiltinNameF64ReinterpretI64  = "~lib/builtins/f64.reinterpret_i64"
	BuiltinNameF32Sqrt            = "~lib/builtins/f32.sqrt"
	BuiltinNameF64Sqrt            = "~lib/builtins/f64.sqrt"
	BuiltinNameF32Trunc           = "~lib/builtins/f32.trunc"
	BuiltinNameF64Trunc           = "~lib/builtins/f64.trunc"

	// i32/i64/f32/f64 arithmetic operations.
	BuiltinNameI32Add  = "~lib/builtins/i32.add"
	BuiltinNameI64Add  = "~lib/builtins/i64.add"
	BuiltinNameF32Add  = "~lib/builtins/f32.add"
	BuiltinNameF64Add  = "~lib/builtins/f64.add"
	BuiltinNameI32Sub  = "~lib/builtins/i32.sub"
	BuiltinNameI64Sub  = "~lib/builtins/i64.sub"
	BuiltinNameF32Sub  = "~lib/builtins/f32.sub"
	BuiltinNameF64Sub  = "~lib/builtins/f64.sub"
	BuiltinNameI32Mul  = "~lib/builtins/i32.mul"
	BuiltinNameI64Mul  = "~lib/builtins/i64.mul"
	BuiltinNameF32Mul  = "~lib/builtins/f32.mul"
	BuiltinNameF64Mul  = "~lib/builtins/f64.mul"
	BuiltinNameI32DivS = "~lib/builtins/i32.div_s"
	BuiltinNameI32DivU = "~lib/builtins/i32.div_u"
	BuiltinNameI64DivS = "~lib/builtins/i64.div_s"
	BuiltinNameI64DivU = "~lib/builtins/i64.div_u"
	BuiltinNameF32Div  = "~lib/builtins/f32.div"
	BuiltinNameF64Div  = "~lib/builtins/f64.div"

	// i32/i64/f32/f64 comparison operations.
	BuiltinNameI32Eq = "~lib/builtins/i32.eq"
	BuiltinNameI64Eq = "~lib/builtins/i64.eq"
	BuiltinNameF32Eq = "~lib/builtins/f32.eq"
	BuiltinNameF64Eq = "~lib/builtins/f64.eq"
	BuiltinNameI32Ne = "~lib/builtins/i32.ne"
	BuiltinNameI64Ne = "~lib/builtins/i64.ne"
	BuiltinNameF32Ne = "~lib/builtins/f32.ne"
	BuiltinNameF64Ne = "~lib/builtins/f64.ne"

	// i32/i64 remainder operations.
	BuiltinNameI32RemS = "~lib/builtins/i32.rem_s"
	BuiltinNameI32RemU = "~lib/builtins/i32.rem_u"
	BuiltinNameI64RemS = "~lib/builtins/i64.rem_s"
	BuiltinNameI64RemU = "~lib/builtins/i64.rem_u"

	// i32/i64/f32/f64 load operations.
	BuiltinNameI32Load8S  = "~lib/builtins/i32.load8_s"
	BuiltinNameI32Load8U  = "~lib/builtins/i32.load8_u"
	BuiltinNameI32Load16S = "~lib/builtins/i32.load16_s"
	BuiltinNameI32Load16U = "~lib/builtins/i32.load16_u"
	BuiltinNameI32Load    = "~lib/builtins/i32.load"
	BuiltinNameI64Load8S  = "~lib/builtins/i64.load8_s"
	BuiltinNameI64Load8U  = "~lib/builtins/i64.load8_u"
	BuiltinNameI64Load16S = "~lib/builtins/i64.load16_s"
	BuiltinNameI64Load16U = "~lib/builtins/i64.load16_u"
	BuiltinNameI64Load32S = "~lib/builtins/i64.load32_s"
	BuiltinNameI64Load32U = "~lib/builtins/i64.load32_u"
	BuiltinNameI64Load    = "~lib/builtins/i64.load"
	BuiltinNameF32Load    = "~lib/builtins/f32.load"
	BuiltinNameF64Load    = "~lib/builtins/f64.load"

	// i32/i64/f32/f64 store operations.
	BuiltinNameI32Store8  = "~lib/builtins/i32.store8"
	BuiltinNameI32Store16 = "~lib/builtins/i32.store16"
	BuiltinNameI32Store   = "~lib/builtins/i32.store"
	BuiltinNameI64Store8  = "~lib/builtins/i64.store8"
	BuiltinNameI64Store16 = "~lib/builtins/i64.store16"
	BuiltinNameI64Store32 = "~lib/builtins/i64.store32"
	BuiltinNameI64Store   = "~lib/builtins/i64.store"
	BuiltinNameF32Store   = "~lib/builtins/f32.store"
	BuiltinNameF64Store   = "~lib/builtins/f64.store"

	// i32/i64 atomic load operations.
	BuiltinNameI32AtomicLoad8U  = "~lib/builtins/i32.atomic.load8_u"
	BuiltinNameI32AtomicLoad16U = "~lib/builtins/i32.atomic.load16_u"
	BuiltinNameI32AtomicLoad    = "~lib/builtins/i32.atomic.load"
	BuiltinNameI64AtomicLoad8U  = "~lib/builtins/i64.atomic.load8_u"
	BuiltinNameI64AtomicLoad16U = "~lib/builtins/i64.atomic.load16_u"
	BuiltinNameI64AtomicLoad32U = "~lib/builtins/i64.atomic.load32_u"
	BuiltinNameI64AtomicLoad    = "~lib/builtins/i64.atomic.load"

	// i32/i64 atomic store operations.
	BuiltinNameI32AtomicStore8  = "~lib/builtins/i32.atomic.store8"
	BuiltinNameI32AtomicStore16 = "~lib/builtins/i32.atomic.store16"
	BuiltinNameI32AtomicStore   = "~lib/builtins/i32.atomic.store"
	BuiltinNameI64AtomicStore8  = "~lib/builtins/i64.atomic.store8"
	BuiltinNameI64AtomicStore16 = "~lib/builtins/i64.atomic.store16"
	BuiltinNameI64AtomicStore32 = "~lib/builtins/i64.atomic.store32"
	BuiltinNameI64AtomicStore   = "~lib/builtins/i64.atomic.store"

	// i32/i64 atomic RMW add operations.
	BuiltinNameI32AtomicRmw8AddU  = "~lib/builtins/i32.atomic.rmw8.add_u"
	BuiltinNameI32AtomicRmw16AddU = "~lib/builtins/i32.atomic.rmw16.add_u"
	BuiltinNameI32AtomicRmwAdd    = "~lib/builtins/i32.atomic.rmw.add"
	BuiltinNameI64AtomicRmw8AddU  = "~lib/builtins/i64.atomic.rmw8.add_u"
	BuiltinNameI64AtomicRmw16AddU = "~lib/builtins/i64.atomic.rmw16.add_u"
	BuiltinNameI64AtomicRmw32AddU = "~lib/builtins/i64.atomic.rmw32.add_u"
	BuiltinNameI64AtomicRmwAdd    = "~lib/builtins/i64.atomic.rmw.add"

	// i32/i64 atomic RMW sub operations.
	BuiltinNameI32AtomicRmw8SubU  = "~lib/builtins/i32.atomic.rmw8.sub_u"
	BuiltinNameI32AtomicRmw16SubU = "~lib/builtins/i32.atomic.rmw16.sub_u"
	BuiltinNameI32AtomicRmwSub    = "~lib/builtins/i32.atomic.rmw.sub"
	BuiltinNameI64AtomicRmw8SubU  = "~lib/builtins/i64.atomic.rmw8.sub_u"
	BuiltinNameI64AtomicRmw16SubU = "~lib/builtins/i64.atomic.rmw16.sub_u"
	BuiltinNameI64AtomicRmw32SubU = "~lib/builtins/i64.atomic.rmw32.sub_u"
	BuiltinNameI64AtomicRmwSub    = "~lib/builtins/i64.atomic.rmw.sub"

	// i32/i64 atomic RMW and operations.
	BuiltinNameI32AtomicRmw8AndU  = "~lib/builtins/i32.atomic.rmw8.and_u"
	BuiltinNameI32AtomicRmw16AndU = "~lib/builtins/i32.atomic.rmw16.and_u"
	BuiltinNameI32AtomicRmwAnd    = "~lib/builtins/i32.atomic.rmw.and"
	BuiltinNameI64AtomicRmw8AndU  = "~lib/builtins/i64.atomic.rmw8.and_u"
	BuiltinNameI64AtomicRmw16AndU = "~lib/builtins/i64.atomic.rmw16.and_u"
	BuiltinNameI64AtomicRmw32AndU = "~lib/builtins/i64.atomic.rmw32.and_u"
	BuiltinNameI64AtomicRmwAnd    = "~lib/builtins/i64.atomic.rmw.and"

	// i32/i64 atomic RMW or operations.
	BuiltinNameI32AtomicRmw8OrU  = "~lib/builtins/i32.atomic.rmw8.or_u"
	BuiltinNameI32AtomicRmw16OrU = "~lib/builtins/i32.atomic.rmw16.or_u"
	BuiltinNameI32AtomicRmwOr    = "~lib/builtins/i32.atomic.rmw.or"
	BuiltinNameI64AtomicRmw8OrU  = "~lib/builtins/i64.atomic.rmw8.or_u"
	BuiltinNameI64AtomicRmw16OrU = "~lib/builtins/i64.atomic.rmw16.or_u"
	BuiltinNameI64AtomicRmw32OrU = "~lib/builtins/i64.atomic.rmw32.or_u"
	BuiltinNameI64AtomicRmwOr    = "~lib/builtins/i64.atomic.rmw.or"

	// i32/i64 atomic RMW xor operations.
	BuiltinNameI32AtomicRmw8XorU  = "~lib/builtins/i32.atomic.rmw8.xor_u"
	BuiltinNameI32AtomicRmw16XorU = "~lib/builtins/i32.atomic.rmw16.xor_u"
	BuiltinNameI32AtomicRmwXor    = "~lib/builtins/i32.atomic.rmw.xor"
	BuiltinNameI64AtomicRmw8XorU  = "~lib/builtins/i64.atomic.rmw8.xor_u"
	BuiltinNameI64AtomicRmw16XorU = "~lib/builtins/i64.atomic.rmw16.xor_u"
	BuiltinNameI64AtomicRmw32XorU = "~lib/builtins/i64.atomic.rmw32.xor_u"
	BuiltinNameI64AtomicRmwXor    = "~lib/builtins/i64.atomic.rmw.xor"

	// i32/i64 atomic RMW xchg operations.
	BuiltinNameI32AtomicRmw8XchgU  = "~lib/builtins/i32.atomic.rmw8.xchg_u"
	BuiltinNameI32AtomicRmw16XchgU = "~lib/builtins/i32.atomic.rmw16.xchg_u"
	BuiltinNameI32AtomicRmwXchg    = "~lib/builtins/i32.atomic.rmw.xchg"
	BuiltinNameI64AtomicRmw8XchgU  = "~lib/builtins/i64.atomic.rmw8.xchg_u"
	BuiltinNameI64AtomicRmw16XchgU = "~lib/builtins/i64.atomic.rmw16.xchg_u"
	BuiltinNameI64AtomicRmw32XchgU = "~lib/builtins/i64.atomic.rmw32.xchg_u"
	BuiltinNameI64AtomicRmwXchg    = "~lib/builtins/i64.atomic.rmw.xchg"

	// i32/i64 atomic RMW cmpxchg operations.
	BuiltinNameI32AtomicRmw8CmpxchgU  = "~lib/builtins/i32.atomic.rmw8.cmpxchg_u"
	BuiltinNameI32AtomicRmw16CmpxchgU = "~lib/builtins/i32.atomic.rmw16.cmpxchg_u"
	BuiltinNameI32AtomicRmwCmpxchg    = "~lib/builtins/i32.atomic.rmw.cmpxchg"
	BuiltinNameI64AtomicRmw8CmpxchgU  = "~lib/builtins/i64.atomic.rmw8.cmpxchg_u"
	BuiltinNameI64AtomicRmw16CmpxchgU = "~lib/builtins/i64.atomic.rmw16.cmpxchg_u"
	BuiltinNameI64AtomicRmw32CmpxchgU = "~lib/builtins/i64.atomic.rmw32.cmpxchg_u"
	BuiltinNameI64AtomicRmwCmpxchg    = "~lib/builtins/i64.atomic.rmw.cmpxchg"

	// Memory atomic wait operations.
	BuiltinNameMemoryAtomicWait32 = "~lib/memory/memory.atomic.wait32"
	BuiltinNameMemoryAtomicWait64 = "~lib/memory/memory.atomic.wait64"

	// v128 generic operations.
	BuiltinNameV128Splat           = "~lib/builtins/v128.splat"
	BuiltinNameV128ExtractLane     = "~lib/builtins/v128.extract_lane"
	BuiltinNameV128ReplaceLane     = "~lib/builtins/v128.replace_lane"
	BuiltinNameV128Shuffle         = "~lib/builtins/v128.shuffle"
	BuiltinNameV128Swizzle         = "~lib/builtins/v128.swizzle"
	BuiltinNameV128LoadSplat       = "~lib/builtins/v128.load_splat"
	BuiltinNameV128LoadExt         = "~lib/builtins/v128.load_ext"
	BuiltinNameV128LoadZero        = "~lib/builtins/v128.load_zero"
	BuiltinNameV128LoadLane        = "~lib/builtins/v128.load_lane"
	BuiltinNameV128StoreLane       = "~lib/builtins/v128.store_lane"
	BuiltinNameV128Load            = "~lib/builtins/v128.load"
	BuiltinNameV128Load8x8S       = "~lib/builtins/v128.load8x8_s"
	BuiltinNameV128Load8x8U       = "~lib/builtins/v128.load8x8_u"
	BuiltinNameV128Load16x4S      = "~lib/builtins/v128.load16x4_s"
	BuiltinNameV128Load16x4U      = "~lib/builtins/v128.load16x4_u"
	BuiltinNameV128Load32x2S      = "~lib/builtins/v128.load32x2_s"
	BuiltinNameV128Load32x2U      = "~lib/builtins/v128.load32x2_u"
	BuiltinNameV128Load8Splat     = "~lib/builtins/v128.load8_splat"
	BuiltinNameV128Load16Splat    = "~lib/builtins/v128.load16_splat"
	BuiltinNameV128Load32Splat    = "~lib/builtins/v128.load32_splat"
	BuiltinNameV128Load64Splat    = "~lib/builtins/v128.load64_splat"
	BuiltinNameV128Load32Zero     = "~lib/builtins/v128.load32_zero"
	BuiltinNameV128Load64Zero     = "~lib/builtins/v128.load64_zero"
	BuiltinNameV128Load8Lane      = "~lib/builtins/v128.load8_lane"
	BuiltinNameV128Load16Lane     = "~lib/builtins/v128.load16_lane"
	BuiltinNameV128Load32Lane     = "~lib/builtins/v128.load32_lane"
	BuiltinNameV128Load64Lane     = "~lib/builtins/v128.load64_lane"
	BuiltinNameV128Store8Lane     = "~lib/builtins/v128.store8_lane"
	BuiltinNameV128Store16Lane    = "~lib/builtins/v128.store16_lane"
	BuiltinNameV128Store32Lane    = "~lib/builtins/v128.store32_lane"
	BuiltinNameV128Store64Lane    = "~lib/builtins/v128.store64_lane"
	BuiltinNameV128Store           = "~lib/builtins/v128.store"
	BuiltinNameV128Add             = "~lib/builtins/v128.add"
	BuiltinNameV128Sub             = "~lib/builtins/v128.sub"
	BuiltinNameV128Mul             = "~lib/builtins/v128.mul"
	BuiltinNameV128DivOp           = "~lib/builtins/v128.div"
	BuiltinNameV128Neg             = "~lib/builtins/v128.neg"
	BuiltinNameV128AddSat          = "~lib/builtins/v128.add_sat"
	BuiltinNameV128SubSat          = "~lib/builtins/v128.sub_sat"
	BuiltinNameV128Shl             = "~lib/builtins/v128.shl"
	BuiltinNameV128Shr             = "~lib/builtins/v128.shr"
	BuiltinNameV128And             = "~lib/builtins/v128.and"
	BuiltinNameV128Or              = "~lib/builtins/v128.or"
	BuiltinNameV128Xor             = "~lib/builtins/v128.xor"
	BuiltinNameV128Andnot          = "~lib/builtins/v128.andnot"
	BuiltinNameV128Not             = "~lib/builtins/v128.not"
	BuiltinNameV128Bitselect       = "~lib/builtins/v128.bitselect"
	BuiltinNameV128AnyTrue         = "~lib/builtins/v128.any_true"
	BuiltinNameV128AllTrue         = "~lib/builtins/v128.all_true"
	BuiltinNameV128Bitmask         = "~lib/builtins/v128.bitmask"
	BuiltinNameV128PopcntOp        = "~lib/builtins/v128.popcnt"
	BuiltinNameV128MinOp           = "~lib/builtins/v128.min"
	BuiltinNameV128MaxOp           = "~lib/builtins/v128.max"
	BuiltinNameV128Pmin            = "~lib/builtins/v128.pmin"
	BuiltinNameV128Pmax            = "~lib/builtins/v128.pmax"
	BuiltinNameV128Dot             = "~lib/builtins/v128.dot"
	BuiltinNameV128Avgr            = "~lib/builtins/v128.avgr"
	BuiltinNameV128AbsOp           = "~lib/builtins/v128.abs"
	BuiltinNameV128SqrtOp          = "~lib/builtins/v128.sqrt"
	BuiltinNameV128CeilOp          = "~lib/builtins/v128.ceil"
	BuiltinNameV128FloorOp         = "~lib/builtins/v128.floor"
	BuiltinNameV128TruncOp         = "~lib/builtins/v128.trunc"
	BuiltinNameV128NearestOp       = "~lib/builtins/v128.nearest"
	BuiltinNameV128EqOp            = "~lib/builtins/v128.eq"
	BuiltinNameV128NeOp            = "~lib/builtins/v128.ne"
	BuiltinNameV128Lt              = "~lib/builtins/v128.lt"
	BuiltinNameV128Le              = "~lib/builtins/v128.le"
	BuiltinNameV128Gt              = "~lib/builtins/v128.gt"
	BuiltinNameV128Ge              = "~lib/builtins/v128.ge"
	BuiltinNameV128Convert         = "~lib/builtins/v128.convert"
	BuiltinNameV128ConvertLow      = "~lib/builtins/v128.convert_low"
	BuiltinNameV128TruncSat        = "~lib/builtins/v128.trunc_sat"
	BuiltinNameV128TruncSatZero    = "~lib/builtins/v128.trunc_sat_zero"
	BuiltinNameV128Narrow          = "~lib/builtins/v128.narrow"
	BuiltinNameV128ExtendLow       = "~lib/builtins/v128.extend_low"
	BuiltinNameV128ExtendHigh      = "~lib/builtins/v128.extend_high"
	BuiltinNameV128ExtaddPairwise  = "~lib/builtins/v128.extadd_pairwise"
	BuiltinNameV128DemoteZero      = "~lib/builtins/v128.demote_zero"
	BuiltinNameV128PromoteLow      = "~lib/builtins/v128.promote_low"
	BuiltinNameV128Q15mulrSat      = "~lib/builtins/v128.q15mulr_sat"
	BuiltinNameV128ExtmulLow       = "~lib/builtins/v128.extmul_low"
	BuiltinNameV128ExtmulHigh      = "~lib/builtins/v128.extmul_high"
	BuiltinNameV128RelaxedSwizzle  = "~lib/builtins/v128.relaxed_swizzle"
	BuiltinNameV128RelaxedTrunc    = "~lib/builtins/v128.relaxed_trunc"
	BuiltinNameV128RelaxedTruncZero = "~lib/builtins/v128.relaxed_trunc_zero"
	BuiltinNameV128RelaxedMadd     = "~lib/builtins/v128.relaxed_madd"
	BuiltinNameV128RelaxedNmadd    = "~lib/builtins/v128.relaxed_nmadd"
	BuiltinNameV128RelaxedLaneselect = "~lib/builtins/v128.relaxed_laneselect"
	BuiltinNameV128RelaxedMin      = "~lib/builtins/v128.relaxed_min"
	BuiltinNameV128RelaxedMax      = "~lib/builtins/v128.relaxed_max"
	BuiltinNameV128RelaxedQ15mulr  = "~lib/builtins/v128.relaxed_q15mulr"
	BuiltinNameV128RelaxedDot      = "~lib/builtins/v128.relaxed_dot"
	BuiltinNameV128RelaxedDotAdd   = "~lib/builtins/v128.relaxed_dot_add"

	// SIMD lane type namespaces.
	BuiltinNameI8x16 = "~lib/builtins/i8x16"
	BuiltinNameI16x8 = "~lib/builtins/i16x8"
	BuiltinNameI32x4 = "~lib/builtins/i32x4"
	BuiltinNameI64x2 = "~lib/builtins/i64x2"
	BuiltinNameF32x4 = "~lib/builtins/f32x4"
	BuiltinNameF64x2 = "~lib/builtins/f64x2"

	// i8x16 operations.
	BuiltinNameI8x16Splat         = "~lib/builtins/i8x16.splat"
	BuiltinNameI8x16ExtractLaneS  = "~lib/builtins/i8x16.extract_lane_s"
	BuiltinNameI8x16ExtractLaneU  = "~lib/builtins/i8x16.extract_lane_u"
	BuiltinNameI8x16ReplaceLane   = "~lib/builtins/i8x16.replace_lane"
	BuiltinNameI8x16Add           = "~lib/builtins/i8x16.add"
	BuiltinNameI8x16Sub           = "~lib/builtins/i8x16.sub"
	BuiltinNameI8x16Mul           = "~lib/builtins/i8x16.mul"
	BuiltinNameI8x16MinS          = "~lib/builtins/i8x16.min_s"
	BuiltinNameI8x16MinU          = "~lib/builtins/i8x16.min_u"
	BuiltinNameI8x16MaxS          = "~lib/builtins/i8x16.max_s"
	BuiltinNameI8x16MaxU          = "~lib/builtins/i8x16.max_u"
	BuiltinNameI8x16AvgrU         = "~lib/builtins/i8x16.avgr_u"
	BuiltinNameI8x16Abs           = "~lib/builtins/i8x16.abs"
	BuiltinNameI8x16Neg           = "~lib/builtins/i8x16.neg"
	BuiltinNameI8x16AddSatS       = "~lib/builtins/i8x16.add_sat_s"
	BuiltinNameI8x16AddSatU       = "~lib/builtins/i8x16.add_sat_u"
	BuiltinNameI8x16SubSatS       = "~lib/builtins/i8x16.sub_sat_s"
	BuiltinNameI8x16SubSatU       = "~lib/builtins/i8x16.sub_sat_u"
	BuiltinNameI8x16Shl           = "~lib/builtins/i8x16.shl"
	BuiltinNameI8x16ShrS          = "~lib/builtins/i8x16.shr_s"
	BuiltinNameI8x16ShrU          = "~lib/builtins/i8x16.shr_u"
	BuiltinNameI8x16AllTrue       = "~lib/builtins/i8x16.all_true"
	BuiltinNameI8x16Bitmask       = "~lib/builtins/i8x16.bitmask"
	BuiltinNameI8x16Popcnt        = "~lib/builtins/i8x16.popcnt"
	BuiltinNameI8x16Eq            = "~lib/builtins/i8x16.eq"
	BuiltinNameI8x16Ne            = "~lib/builtins/i8x16.ne"
	BuiltinNameI8x16LtS           = "~lib/builtins/i8x16.lt_s"
	BuiltinNameI8x16LtU           = "~lib/builtins/i8x16.lt_u"
	BuiltinNameI8x16LeS           = "~lib/builtins/i8x16.le_s"
	BuiltinNameI8x16LeU           = "~lib/builtins/i8x16.le_u"
	BuiltinNameI8x16GtS           = "~lib/builtins/i8x16.gt_s"
	BuiltinNameI8x16GtU           = "~lib/builtins/i8x16.gt_u"
	BuiltinNameI8x16GeS           = "~lib/builtins/i8x16.ge_s"
	BuiltinNameI8x16GeU           = "~lib/builtins/i8x16.ge_u"
	BuiltinNameI8x16NarrowI16x8S  = "~lib/builtins/i8x16.narrow_i16x8_s"
	BuiltinNameI8x16NarrowI16x8U  = "~lib/builtins/i8x16.narrow_i16x8_u"
	BuiltinNameI8x16Shuffle       = "~lib/builtins/i8x16.shuffle"
	BuiltinNameI8x16SwizzleOp     = "~lib/builtins/i8x16.swizzle"

	// i16x8 operations.
	BuiltinNameI16x8Splat               = "~lib/builtins/i16x8.splat"
	BuiltinNameI16x8ExtractLaneS        = "~lib/builtins/i16x8.extract_lane_s"
	BuiltinNameI16x8ExtractLaneU        = "~lib/builtins/i16x8.extract_lane_u"
	BuiltinNameI16x8ReplaceLane         = "~lib/builtins/i16x8.replace_lane"
	BuiltinNameI16x8Add                 = "~lib/builtins/i16x8.add"
	BuiltinNameI16x8Sub                 = "~lib/builtins/i16x8.sub"
	BuiltinNameI16x8Mul                 = "~lib/builtins/i16x8.mul"
	BuiltinNameI16x8MinS                = "~lib/builtins/i16x8.min_s"
	BuiltinNameI16x8MinU                = "~lib/builtins/i16x8.min_u"
	BuiltinNameI16x8MaxS                = "~lib/builtins/i16x8.max_s"
	BuiltinNameI16x8MaxU                = "~lib/builtins/i16x8.max_u"
	BuiltinNameI16x8AvgrU               = "~lib/builtins/i16x8.avgr_u"
	BuiltinNameI16x8Abs                 = "~lib/builtins/i16x8.abs"
	BuiltinNameI16x8Neg                 = "~lib/builtins/i16x8.neg"
	BuiltinNameI16x8AddSatS             = "~lib/builtins/i16x8.add_sat_s"
	BuiltinNameI16x8AddSatU             = "~lib/builtins/i16x8.add_sat_u"
	BuiltinNameI16x8SubSatS             = "~lib/builtins/i16x8.sub_sat_s"
	BuiltinNameI16x8SubSatU             = "~lib/builtins/i16x8.sub_sat_u"
	BuiltinNameI16x8Shl                 = "~lib/builtins/i16x8.shl"
	BuiltinNameI16x8ShrS                = "~lib/builtins/i16x8.shr_s"
	BuiltinNameI16x8ShrU                = "~lib/builtins/i16x8.shr_u"
	BuiltinNameI16x8AllTrue             = "~lib/builtins/i16x8.all_true"
	BuiltinNameI16x8Bitmask             = "~lib/builtins/i16x8.bitmask"
	BuiltinNameI16x8Eq                  = "~lib/builtins/i16x8.eq"
	BuiltinNameI16x8Ne                  = "~lib/builtins/i16x8.ne"
	BuiltinNameI16x8LtS                 = "~lib/builtins/i16x8.lt_s"
	BuiltinNameI16x8LtU                 = "~lib/builtins/i16x8.lt_u"
	BuiltinNameI16x8LeS                 = "~lib/builtins/i16x8.le_s"
	BuiltinNameI16x8LeU                 = "~lib/builtins/i16x8.le_u"
	BuiltinNameI16x8GtS                 = "~lib/builtins/i16x8.gt_s"
	BuiltinNameI16x8GtU                 = "~lib/builtins/i16x8.gt_u"
	BuiltinNameI16x8GeS                 = "~lib/builtins/i16x8.ge_s"
	BuiltinNameI16x8GeU                 = "~lib/builtins/i16x8.ge_u"
	BuiltinNameI16x8NarrowI32x4S        = "~lib/builtins/i16x8.narrow_i32x4_s"
	BuiltinNameI16x8NarrowI32x4U        = "~lib/builtins/i16x8.narrow_i32x4_u"
	BuiltinNameI16x8ExtendLowI8x16S     = "~lib/builtins/i16x8.extend_low_i8x16_s"
	BuiltinNameI16x8ExtendLowI8x16U     = "~lib/builtins/i16x8.extend_low_i8x16_u"
	BuiltinNameI16x8ExtendHighI8x16S    = "~lib/builtins/i16x8.extend_high_i8x16_s"
	BuiltinNameI16x8ExtendHighI8x16U    = "~lib/builtins/i16x8.extend_high_i8x16_u"
	BuiltinNameI16x8ExtaddPairwiseI8x16S = "~lib/builtins/i16x8.extadd_pairwise_i8x16_s"
	BuiltinNameI16x8ExtaddPairwiseI8x16U = "~lib/builtins/i16x8.extadd_pairwise_i8x16_u"
	BuiltinNameI16x8Q15mulrSatS         = "~lib/builtins/i16x8.q15mulr_sat_s"
	BuiltinNameI16x8ExtmulLowI8x16S     = "~lib/builtins/i16x8.extmul_low_i8x16_s"
	BuiltinNameI16x8ExtmulLowI8x16U     = "~lib/builtins/i16x8.extmul_low_i8x16_u"
	BuiltinNameI16x8ExtmulHighI8x16S    = "~lib/builtins/i16x8.extmul_high_i8x16_s"
	BuiltinNameI16x8ExtmulHighI8x16U    = "~lib/builtins/i16x8.extmul_high_i8x16_u"
	BuiltinNameI16x8Shuffle              = "~lib/builtins/i16x8.shuffle"

	// i32x4 operations.
	BuiltinNameI32x4Splat               = "~lib/builtins/i32x4.splat"
	BuiltinNameI32x4ExtractLane         = "~lib/builtins/i32x4.extract_lane"
	BuiltinNameI32x4ReplaceLane         = "~lib/builtins/i32x4.replace_lane"
	BuiltinNameI32x4Add                 = "~lib/builtins/i32x4.add"
	BuiltinNameI32x4Sub                 = "~lib/builtins/i32x4.sub"
	BuiltinNameI32x4Mul                 = "~lib/builtins/i32x4.mul"
	BuiltinNameI32x4MinS                = "~lib/builtins/i32x4.min_s"
	BuiltinNameI32x4MinU                = "~lib/builtins/i32x4.min_u"
	BuiltinNameI32x4MaxS                = "~lib/builtins/i32x4.max_s"
	BuiltinNameI32x4MaxU                = "~lib/builtins/i32x4.max_u"
	BuiltinNameI32x4DotI16x8S           = "~lib/builtins/i32x4.dot_i16x8_s"
	BuiltinNameI32x4Abs                 = "~lib/builtins/i32x4.abs"
	BuiltinNameI32x4Neg                 = "~lib/builtins/i32x4.neg"
	BuiltinNameI32x4Shl                 = "~lib/builtins/i32x4.shl"
	BuiltinNameI32x4ShrS                = "~lib/builtins/i32x4.shr_s"
	BuiltinNameI32x4ShrU                = "~lib/builtins/i32x4.shr_u"
	BuiltinNameI32x4AllTrue             = "~lib/builtins/i32x4.all_true"
	BuiltinNameI32x4Bitmask             = "~lib/builtins/i32x4.bitmask"
	BuiltinNameI32x4Eq                  = "~lib/builtins/i32x4.eq"
	BuiltinNameI32x4Ne                  = "~lib/builtins/i32x4.ne"
	BuiltinNameI32x4LtS                 = "~lib/builtins/i32x4.lt_s"
	BuiltinNameI32x4LtU                 = "~lib/builtins/i32x4.lt_u"
	BuiltinNameI32x4LeS                 = "~lib/builtins/i32x4.le_s"
	BuiltinNameI32x4LeU                 = "~lib/builtins/i32x4.le_u"
	BuiltinNameI32x4GtS                 = "~lib/builtins/i32x4.gt_s"
	BuiltinNameI32x4GtU                 = "~lib/builtins/i32x4.gt_u"
	BuiltinNameI32x4GeS                 = "~lib/builtins/i32x4.ge_s"
	BuiltinNameI32x4GeU                 = "~lib/builtins/i32x4.ge_u"
	BuiltinNameI32x4TruncSatF32x4S      = "~lib/builtins/i32x4.trunc_sat_f32x4_s"
	BuiltinNameI32x4TruncSatF32x4U      = "~lib/builtins/i32x4.trunc_sat_f32x4_u"
	BuiltinNameI32x4TruncSatF64x2SZero  = "~lib/builtins/i32x4.trunc_sat_f64x2_s_zero"
	BuiltinNameI32x4TruncSatF64x2UZero  = "~lib/builtins/i32x4.trunc_sat_f64x2_u_zero"
	BuiltinNameI32x4ExtendLowI16x8S     = "~lib/builtins/i32x4.extend_low_i16x8_s"
	BuiltinNameI32x4ExtendLowI16x8U     = "~lib/builtins/i32x4.extend_low_i16x8_u"
	BuiltinNameI32x4ExtendHighI16x8S    = "~lib/builtins/i32x4.extend_high_i16x8_s"
	BuiltinNameI32x4ExtendHighI16x8U    = "~lib/builtins/i32x4.extend_high_i16x8_u"
	BuiltinNameI32x4ExtaddPairwiseI16x8S = "~lib/builtins/i32x4.extadd_pairwise_i16x8_s"
	BuiltinNameI32x4ExtaddPairwiseI16x8U = "~lib/builtins/i32x4.extadd_pairwise_i16x8_u"
	BuiltinNameI32x4ExtmulLowI16x8S     = "~lib/builtins/i32x4.extmul_low_i16x8_s"
	BuiltinNameI32x4ExtmulLowI16x8U     = "~lib/builtins/i32x4.extmul_low_i16x8_u"
	BuiltinNameI32x4ExtmulHighI16x8S    = "~lib/builtins/i32x4.extmul_high_i16x8_s"
	BuiltinNameI32x4ExtmulHighI16x8U    = "~lib/builtins/i32x4.extmul_high_i16x8_u"
	BuiltinNameI32x4Shuffle              = "~lib/builtins/i32x4.shuffle"

	// i64x2 operations.
	BuiltinNameI64x2Splat             = "~lib/builtins/i64x2.splat"
	BuiltinNameI64x2ExtractLane       = "~lib/builtins/i64x2.extract_lane"
	BuiltinNameI64x2ReplaceLane       = "~lib/builtins/i64x2.replace_lane"
	BuiltinNameI64x2Add               = "~lib/builtins/i64x2.add"
	BuiltinNameI64x2Sub               = "~lib/builtins/i64x2.sub"
	BuiltinNameI64x2Mul               = "~lib/builtins/i64x2.mul"
	BuiltinNameI64x2Abs               = "~lib/builtins/i64x2.abs"
	BuiltinNameI64x2Neg               = "~lib/builtins/i64x2.neg"
	BuiltinNameI64x2Shl               = "~lib/builtins/i64x2.shl"
	BuiltinNameI64x2ShrS              = "~lib/builtins/i64x2.shr_s"
	BuiltinNameI64x2ShrU              = "~lib/builtins/i64x2.shr_u"
	BuiltinNameI64x2AllTrue           = "~lib/builtins/i64x2.all_true"
	BuiltinNameI64x2Bitmask           = "~lib/builtins/i64x2.bitmask"
	BuiltinNameI64x2Eq                = "~lib/builtins/i64x2.eq"
	BuiltinNameI64x2Ne                = "~lib/builtins/i64x2.ne"
	BuiltinNameI64x2LtS               = "~lib/builtins/i64x2.lt_s"
	BuiltinNameI64x2LtU               = "~lib/builtins/i64x2.lt_u"
	BuiltinNameI64x2LeS               = "~lib/builtins/i64x2.le_s"
	BuiltinNameI64x2LeU               = "~lib/builtins/i64x2.le_u"
	BuiltinNameI64x2GtS               = "~lib/builtins/i64x2.gt_s"
	BuiltinNameI64x2GtU               = "~lib/builtins/i64x2.gt_u"
	BuiltinNameI64x2GeS               = "~lib/builtins/i64x2.ge_s"
	BuiltinNameI64x2GeU               = "~lib/builtins/i64x2.ge_u"
	BuiltinNameI64x2ExtendLowI32x4S   = "~lib/builtins/i64x2.extend_low_i32x4_s"
	BuiltinNameI64x2ExtendLowI32x4U   = "~lib/builtins/i64x2.extend_low_i32x4_u"
	BuiltinNameI64x2ExtendHighI32x4S  = "~lib/builtins/i64x2.extend_high_i32x4_s"
	BuiltinNameI64x2ExtendHighI32x4U  = "~lib/builtins/i64x2.extend_high_i32x4_u"
	BuiltinNameI64x2ExtmulLowI32x4S   = "~lib/builtins/i64x2.extmul_low_i32x4_s"
	BuiltinNameI64x2ExtmulLowI32x4U   = "~lib/builtins/i64x2.extmul_low_i32x4_u"
	BuiltinNameI64x2ExtmulHighI32x4S  = "~lib/builtins/i64x2.extmul_high_i32x4_s"
	BuiltinNameI64x2ExtmulHighI32x4U  = "~lib/builtins/i64x2.extmul_high_i32x4_u"
	BuiltinNameI64x2Shuffle           = "~lib/builtins/i64x2.shuffle"

	// f32x4 operations.
	BuiltinNameF32x4Splat             = "~lib/builtins/f32x4.splat"
	BuiltinNameF32x4ExtractLane       = "~lib/builtins/f32x4.extract_lane"
	BuiltinNameF32x4ReplaceLane       = "~lib/builtins/f32x4.replace_lane"
	BuiltinNameF32x4Add               = "~lib/builtins/f32x4.add"
	BuiltinNameF32x4Sub               = "~lib/builtins/f32x4.sub"
	BuiltinNameF32x4Mul               = "~lib/builtins/f32x4.mul"
	BuiltinNameF32x4Div               = "~lib/builtins/f32x4.div"
	BuiltinNameF32x4Neg               = "~lib/builtins/f32x4.neg"
	BuiltinNameF32x4Min               = "~lib/builtins/f32x4.min"
	BuiltinNameF32x4Max               = "~lib/builtins/f32x4.max"
	BuiltinNameF32x4Pmin              = "~lib/builtins/f32x4.pmin"
	BuiltinNameF32x4Pmax              = "~lib/builtins/f32x4.pmax"
	BuiltinNameF32x4Abs               = "~lib/builtins/f32x4.abs"
	BuiltinNameF32x4Sqrt              = "~lib/builtins/f32x4.sqrt"
	BuiltinNameF32x4Ceil              = "~lib/builtins/f32x4.ceil"
	BuiltinNameF32x4Floor             = "~lib/builtins/f32x4.floor"
	BuiltinNameF32x4Trunc             = "~lib/builtins/f32x4.trunc"
	BuiltinNameF32x4Nearest           = "~lib/builtins/f32x4.nearest"
	BuiltinNameF32x4Eq                = "~lib/builtins/f32x4.eq"
	BuiltinNameF32x4Ne                = "~lib/builtins/f32x4.ne"
	BuiltinNameF32x4Lt                = "~lib/builtins/f32x4.lt"
	BuiltinNameF32x4Le                = "~lib/builtins/f32x4.le"
	BuiltinNameF32x4Gt                = "~lib/builtins/f32x4.gt"
	BuiltinNameF32x4Ge                = "~lib/builtins/f32x4.ge"
	BuiltinNameF32x4ConvertI32x4S     = "~lib/builtins/f32x4.convert_i32x4_s"
	BuiltinNameF32x4ConvertI32x4U     = "~lib/builtins/f32x4.convert_i32x4_u"
	BuiltinNameF32x4DemoteF64x2Zero   = "~lib/builtins/f32x4.demote_f64x2_zero"
	BuiltinNameF32x4Shuffle           = "~lib/builtins/f32x4.shuffle"

	// f64x2 operations.
	BuiltinNameF64x2Splat             = "~lib/builtins/f64x2.splat"
	BuiltinNameF64x2ExtractLane       = "~lib/builtins/f64x2.extract_lane"
	BuiltinNameF64x2ReplaceLane       = "~lib/builtins/f64x2.replace_lane"
	BuiltinNameF64x2Add               = "~lib/builtins/f64x2.add"
	BuiltinNameF64x2Sub               = "~lib/builtins/f64x2.sub"
	BuiltinNameF64x2Mul               = "~lib/builtins/f64x2.mul"
	BuiltinNameF64x2Div               = "~lib/builtins/f64x2.div"
	BuiltinNameF64x2Neg               = "~lib/builtins/f64x2.neg"
	BuiltinNameF64x2Min               = "~lib/builtins/f64x2.min"
	BuiltinNameF64x2Max               = "~lib/builtins/f64x2.max"
	BuiltinNameF64x2Pmin              = "~lib/builtins/f64x2.pmin"
	BuiltinNameF64x2Pmax              = "~lib/builtins/f64x2.pmax"
	BuiltinNameF64x2Abs               = "~lib/builtins/f64x2.abs"
	BuiltinNameF64x2Sqrt              = "~lib/builtins/f64x2.sqrt"
	BuiltinNameF64x2Ceil              = "~lib/builtins/f64x2.ceil"
	BuiltinNameF64x2Floor             = "~lib/builtins/f64x2.floor"
	BuiltinNameF64x2Trunc             = "~lib/builtins/f64x2.trunc"
	BuiltinNameF64x2Nearest           = "~lib/builtins/f64x2.nearest"
	BuiltinNameF64x2Eq                = "~lib/builtins/f64x2.eq"
	BuiltinNameF64x2Ne                = "~lib/builtins/f64x2.ne"
	BuiltinNameF64x2Lt                = "~lib/builtins/f64x2.lt"
	BuiltinNameF64x2Le                = "~lib/builtins/f64x2.le"
	BuiltinNameF64x2Gt                = "~lib/builtins/f64x2.gt"
	BuiltinNameF64x2Ge                = "~lib/builtins/f64x2.ge"
	BuiltinNameF64x2ConvertLowI32x4S  = "~lib/builtins/f64x2.convert_low_i32x4_s"
	BuiltinNameF64x2ConvertLowI32x4U  = "~lib/builtins/f64x2.convert_low_i32x4_u"
	BuiltinNameF64x2PromoteLowF32x4   = "~lib/builtins/f64x2.promote_low_f32x4"
	BuiltinNameF64x2Shuffle           = "~lib/builtins/f64x2.shuffle"

	// Relaxed SIMD lane-specific operations.
	BuiltinNameI8x16RelaxedSwizzle          = "~lib/builtins/i8x16.relaxed_swizzle"
	BuiltinNameI32x4RelaxedTruncF32x4S      = "~lib/builtins/i32x4.relaxed_trunc_f32x4_s"
	BuiltinNameI32x4RelaxedTruncF32x4U      = "~lib/builtins/i32x4.relaxed_trunc_f32x4_u"
	BuiltinNameI32x4RelaxedTruncF64x2SZero  = "~lib/builtins/i32x4.relaxed_trunc_f64x2_s_zero"
	BuiltinNameI32x4RelaxedTruncF64x2UZero  = "~lib/builtins/i32x4.relaxed_trunc_f64x2_u_zero"
	BuiltinNameF32x4RelaxedMadd             = "~lib/builtins/f32x4.relaxed_madd"
	BuiltinNameF32x4RelaxedNmadd            = "~lib/builtins/f32x4.relaxed_nmadd"
	BuiltinNameF64x2RelaxedMadd             = "~lib/builtins/f64x2.relaxed_madd"
	BuiltinNameF64x2RelaxedNmadd            = "~lib/builtins/f64x2.relaxed_nmadd"
	BuiltinNameI8x16RelaxedLaneselect       = "~lib/builtins/i8x16.relaxed_laneselect"
	BuiltinNameI16x8RelaxedLaneselect       = "~lib/builtins/i16x8.relaxed_laneselect"
	BuiltinNameI32x4RelaxedLaneselect       = "~lib/builtins/i32x4.relaxed_laneselect"
	BuiltinNameI64x2RelaxedLaneselect       = "~lib/builtins/i64x2.relaxed_laneselect"
	BuiltinNameF32x4RelaxedMin              = "~lib/builtins/f32x4.relaxed_min"
	BuiltinNameF32x4RelaxedMax              = "~lib/builtins/f32x4.relaxed_max"
	BuiltinNameF64x2RelaxedMin              = "~lib/builtins/f64x2.relaxed_min"
	BuiltinNameF64x2RelaxedMax              = "~lib/builtins/f64x2.relaxed_max"
	BuiltinNameI16x8RelaxedQ15mulrS         = "~lib/builtins/i16x8.relaxed_q15mulr_s"
	BuiltinNameI16x8RelaxedDotI8x16I7x16S  = "~lib/builtins/i16x8.relaxed_dot_i8x16_i7x16_s"
	BuiltinNameI32x4RelaxedDotI8x16I7x16AddS = "~lib/builtins/i32x4.relaxed_dot_i8x16_i7x16_add_s"

	// GC builtins.
	BuiltinNameI31New = "~lib/builtins/i31.new"
	BuiltinNameI31Get = "~lib/builtins/i31.get"

	// Internals / runtime globals.
	BuiltinNameDataEnd      = "~lib/memory/__data_end"
	BuiltinNameStackPointer = "~lib/memory/__stack_pointer"
	BuiltinNameHeapBase     = "~lib/memory/__heap_base"
	BuiltinNameRttiBase     = "~lib/rt/__rtti_base"
	BuiltinNameVisitGlobals = "~lib/rt/__visit_globals"
	BuiltinNameVisitMembers = "~lib/rt/__visit_members"
	BuiltinNameTostack      = "~lib/rt/__tostack"

	// std/number.ts
	BuiltinNameNaN      = "~lib/number/NaN"
	BuiltinNameInfinity = "~lib/number/Infinity"
	BuiltinNameIsNaN    = "~lib/number/isNaN"
	BuiltinNameIsFinite = "~lib/number/isFinite"

	// std/diagnostics.ts
	BuiltinNameERROR   = "~lib/diagnostics/ERROR"
	BuiltinNameWARNING = "~lib/diagnostics/WARNING"
	BuiltinNameINFO    = "~lib/diagnostics/INFO"

	// std/function.ts
	BuiltinNameFunction     = "~lib/function/Function"
	BuiltinNameFunctionCall = "~lib/function/Function#call"

	// std/memory.ts
	BuiltinNameMemorySize = "~lib/memory/memory.size"
	BuiltinNameMemoryGrow = "~lib/memory/memory.grow"
	BuiltinNameMemoryCopy = "~lib/memory/memory.copy"
	BuiltinNameMemoryFill = "~lib/memory/memory.fill"
	BuiltinNameMemoryData = "~lib/memory/memory.data"

	// std/typedarray.ts
	BuiltinNameInt8Array         = "~lib/typedarray/Int8Array"
	BuiltinNameUint8Array        = "~lib/typedarray/Uint8Array"
	BuiltinNameUint8ClampedArray = "~lib/typedarray/Uint8ClampedArray"
	BuiltinNameInt16Array        = "~lib/typedarray/Int16Array"
	BuiltinNameUint16Array       = "~lib/typedarray/Uint16Array"
	BuiltinNameInt32Array        = "~lib/typedarray/Int32Array"
	BuiltinNameUint32Array       = "~lib/typedarray/Uint32Array"
	BuiltinNameInt64Array        = "~lib/typedarray/Int64Array"
	BuiltinNameUint64Array       = "~lib/typedarray/Uint64Array"
	BuiltinNameFloat32Array      = "~lib/typedarray/Float32Array"
	BuiltinNameFloat64Array      = "~lib/typedarray/Float64Array"

	// std/string.ts
	BuiltinNameStringRaw = "~lib/string/String.raw"
	BuiltinNameStringEq  = "~lib/string/String.__eq"
	BuiltinNameStringNe  = "~lib/string/String.__ne"
	BuiltinNameStringNot = "~lib/string/String.__not"

	// std/object.ts
	BuiltinNameObject = "~lib/object/Object"
)
