package common

type CommonFlags uint32

const (
	CommonFlagsNone               CommonFlags = 0
	CommonFlagsImport             CommonFlags = 1 << 0
	CommonFlagsExport             CommonFlags = 1 << 1
	CommonFlagsDeclare            CommonFlags = 1 << 2
	CommonFlagsConst              CommonFlags = 1 << 3
	CommonFlagsLet                CommonFlags = 1 << 4
	CommonFlagsStatic             CommonFlags = 1 << 5
	CommonFlagsReadonly           CommonFlags = 1 << 6
	CommonFlagsAbstract           CommonFlags = 1 << 7
	CommonFlagsPublic             CommonFlags = 1 << 8
	CommonFlagsPrivate            CommonFlags = 1 << 9
	CommonFlagsProtected          CommonFlags = 1 << 10
	CommonFlagsGet                CommonFlags = 1 << 11
	CommonFlagsSet                CommonFlags = 1 << 12
	CommonFlagsOverride           CommonFlags = 1 << 13
	CommonFlagsDefinitelyAssigned CommonFlags = 1 << 14
	CommonFlagsAmbient            CommonFlags = 1 << 15
	CommonFlagsGeneric            CommonFlags = 1 << 16
	CommonFlagsGenericContext     CommonFlags = 1 << 17
	CommonFlagsInstance           CommonFlags = 1 << 18
	CommonFlagsConstructor        CommonFlags = 1 << 19
	CommonFlagsModuleExport       CommonFlags = 1 << 20
	CommonFlagsModuleImport       CommonFlags = 1 << 21
	CommonFlagsResolved           CommonFlags = 1 << 22
	CommonFlagsCompiled           CommonFlags = 1 << 23
	CommonFlagsErrored            CommonFlags = 1 << 24
	CommonFlagsInlined            CommonFlags = 1 << 25
	CommonFlagsScoped             CommonFlags = 1 << 26
	CommonFlagsStub               CommonFlags = 1 << 27
	CommonFlagsOverridden         CommonFlags = 1 << 28
	CommonFlagsClosure            CommonFlags = 1 << 29
	CommonFlagsQuoted             CommonFlags = 1 << 30
	CommonFlagsInternallyNullable CommonFlags = 1 << 31
)

const (
	PATH_DELIMITER     = "/"
	PARENT_SUBST       = ".."
	GETTER_PREFIX      = "get:"
	SETTER_PREFIX      = "set:"
	INSTANCE_DELIMITER = "#"
	STATIC_DELIMITER   = "."
	INNER_DELIMITER    = "~"
	LIBRARY_SUBST      = "~lib"
	LIBRARY_PREFIX     = "~lib/"
	INDEX_SUFFIX       = "/index"
	STUB_DELIMITER     = "@"
)

const (
	CommonNameEmpty                    = ""
	CommonNameI8                       = "i8"
	CommonNameI16                      = "i16"
	CommonNameI32                      = "i32"
	CommonNameI64                      = "i64"
	CommonNameIsize                    = "isize"
	CommonNameU8                       = "u8"
	CommonNameU16                      = "u16"
	CommonNameU32                      = "u32"
	CommonNameU64                      = "u64"
	CommonNameUsize                    = "usize"
	CommonNameBool                     = "bool"
	CommonNameF32                      = "f32"
	CommonNameF64                      = "f64"
	CommonNameV128                     = "v128"
	CommonNameRefFunc                  = "ref_func"
	CommonNameRefExtern                = "ref_extern"
	CommonNameRefAny                   = "ref_any"
	CommonNameRefEq                    = "ref_eq"
	CommonNameRefStruct                = "ref_struct"
	CommonNameRefArray                 = "ref_array"
	CommonNameRefI31                   = "ref_i31"
	CommonNameRefString                = "ref_string"
	CommonNameRefStringviewWtf8        = "ref_stringview_wtf8"
	CommonNameRefStringviewWtf16       = "ref_stringview_wtf16"
	CommonNameRefStringviewIter        = "ref_stringview_iter"
	CommonNameI8x16                    = "i8x16"
	CommonNameU8x16                    = "u8x16"
	CommonNameI16x8                    = "i16x8"
	CommonNameU16x8                    = "u16x8"
	CommonNameI32x4                    = "i32x4"
	CommonNameU32x4                    = "u32x4"
	CommonNameI64x2                    = "i64x2"
	CommonNameU64x2                    = "u64x2"
	CommonNameF32x4                    = "f32x4"
	CommonNameF64x2                    = "f64x2"
	CommonNameVoid                     = "void"
	CommonNameNumber                   = "number"
	CommonNameBoolean                  = "boolean"
	CommonNameString                   = "string"
	CommonNameNative                   = "native"
	CommonNameIndexof                  = "indexof"
	CommonNameValueof                  = "valueof"
	CommonNameReturnof                 = "returnof"
	CommonNameNonnull                  = "nonnull"
	CommonNameNull                     = "null"
	CommonNameTrue                     = "true"
	CommonNameFalse                    = "false"
	CommonNameThis                     = "this"
	CommonNameSuper                    = "super"
	CommonNameConstructor              = "constructor"
	CommonNameASCTarget                = "ASC_TARGET"
	CommonNameASCRuntime               = "ASC_RUNTIME"
	CommonNameASCNoAssert              = "ASC_NO_ASSERT"
	CommonNameASCMemoryBase            = "ASC_MEMORY_BASE"
	CommonNameASCTableBase             = "ASC_TABLE_BASE"
	CommonNameASCOptimizeLevel         = "ASC_OPTIMIZE_LEVEL"
	CommonNameASCShrinkLevel           = "ASC_SHRINK_LEVEL"
	CommonNameASCLowMemoryLimit        = "ASC_LOW_MEMORY_LIMIT"
	CommonNameASCExportRuntime         = "ASC_EXPORT_RUNTIME"
	CommonNameASCFeatureSignExtension  = "ASC_FEATURE_SIGN_EXTENSION"
	CommonNameASCFeatureMutableGlobals = "ASC_FEATURE_MUTABLE_GLOBALS"
	CommonNameASCFeatureNontrappingF2I = "ASC_FEATURE_NONTRAPPING_F2I"
	CommonNameASCFeatureBulkMemory     = "ASC_FEATURE_BULK_MEMORY"
	CommonNameASCFeatureSimd           = "ASC_FEATURE_SIMD"
	CommonNameASCFeatureThreads        = "ASC_FEATURE_THREADS"
	CommonNameASCFeatureExceptionHandling = "ASC_FEATURE_EXCEPTION_HANDLING"
	CommonNameASCFeatureTailCalls      = "ASC_FEATURE_TAIL_CALLS"
	CommonNameASCFeatureReferenceTypes = "ASC_FEATURE_REFERENCE_TYPES"
	CommonNameASCFeatureMultiValue     = "ASC_FEATURE_MULTI_VALUE"
	CommonNameASCFeatureGC             = "ASC_FEATURE_GC"
	CommonNameASCFeatureMemory64       = "ASC_FEATURE_MEMORY64"
	CommonNameASCFeatureRelaxedSimd    = "ASC_FEATURE_RELAXED_SIMD"
	CommonNameASCFeatureExtendedConst  = "ASC_FEATURE_EXTENDED_CONST"
	CommonNameASCFeatureStringref      = "ASC_FEATURE_STRINGREF"
	CommonNameASCVersionMajor          = "ASC_VERSION_MAJOR"
	CommonNameASCVersionMinor          = "ASC_VERSION_MINOR"
	CommonNameASCVersionPatch          = "ASC_VERSION_PATCH"
	CommonNameEnumToString             = "__enum_to_string"
	CommonNameCapI8                    = "I8"
	CommonNameCapI16                   = "I16"
	CommonNameCapI32                   = "I32"
	CommonNameCapI64                   = "I64"
	CommonNameCapIsize                 = "Isize"
	CommonNameCapU8                    = "U8"
	CommonNameCapU16                   = "U16"
	CommonNameCapU32                   = "U32"
	CommonNameCapU64                   = "U64"
	CommonNameCapUsize                 = "Usize"
	CommonNameCapBool                  = "Bool"
	CommonNameCapF32                   = "F32"
	CommonNameCapF64                   = "F64"
	CommonNameCapV128                  = "V128"
	CommonNameCapRefFunc               = "RefFunc"
	CommonNameCapRefExtern             = "RefExtern"
	CommonNameCapRefAny                = "RefAny"
	CommonNameCapRefEq                 = "RefEq"
	CommonNameCapRefStruct             = "RefStruct"
	CommonNameCapRefArray              = "RefArray"
	CommonNameCapRefI31                = "RefI31"
	CommonNameCapRefString             = "RefString"
	CommonNameCapString                = "String"
	CommonNameRegExp                   = "RegExp"
	CommonNameObject                   = "Object"
	CommonNameArray                    = "Array"
	CommonNameStaticArray              = "StaticArray"
	CommonNameSet                      = "Set"
	CommonNameMap                      = "Map"
	CommonNameFunction                 = "Function"
	CommonNameArrayBufferView          = "ArrayBufferView"
	CommonNameArrayBuffer              = "ArrayBuffer"
	CommonNameMath                     = "Math"
	CommonNameMathf                    = "Mathf"
	CommonNameNativeMath               = "NativeMath"
	CommonNameNativeMathf              = "NativeMathf"
	CommonNameInt8Array                = "Int8Array"
	CommonNameInt16Array               = "Int16Array"
	CommonNameInt32Array               = "Int32Array"
	CommonNameInt64Array               = "Int64Array"
	CommonNameUint8Array               = "Uint8Array"
	CommonNameUint8ClampedArray        = "Uint8ClampedArray"
	CommonNameUint16Array              = "Uint16Array"
	CommonNameUint32Array              = "Uint32Array"
	CommonNameUint64Array              = "Uint64Array"
	CommonNameFloat32Array             = "Float32Array"
	CommonNameFloat64Array             = "Float64Array"
	CommonNameTemplateStringsArray     = "TemplateStringsArray"
	CommonNameError                    = "Error"
	CommonNameAbort                    = "abort"
	CommonNameTrace                    = "trace"
	CommonNameSeed                     = "seed"
	CommonNamePow                      = "pow"
	CommonNameIpow32                   = "ipow32"
	CommonNameIpow64                   = "ipow64"
	CommonNameMod                      = "mod"
	CommonNameAlloc                    = "__alloc"
	CommonNameRealloc                  = "__realloc"
	CommonNameFree                     = "__free"
	CommonNameNew                      = "__new"
	CommonNameRenew                    = "__renew"
	CommonNameLink                     = "__link"
	CommonNameCollect                  = "__collect"
	CommonNameVisit                    = "__visit"
	CommonNameNewBuffer                = "__newBuffer"
	CommonNameNewArray                 = "__newArray"
	CommonNameBlock                    = "~lib/rt/common/BLOCK"
	CommonNameObject_                  = "~lib/rt/common/OBJECT"
	CommonNameDefaultMemory            = "0"
	CommonNameDefaultTable             = "0"
)
