// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit publish/subscribe/call/emit.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// The underlying generic publish/call patterns are unchanged. These wrappers
// just add type safety.
//
// Regenerate with cmd/sdkgen from this repository.
package agentmsg

import (
	"context"

	"github.com/brainlet/brainkit/sdk"
)

// PublishAgentDiscover publishes a AgentDiscoverMsg and returns routing info for the response.
func PublishAgentDiscover(rt sdk.Runtime, ctx context.Context, msg AgentDiscoverMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeAgentDiscoverResp subscribes to the response topic for a AgentDiscoverMsg command.
func SubscribeAgentDiscoverResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(AgentDiscoverResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[AgentDiscoverResp](rt, ctx, topic, handler)
}

// CallAgentDiscover issues a synchronous request-response Call for AgentDiscoverMsg.
func CallAgentDiscover(rt sdk.CallerRuntime, ctx context.Context, msg AgentDiscoverMsg, opts ...sdk.CallOption) (AgentDiscoverResp, error) {
	return sdk.Call[AgentDiscoverMsg, AgentDiscoverResp](rt, ctx, msg, opts...)
}

// PublishAgentGetStatus publishes a AgentGetStatusMsg and returns routing info for the response.
func PublishAgentGetStatus(rt sdk.Runtime, ctx context.Context, msg AgentGetStatusMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeAgentGetStatusResp subscribes to the response topic for a AgentGetStatusMsg command.
func SubscribeAgentGetStatusResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(AgentGetStatusResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[AgentGetStatusResp](rt, ctx, topic, handler)
}

// CallAgentGetStatus issues a synchronous request-response Call for AgentGetStatusMsg.
func CallAgentGetStatus(rt sdk.CallerRuntime, ctx context.Context, msg AgentGetStatusMsg, opts ...sdk.CallOption) (AgentGetStatusResp, error) {
	return sdk.Call[AgentGetStatusMsg, AgentGetStatusResp](rt, ctx, msg, opts...)
}

// PublishAgentList publishes a AgentListMsg and returns routing info for the response.
func PublishAgentList(rt sdk.Runtime, ctx context.Context, msg AgentListMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeAgentListResp subscribes to the response topic for a AgentListMsg command.
func SubscribeAgentListResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(AgentListResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[AgentListResp](rt, ctx, topic, handler)
}

// CallAgentList issues a synchronous request-response Call for AgentListMsg.
func CallAgentList(rt sdk.CallerRuntime, ctx context.Context, msg AgentListMsg, opts ...sdk.CallOption) (AgentListResp, error) {
	return sdk.Call[AgentListMsg, AgentListResp](rt, ctx, msg, opts...)
}

// PublishAgentSetStatus publishes a AgentSetStatusMsg and returns routing info for the response.
func PublishAgentSetStatus(rt sdk.Runtime, ctx context.Context, msg AgentSetStatusMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeAgentSetStatusResp subscribes to the response topic for a AgentSetStatusMsg command.
func SubscribeAgentSetStatusResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(AgentSetStatusResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[AgentSetStatusResp](rt, ctx, topic, handler)
}

// CallAgentSetStatus issues a synchronous request-response Call for AgentSetStatusMsg.
func CallAgentSetStatus(rt sdk.CallerRuntime, ctx context.Context, msg AgentSetStatusMsg, opts ...sdk.CallOption) (AgentSetStatusResp, error) {
	return sdk.Call[AgentSetStatusMsg, AgentSetStatusResp](rt, ctx, msg, opts...)
}

