// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit call/emit/subscribe.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// Low-level publish/reply-topic helpers are intentionally not generated; use
// the generic SDK protocol primitives directly when testing transport behavior.
//
// Regenerate with cmd/sdkgen from this repository.
package agentmsg

import (
	"context"

	bkmodule "github.com/brainlet/brainkit/module"
	"github.com/brainlet/brainkit/sdk"
)

// CallAgentDiscover issues a synchronous request-response Call for AgentDiscoverMsg.
func CallAgentDiscover(rt sdk.CallerRuntime, ctx context.Context, msg AgentDiscoverMsg, opts ...sdk.CallOption) (AgentDiscoverResp, error) {
	return sdk.Call[AgentDiscoverMsg, AgentDiscoverResp](rt, ctx, msg, opts...)
}

// CallAgentDiscoverWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallAgentDiscoverWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg AgentDiscoverMsg, opts ...sdk.CallOption) (AgentDiscoverResp, error) {
	return sdk.CallWithCaller[AgentDiscoverMsg, AgentDiscoverResp](caller, ctx, msg, opts...)
}

// CallAgentGetStatus issues a synchronous request-response Call for AgentGetStatusMsg.
func CallAgentGetStatus(rt sdk.CallerRuntime, ctx context.Context, msg AgentGetStatusMsg, opts ...sdk.CallOption) (AgentGetStatusResp, error) {
	return sdk.Call[AgentGetStatusMsg, AgentGetStatusResp](rt, ctx, msg, opts...)
}

// CallAgentGetStatusWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallAgentGetStatusWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg AgentGetStatusMsg, opts ...sdk.CallOption) (AgentGetStatusResp, error) {
	return sdk.CallWithCaller[AgentGetStatusMsg, AgentGetStatusResp](caller, ctx, msg, opts...)
}

// CallAgentList issues a synchronous request-response Call for AgentListMsg.
func CallAgentList(rt sdk.CallerRuntime, ctx context.Context, msg AgentListMsg, opts ...sdk.CallOption) (AgentListResp, error) {
	return sdk.Call[AgentListMsg, AgentListResp](rt, ctx, msg, opts...)
}

// CallAgentListWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallAgentListWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg AgentListMsg, opts ...sdk.CallOption) (AgentListResp, error) {
	return sdk.CallWithCaller[AgentListMsg, AgentListResp](caller, ctx, msg, opts...)
}

// CallAgentSetStatus issues a synchronous request-response Call for AgentSetStatusMsg.
func CallAgentSetStatus(rt sdk.CallerRuntime, ctx context.Context, msg AgentSetStatusMsg, opts ...sdk.CallOption) (AgentSetStatusResp, error) {
	return sdk.Call[AgentSetStatusMsg, AgentSetStatusResp](rt, ctx, msg, opts...)
}

// CallAgentSetStatusWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallAgentSetStatusWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg AgentSetStatusMsg, opts ...sdk.CallOption) (AgentSetStatusResp, error) {
	return sdk.CallWithCaller[AgentSetStatusMsg, AgentSetStatusResp](caller, ctx, msg, opts...)
}

