// Ported from: packages/ai/src/prompt/content-part.ts
package prompt

// ProviderOptions is a map of provider-specific options.
// TODO: import from brainlink/experiments/ai-kit/providerutils once it exists
type ProviderOptions = map[string]map[string]interface{}

// TextPart is a text content part of a prompt.
type TextPart struct {
	Type            string          `json:"type"` // always "text"
	Text            string          `json:"text"`
	ProviderOptions ProviderOptions `json:"providerOptions,omitempty"`
}

// ImagePart is an image content part of a prompt.
type ImagePart struct {
	Type            string          `json:"type"` // always "image"
	Image           interface{}     `json:"image"` // DataContent or *url.URL
	MediaType       *string         `json:"mediaType,omitempty"`
	ProviderOptions ProviderOptions `json:"providerOptions,omitempty"`
}

// FilePart is a file content part of a prompt.
type FilePart struct {
	Type            string          `json:"type"` // always "file"
	Data            interface{}     `json:"data"` // DataContent or *url.URL
	Filename        *string         `json:"filename,omitempty"`
	MediaType       string          `json:"mediaType"`
	ProviderOptions ProviderOptions `json:"providerOptions,omitempty"`
}

// ReasoningPart is a reasoning content part of a prompt.
type ReasoningPart struct {
	Type            string          `json:"type"` // always "reasoning"
	Text            string          `json:"text"`
	ProviderOptions ProviderOptions `json:"providerOptions,omitempty"`
}

// ToolCallPart is a tool call content part of a prompt.
// It contains a tool call (usually generated by the AI model).
type ToolCallPart struct {
	Type             string          `json:"type"` // always "tool-call"
	ToolCallID       string          `json:"toolCallId"`
	ToolName         string          `json:"toolName"`
	Input            interface{}     `json:"input"`
	ProviderOptions  ProviderOptions `json:"providerOptions,omitempty"`
	ProviderExecuted *bool           `json:"providerExecuted,omitempty"`
}

// ToolResultOutput represents the output of a tool result.
// TODO: import from brainlink/experiments/ai-kit/providerutils once it exists
type ToolResultOutput struct {
	Type  string      `json:"type"` // "text", "json", "error-text", "error-json", "content", "execution-denied"
	Value interface{} `json:"value,omitempty"`
	// For "execution-denied" type:
	Reason *string `json:"reason,omitempty"`
}

// ToolResultPart is a tool result content part of a prompt.
type ToolResultPart struct {
	Type            string           `json:"type"` // always "tool-result"
	ToolCallID      string           `json:"toolCallId"`
	ToolName        string           `json:"toolName"`
	Output          ToolResultOutput `json:"output"`
	ProviderOptions ProviderOptions  `json:"providerOptions,omitempty"`
}

// ToolApprovalRequest is a tool approval request content part.
type ToolApprovalRequest struct {
	Type       string `json:"type"` // always "tool-approval-request"
	ApprovalID string `json:"approvalId"`
	ToolCallID string `json:"toolCallId"`
}

// ToolApprovalResponse is a tool approval response content part.
type ToolApprovalResponse struct {
	Type             string  `json:"type"` // always "tool-approval-response"
	ApprovalID       string  `json:"approvalId"`
	Approved         bool    `json:"approved"`
	Reason           *string `json:"reason,omitempty"`
	ProviderExecuted *bool   `json:"providerExecuted,omitempty"`
}
