// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit publish/subscribe/call/emit.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// The underlying generic publish/call patterns are unchanged. These wrappers
// just add type safety.
//
// Regenerate with cmd/sdkgen from this repository.
package pluginmsg

import (
	"context"

	"github.com/brainlet/brainkit/sdk"
)

// PublishPluginListRunning publishes a PluginListRunningMsg and returns routing info for the response.
func PublishPluginListRunning(rt sdk.Runtime, ctx context.Context, msg PluginListRunningMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribePluginListRunningResp subscribes to the response topic for a PluginListRunningMsg command.
func SubscribePluginListRunningResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(PluginListRunningResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[PluginListRunningResp](rt, ctx, topic, handler)
}

// CallPluginListRunning issues a synchronous request-response Call for PluginListRunningMsg.
func CallPluginListRunning(rt sdk.CallerRuntime, ctx context.Context, msg PluginListRunningMsg, opts ...sdk.CallOption) (PluginListRunningResp, error) {
	return sdk.Call[PluginListRunningMsg, PluginListRunningResp](rt, ctx, msg, opts...)
}

// PublishPluginManifest publishes a PluginManifestMsg and returns routing info for the response.
func PublishPluginManifest(rt sdk.Runtime, ctx context.Context, msg PluginManifestMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribePluginManifestResp subscribes to the response topic for a PluginManifestMsg command.
func SubscribePluginManifestResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(PluginManifestResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[PluginManifestResp](rt, ctx, topic, handler)
}

// CallPluginManifest issues a synchronous request-response Call for PluginManifestMsg.
func CallPluginManifest(rt sdk.CallerRuntime, ctx context.Context, msg PluginManifestMsg, opts ...sdk.CallOption) (PluginManifestResp, error) {
	return sdk.Call[PluginManifestMsg, PluginManifestResp](rt, ctx, msg, opts...)
}

// PublishPluginRestart publishes a PluginRestartMsg and returns routing info for the response.
func PublishPluginRestart(rt sdk.Runtime, ctx context.Context, msg PluginRestartMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribePluginRestartResp subscribes to the response topic for a PluginRestartMsg command.
func SubscribePluginRestartResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(PluginRestartResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[PluginRestartResp](rt, ctx, topic, handler)
}

// CallPluginRestart issues a synchronous request-response Call for PluginRestartMsg.
func CallPluginRestart(rt sdk.CallerRuntime, ctx context.Context, msg PluginRestartMsg, opts ...sdk.CallOption) (PluginRestartResp, error) {
	return sdk.Call[PluginRestartMsg, PluginRestartResp](rt, ctx, msg, opts...)
}

// PublishPluginStart publishes a PluginStartMsg and returns routing info for the response.
func PublishPluginStart(rt sdk.Runtime, ctx context.Context, msg PluginStartMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribePluginStartResp subscribes to the response topic for a PluginStartMsg command.
func SubscribePluginStartResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(PluginStartResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[PluginStartResp](rt, ctx, topic, handler)
}

// CallPluginStart issues a synchronous request-response Call for PluginStartMsg.
func CallPluginStart(rt sdk.CallerRuntime, ctx context.Context, msg PluginStartMsg, opts ...sdk.CallOption) (PluginStartResp, error) {
	return sdk.Call[PluginStartMsg, PluginStartResp](rt, ctx, msg, opts...)
}

// PublishPluginStatus publishes a PluginStatusMsg and returns routing info for the response.
func PublishPluginStatus(rt sdk.Runtime, ctx context.Context, msg PluginStatusMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribePluginStatusResp subscribes to the response topic for a PluginStatusMsg command.
func SubscribePluginStatusResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(PluginStatusResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[PluginStatusResp](rt, ctx, topic, handler)
}

// CallPluginStatus issues a synchronous request-response Call for PluginStatusMsg.
func CallPluginStatus(rt sdk.CallerRuntime, ctx context.Context, msg PluginStatusMsg, opts ...sdk.CallOption) (PluginStatusResp, error) {
	return sdk.Call[PluginStatusMsg, PluginStatusResp](rt, ctx, msg, opts...)
}

// PublishPluginStop publishes a PluginStopMsg and returns routing info for the response.
func PublishPluginStop(rt sdk.Runtime, ctx context.Context, msg PluginStopMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribePluginStopResp subscribes to the response topic for a PluginStopMsg command.
func SubscribePluginStopResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(PluginStopResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[PluginStopResp](rt, ctx, topic, handler)
}

// CallPluginStop issues a synchronous request-response Call for PluginStopMsg.
func CallPluginStop(rt sdk.CallerRuntime, ctx context.Context, msg PluginStopMsg, opts ...sdk.CallOption) (PluginStopResp, error) {
	return sdk.Call[PluginStopMsg, PluginStopResp](rt, ctx, msg, opts...)
}

// EmitPluginRegistered fires a PluginRegisteredEvent event (no response expected).
func EmitPluginRegistered(rt sdk.Runtime, ctx context.Context, msg PluginRegisteredEvent) error {
	return sdk.Emit(rt, ctx, msg)
}

// SubscribePluginRegistered listens for PluginRegisteredEvent events.
func SubscribePluginRegistered(rt sdk.Runtime, ctx context.Context, topic string, handler func(PluginRegisteredEvent, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[PluginRegisteredEvent](rt, ctx, topic, handler)
}

// EmitPluginStarted fires a PluginStartedEvent event (no response expected).
func EmitPluginStarted(rt sdk.Runtime, ctx context.Context, msg PluginStartedEvent) error {
	return sdk.Emit(rt, ctx, msg)
}

// SubscribePluginStarted listens for PluginStartedEvent events.
func SubscribePluginStarted(rt sdk.Runtime, ctx context.Context, topic string, handler func(PluginStartedEvent, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[PluginStartedEvent](rt, ctx, topic, handler)
}

// EmitPluginStopped fires a PluginStoppedEvent event (no response expected).
func EmitPluginStopped(rt sdk.Runtime, ctx context.Context, msg PluginStoppedEvent) error {
	return sdk.Emit(rt, ctx, msg)
}

// SubscribePluginStopped listens for PluginStoppedEvent events.
func SubscribePluginStopped(rt sdk.Runtime, ctx context.Context, topic string, handler func(PluginStoppedEvent, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[PluginStoppedEvent](rt, ctx, topic, handler)
}

