// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit call/emit/subscribe.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// Low-level publish/reply-topic helpers are intentionally not generated; use
// the generic SDK protocol primitives directly when testing transport behavior.
//
// Regenerate with cmd/sdkgen from this repository.
package pluginmsg

import (
	"context"

	bkmodule "github.com/brainlet/brainkit/module"
	"github.com/brainlet/brainkit/sdk"
)

// CallPluginListRunning issues a synchronous request-response Call for PluginListRunningMsg.
func CallPluginListRunning(rt sdk.CallerRuntime, ctx context.Context, msg PluginListRunningMsg, opts ...sdk.CallOption) (PluginListRunningResp, error) {
	return sdk.Call[PluginListRunningMsg, PluginListRunningResp](rt, ctx, msg, opts...)
}

// CallPluginListRunningWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallPluginListRunningWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg PluginListRunningMsg, opts ...sdk.CallOption) (PluginListRunningResp, error) {
	return sdk.CallWithCaller[PluginListRunningMsg, PluginListRunningResp](caller, ctx, msg, opts...)
}

// CallPluginManifest issues a synchronous request-response Call for PluginManifestMsg.
func CallPluginManifest(rt sdk.CallerRuntime, ctx context.Context, msg PluginManifestMsg, opts ...sdk.CallOption) (PluginManifestResp, error) {
	return sdk.Call[PluginManifestMsg, PluginManifestResp](rt, ctx, msg, opts...)
}

// CallPluginManifestWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallPluginManifestWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg PluginManifestMsg, opts ...sdk.CallOption) (PluginManifestResp, error) {
	return sdk.CallWithCaller[PluginManifestMsg, PluginManifestResp](caller, ctx, msg, opts...)
}

// CallPluginRestart issues a synchronous request-response Call for PluginRestartMsg.
func CallPluginRestart(rt sdk.CallerRuntime, ctx context.Context, msg PluginRestartMsg, opts ...sdk.CallOption) (PluginRestartResp, error) {
	return sdk.Call[PluginRestartMsg, PluginRestartResp](rt, ctx, msg, opts...)
}

// CallPluginRestartWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallPluginRestartWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg PluginRestartMsg, opts ...sdk.CallOption) (PluginRestartResp, error) {
	return sdk.CallWithCaller[PluginRestartMsg, PluginRestartResp](caller, ctx, msg, opts...)
}

// CallPluginStart issues a synchronous request-response Call for PluginStartMsg.
func CallPluginStart(rt sdk.CallerRuntime, ctx context.Context, msg PluginStartMsg, opts ...sdk.CallOption) (PluginStartResp, error) {
	return sdk.Call[PluginStartMsg, PluginStartResp](rt, ctx, msg, opts...)
}

// CallPluginStartWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallPluginStartWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg PluginStartMsg, opts ...sdk.CallOption) (PluginStartResp, error) {
	return sdk.CallWithCaller[PluginStartMsg, PluginStartResp](caller, ctx, msg, opts...)
}

// CallPluginStatus issues a synchronous request-response Call for PluginStatusMsg.
func CallPluginStatus(rt sdk.CallerRuntime, ctx context.Context, msg PluginStatusMsg, opts ...sdk.CallOption) (PluginStatusResp, error) {
	return sdk.Call[PluginStatusMsg, PluginStatusResp](rt, ctx, msg, opts...)
}

// CallPluginStatusWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallPluginStatusWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg PluginStatusMsg, opts ...sdk.CallOption) (PluginStatusResp, error) {
	return sdk.CallWithCaller[PluginStatusMsg, PluginStatusResp](caller, ctx, msg, opts...)
}

// CallPluginStop issues a synchronous request-response Call for PluginStopMsg.
func CallPluginStop(rt sdk.CallerRuntime, ctx context.Context, msg PluginStopMsg, opts ...sdk.CallOption) (PluginStopResp, error) {
	return sdk.Call[PluginStopMsg, PluginStopResp](rt, ctx, msg, opts...)
}

// CallPluginStopWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallPluginStopWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg PluginStopMsg, opts ...sdk.CallOption) (PluginStopResp, error) {
	return sdk.CallWithCaller[PluginStopMsg, PluginStopResp](caller, ctx, msg, opts...)
}

// EmitPluginRegistered fires a PluginRegisteredEvent event (no response expected).
func EmitPluginRegistered(rt sdk.Runtime, ctx context.Context, msg PluginRegisteredEvent) error {
	return sdk.Emit(rt, ctx, msg)
}

// SubscribePluginRegistered listens for PluginRegisteredEvent events.
func SubscribePluginRegistered(rt sdk.Runtime, ctx context.Context, topic string, handler func(PluginRegisteredEvent, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[PluginRegisteredEvent](rt, ctx, topic, handler)
}

// EmitPluginStarted fires a PluginStartedEvent event (no response expected).
func EmitPluginStarted(rt sdk.Runtime, ctx context.Context, msg PluginStartedEvent) error {
	return sdk.Emit(rt, ctx, msg)
}

// SubscribePluginStarted listens for PluginStartedEvent events.
func SubscribePluginStarted(rt sdk.Runtime, ctx context.Context, topic string, handler func(PluginStartedEvent, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[PluginStartedEvent](rt, ctx, topic, handler)
}

// EmitPluginStopped fires a PluginStoppedEvent event (no response expected).
func EmitPluginStopped(rt sdk.Runtime, ctx context.Context, msg PluginStoppedEvent) error {
	return sdk.Emit(rt, ctx, msg)
}

// SubscribePluginStopped listens for PluginStoppedEvent events.
func SubscribePluginStopped(rt sdk.Runtime, ctx context.Context, topic string, handler func(PluginStoppedEvent, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[PluginStoppedEvent](rt, ctx, topic, handler)
}

