// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Synchronous Call wrappers — one per sdk.Msg/sdk.Resp pair — that
// remove the type-parameter guessing from brainkit.Call.
//
// Instead of:
//
//	resp, err := brainkit.Call[sdk.ToolCallMsg, sdk.ToolCallResp](k, ctx, msg)
//
// write:
//
//	resp, err := brainkit.CallToolCall(k, ctx, msg)
//
// The underlying generic stays exported for advanced uses. These
// wrappers just saturate the type parameters mechanically.
//
// Regenerate: go run ./cmd/sdkgen/ -messages ./sdk -out ./sdk/typed_gen.go -call-out ./call_gen.go
package brainkit

import (
	"context"

	"github.com/brainlet/brainkit/sdk"
)

// CallAgentDiscover issues a synchronous request→response Call for AgentDiscoverMsg and
// returns the decoded AgentDiscoverResp. Equivalent to
// Call[sdk.AgentDiscoverMsg, sdk.AgentDiscoverResp] with the types saturated.
func CallAgentDiscover(k *Kit, ctx context.Context, msg sdk.AgentDiscoverMsg, opts ...CallOption) (sdk.AgentDiscoverResp, error) {
	return Call[sdk.AgentDiscoverMsg, sdk.AgentDiscoverResp](k, ctx, msg, opts...)
}

// CallAgentGetStatus issues a synchronous request→response Call for AgentGetStatusMsg and
// returns the decoded AgentGetStatusResp. Equivalent to
// Call[sdk.AgentGetStatusMsg, sdk.AgentGetStatusResp] with the types saturated.
func CallAgentGetStatus(k *Kit, ctx context.Context, msg sdk.AgentGetStatusMsg, opts ...CallOption) (sdk.AgentGetStatusResp, error) {
	return Call[sdk.AgentGetStatusMsg, sdk.AgentGetStatusResp](k, ctx, msg, opts...)
}

// CallAgentList issues a synchronous request→response Call for AgentListMsg and
// returns the decoded AgentListResp. Equivalent to
// Call[sdk.AgentListMsg, sdk.AgentListResp] with the types saturated.
func CallAgentList(k *Kit, ctx context.Context, msg sdk.AgentListMsg, opts ...CallOption) (sdk.AgentListResp, error) {
	return Call[sdk.AgentListMsg, sdk.AgentListResp](k, ctx, msg, opts...)
}

// CallAgentSetStatus issues a synchronous request→response Call for AgentSetStatusMsg and
// returns the decoded AgentSetStatusResp. Equivalent to
// Call[sdk.AgentSetStatusMsg, sdk.AgentSetStatusResp] with the types saturated.
func CallAgentSetStatus(k *Kit, ctx context.Context, msg sdk.AgentSetStatusMsg, opts ...CallOption) (sdk.AgentSetStatusResp, error) {
	return Call[sdk.AgentSetStatusMsg, sdk.AgentSetStatusResp](k, ctx, msg, opts...)
}

// CallAuditPrune issues a synchronous request→response Call for AuditPruneMsg and
// returns the decoded AuditPruneResp. Equivalent to
// Call[sdk.AuditPruneMsg, sdk.AuditPruneResp] with the types saturated.
func CallAuditPrune(k *Kit, ctx context.Context, msg sdk.AuditPruneMsg, opts ...CallOption) (sdk.AuditPruneResp, error) {
	return Call[sdk.AuditPruneMsg, sdk.AuditPruneResp](k, ctx, msg, opts...)
}

// CallAuditQuery issues a synchronous request→response Call for AuditQueryMsg and
// returns the decoded AuditQueryResp. Equivalent to
// Call[sdk.AuditQueryMsg, sdk.AuditQueryResp] with the types saturated.
func CallAuditQuery(k *Kit, ctx context.Context, msg sdk.AuditQueryMsg, opts ...CallOption) (sdk.AuditQueryResp, error) {
	return Call[sdk.AuditQueryMsg, sdk.AuditQueryResp](k, ctx, msg, opts...)
}

// CallAuditStats issues a synchronous request→response Call for AuditStatsMsg and
// returns the decoded AuditStatsResp. Equivalent to
// Call[sdk.AuditStatsMsg, sdk.AuditStatsResp] with the types saturated.
func CallAuditStats(k *Kit, ctx context.Context, msg sdk.AuditStatsMsg, opts ...CallOption) (sdk.AuditStatsResp, error) {
	return Call[sdk.AuditStatsMsg, sdk.AuditStatsResp](k, ctx, msg, opts...)
}

// CallClusterPeers issues a synchronous request→response Call for ClusterPeersMsg and
// returns the decoded ClusterPeersResp. Equivalent to
// Call[sdk.ClusterPeersMsg, sdk.ClusterPeersResp] with the types saturated.
func CallClusterPeers(k *Kit, ctx context.Context, msg sdk.ClusterPeersMsg, opts ...CallOption) (sdk.ClusterPeersResp, error) {
	return Call[sdk.ClusterPeersMsg, sdk.ClusterPeersResp](k, ctx, msg, opts...)
}

// CallGatewayRouteAdd issues a synchronous request→response Call for GatewayRouteAddMsg and
// returns the decoded GatewayRouteAddResp. Equivalent to
// Call[sdk.GatewayRouteAddMsg, sdk.GatewayRouteAddResp] with the types saturated.
func CallGatewayRouteAdd(k *Kit, ctx context.Context, msg sdk.GatewayRouteAddMsg, opts ...CallOption) (sdk.GatewayRouteAddResp, error) {
	return Call[sdk.GatewayRouteAddMsg, sdk.GatewayRouteAddResp](k, ctx, msg, opts...)
}

// CallGatewayRouteList issues a synchronous request→response Call for GatewayRouteListMsg and
// returns the decoded GatewayRouteListResp. Equivalent to
// Call[sdk.GatewayRouteListMsg, sdk.GatewayRouteListResp] with the types saturated.
func CallGatewayRouteList(k *Kit, ctx context.Context, msg sdk.GatewayRouteListMsg, opts ...CallOption) (sdk.GatewayRouteListResp, error) {
	return Call[sdk.GatewayRouteListMsg, sdk.GatewayRouteListResp](k, ctx, msg, opts...)
}

// CallGatewayRouteRemove issues a synchronous request→response Call for GatewayRouteRemoveMsg and
// returns the decoded GatewayRouteRemoveResp. Equivalent to
// Call[sdk.GatewayRouteRemoveMsg, sdk.GatewayRouteRemoveResp] with the types saturated.
func CallGatewayRouteRemove(k *Kit, ctx context.Context, msg sdk.GatewayRouteRemoveMsg, opts ...CallOption) (sdk.GatewayRouteRemoveResp, error) {
	return Call[sdk.GatewayRouteRemoveMsg, sdk.GatewayRouteRemoveResp](k, ctx, msg, opts...)
}

// CallGatewayStatus issues a synchronous request→response Call for GatewayStatusMsg and
// returns the decoded GatewayStatusResp. Equivalent to
// Call[sdk.GatewayStatusMsg, sdk.GatewayStatusResp] with the types saturated.
func CallGatewayStatus(k *Kit, ctx context.Context, msg sdk.GatewayStatusMsg, opts ...CallOption) (sdk.GatewayStatusResp, error) {
	return Call[sdk.GatewayStatusMsg, sdk.GatewayStatusResp](k, ctx, msg, opts...)
}

// CallKitEval issues a synchronous request→response Call for KitEvalMsg and
// returns the decoded KitEvalResp. Equivalent to
// Call[sdk.KitEvalMsg, sdk.KitEvalResp] with the types saturated.
func CallKitEval(k *Kit, ctx context.Context, msg sdk.KitEvalMsg, opts ...CallOption) (sdk.KitEvalResp, error) {
	return Call[sdk.KitEvalMsg, sdk.KitEvalResp](k, ctx, msg, opts...)
}

// CallKitHealth issues a synchronous request→response Call for KitHealthMsg and
// returns the decoded KitHealthResp. Equivalent to
// Call[sdk.KitHealthMsg, sdk.KitHealthResp] with the types saturated.
func CallKitHealth(k *Kit, ctx context.Context, msg sdk.KitHealthMsg, opts ...CallOption) (sdk.KitHealthResp, error) {
	return Call[sdk.KitHealthMsg, sdk.KitHealthResp](k, ctx, msg, opts...)
}

// CallKitSend issues a synchronous request→response Call for KitSendMsg and
// returns the decoded KitSendResp. Equivalent to
// Call[sdk.KitSendMsg, sdk.KitSendResp] with the types saturated.
func CallKitSend(k *Kit, ctx context.Context, msg sdk.KitSendMsg, opts ...CallOption) (sdk.KitSendResp, error) {
	return Call[sdk.KitSendMsg, sdk.KitSendResp](k, ctx, msg, opts...)
}

// CallKitSetDraining issues a synchronous request→response Call for KitSetDrainingMsg and
// returns the decoded KitSetDrainingResp. Equivalent to
// Call[sdk.KitSetDrainingMsg, sdk.KitSetDrainingResp] with the types saturated.
func CallKitSetDraining(k *Kit, ctx context.Context, msg sdk.KitSetDrainingMsg, opts ...CallOption) (sdk.KitSetDrainingResp, error) {
	return Call[sdk.KitSetDrainingMsg, sdk.KitSetDrainingResp](k, ctx, msg, opts...)
}

// CallMcpCallTool issues a synchronous request→response Call for McpCallToolMsg and
// returns the decoded McpCallToolResp. Equivalent to
// Call[sdk.McpCallToolMsg, sdk.McpCallToolResp] with the types saturated.
func CallMcpCallTool(k *Kit, ctx context.Context, msg sdk.McpCallToolMsg, opts ...CallOption) (sdk.McpCallToolResp, error) {
	return Call[sdk.McpCallToolMsg, sdk.McpCallToolResp](k, ctx, msg, opts...)
}

// CallMcpListTools issues a synchronous request→response Call for McpListToolsMsg and
// returns the decoded McpListToolsResp. Equivalent to
// Call[sdk.McpListToolsMsg, sdk.McpListToolsResp] with the types saturated.
func CallMcpListTools(k *Kit, ctx context.Context, msg sdk.McpListToolsMsg, opts ...CallOption) (sdk.McpListToolsResp, error) {
	return Call[sdk.McpListToolsMsg, sdk.McpListToolsResp](k, ctx, msg, opts...)
}

// CallMetricsGet issues a synchronous request→response Call for MetricsGetMsg and
// returns the decoded MetricsGetResp. Equivalent to
// Call[sdk.MetricsGetMsg, sdk.MetricsGetResp] with the types saturated.
func CallMetricsGet(k *Kit, ctx context.Context, msg sdk.MetricsGetMsg, opts ...CallOption) (sdk.MetricsGetResp, error) {
	return Call[sdk.MetricsGetMsg, sdk.MetricsGetResp](k, ctx, msg, opts...)
}

// CallPackageDeploy issues a synchronous request→response Call for PackageDeployMsg and
// returns the decoded PackageDeployResp. Equivalent to
// Call[sdk.PackageDeployMsg, sdk.PackageDeployResp] with the types saturated.
func CallPackageDeploy(k *Kit, ctx context.Context, msg sdk.PackageDeployMsg, opts ...CallOption) (sdk.PackageDeployResp, error) {
	return Call[sdk.PackageDeployMsg, sdk.PackageDeployResp](k, ctx, msg, opts...)
}

// CallPackageDeployInfo issues a synchronous request→response Call for PackageDeployInfoMsg and
// returns the decoded PackageDeployInfoResp. Equivalent to
// Call[sdk.PackageDeployInfoMsg, sdk.PackageDeployInfoResp] with the types saturated.
func CallPackageDeployInfo(k *Kit, ctx context.Context, msg sdk.PackageDeployInfoMsg, opts ...CallOption) (sdk.PackageDeployInfoResp, error) {
	return Call[sdk.PackageDeployInfoMsg, sdk.PackageDeployInfoResp](k, ctx, msg, opts...)
}

// CallPackageListDeployed issues a synchronous request→response Call for PackageListDeployedMsg and
// returns the decoded PackageListDeployedResp. Equivalent to
// Call[sdk.PackageListDeployedMsg, sdk.PackageListDeployedResp] with the types saturated.
func CallPackageListDeployed(k *Kit, ctx context.Context, msg sdk.PackageListDeployedMsg, opts ...CallOption) (sdk.PackageListDeployedResp, error) {
	return Call[sdk.PackageListDeployedMsg, sdk.PackageListDeployedResp](k, ctx, msg, opts...)
}

// CallPackageTeardown issues a synchronous request→response Call for PackageTeardownMsg and
// returns the decoded PackageTeardownResp. Equivalent to
// Call[sdk.PackageTeardownMsg, sdk.PackageTeardownResp] with the types saturated.
func CallPackageTeardown(k *Kit, ctx context.Context, msg sdk.PackageTeardownMsg, opts ...CallOption) (sdk.PackageTeardownResp, error) {
	return Call[sdk.PackageTeardownMsg, sdk.PackageTeardownResp](k, ctx, msg, opts...)
}

// CallPeersList issues a synchronous request→response Call for PeersListMsg and
// returns the decoded PeersListResp. Equivalent to
// Call[sdk.PeersListMsg, sdk.PeersListResp] with the types saturated.
func CallPeersList(k *Kit, ctx context.Context, msg sdk.PeersListMsg, opts ...CallOption) (sdk.PeersListResp, error) {
	return Call[sdk.PeersListMsg, sdk.PeersListResp](k, ctx, msg, opts...)
}

// CallPeersResolve issues a synchronous request→response Call for PeersResolveMsg and
// returns the decoded PeersResolveResp. Equivalent to
// Call[sdk.PeersResolveMsg, sdk.PeersResolveResp] with the types saturated.
func CallPeersResolve(k *Kit, ctx context.Context, msg sdk.PeersResolveMsg, opts ...CallOption) (sdk.PeersResolveResp, error) {
	return Call[sdk.PeersResolveMsg, sdk.PeersResolveResp](k, ctx, msg, opts...)
}

// CallPluginListRunning issues a synchronous request→response Call for PluginListRunningMsg and
// returns the decoded PluginListRunningResp. Equivalent to
// Call[sdk.PluginListRunningMsg, sdk.PluginListRunningResp] with the types saturated.
func CallPluginListRunning(k *Kit, ctx context.Context, msg sdk.PluginListRunningMsg, opts ...CallOption) (sdk.PluginListRunningResp, error) {
	return Call[sdk.PluginListRunningMsg, sdk.PluginListRunningResp](k, ctx, msg, opts...)
}

// CallPluginManifest issues a synchronous request→response Call for PluginManifestMsg and
// returns the decoded PluginManifestResp. Equivalent to
// Call[sdk.PluginManifestMsg, sdk.PluginManifestResp] with the types saturated.
func CallPluginManifest(k *Kit, ctx context.Context, msg sdk.PluginManifestMsg, opts ...CallOption) (sdk.PluginManifestResp, error) {
	return Call[sdk.PluginManifestMsg, sdk.PluginManifestResp](k, ctx, msg, opts...)
}

// CallPluginRestart issues a synchronous request→response Call for PluginRestartMsg and
// returns the decoded PluginRestartResp. Equivalent to
// Call[sdk.PluginRestartMsg, sdk.PluginRestartResp] with the types saturated.
func CallPluginRestart(k *Kit, ctx context.Context, msg sdk.PluginRestartMsg, opts ...CallOption) (sdk.PluginRestartResp, error) {
	return Call[sdk.PluginRestartMsg, sdk.PluginRestartResp](k, ctx, msg, opts...)
}

// CallPluginStart issues a synchronous request→response Call for PluginStartMsg and
// returns the decoded PluginStartResp. Equivalent to
// Call[sdk.PluginStartMsg, sdk.PluginStartResp] with the types saturated.
func CallPluginStart(k *Kit, ctx context.Context, msg sdk.PluginStartMsg, opts ...CallOption) (sdk.PluginStartResp, error) {
	return Call[sdk.PluginStartMsg, sdk.PluginStartResp](k, ctx, msg, opts...)
}

// CallPluginStatus issues a synchronous request→response Call for PluginStatusMsg and
// returns the decoded PluginStatusResp. Equivalent to
// Call[sdk.PluginStatusMsg, sdk.PluginStatusResp] with the types saturated.
func CallPluginStatus(k *Kit, ctx context.Context, msg sdk.PluginStatusMsg, opts ...CallOption) (sdk.PluginStatusResp, error) {
	return Call[sdk.PluginStatusMsg, sdk.PluginStatusResp](k, ctx, msg, opts...)
}

// CallPluginStop issues a synchronous request→response Call for PluginStopMsg and
// returns the decoded PluginStopResp. Equivalent to
// Call[sdk.PluginStopMsg, sdk.PluginStopResp] with the types saturated.
func CallPluginStop(k *Kit, ctx context.Context, msg sdk.PluginStopMsg, opts ...CallOption) (sdk.PluginStopResp, error) {
	return Call[sdk.PluginStopMsg, sdk.PluginStopResp](k, ctx, msg, opts...)
}

// CallProviderAdd issues a synchronous request→response Call for ProviderAddMsg and
// returns the decoded ProviderAddResp. Equivalent to
// Call[sdk.ProviderAddMsg, sdk.ProviderAddResp] with the types saturated.
func CallProviderAdd(k *Kit, ctx context.Context, msg sdk.ProviderAddMsg, opts ...CallOption) (sdk.ProviderAddResp, error) {
	return Call[sdk.ProviderAddMsg, sdk.ProviderAddResp](k, ctx, msg, opts...)
}

// CallProviderRemove issues a synchronous request→response Call for ProviderRemoveMsg and
// returns the decoded ProviderRemoveResp. Equivalent to
// Call[sdk.ProviderRemoveMsg, sdk.ProviderRemoveResp] with the types saturated.
func CallProviderRemove(k *Kit, ctx context.Context, msg sdk.ProviderRemoveMsg, opts ...CallOption) (sdk.ProviderRemoveResp, error) {
	return Call[sdk.ProviderRemoveMsg, sdk.ProviderRemoveResp](k, ctx, msg, opts...)
}

// CallRegistryHas issues a synchronous request→response Call for RegistryHasMsg and
// returns the decoded RegistryHasResp. Equivalent to
// Call[sdk.RegistryHasMsg, sdk.RegistryHasResp] with the types saturated.
func CallRegistryHas(k *Kit, ctx context.Context, msg sdk.RegistryHasMsg, opts ...CallOption) (sdk.RegistryHasResp, error) {
	return Call[sdk.RegistryHasMsg, sdk.RegistryHasResp](k, ctx, msg, opts...)
}

// CallRegistryList issues a synchronous request→response Call for RegistryListMsg and
// returns the decoded RegistryListResp. Equivalent to
// Call[sdk.RegistryListMsg, sdk.RegistryListResp] with the types saturated.
func CallRegistryList(k *Kit, ctx context.Context, msg sdk.RegistryListMsg, opts ...CallOption) (sdk.RegistryListResp, error) {
	return Call[sdk.RegistryListMsg, sdk.RegistryListResp](k, ctx, msg, opts...)
}

// CallRegistryResolve issues a synchronous request→response Call for RegistryResolveMsg and
// returns the decoded RegistryResolveResp. Equivalent to
// Call[sdk.RegistryResolveMsg, sdk.RegistryResolveResp] with the types saturated.
func CallRegistryResolve(k *Kit, ctx context.Context, msg sdk.RegistryResolveMsg, opts ...CallOption) (sdk.RegistryResolveResp, error) {
	return Call[sdk.RegistryResolveMsg, sdk.RegistryResolveResp](k, ctx, msg, opts...)
}

// CallScheduleCancel issues a synchronous request→response Call for ScheduleCancelMsg and
// returns the decoded ScheduleCancelResp. Equivalent to
// Call[sdk.ScheduleCancelMsg, sdk.ScheduleCancelResp] with the types saturated.
func CallScheduleCancel(k *Kit, ctx context.Context, msg sdk.ScheduleCancelMsg, opts ...CallOption) (sdk.ScheduleCancelResp, error) {
	return Call[sdk.ScheduleCancelMsg, sdk.ScheduleCancelResp](k, ctx, msg, opts...)
}

// CallScheduleCreate issues a synchronous request→response Call for ScheduleCreateMsg and
// returns the decoded ScheduleCreateResp. Equivalent to
// Call[sdk.ScheduleCreateMsg, sdk.ScheduleCreateResp] with the types saturated.
func CallScheduleCreate(k *Kit, ctx context.Context, msg sdk.ScheduleCreateMsg, opts ...CallOption) (sdk.ScheduleCreateResp, error) {
	return Call[sdk.ScheduleCreateMsg, sdk.ScheduleCreateResp](k, ctx, msg, opts...)
}

// CallScheduleList issues a synchronous request→response Call for ScheduleListMsg and
// returns the decoded ScheduleListResp. Equivalent to
// Call[sdk.ScheduleListMsg, sdk.ScheduleListResp] with the types saturated.
func CallScheduleList(k *Kit, ctx context.Context, msg sdk.ScheduleListMsg, opts ...CallOption) (sdk.ScheduleListResp, error) {
	return Call[sdk.ScheduleListMsg, sdk.ScheduleListResp](k, ctx, msg, opts...)
}

// CallSecretsDelete issues a synchronous request→response Call for SecretsDeleteMsg and
// returns the decoded SecretsDeleteResp. Equivalent to
// Call[sdk.SecretsDeleteMsg, sdk.SecretsDeleteResp] with the types saturated.
func CallSecretsDelete(k *Kit, ctx context.Context, msg sdk.SecretsDeleteMsg, opts ...CallOption) (sdk.SecretsDeleteResp, error) {
	return Call[sdk.SecretsDeleteMsg, sdk.SecretsDeleteResp](k, ctx, msg, opts...)
}

// CallSecretsGet issues a synchronous request→response Call for SecretsGetMsg and
// returns the decoded SecretsGetResp. Equivalent to
// Call[sdk.SecretsGetMsg, sdk.SecretsGetResp] with the types saturated.
func CallSecretsGet(k *Kit, ctx context.Context, msg sdk.SecretsGetMsg, opts ...CallOption) (sdk.SecretsGetResp, error) {
	return Call[sdk.SecretsGetMsg, sdk.SecretsGetResp](k, ctx, msg, opts...)
}

// CallSecretsList issues a synchronous request→response Call for SecretsListMsg and
// returns the decoded SecretsListResp. Equivalent to
// Call[sdk.SecretsListMsg, sdk.SecretsListResp] with the types saturated.
func CallSecretsList(k *Kit, ctx context.Context, msg sdk.SecretsListMsg, opts ...CallOption) (sdk.SecretsListResp, error) {
	return Call[sdk.SecretsListMsg, sdk.SecretsListResp](k, ctx, msg, opts...)
}

// CallSecretsRotate issues a synchronous request→response Call for SecretsRotateMsg and
// returns the decoded SecretsRotateResp. Equivalent to
// Call[sdk.SecretsRotateMsg, sdk.SecretsRotateResp] with the types saturated.
func CallSecretsRotate(k *Kit, ctx context.Context, msg sdk.SecretsRotateMsg, opts ...CallOption) (sdk.SecretsRotateResp, error) {
	return Call[sdk.SecretsRotateMsg, sdk.SecretsRotateResp](k, ctx, msg, opts...)
}

// CallSecretsSet issues a synchronous request→response Call for SecretsSetMsg and
// returns the decoded SecretsSetResp. Equivalent to
// Call[sdk.SecretsSetMsg, sdk.SecretsSetResp] with the types saturated.
func CallSecretsSet(k *Kit, ctx context.Context, msg sdk.SecretsSetMsg, opts ...CallOption) (sdk.SecretsSetResp, error) {
	return Call[sdk.SecretsSetMsg, sdk.SecretsSetResp](k, ctx, msg, opts...)
}

// CallStorageAdd issues a synchronous request→response Call for StorageAddMsg and
// returns the decoded StorageAddResp. Equivalent to
// Call[sdk.StorageAddMsg, sdk.StorageAddResp] with the types saturated.
func CallStorageAdd(k *Kit, ctx context.Context, msg sdk.StorageAddMsg, opts ...CallOption) (sdk.StorageAddResp, error) {
	return Call[sdk.StorageAddMsg, sdk.StorageAddResp](k, ctx, msg, opts...)
}

// CallStorageRemove issues a synchronous request→response Call for StorageRemoveMsg and
// returns the decoded StorageRemoveResp. Equivalent to
// Call[sdk.StorageRemoveMsg, sdk.StorageRemoveResp] with the types saturated.
func CallStorageRemove(k *Kit, ctx context.Context, msg sdk.StorageRemoveMsg, opts ...CallOption) (sdk.StorageRemoveResp, error) {
	return Call[sdk.StorageRemoveMsg, sdk.StorageRemoveResp](k, ctx, msg, opts...)
}

// CallTestRun issues a synchronous request→response Call for TestRunMsg and
// returns the decoded TestRunResp. Equivalent to
// Call[sdk.TestRunMsg, sdk.TestRunResp] with the types saturated.
func CallTestRun(k *Kit, ctx context.Context, msg sdk.TestRunMsg, opts ...CallOption) (sdk.TestRunResp, error) {
	return Call[sdk.TestRunMsg, sdk.TestRunResp](k, ctx, msg, opts...)
}

// CallToolCall issues a synchronous request→response Call for ToolCallMsg and
// returns the decoded ToolCallResp. Equivalent to
// Call[sdk.ToolCallMsg, sdk.ToolCallResp] with the types saturated.
func CallToolCall(k *Kit, ctx context.Context, msg sdk.ToolCallMsg, opts ...CallOption) (sdk.ToolCallResp, error) {
	return Call[sdk.ToolCallMsg, sdk.ToolCallResp](k, ctx, msg, opts...)
}

// CallToolList issues a synchronous request→response Call for ToolListMsg and
// returns the decoded ToolListResp. Equivalent to
// Call[sdk.ToolListMsg, sdk.ToolListResp] with the types saturated.
func CallToolList(k *Kit, ctx context.Context, msg sdk.ToolListMsg, opts ...CallOption) (sdk.ToolListResp, error) {
	return Call[sdk.ToolListMsg, sdk.ToolListResp](k, ctx, msg, opts...)
}

// CallToolResolve issues a synchronous request→response Call for ToolResolveMsg and
// returns the decoded ToolResolveResp. Equivalent to
// Call[sdk.ToolResolveMsg, sdk.ToolResolveResp] with the types saturated.
func CallToolResolve(k *Kit, ctx context.Context, msg sdk.ToolResolveMsg, opts ...CallOption) (sdk.ToolResolveResp, error) {
	return Call[sdk.ToolResolveMsg, sdk.ToolResolveResp](k, ctx, msg, opts...)
}

// CallTraceGet issues a synchronous request→response Call for TraceGetMsg and
// returns the decoded TraceGetResp. Equivalent to
// Call[sdk.TraceGetMsg, sdk.TraceGetResp] with the types saturated.
func CallTraceGet(k *Kit, ctx context.Context, msg sdk.TraceGetMsg, opts ...CallOption) (sdk.TraceGetResp, error) {
	return Call[sdk.TraceGetMsg, sdk.TraceGetResp](k, ctx, msg, opts...)
}

// CallTraceList issues a synchronous request→response Call for TraceListMsg and
// returns the decoded TraceListResp. Equivalent to
// Call[sdk.TraceListMsg, sdk.TraceListResp] with the types saturated.
func CallTraceList(k *Kit, ctx context.Context, msg sdk.TraceListMsg, opts ...CallOption) (sdk.TraceListResp, error) {
	return Call[sdk.TraceListMsg, sdk.TraceListResp](k, ctx, msg, opts...)
}

// CallVectorAdd issues a synchronous request→response Call for VectorAddMsg and
// returns the decoded VectorAddResp. Equivalent to
// Call[sdk.VectorAddMsg, sdk.VectorAddResp] with the types saturated.
func CallVectorAdd(k *Kit, ctx context.Context, msg sdk.VectorAddMsg, opts ...CallOption) (sdk.VectorAddResp, error) {
	return Call[sdk.VectorAddMsg, sdk.VectorAddResp](k, ctx, msg, opts...)
}

// CallVectorRemove issues a synchronous request→response Call for VectorRemoveMsg and
// returns the decoded VectorRemoveResp. Equivalent to
// Call[sdk.VectorRemoveMsg, sdk.VectorRemoveResp] with the types saturated.
func CallVectorRemove(k *Kit, ctx context.Context, msg sdk.VectorRemoveMsg, opts ...CallOption) (sdk.VectorRemoveResp, error) {
	return Call[sdk.VectorRemoveMsg, sdk.VectorRemoveResp](k, ctx, msg, opts...)
}

// CallWorkflowCancel issues a synchronous request→response Call for WorkflowCancelMsg and
// returns the decoded WorkflowCancelResp. Equivalent to
// Call[sdk.WorkflowCancelMsg, sdk.WorkflowCancelResp] with the types saturated.
func CallWorkflowCancel(k *Kit, ctx context.Context, msg sdk.WorkflowCancelMsg, opts ...CallOption) (sdk.WorkflowCancelResp, error) {
	return Call[sdk.WorkflowCancelMsg, sdk.WorkflowCancelResp](k, ctx, msg, opts...)
}

// CallWorkflowList issues a synchronous request→response Call for WorkflowListMsg and
// returns the decoded WorkflowListResp. Equivalent to
// Call[sdk.WorkflowListMsg, sdk.WorkflowListResp] with the types saturated.
func CallWorkflowList(k *Kit, ctx context.Context, msg sdk.WorkflowListMsg, opts ...CallOption) (sdk.WorkflowListResp, error) {
	return Call[sdk.WorkflowListMsg, sdk.WorkflowListResp](k, ctx, msg, opts...)
}

// CallWorkflowRestart issues a synchronous request→response Call for WorkflowRestartMsg and
// returns the decoded WorkflowRestartResp. Equivalent to
// Call[sdk.WorkflowRestartMsg, sdk.WorkflowRestartResp] with the types saturated.
func CallWorkflowRestart(k *Kit, ctx context.Context, msg sdk.WorkflowRestartMsg, opts ...CallOption) (sdk.WorkflowRestartResp, error) {
	return Call[sdk.WorkflowRestartMsg, sdk.WorkflowRestartResp](k, ctx, msg, opts...)
}

// CallWorkflowResume issues a synchronous request→response Call for WorkflowResumeMsg and
// returns the decoded WorkflowResumeResp. Equivalent to
// Call[sdk.WorkflowResumeMsg, sdk.WorkflowResumeResp] with the types saturated.
func CallWorkflowResume(k *Kit, ctx context.Context, msg sdk.WorkflowResumeMsg, opts ...CallOption) (sdk.WorkflowResumeResp, error) {
	return Call[sdk.WorkflowResumeMsg, sdk.WorkflowResumeResp](k, ctx, msg, opts...)
}

// CallWorkflowRuns issues a synchronous request→response Call for WorkflowRunsMsg and
// returns the decoded WorkflowRunsResp. Equivalent to
// Call[sdk.WorkflowRunsMsg, sdk.WorkflowRunsResp] with the types saturated.
func CallWorkflowRuns(k *Kit, ctx context.Context, msg sdk.WorkflowRunsMsg, opts ...CallOption) (sdk.WorkflowRunsResp, error) {
	return Call[sdk.WorkflowRunsMsg, sdk.WorkflowRunsResp](k, ctx, msg, opts...)
}

// CallWorkflowStart issues a synchronous request→response Call for WorkflowStartMsg and
// returns the decoded WorkflowStartResp. Equivalent to
// Call[sdk.WorkflowStartMsg, sdk.WorkflowStartResp] with the types saturated.
func CallWorkflowStart(k *Kit, ctx context.Context, msg sdk.WorkflowStartMsg, opts ...CallOption) (sdk.WorkflowStartResp, error) {
	return Call[sdk.WorkflowStartMsg, sdk.WorkflowStartResp](k, ctx, msg, opts...)
}

// CallWorkflowStartAsync issues a synchronous request→response Call for WorkflowStartAsyncMsg and
// returns the decoded WorkflowStartAsyncResp. Equivalent to
// Call[sdk.WorkflowStartAsyncMsg, sdk.WorkflowStartAsyncResp] with the types saturated.
func CallWorkflowStartAsync(k *Kit, ctx context.Context, msg sdk.WorkflowStartAsyncMsg, opts ...CallOption) (sdk.WorkflowStartAsyncResp, error) {
	return Call[sdk.WorkflowStartAsyncMsg, sdk.WorkflowStartAsyncResp](k, ctx, msg, opts...)
}

// CallWorkflowStatus issues a synchronous request→response Call for WorkflowStatusMsg and
// returns the decoded WorkflowStatusResp. Equivalent to
// Call[sdk.WorkflowStatusMsg, sdk.WorkflowStatusResp] with the types saturated.
func CallWorkflowStatus(k *Kit, ctx context.Context, msg sdk.WorkflowStatusMsg, opts ...CallOption) (sdk.WorkflowStatusResp, error) {
	return Call[sdk.WorkflowStatusMsg, sdk.WorkflowStatusResp](k, ctx, msg, opts...)
}

