// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit call/emit/subscribe.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// Low-level publish/reply-topic helpers are intentionally not generated; use
// the generic SDK protocol primitives directly when testing transport behavior.
//
// Regenerate with cmd/sdkgen from this repository.
package toolmsg

import (
	"context"

	bkmodule "github.com/brainlet/brainkit/module"
	"github.com/brainlet/brainkit/sdk"
)

// CallToolCall issues a synchronous request-response Call for ToolCallMsg.
func CallToolCall(rt sdk.CallerRuntime, ctx context.Context, msg ToolCallMsg, opts ...sdk.CallOption) (ToolCallResp, error) {
	return sdk.Call[ToolCallMsg, ToolCallResp](rt, ctx, msg, opts...)
}

// CallToolCallWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallToolCallWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg ToolCallMsg, opts ...sdk.CallOption) (ToolCallResp, error) {
	return sdk.CallWithCaller[ToolCallMsg, ToolCallResp](caller, ctx, msg, opts...)
}

// CallToolList issues a synchronous request-response Call for ToolListMsg.
func CallToolList(rt sdk.CallerRuntime, ctx context.Context, msg ToolListMsg, opts ...sdk.CallOption) (ToolListResp, error) {
	return sdk.Call[ToolListMsg, ToolListResp](rt, ctx, msg, opts...)
}

// CallToolListWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallToolListWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg ToolListMsg, opts ...sdk.CallOption) (ToolListResp, error) {
	return sdk.CallWithCaller[ToolListMsg, ToolListResp](caller, ctx, msg, opts...)
}

// CallToolResolve issues a synchronous request-response Call for ToolResolveMsg.
func CallToolResolve(rt sdk.CallerRuntime, ctx context.Context, msg ToolResolveMsg, opts ...sdk.CallOption) (ToolResolveResp, error) {
	return sdk.Call[ToolResolveMsg, ToolResolveResp](rt, ctx, msg, opts...)
}

// CallToolResolveWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallToolResolveWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg ToolResolveMsg, opts ...sdk.CallOption) (ToolResolveResp, error) {
	return sdk.CallWithCaller[ToolResolveMsg, ToolResolveResp](caller, ctx, msg, opts...)
}

