// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit publish/subscribe/call/emit.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// The underlying generic publish/call patterns are unchanged. These wrappers
// just add type safety.
//
// Regenerate with cmd/sdkgen from this repository.
package toolmsg

import (
	"context"

	"github.com/brainlet/brainkit/sdk"
)

// PublishToolCall publishes a ToolCallMsg and returns routing info for the response.
func PublishToolCall(rt sdk.Runtime, ctx context.Context, msg ToolCallMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeToolCallResp subscribes to the response topic for a ToolCallMsg command.
func SubscribeToolCallResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(ToolCallResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[ToolCallResp](rt, ctx, topic, handler)
}

// CallToolCall issues a synchronous request-response Call for ToolCallMsg.
func CallToolCall(rt sdk.CallerRuntime, ctx context.Context, msg ToolCallMsg, opts ...sdk.CallOption) (ToolCallResp, error) {
	return sdk.Call[ToolCallMsg, ToolCallResp](rt, ctx, msg, opts...)
}

// PublishToolList publishes a ToolListMsg and returns routing info for the response.
func PublishToolList(rt sdk.Runtime, ctx context.Context, msg ToolListMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeToolListResp subscribes to the response topic for a ToolListMsg command.
func SubscribeToolListResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(ToolListResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[ToolListResp](rt, ctx, topic, handler)
}

// CallToolList issues a synchronous request-response Call for ToolListMsg.
func CallToolList(rt sdk.CallerRuntime, ctx context.Context, msg ToolListMsg, opts ...sdk.CallOption) (ToolListResp, error) {
	return sdk.Call[ToolListMsg, ToolListResp](rt, ctx, msg, opts...)
}

// PublishToolResolve publishes a ToolResolveMsg and returns routing info for the response.
func PublishToolResolve(rt sdk.Runtime, ctx context.Context, msg ToolResolveMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeToolResolveResp subscribes to the response topic for a ToolResolveMsg command.
func SubscribeToolResolveResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(ToolResolveResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[ToolResolveResp](rt, ctx, topic, handler)
}

// CallToolResolve issues a synchronous request-response Call for ToolResolveMsg.
func CallToolResolve(rt sdk.CallerRuntime, ctx context.Context, msg ToolResolveMsg, opts ...sdk.CallOption) (ToolResolveResp, error) {
	return sdk.Call[ToolResolveMsg, ToolResolveResp](rt, ctx, msg, opts...)
}

