// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit publish/subscribe/call/emit.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// The underlying generic publish/call patterns are unchanged. These wrappers
// just add type safety.
//
// Regenerate with cmd/sdkgen from this repository.
package messaging

import (
	"context"

	"github.com/brainlet/brainkit/sdk"
)

// PublishKitSend publishes a KitSendMsg and returns routing info for the response.
func PublishKitSend(rt sdk.Runtime, ctx context.Context, msg KitSendMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeKitSendResp subscribes to the response topic for a KitSendMsg command.
func SubscribeKitSendResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(KitSendResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[KitSendResp](rt, ctx, topic, handler)
}

// CallKitSend issues a synchronous request-response Call for KitSendMsg.
func CallKitSend(rt sdk.CallerRuntime, ctx context.Context, msg KitSendMsg, opts ...sdk.CallOption) (KitSendResp, error) {
	return sdk.Call[KitSendMsg, KitSendResp](rt, ctx, msg, opts...)
}

