// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit call/emit/subscribe.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// Low-level publish/reply-topic helpers are intentionally not generated; use
// the generic SDK protocol primitives directly when testing transport behavior.
//
// Regenerate with cmd/sdkgen from this repository.
package messaging

import (
	"context"

	bkmodule "github.com/brainlet/brainkit/module"
	"github.com/brainlet/brainkit/sdk"
)

// CallKitSend issues a synchronous request-response Call for KitSendMsg.
func CallKitSend(rt sdk.CallerRuntime, ctx context.Context, msg KitSendMsg, opts ...sdk.CallOption) (KitSendResp, error) {
	return sdk.Call[KitSendMsg, KitSendResp](rt, ctx, msg, opts...)
}

// CallKitSendWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallKitSendWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg KitSendMsg, opts ...sdk.CallOption) (KitSendResp, error) {
	return sdk.CallWithCaller[KitSendMsg, KitSendResp](caller, ctx, msg, opts...)
}

