// Code generated by brainkit message tooling; DO NOT EDIT.
package browsermsg

import (
	"context"

	bkmodule "github.com/brainlet/brainkit/module"
	"github.com/brainlet/brainkit/sdk"
)

func CallBrowserSessionLaunch(rt sdk.CallerRuntime, ctx context.Context, msg BrowserSessionLaunchMsg, opts ...sdk.CallOption) (BrowserSessionLaunchResp, error) {
	return sdk.Call[BrowserSessionLaunchMsg, BrowserSessionLaunchResp](rt, ctx, msg, opts...)
}

func CallBrowserSessionLaunchWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg BrowserSessionLaunchMsg, opts ...sdk.CallOption) (BrowserSessionLaunchResp, error) {
	return sdk.CallWithCaller[BrowserSessionLaunchMsg, BrowserSessionLaunchResp](caller, ctx, msg, opts...)
}

func CallBrowserSessionClose(rt sdk.CallerRuntime, ctx context.Context, msg BrowserSessionCloseMsg, opts ...sdk.CallOption) (BrowserSessionCloseResp, error) {
	return sdk.Call[BrowserSessionCloseMsg, BrowserSessionCloseResp](rt, ctx, msg, opts...)
}

func CallBrowserSessionCloseWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg BrowserSessionCloseMsg, opts ...sdk.CallOption) (BrowserSessionCloseResp, error) {
	return sdk.CallWithCaller[BrowserSessionCloseMsg, BrowserSessionCloseResp](caller, ctx, msg, opts...)
}

func CallBrowserSessionList(rt sdk.CallerRuntime, ctx context.Context, msg BrowserSessionListMsg, opts ...sdk.CallOption) (BrowserSessionListResp, error) {
	return sdk.Call[BrowserSessionListMsg, BrowserSessionListResp](rt, ctx, msg, opts...)
}

func CallBrowserSessionListWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg BrowserSessionListMsg, opts ...sdk.CallOption) (BrowserSessionListResp, error) {
	return sdk.CallWithCaller[BrowserSessionListMsg, BrowserSessionListResp](caller, ctx, msg, opts...)
}
