// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit publish/subscribe/call/emit.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// The underlying generic publish/call patterns are unchanged. These wrappers
// just add type safety.
//
// Regenerate with cmd/sdkgen from this repository.
package control

import (
	"context"

	"github.com/brainlet/brainkit/sdk"
)

// PublishClusterPeers publishes a ClusterPeersMsg and returns routing info for the response.
func PublishClusterPeers(rt sdk.Runtime, ctx context.Context, msg ClusterPeersMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeClusterPeersResp subscribes to the response topic for a ClusterPeersMsg command.
func SubscribeClusterPeersResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(ClusterPeersResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[ClusterPeersResp](rt, ctx, topic, handler)
}

// CallClusterPeers issues a synchronous request-response Call for ClusterPeersMsg.
func CallClusterPeers(rt sdk.CallerRuntime, ctx context.Context, msg ClusterPeersMsg, opts ...sdk.CallOption) (ClusterPeersResp, error) {
	return sdk.Call[ClusterPeersMsg, ClusterPeersResp](rt, ctx, msg, opts...)
}

// PublishKitSetDraining publishes a KitSetDrainingMsg and returns routing info for the response.
func PublishKitSetDraining(rt sdk.Runtime, ctx context.Context, msg KitSetDrainingMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeKitSetDrainingResp subscribes to the response topic for a KitSetDrainingMsg command.
func SubscribeKitSetDrainingResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(KitSetDrainingResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[KitSetDrainingResp](rt, ctx, topic, handler)
}

// CallKitSetDraining issues a synchronous request-response Call for KitSetDrainingMsg.
func CallKitSetDraining(rt sdk.CallerRuntime, ctx context.Context, msg KitSetDrainingMsg, opts ...sdk.CallOption) (KitSetDrainingResp, error) {
	return sdk.Call[KitSetDrainingMsg, KitSetDrainingResp](rt, ctx, msg, opts...)
}

