// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit call/emit/subscribe.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// Low-level publish/reply-topic helpers are intentionally not generated; use
// the generic SDK protocol primitives directly when testing transport behavior.
//
// Regenerate with cmd/sdkgen from this repository.
package control

import (
	"context"

	bkmodule "github.com/brainlet/brainkit/module"
	"github.com/brainlet/brainkit/sdk"
)

// CallClusterPeers issues a synchronous request-response Call for ClusterPeersMsg.
func CallClusterPeers(rt sdk.CallerRuntime, ctx context.Context, msg ClusterPeersMsg, opts ...sdk.CallOption) (ClusterPeersResp, error) {
	return sdk.Call[ClusterPeersMsg, ClusterPeersResp](rt, ctx, msg, opts...)
}

// CallClusterPeersWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallClusterPeersWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg ClusterPeersMsg, opts ...sdk.CallOption) (ClusterPeersResp, error) {
	return sdk.CallWithCaller[ClusterPeersMsg, ClusterPeersResp](caller, ctx, msg, opts...)
}

// CallKitLifecycle issues a synchronous request-response Call for KitLifecycleMsg.
func CallKitLifecycle(rt sdk.CallerRuntime, ctx context.Context, msg KitLifecycleMsg, opts ...sdk.CallOption) (KitLifecycleResp, error) {
	return sdk.Call[KitLifecycleMsg, KitLifecycleResp](rt, ctx, msg, opts...)
}

// CallKitLifecycleWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallKitLifecycleWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg KitLifecycleMsg, opts ...sdk.CallOption) (KitLifecycleResp, error) {
	return sdk.CallWithCaller[KitLifecycleMsg, KitLifecycleResp](caller, ctx, msg, opts...)
}

// CallKitModuleDescribe issues a synchronous request-response Call for KitModuleDescribeMsg.
func CallKitModuleDescribe(rt sdk.CallerRuntime, ctx context.Context, msg KitModuleDescribeMsg, opts ...sdk.CallOption) (KitModuleDescribeResp, error) {
	return sdk.Call[KitModuleDescribeMsg, KitModuleDescribeResp](rt, ctx, msg, opts...)
}

// CallKitModuleDescribeWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallKitModuleDescribeWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg KitModuleDescribeMsg, opts ...sdk.CallOption) (KitModuleDescribeResp, error) {
	return sdk.CallWithCaller[KitModuleDescribeMsg, KitModuleDescribeResp](caller, ctx, msg, opts...)
}

// CallKitModuleMount issues a synchronous request-response Call for KitModuleMountMsg.
func CallKitModuleMount(rt sdk.CallerRuntime, ctx context.Context, msg KitModuleMountMsg, opts ...sdk.CallOption) (KitModuleMountResp, error) {
	return sdk.Call[KitModuleMountMsg, KitModuleMountResp](rt, ctx, msg, opts...)
}

// CallKitModuleMountWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallKitModuleMountWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg KitModuleMountMsg, opts ...sdk.CallOption) (KitModuleMountResp, error) {
	return sdk.CallWithCaller[KitModuleMountMsg, KitModuleMountResp](caller, ctx, msg, opts...)
}

// CallKitModuleUnmount issues a synchronous request-response Call for KitModuleUnmountMsg.
func CallKitModuleUnmount(rt sdk.CallerRuntime, ctx context.Context, msg KitModuleUnmountMsg, opts ...sdk.CallOption) (KitModuleUnmountResp, error) {
	return sdk.Call[KitModuleUnmountMsg, KitModuleUnmountResp](rt, ctx, msg, opts...)
}

// CallKitModuleUnmountWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallKitModuleUnmountWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg KitModuleUnmountMsg, opts ...sdk.CallOption) (KitModuleUnmountResp, error) {
	return sdk.CallWithCaller[KitModuleUnmountMsg, KitModuleUnmountResp](caller, ctx, msg, opts...)
}

// CallKitModules issues a synchronous request-response Call for KitModulesMsg.
func CallKitModules(rt sdk.CallerRuntime, ctx context.Context, msg KitModulesMsg, opts ...sdk.CallOption) (KitModulesResp, error) {
	return sdk.Call[KitModulesMsg, KitModulesResp](rt, ctx, msg, opts...)
}

// CallKitModulesWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallKitModulesWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg KitModulesMsg, opts ...sdk.CallOption) (KitModulesResp, error) {
	return sdk.CallWithCaller[KitModulesMsg, KitModulesResp](caller, ctx, msg, opts...)
}

// CallKitSetDraining issues a synchronous request-response Call for KitSetDrainingMsg.
func CallKitSetDraining(rt sdk.CallerRuntime, ctx context.Context, msg KitSetDrainingMsg, opts ...sdk.CallOption) (KitSetDrainingResp, error) {
	return sdk.Call[KitSetDrainingMsg, KitSetDrainingResp](rt, ctx, msg, opts...)
}

// CallKitSetDrainingWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallKitSetDrainingWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg KitSetDrainingMsg, opts ...sdk.CallOption) (KitSetDrainingResp, error) {
	return sdk.CallWithCaller[KitSetDrainingMsg, KitSetDrainingResp](caller, ctx, msg, opts...)
}

