// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit call/emit/subscribe.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// Low-level publish/reply-topic helpers are intentionally not generated; use
// the generic SDK protocol primitives directly when testing transport behavior.
//
// Regenerate with cmd/sdkgen from this repository.
package auditmsg

import (
	"context"

	bkmodule "github.com/brainlet/brainkit/module"
	"github.com/brainlet/brainkit/sdk"
)

// CallAuditPrune issues a synchronous request-response Call for AuditPruneMsg.
func CallAuditPrune(rt sdk.CallerRuntime, ctx context.Context, msg AuditPruneMsg, opts ...sdk.CallOption) (AuditPruneResp, error) {
	return sdk.Call[AuditPruneMsg, AuditPruneResp](rt, ctx, msg, opts...)
}

// CallAuditPruneWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallAuditPruneWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg AuditPruneMsg, opts ...sdk.CallOption) (AuditPruneResp, error) {
	return sdk.CallWithCaller[AuditPruneMsg, AuditPruneResp](caller, ctx, msg, opts...)
}

// CallAuditQuery issues a synchronous request-response Call for AuditQueryMsg.
func CallAuditQuery(rt sdk.CallerRuntime, ctx context.Context, msg AuditQueryMsg, opts ...sdk.CallOption) (AuditQueryResp, error) {
	return sdk.Call[AuditQueryMsg, AuditQueryResp](rt, ctx, msg, opts...)
}

// CallAuditQueryWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallAuditQueryWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg AuditQueryMsg, opts ...sdk.CallOption) (AuditQueryResp, error) {
	return sdk.CallWithCaller[AuditQueryMsg, AuditQueryResp](caller, ctx, msg, opts...)
}

// CallAuditStats issues a synchronous request-response Call for AuditStatsMsg.
func CallAuditStats(rt sdk.CallerRuntime, ctx context.Context, msg AuditStatsMsg, opts ...sdk.CallOption) (AuditStatsResp, error) {
	return sdk.Call[AuditStatsMsg, AuditStatsResp](rt, ctx, msg, opts...)
}

// CallAuditStatsWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallAuditStatsWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg AuditStatsMsg, opts ...sdk.CallOption) (AuditStatsResp, error) {
	return sdk.CallWithCaller[AuditStatsMsg, AuditStatsResp](caller, ctx, msg, opts...)
}

