// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit publish/subscribe/call/emit.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// The underlying generic publish/call patterns are unchanged. These wrappers
// just add type safety.
//
// Regenerate with cmd/sdkgen from this repository.
package auditmsg

import (
	"context"

	"github.com/brainlet/brainkit/sdk"
)

// PublishAuditPrune publishes a AuditPruneMsg and returns routing info for the response.
func PublishAuditPrune(rt sdk.Runtime, ctx context.Context, msg AuditPruneMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeAuditPruneResp subscribes to the response topic for a AuditPruneMsg command.
func SubscribeAuditPruneResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(AuditPruneResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[AuditPruneResp](rt, ctx, topic, handler)
}

// CallAuditPrune issues a synchronous request-response Call for AuditPruneMsg.
func CallAuditPrune(rt sdk.CallerRuntime, ctx context.Context, msg AuditPruneMsg, opts ...sdk.CallOption) (AuditPruneResp, error) {
	return sdk.Call[AuditPruneMsg, AuditPruneResp](rt, ctx, msg, opts...)
}

// PublishAuditQuery publishes a AuditQueryMsg and returns routing info for the response.
func PublishAuditQuery(rt sdk.Runtime, ctx context.Context, msg AuditQueryMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeAuditQueryResp subscribes to the response topic for a AuditQueryMsg command.
func SubscribeAuditQueryResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(AuditQueryResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[AuditQueryResp](rt, ctx, topic, handler)
}

// CallAuditQuery issues a synchronous request-response Call for AuditQueryMsg.
func CallAuditQuery(rt sdk.CallerRuntime, ctx context.Context, msg AuditQueryMsg, opts ...sdk.CallOption) (AuditQueryResp, error) {
	return sdk.Call[AuditQueryMsg, AuditQueryResp](rt, ctx, msg, opts...)
}

// PublishAuditStats publishes a AuditStatsMsg and returns routing info for the response.
func PublishAuditStats(rt sdk.Runtime, ctx context.Context, msg AuditStatsMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeAuditStatsResp subscribes to the response topic for a AuditStatsMsg command.
func SubscribeAuditStatsResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(AuditStatsResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[AuditStatsResp](rt, ctx, topic, handler)
}

// CallAuditStats issues a synchronous request-response Call for AuditStatsMsg.
func CallAuditStats(rt sdk.CallerRuntime, ctx context.Context, msg AuditStatsMsg, opts ...sdk.CallOption) (AuditStatsResp, error) {
	return sdk.Call[AuditStatsMsg, AuditStatsResp](rt, ctx, msg, opts...)
}

