// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit publish/subscribe/call/emit.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// The underlying generic publish/call patterns are unchanged. These wrappers
// just add type safety.
//
// Regenerate with cmd/sdkgen from this repository.
package gatewaymsg

import (
	"context"

	"github.com/brainlet/brainkit/sdk"
)

// PublishGatewayRouteAdd publishes a GatewayRouteAddMsg and returns routing info for the response.
func PublishGatewayRouteAdd(rt sdk.Runtime, ctx context.Context, msg GatewayRouteAddMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeGatewayRouteAddResp subscribes to the response topic for a GatewayRouteAddMsg command.
func SubscribeGatewayRouteAddResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(GatewayRouteAddResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[GatewayRouteAddResp](rt, ctx, topic, handler)
}

// CallGatewayRouteAdd issues a synchronous request-response Call for GatewayRouteAddMsg.
func CallGatewayRouteAdd(rt sdk.CallerRuntime, ctx context.Context, msg GatewayRouteAddMsg, opts ...sdk.CallOption) (GatewayRouteAddResp, error) {
	return sdk.Call[GatewayRouteAddMsg, GatewayRouteAddResp](rt, ctx, msg, opts...)
}

// PublishGatewayRouteList publishes a GatewayRouteListMsg and returns routing info for the response.
func PublishGatewayRouteList(rt sdk.Runtime, ctx context.Context, msg GatewayRouteListMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeGatewayRouteListResp subscribes to the response topic for a GatewayRouteListMsg command.
func SubscribeGatewayRouteListResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(GatewayRouteListResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[GatewayRouteListResp](rt, ctx, topic, handler)
}

// CallGatewayRouteList issues a synchronous request-response Call for GatewayRouteListMsg.
func CallGatewayRouteList(rt sdk.CallerRuntime, ctx context.Context, msg GatewayRouteListMsg, opts ...sdk.CallOption) (GatewayRouteListResp, error) {
	return sdk.Call[GatewayRouteListMsg, GatewayRouteListResp](rt, ctx, msg, opts...)
}

// PublishGatewayRouteRemove publishes a GatewayRouteRemoveMsg and returns routing info for the response.
func PublishGatewayRouteRemove(rt sdk.Runtime, ctx context.Context, msg GatewayRouteRemoveMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeGatewayRouteRemoveResp subscribes to the response topic for a GatewayRouteRemoveMsg command.
func SubscribeGatewayRouteRemoveResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(GatewayRouteRemoveResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[GatewayRouteRemoveResp](rt, ctx, topic, handler)
}

// CallGatewayRouteRemove issues a synchronous request-response Call for GatewayRouteRemoveMsg.
func CallGatewayRouteRemove(rt sdk.CallerRuntime, ctx context.Context, msg GatewayRouteRemoveMsg, opts ...sdk.CallOption) (GatewayRouteRemoveResp, error) {
	return sdk.Call[GatewayRouteRemoveMsg, GatewayRouteRemoveResp](rt, ctx, msg, opts...)
}

// PublishGatewayStatus publishes a GatewayStatusMsg and returns routing info for the response.
func PublishGatewayStatus(rt sdk.Runtime, ctx context.Context, msg GatewayStatusMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeGatewayStatusResp subscribes to the response topic for a GatewayStatusMsg command.
func SubscribeGatewayStatusResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(GatewayStatusResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[GatewayStatusResp](rt, ctx, topic, handler)
}

// CallGatewayStatus issues a synchronous request-response Call for GatewayStatusMsg.
func CallGatewayStatus(rt sdk.CallerRuntime, ctx context.Context, msg GatewayStatusMsg, opts ...sdk.CallOption) (GatewayStatusResp, error) {
	return sdk.Call[GatewayStatusMsg, GatewayStatusResp](rt, ctx, msg, opts...)
}

