// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit call/emit/subscribe.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// Low-level publish/reply-topic helpers are intentionally not generated; use
// the generic SDK protocol primitives directly when testing transport behavior.
//
// Regenerate with cmd/sdkgen from this repository.
package gatewaymsg

import (
	"context"

	bkmodule "github.com/brainlet/brainkit/module"
	"github.com/brainlet/brainkit/sdk"
)

// CallGatewayRouteAdd issues a synchronous request-response Call for GatewayRouteAddMsg.
func CallGatewayRouteAdd(rt sdk.CallerRuntime, ctx context.Context, msg GatewayRouteAddMsg, opts ...sdk.CallOption) (GatewayRouteAddResp, error) {
	return sdk.Call[GatewayRouteAddMsg, GatewayRouteAddResp](rt, ctx, msg, opts...)
}

// CallGatewayRouteAddWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallGatewayRouteAddWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg GatewayRouteAddMsg, opts ...sdk.CallOption) (GatewayRouteAddResp, error) {
	return sdk.CallWithCaller[GatewayRouteAddMsg, GatewayRouteAddResp](caller, ctx, msg, opts...)
}

// CallGatewayRouteList issues a synchronous request-response Call for GatewayRouteListMsg.
func CallGatewayRouteList(rt sdk.CallerRuntime, ctx context.Context, msg GatewayRouteListMsg, opts ...sdk.CallOption) (GatewayRouteListResp, error) {
	return sdk.Call[GatewayRouteListMsg, GatewayRouteListResp](rt, ctx, msg, opts...)
}

// CallGatewayRouteListWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallGatewayRouteListWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg GatewayRouteListMsg, opts ...sdk.CallOption) (GatewayRouteListResp, error) {
	return sdk.CallWithCaller[GatewayRouteListMsg, GatewayRouteListResp](caller, ctx, msg, opts...)
}

// CallGatewayRouteRemove issues a synchronous request-response Call for GatewayRouteRemoveMsg.
func CallGatewayRouteRemove(rt sdk.CallerRuntime, ctx context.Context, msg GatewayRouteRemoveMsg, opts ...sdk.CallOption) (GatewayRouteRemoveResp, error) {
	return sdk.Call[GatewayRouteRemoveMsg, GatewayRouteRemoveResp](rt, ctx, msg, opts...)
}

// CallGatewayRouteRemoveWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallGatewayRouteRemoveWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg GatewayRouteRemoveMsg, opts ...sdk.CallOption) (GatewayRouteRemoveResp, error) {
	return sdk.CallWithCaller[GatewayRouteRemoveMsg, GatewayRouteRemoveResp](caller, ctx, msg, opts...)
}

// CallGatewayStatus issues a synchronous request-response Call for GatewayStatusMsg.
func CallGatewayStatus(rt sdk.CallerRuntime, ctx context.Context, msg GatewayStatusMsg, opts ...sdk.CallOption) (GatewayStatusResp, error) {
	return sdk.Call[GatewayStatusMsg, GatewayStatusResp](rt, ctx, msg, opts...)
}

// CallGatewayStatusWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallGatewayStatusWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg GatewayStatusMsg, opts ...sdk.CallOption) (GatewayStatusResp, error) {
	return sdk.CallWithCaller[GatewayStatusMsg, GatewayStatusResp](caller, ctx, msg, opts...)
}

