// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit publish/subscribe/call/emit.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// The underlying generic publish/call patterns are unchanged. These wrappers
// just add type safety.
//
// Regenerate with cmd/sdkgen from this repository.
package mcpmsg

import (
	"context"

	"github.com/brainlet/brainkit/sdk"
)

// PublishMcpCallTool publishes a McpCallToolMsg and returns routing info for the response.
func PublishMcpCallTool(rt sdk.Runtime, ctx context.Context, msg McpCallToolMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeMcpCallToolResp subscribes to the response topic for a McpCallToolMsg command.
func SubscribeMcpCallToolResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(McpCallToolResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[McpCallToolResp](rt, ctx, topic, handler)
}

// CallMcpCallTool issues a synchronous request-response Call for McpCallToolMsg.
func CallMcpCallTool(rt sdk.CallerRuntime, ctx context.Context, msg McpCallToolMsg, opts ...sdk.CallOption) (McpCallToolResp, error) {
	return sdk.Call[McpCallToolMsg, McpCallToolResp](rt, ctx, msg, opts...)
}

// PublishMcpListTools publishes a McpListToolsMsg and returns routing info for the response.
func PublishMcpListTools(rt sdk.Runtime, ctx context.Context, msg McpListToolsMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeMcpListToolsResp subscribes to the response topic for a McpListToolsMsg command.
func SubscribeMcpListToolsResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(McpListToolsResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[McpListToolsResp](rt, ctx, topic, handler)
}

// CallMcpListTools issues a synchronous request-response Call for McpListToolsMsg.
func CallMcpListTools(rt sdk.CallerRuntime, ctx context.Context, msg McpListToolsMsg, opts ...sdk.CallOption) (McpListToolsResp, error) {
	return sdk.Call[McpListToolsMsg, McpListToolsResp](rt, ctx, msg, opts...)
}

