// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit call/emit/subscribe.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// Low-level publish/reply-topic helpers are intentionally not generated; use
// the generic SDK protocol primitives directly when testing transport behavior.
//
// Regenerate with cmd/sdkgen from this repository.
package mcpmsg

import (
	"context"

	bkmodule "github.com/brainlet/brainkit/module"
	"github.com/brainlet/brainkit/sdk"
)

// CallMcpCallTool issues a synchronous request-response Call for McpCallToolMsg.
func CallMcpCallTool(rt sdk.CallerRuntime, ctx context.Context, msg McpCallToolMsg, opts ...sdk.CallOption) (McpCallToolResp, error) {
	return sdk.Call[McpCallToolMsg, McpCallToolResp](rt, ctx, msg, opts...)
}

// CallMcpCallToolWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallMcpCallToolWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg McpCallToolMsg, opts ...sdk.CallOption) (McpCallToolResp, error) {
	return sdk.CallWithCaller[McpCallToolMsg, McpCallToolResp](caller, ctx, msg, opts...)
}

// CallMcpListTools issues a synchronous request-response Call for McpListToolsMsg.
func CallMcpListTools(rt sdk.CallerRuntime, ctx context.Context, msg McpListToolsMsg, opts ...sdk.CallOption) (McpListToolsResp, error) {
	return sdk.Call[McpListToolsMsg, McpListToolsResp](rt, ctx, msg, opts...)
}

// CallMcpListToolsWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallMcpListToolsWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg McpListToolsMsg, opts ...sdk.CallOption) (McpListToolsResp, error) {
	return sdk.CallWithCaller[McpListToolsMsg, McpListToolsResp](caller, ctx, msg, opts...)
}

