// Ported from: packages/provider/src/language-model/v3/language-model-v3-file.ts
package languagemodel

import "github.com/brainlet/brainkit/ai-kit/provider/shared"

// File represents a file that has been generated by the model.
// Generated files as base64 encoded strings or binary data.
// The files should be returned without any unnecessary conversion.
type File struct {
	// MediaType is the IANA media type of the file, e.g. "image/png" or "audio/mp3".
	MediaType string

	// Data is generated file data as base64 encoded string or binary data.
	// Use FileDataString for base64 or FileDataBytes for binary.
	Data FileData

	// ProviderMetadata is optional provider-specific metadata for the file part.
	ProviderMetadata shared.ProviderMetadata
}

func (File) isContent()    {}
func (File) isStreamPart() {}

// FileData represents file data that can be a string or bytes.
type FileData interface {
	fileData()
}

// FileDataString represents base64 encoded file data.
type FileDataString struct {
	Value string
}

func (FileDataString) fileData() {}

// FileDataBytes represents binary file data.
type FileDataBytes struct {
	Data []byte
}

func (FileDataBytes) fileData() {}
