// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit call/emit/subscribe.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// Low-level publish/reply-topic helpers are intentionally not generated; use
// the generic SDK protocol primitives directly when testing transport behavior.
//
// Regenerate with cmd/sdkgen from this repository.
package metrics

import (
	"context"

	bkmodule "github.com/brainlet/brainkit/module"
	"github.com/brainlet/brainkit/sdk"
)

// CallMetricsGet issues a synchronous request-response Call for MetricsGetMsg.
func CallMetricsGet(rt sdk.CallerRuntime, ctx context.Context, msg MetricsGetMsg, opts ...sdk.CallOption) (MetricsGetResp, error) {
	return sdk.Call[MetricsGetMsg, MetricsGetResp](rt, ctx, msg, opts...)
}

// CallMetricsGetWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallMetricsGetWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg MetricsGetMsg, opts ...sdk.CallOption) (MetricsGetResp, error) {
	return sdk.CallWithCaller[MetricsGetMsg, MetricsGetResp](caller, ctx, msg, opts...)
}

