// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit publish/subscribe/call/emit.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// The underlying generic publish/call patterns are unchanged. These wrappers
// just add type safety.
//
// Regenerate with cmd/sdkgen from this repository.
package metrics

import (
	"context"

	"github.com/brainlet/brainkit/sdk"
)

// PublishMetricsGet publishes a MetricsGetMsg and returns routing info for the response.
func PublishMetricsGet(rt sdk.Runtime, ctx context.Context, msg MetricsGetMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeMetricsGetResp subscribes to the response topic for a MetricsGetMsg command.
func SubscribeMetricsGetResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(MetricsGetResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[MetricsGetResp](rt, ctx, topic, handler)
}

// CallMetricsGet issues a synchronous request-response Call for MetricsGetMsg.
func CallMetricsGet(rt sdk.CallerRuntime, ctx context.Context, msg MetricsGetMsg, opts ...sdk.CallOption) (MetricsGetResp, error) {
	return sdk.Call[MetricsGetMsg, MetricsGetResp](rt, ctx, msg, opts...)
}

