package esbuild

import (
	"fmt"
	"strings"
)

const brainkitRuntimeModuleNamespace = "brainkit-runtime-module"

var brainkitRuntimeModuleExports = map[string][]string{
	"kit": {
		"bus",
		"kit",
		"model",
		"embeddingModel",
		"provider",
		"storage",
		"vectorStore",
		"registry",
		"tools",
		"tool",
		"browser",
		"fs",
		"mcp",
		"output",
		"secrets",
		"generateWithApproval",
	},
	"ai": {
		"generateText",
		"streamText",
		"generateObject",
		"streamObject",
		"embed",
		"embedMany",
		"z",
		"tool",
		"dynamicTool",
		"jsonSchema",
		"zodSchema",
		"asSchema",
		"generateId",
		"createIdGenerator",
		"hasToolCall",
		"stepCountIs",
		"isLoopFinished",
		"wrapLanguageModel",
		"wrapEmbeddingModel",
		"wrapImageModel",
		"wrapProvider",
		"extractReasoningMiddleware",
		"extractJsonMiddleware",
		"defaultSettingsMiddleware",
		"defaultEmbeddingSettingsMiddleware",
		"simulateStreamingMiddleware",
		"smoothStream",
		"addToolInputExamplesMiddleware",
		"createProviderRegistry",
		"customProvider",
		"experimental_createProviderRegistry",
		"experimental_customProvider",
		"convertToModelMessages",
		"pruneMessages",
		"validateUIMessages",
		"safeValidateUIMessages",
		"readUIMessageStream",
		"consumeStream",
		"convertFileListToUIParts",
		"convertFileListToModelMessages",
		"convertFileListToFileUIParts",
		"generateImage",
		"experimental_generateImage",
		"experimental_generateVideo",
		"experimental_transcribe",
		"experimental_generateSpeech",
		"cosineSimilarity",
		"simulateReadableStream",
		"parsePartialJson",
		"parseJsonEventStream",
		"gateway",
		"createGateway",
		"AISDKError",
		"APICallError",
		"NoObjectGeneratedError",
		"NoSuchModelError",
		"NoSuchToolError",
		"InvalidArgumentError",
		"InvalidDataContentError",
		"InvalidPromptError",
		"InvalidToolInputError",
		"NoContentGeneratedError",
		"NoSpeechGeneratedError",
		"NoTranscriptGeneratedError",
		"NoVideoGeneratedError",
		"RetryError",
		"ToolCallRepairError",
		"TypeValidationError",
		"MessageConversionError",
		"MissingToolResultsError",
		"LoadAPIKeyError",
		"InvalidToolApprovalError",
		"ToolCallNotFoundForApprovalError",
	},
	"agent": {
		"Agent",
		"Mastra",
		"TripWire",
		"MessageList",
		"convertMessages",
		"TypeDetector",
		"createTool",
		"createWorkflow",
		"createStep",
		"Workflow",
		"cloneWorkflow",
		"cloneStep",
		"mapVariable",
		"Memory",
		"RequestContext",
		"RuntimeContext",
		"z",
		"BackgroundTaskManager",
		"createBackgroundTask",
		"generateBackgroundTaskSystemPrompt",
		"__brainkitMastraBackgroundTaskDebug",
		"Harness",
		"assignTaskIds",
		"askUserTool",
		"defaultDisplayState",
		"defaultOMProgressState",
		"parseSubagentMeta",
		"submitPlanTool",
		"taskWriteTool",
		"taskUpdateTool",
		"taskCompleteTool",
		"taskCheckTool",
		"ConsoleLogger",
		"MultiLogger",
		"DualLogger",
		"InMemoryStore",
		"LibSQLStore",
		"UpstashStore",
		"PostgresStore",
		"MongoDBStore",
		"LibSQLVector",
		"PgVector",
		"MongoDBVector",
		"PineconeVector",
		"ChromaVector",
		"QdrantVector",
		"ModelRouterEmbeddingModel",
		"Workspace",
		"LocalFilesystem",
		"LocalSandbox",
		"CompositeFilesystem",
		"WORKSPACE_TOOLS_PREFIX",
		"WORKSPACE_TOOLS",
		"createWorkspaceTools",
		"resolveToolConfig",
		"readFileTool",
		"writeFileTool",
		"editFileTool",
		"listFilesTool",
		"deleteFileTool",
		"fileStatTool",
		"mkdirTool",
		"searchTool",
		"indexContentTool",
		"executeCommandTool",
		"requireWorkspace",
		"requireFilesystem",
		"requireSandbox",
		"MastraBrowser",
		"BrowserContextProcessor",
		"AgentChannels",
		"ChatChannelProcessor",
		"MastraStateAdapter",
		"MDocument",
		"GraphRAG",
		"createVectorQueryTool",
		"createDocumentChunkerTool",
		"createGraphRAGTool",
		"rerank",
		"rerankWithScorer",
		"CohereRelevanceScorer",
		"MastraAgentRelevanceScorer",
		"ZeroEntropyRelevanceScorer",
		"Observability",
		"DefaultExporter",
		"SensitiveDataFilter",
		"BaseExporter",
		"CloudExporter",
		"ConsoleExporter",
		"TestExporter",
		"TrackingExporter",
		"chainFormatters",
		"BatchSpanProcessor",
		"SimpleSpanProcessor",
		"NoopSpanProcessor",
		"ConsoleSpanExporter",
		"InMemorySpanExporter",
		"BasicTracerProvider",
		"AlwaysOnSampler",
		"AlwaysOffSampler",
		"ParentBasedSampler",
		"TraceIdRatioBasedSampler",
		"MastraVoice",
		"CompositeVoice",
		"DefaultVoice",
		"AISDKSpeech",
		"AISDKTranscription",
		"OpenAIVoice",
		"OpenAIRealtimeVoice",
		"AzureVoice",
		"ElevenLabsVoice",
		"CloudflareVoice",
		"DeepgramVoice",
		"PlayAIVoice",
		"PLAYAI_VOICES",
		"SpeechifyVoice",
		"SarvamVoice",
		"MurfVoice",
		"createScorer",
		"runEvals",
		"MastraScorer",
		"registerHook",
		"executeHook",
		"AvailableHooks",
		"createCompletenessScorer",
		"createTextualDifferenceScorer",
		"createKeywordCoverageScorer",
		"createContentSimilarityScorer",
		"createToneScorer",
		"createAnswerRelevancyScorer",
		"createAnswerSimilarityScorer",
		"createFaithfulnessScorer",
		"createHallucinationScorer",
		"createBiasScorer",
		"createToxicityScorer",
		"createContextPrecisionScorer",
		"createContextRelevanceScorerLLM",
		"createNoiseSensitivityScorerLLM",
		"createPromptAlignmentScorerLLM",
		"createToolCallAccuracyScorerLLM",
		"createTrajectoryAccuracyScorerLLM",
		"createToolCallAccuracyScorerCode",
		"createTrajectoryAccuracyScorerCode",
		"createTrajectoryScorerCode",
		"ModerationProcessor",
		"PromptInjectionDetector",
		"PIIDetector",
		"SystemPromptScrubber",
		"UnicodeNormalizer",
		"LanguageDetector",
		"TokenLimiterProcessor",
		"BatchPartsProcessor",
		"StructuredOutputProcessor",
		"ToolCallFilter",
		"ToolSearchProcessor",
		"AgentsMDInjector",
		"SkillsProcessor",
		"SkillSearchProcessor",
		"WorkspaceInstructionsProcessor",
		"ResponseCache",
		"DEFAULT_RESPONSE_CACHE_TTL_SECONDS",
		"RESPONSE_CACHE_CONTEXT_KEY",
		"buildResponseCacheKey",
		"InMemoryServerCache",
		"MastraServerCache",
	},
	"compiler": {},
}

func brainkitRuntimeModuleStub(specifier string) (string, bool) {
	_, ok := brainkitRuntimeModuleExports[specifier]
	return specifier, ok
}

func brainkitRuntimeModuleStubContents(specifier string) (string, bool) {
	names, ok := brainkitRuntimeModuleExports[specifier]
	if !ok {
		return "", false
	}

	var b strings.Builder
	b.WriteString("// Brainkit runtime module stub generated by modules/packages/bundlers/esbuild.\n")
	for _, name := range names {
		fmt.Fprintf(&b, "export var %s = globalThis.%s;\n", name, name)
	}

	b.WriteString("var __default = {")
	for i, name := range names {
		if i > 0 {
			b.WriteString(",")
		}
		fmt.Fprintf(&b, "%s:%s", name, name)
	}
	b.WriteString("};\nexport default __default;\n")
	return b.String(), true
}
