// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit call/emit/subscribe.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// Low-level publish/reply-topic helpers are intentionally not generated; use
// the generic SDK protocol primitives directly when testing transport behavior.
//
// Regenerate with cmd/sdkgen from this repository.
package workflowmsg

import (
	"context"

	bkmodule "github.com/brainlet/brainkit/module"
	"github.com/brainlet/brainkit/sdk"
)

// CallWorkflowCancel issues a synchronous request-response Call for WorkflowCancelMsg.
func CallWorkflowCancel(rt sdk.CallerRuntime, ctx context.Context, msg WorkflowCancelMsg, opts ...sdk.CallOption) (WorkflowCancelResp, error) {
	return sdk.Call[WorkflowCancelMsg, WorkflowCancelResp](rt, ctx, msg, opts...)
}

// CallWorkflowCancelWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallWorkflowCancelWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg WorkflowCancelMsg, opts ...sdk.CallOption) (WorkflowCancelResp, error) {
	return sdk.CallWithCaller[WorkflowCancelMsg, WorkflowCancelResp](caller, ctx, msg, opts...)
}

// CallWorkflowList issues a synchronous request-response Call for WorkflowListMsg.
func CallWorkflowList(rt sdk.CallerRuntime, ctx context.Context, msg WorkflowListMsg, opts ...sdk.CallOption) (WorkflowListResp, error) {
	return sdk.Call[WorkflowListMsg, WorkflowListResp](rt, ctx, msg, opts...)
}

// CallWorkflowListWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallWorkflowListWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg WorkflowListMsg, opts ...sdk.CallOption) (WorkflowListResp, error) {
	return sdk.CallWithCaller[WorkflowListMsg, WorkflowListResp](caller, ctx, msg, opts...)
}

// CallWorkflowRestart issues a synchronous request-response Call for WorkflowRestartMsg.
func CallWorkflowRestart(rt sdk.CallerRuntime, ctx context.Context, msg WorkflowRestartMsg, opts ...sdk.CallOption) (WorkflowRestartResp, error) {
	return sdk.Call[WorkflowRestartMsg, WorkflowRestartResp](rt, ctx, msg, opts...)
}

// CallWorkflowRestartWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallWorkflowRestartWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg WorkflowRestartMsg, opts ...sdk.CallOption) (WorkflowRestartResp, error) {
	return sdk.CallWithCaller[WorkflowRestartMsg, WorkflowRestartResp](caller, ctx, msg, opts...)
}

// CallWorkflowResume issues a synchronous request-response Call for WorkflowResumeMsg.
func CallWorkflowResume(rt sdk.CallerRuntime, ctx context.Context, msg WorkflowResumeMsg, opts ...sdk.CallOption) (WorkflowResumeResp, error) {
	return sdk.Call[WorkflowResumeMsg, WorkflowResumeResp](rt, ctx, msg, opts...)
}

// CallWorkflowResumeWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallWorkflowResumeWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg WorkflowResumeMsg, opts ...sdk.CallOption) (WorkflowResumeResp, error) {
	return sdk.CallWithCaller[WorkflowResumeMsg, WorkflowResumeResp](caller, ctx, msg, opts...)
}

// CallWorkflowRuns issues a synchronous request-response Call for WorkflowRunsMsg.
func CallWorkflowRuns(rt sdk.CallerRuntime, ctx context.Context, msg WorkflowRunsMsg, opts ...sdk.CallOption) (WorkflowRunsResp, error) {
	return sdk.Call[WorkflowRunsMsg, WorkflowRunsResp](rt, ctx, msg, opts...)
}

// CallWorkflowRunsWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallWorkflowRunsWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg WorkflowRunsMsg, opts ...sdk.CallOption) (WorkflowRunsResp, error) {
	return sdk.CallWithCaller[WorkflowRunsMsg, WorkflowRunsResp](caller, ctx, msg, opts...)
}

// CallWorkflowStart issues a synchronous request-response Call for WorkflowStartMsg.
func CallWorkflowStart(rt sdk.CallerRuntime, ctx context.Context, msg WorkflowStartMsg, opts ...sdk.CallOption) (WorkflowStartResp, error) {
	return sdk.Call[WorkflowStartMsg, WorkflowStartResp](rt, ctx, msg, opts...)
}

// CallWorkflowStartWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallWorkflowStartWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg WorkflowStartMsg, opts ...sdk.CallOption) (WorkflowStartResp, error) {
	return sdk.CallWithCaller[WorkflowStartMsg, WorkflowStartResp](caller, ctx, msg, opts...)
}

// CallWorkflowStartAsync issues a synchronous request-response Call for WorkflowStartAsyncMsg.
func CallWorkflowStartAsync(rt sdk.CallerRuntime, ctx context.Context, msg WorkflowStartAsyncMsg, opts ...sdk.CallOption) (WorkflowStartAsyncResp, error) {
	return sdk.Call[WorkflowStartAsyncMsg, WorkflowStartAsyncResp](rt, ctx, msg, opts...)
}

// CallWorkflowStartAsyncWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallWorkflowStartAsyncWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg WorkflowStartAsyncMsg, opts ...sdk.CallOption) (WorkflowStartAsyncResp, error) {
	return sdk.CallWithCaller[WorkflowStartAsyncMsg, WorkflowStartAsyncResp](caller, ctx, msg, opts...)
}

// CallWorkflowStatus issues a synchronous request-response Call for WorkflowStatusMsg.
func CallWorkflowStatus(rt sdk.CallerRuntime, ctx context.Context, msg WorkflowStatusMsg, opts ...sdk.CallOption) (WorkflowStatusResp, error) {
	return sdk.Call[WorkflowStatusMsg, WorkflowStatusResp](rt, ctx, msg, opts...)
}

// CallWorkflowStatusWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallWorkflowStatusWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg WorkflowStatusMsg, opts ...sdk.CallOption) (WorkflowStatusResp, error) {
	return sdk.CallWithCaller[WorkflowStatusMsg, WorkflowStatusResp](caller, ctx, msg, opts...)
}

