// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit publish/subscribe/call/emit.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// The underlying generic publish/call patterns are unchanged. These wrappers
// just add type safety.
//
// Regenerate with cmd/sdkgen from this repository.
package workflowmsg

import (
	"context"

	"github.com/brainlet/brainkit/sdk"
)

// PublishWorkflowCancel publishes a WorkflowCancelMsg and returns routing info for the response.
func PublishWorkflowCancel(rt sdk.Runtime, ctx context.Context, msg WorkflowCancelMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeWorkflowCancelResp subscribes to the response topic for a WorkflowCancelMsg command.
func SubscribeWorkflowCancelResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(WorkflowCancelResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[WorkflowCancelResp](rt, ctx, topic, handler)
}

// CallWorkflowCancel issues a synchronous request-response Call for WorkflowCancelMsg.
func CallWorkflowCancel(rt sdk.CallerRuntime, ctx context.Context, msg WorkflowCancelMsg, opts ...sdk.CallOption) (WorkflowCancelResp, error) {
	return sdk.Call[WorkflowCancelMsg, WorkflowCancelResp](rt, ctx, msg, opts...)
}

// PublishWorkflowList publishes a WorkflowListMsg and returns routing info for the response.
func PublishWorkflowList(rt sdk.Runtime, ctx context.Context, msg WorkflowListMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeWorkflowListResp subscribes to the response topic for a WorkflowListMsg command.
func SubscribeWorkflowListResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(WorkflowListResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[WorkflowListResp](rt, ctx, topic, handler)
}

// CallWorkflowList issues a synchronous request-response Call for WorkflowListMsg.
func CallWorkflowList(rt sdk.CallerRuntime, ctx context.Context, msg WorkflowListMsg, opts ...sdk.CallOption) (WorkflowListResp, error) {
	return sdk.Call[WorkflowListMsg, WorkflowListResp](rt, ctx, msg, opts...)
}

// PublishWorkflowRestart publishes a WorkflowRestartMsg and returns routing info for the response.
func PublishWorkflowRestart(rt sdk.Runtime, ctx context.Context, msg WorkflowRestartMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeWorkflowRestartResp subscribes to the response topic for a WorkflowRestartMsg command.
func SubscribeWorkflowRestartResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(WorkflowRestartResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[WorkflowRestartResp](rt, ctx, topic, handler)
}

// CallWorkflowRestart issues a synchronous request-response Call for WorkflowRestartMsg.
func CallWorkflowRestart(rt sdk.CallerRuntime, ctx context.Context, msg WorkflowRestartMsg, opts ...sdk.CallOption) (WorkflowRestartResp, error) {
	return sdk.Call[WorkflowRestartMsg, WorkflowRestartResp](rt, ctx, msg, opts...)
}

// PublishWorkflowResume publishes a WorkflowResumeMsg and returns routing info for the response.
func PublishWorkflowResume(rt sdk.Runtime, ctx context.Context, msg WorkflowResumeMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeWorkflowResumeResp subscribes to the response topic for a WorkflowResumeMsg command.
func SubscribeWorkflowResumeResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(WorkflowResumeResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[WorkflowResumeResp](rt, ctx, topic, handler)
}

// CallWorkflowResume issues a synchronous request-response Call for WorkflowResumeMsg.
func CallWorkflowResume(rt sdk.CallerRuntime, ctx context.Context, msg WorkflowResumeMsg, opts ...sdk.CallOption) (WorkflowResumeResp, error) {
	return sdk.Call[WorkflowResumeMsg, WorkflowResumeResp](rt, ctx, msg, opts...)
}

// PublishWorkflowRuns publishes a WorkflowRunsMsg and returns routing info for the response.
func PublishWorkflowRuns(rt sdk.Runtime, ctx context.Context, msg WorkflowRunsMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeWorkflowRunsResp subscribes to the response topic for a WorkflowRunsMsg command.
func SubscribeWorkflowRunsResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(WorkflowRunsResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[WorkflowRunsResp](rt, ctx, topic, handler)
}

// CallWorkflowRuns issues a synchronous request-response Call for WorkflowRunsMsg.
func CallWorkflowRuns(rt sdk.CallerRuntime, ctx context.Context, msg WorkflowRunsMsg, opts ...sdk.CallOption) (WorkflowRunsResp, error) {
	return sdk.Call[WorkflowRunsMsg, WorkflowRunsResp](rt, ctx, msg, opts...)
}

// PublishWorkflowStart publishes a WorkflowStartMsg and returns routing info for the response.
func PublishWorkflowStart(rt sdk.Runtime, ctx context.Context, msg WorkflowStartMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeWorkflowStartResp subscribes to the response topic for a WorkflowStartMsg command.
func SubscribeWorkflowStartResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(WorkflowStartResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[WorkflowStartResp](rt, ctx, topic, handler)
}

// CallWorkflowStart issues a synchronous request-response Call for WorkflowStartMsg.
func CallWorkflowStart(rt sdk.CallerRuntime, ctx context.Context, msg WorkflowStartMsg, opts ...sdk.CallOption) (WorkflowStartResp, error) {
	return sdk.Call[WorkflowStartMsg, WorkflowStartResp](rt, ctx, msg, opts...)
}

// PublishWorkflowStartAsync publishes a WorkflowStartAsyncMsg and returns routing info for the response.
func PublishWorkflowStartAsync(rt sdk.Runtime, ctx context.Context, msg WorkflowStartAsyncMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeWorkflowStartAsyncResp subscribes to the response topic for a WorkflowStartAsyncMsg command.
func SubscribeWorkflowStartAsyncResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(WorkflowStartAsyncResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[WorkflowStartAsyncResp](rt, ctx, topic, handler)
}

// CallWorkflowStartAsync issues a synchronous request-response Call for WorkflowStartAsyncMsg.
func CallWorkflowStartAsync(rt sdk.CallerRuntime, ctx context.Context, msg WorkflowStartAsyncMsg, opts ...sdk.CallOption) (WorkflowStartAsyncResp, error) {
	return sdk.Call[WorkflowStartAsyncMsg, WorkflowStartAsyncResp](rt, ctx, msg, opts...)
}

// PublishWorkflowStatus publishes a WorkflowStatusMsg and returns routing info for the response.
func PublishWorkflowStatus(rt sdk.Runtime, ctx context.Context, msg WorkflowStatusMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeWorkflowStatusResp subscribes to the response topic for a WorkflowStatusMsg command.
func SubscribeWorkflowStatusResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(WorkflowStatusResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[WorkflowStatusResp](rt, ctx, topic, handler)
}

// CallWorkflowStatus issues a synchronous request-response Call for WorkflowStatusMsg.
func CallWorkflowStatus(rt sdk.CallerRuntime, ctx context.Context, msg WorkflowStatusMsg, opts ...sdk.CallOption) (WorkflowStatusResp, error) {
	return sdk.Call[WorkflowStatusMsg, WorkflowStatusResp](rt, ctx, msg, opts...)
}

