// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pggen

import (
	"time"
)

type AuditEvent struct {
	ID        string
	CreatedAt time.Time
	Category  string
	EventType string
	Source    string
	RuntimeID string
	Namespace string
	Data      string
	Duration  int64
	ErrorMsg  string
}

type Deployment struct {
	Source      string
	Code        string
	DeployOrder int32
	DeployedAt  time.Time
	PackageName string
	Role        string
}

type InstalledPlugin struct {
	Name        string
	Owner       string
	Version     string
	BinaryPath  string
	Manifest    string
	InstalledAt time.Time
}

type RunningPlugin struct {
	Name       string
	Owner      string
	Version    string
	BinaryPath string
	Env        string
	Config     string
	StartOrder int32
	StartedAt  time.Time
	Role       string
}

type Schedule struct {
	ID         string
	Expression string
	DurationNs int64
	Topic      string
	Payload    string
	Source     string
	CreatedAt  time.Time
	NextFire   time.Time
	OneTime    bool
}

type ScheduleFire struct {
	ScheduleID string
	FireTime   string
	ClaimedAt  time.Time
}
