// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package pggen

import (
	"context"
	"time"
)

const claimScheduleFire = `-- name: ClaimScheduleFire :exec

INSERT INTO schedule_fires (schedule_id, fire_time, claimed_at)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type ClaimScheduleFireParams struct {
	ScheduleID string
	FireTime   string
	ClaimedAt  time.Time
}

// ── Schedule Fires (deduplication) ──
func (q *Queries) ClaimScheduleFire(ctx context.Context, arg ClaimScheduleFireParams) error {
	_, err := q.db.ExecContext(ctx, claimScheduleFire, arg.ScheduleID, arg.FireTime, arg.ClaimedAt)
	return err
}

const countAuditEvents = `-- name: CountAuditEvents :one
SELECT COUNT(*) FROM audit_events
`

func (q *Queries) CountAuditEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditEventsByCategory = `-- name: CountAuditEventsByCategory :many
SELECT category, COUNT(*) AS cnt FROM audit_events GROUP BY category
`

type CountAuditEventsByCategoryRow struct {
	Category string
	Cnt      int64
}

func (q *Queries) CountAuditEventsByCategory(ctx context.Context) ([]CountAuditEventsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, countAuditEventsByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAuditEventsByCategoryRow{}
	for rows.Next() {
		var i CountAuditEventsByCategoryRow
		if err := rows.Scan(&i.Category, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteDeployment = `-- name: DeleteDeployment :exec
DELETE FROM deployments WHERE source = $1
`

func (q *Queries) DeleteDeployment(ctx context.Context, source string) error {
	_, err := q.db.ExecContext(ctx, deleteDeployment, source)
	return err
}

const deleteInstalledPlugin = `-- name: DeleteInstalledPlugin :exec
DELETE FROM installed_plugins WHERE name = $1
`

func (q *Queries) DeleteInstalledPlugin(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteInstalledPlugin, name)
	return err
}

const deleteRunningPlugin = `-- name: DeleteRunningPlugin :exec
DELETE FROM running_plugins WHERE name = $1
`

func (q *Queries) DeleteRunningPlugin(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteRunningPlugin, name)
	return err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules WHERE id = $1
`

func (q *Queries) DeleteSchedule(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSchedule, id)
	return err
}

const loadDeployment = `-- name: LoadDeployment :one
SELECT source, code, deploy_order, deployed_at, package_name
FROM deployments WHERE source = $1
`

type LoadDeploymentRow struct {
	Source      string
	Code        string
	DeployOrder int32
	DeployedAt  time.Time
	PackageName string
}

func (q *Queries) LoadDeployment(ctx context.Context, source string) (LoadDeploymentRow, error) {
	row := q.db.QueryRowContext(ctx, loadDeployment, source)
	var i LoadDeploymentRow
	err := row.Scan(
		&i.Source,
		&i.Code,
		&i.DeployOrder,
		&i.DeployedAt,
		&i.PackageName,
	)
	return i, err
}

const loadDeployments = `-- name: LoadDeployments :many
SELECT source, code, deploy_order, deployed_at, package_name
FROM deployments ORDER BY deploy_order
`

type LoadDeploymentsRow struct {
	Source      string
	Code        string
	DeployOrder int32
	DeployedAt  time.Time
	PackageName string
}

func (q *Queries) LoadDeployments(ctx context.Context) ([]LoadDeploymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, loadDeployments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadDeploymentsRow{}
	for rows.Next() {
		var i LoadDeploymentsRow
		if err := rows.Scan(
			&i.Source,
			&i.Code,
			&i.DeployOrder,
			&i.DeployedAt,
			&i.PackageName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadInstalledPlugins = `-- name: LoadInstalledPlugins :many
SELECT name, owner, version, binary_path, manifest, installed_at
FROM installed_plugins
`

func (q *Queries) LoadInstalledPlugins(ctx context.Context) ([]InstalledPlugin, error) {
	rows, err := q.db.QueryContext(ctx, loadInstalledPlugins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstalledPlugin{}
	for rows.Next() {
		var i InstalledPlugin
		if err := rows.Scan(
			&i.Name,
			&i.Owner,
			&i.Version,
			&i.BinaryPath,
			&i.Manifest,
			&i.InstalledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadRunningPlugins = `-- name: LoadRunningPlugins :many
SELECT name, owner, version, binary_path, env, config, start_order, started_at
FROM running_plugins ORDER BY start_order
`

type LoadRunningPluginsRow struct {
	Name       string
	Owner      string
	Version    string
	BinaryPath string
	Env        string
	Config     string
	StartOrder int32
	StartedAt  time.Time
}

func (q *Queries) LoadRunningPlugins(ctx context.Context) ([]LoadRunningPluginsRow, error) {
	rows, err := q.db.QueryContext(ctx, loadRunningPlugins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadRunningPluginsRow{}
	for rows.Next() {
		var i LoadRunningPluginsRow
		if err := rows.Scan(
			&i.Name,
			&i.Owner,
			&i.Version,
			&i.BinaryPath,
			&i.Env,
			&i.Config,
			&i.StartOrder,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadSchedules = `-- name: LoadSchedules :many
SELECT id, expression, duration_ns, topic, payload, source, created_at, next_fire, one_time
FROM schedules
`

func (q *Queries) LoadSchedules(ctx context.Context) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, loadSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.Expression,
			&i.DurationNs,
			&i.Topic,
			&i.Payload,
			&i.Source,
			&i.CreatedAt,
			&i.NextFire,
			&i.OneTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAuditEvents = `-- name: PruneAuditEvents :exec
DELETE FROM audit_events WHERE created_at < $1
`

func (q *Queries) PruneAuditEvents(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.ExecContext(ctx, pruneAuditEvents, createdAt)
	return err
}

const queryAuditEventsAll = `-- name: QueryAuditEventsAll :many
SELECT id, created_at, category, event_type, source, runtime_id, namespace, data, duration, error_msg
FROM audit_events ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) QueryAuditEventsAll(ctx context.Context, limit int32) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, queryAuditEventsAll, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Category,
			&i.EventType,
			&i.Source,
			&i.RuntimeID,
			&i.Namespace,
			&i.Data,
			&i.Duration,
			&i.ErrorMsg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryAuditEventsByCategory = `-- name: QueryAuditEventsByCategory :many
SELECT id, created_at, category, event_type, source, runtime_id, namespace, data, duration, error_msg
FROM audit_events WHERE category = $1 ORDER BY created_at DESC LIMIT $2
`

type QueryAuditEventsByCategoryParams struct {
	Category string
	Limit    int32
}

func (q *Queries) QueryAuditEventsByCategory(ctx context.Context, arg QueryAuditEventsByCategoryParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, queryAuditEventsByCategory, arg.Category, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Category,
			&i.EventType,
			&i.Source,
			&i.RuntimeID,
			&i.Namespace,
			&i.Data,
			&i.Duration,
			&i.ErrorMsg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryAuditEventsBySource = `-- name: QueryAuditEventsBySource :many
SELECT id, created_at, category, event_type, source, runtime_id, namespace, data, duration, error_msg
FROM audit_events WHERE source = $1 ORDER BY created_at DESC LIMIT $2
`

type QueryAuditEventsBySourceParams struct {
	Source string
	Limit  int32
}

func (q *Queries) QueryAuditEventsBySource(ctx context.Context, arg QueryAuditEventsBySourceParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, queryAuditEventsBySource, arg.Source, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Category,
			&i.EventType,
			&i.Source,
			&i.RuntimeID,
			&i.Namespace,
			&i.Data,
			&i.Duration,
			&i.ErrorMsg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryAuditEventsByType = `-- name: QueryAuditEventsByType :many
SELECT id, created_at, category, event_type, source, runtime_id, namespace, data, duration, error_msg
FROM audit_events WHERE event_type = $1 ORDER BY created_at DESC LIMIT $2
`

type QueryAuditEventsByTypeParams struct {
	EventType string
	Limit     int32
}

func (q *Queries) QueryAuditEventsByType(ctx context.Context, arg QueryAuditEventsByTypeParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, queryAuditEventsByType, arg.EventType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Category,
			&i.EventType,
			&i.Source,
			&i.RuntimeID,
			&i.Namespace,
			&i.Data,
			&i.Duration,
			&i.ErrorMsg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryAuditEventsSince = `-- name: QueryAuditEventsSince :many
SELECT id, created_at, category, event_type, source, runtime_id, namespace, data, duration, error_msg
FROM audit_events WHERE created_at >= $1 ORDER BY created_at DESC LIMIT $2
`

type QueryAuditEventsSinceParams struct {
	CreatedAt time.Time
	Limit     int32
}

func (q *Queries) QueryAuditEventsSince(ctx context.Context, arg QueryAuditEventsSinceParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, queryAuditEventsSince, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Category,
			&i.EventType,
			&i.Source,
			&i.RuntimeID,
			&i.Namespace,
			&i.Data,
			&i.Duration,
			&i.ErrorMsg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAuditEvent = `-- name: RecordAuditEvent :exec

INSERT INTO audit_events (id, created_at, category, event_type, source, runtime_id, namespace, data, duration, error_msg)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type RecordAuditEventParams struct {
	ID        string
	CreatedAt time.Time
	Category  string
	EventType string
	Source    string
	RuntimeID string
	Namespace string
	Data      string
	Duration  int64
	ErrorMsg  string
}

// ── Audit Events ──
func (q *Queries) RecordAuditEvent(ctx context.Context, arg RecordAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, recordAuditEvent,
		arg.ID,
		arg.CreatedAt,
		arg.Category,
		arg.EventType,
		arg.Source,
		arg.RuntimeID,
		arg.Namespace,
		arg.Data,
		arg.Duration,
		arg.ErrorMsg,
	)
	return err
}

const saveDeployment = `-- name: SaveDeployment :exec

INSERT INTO deployments (source, code, deploy_order, deployed_at, package_name)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (source) DO UPDATE SET
    code = EXCLUDED.code,
    deploy_order = EXCLUDED.deploy_order,
    deployed_at = EXCLUDED.deployed_at,
    package_name = EXCLUDED.package_name
`

type SaveDeploymentParams struct {
	Source      string
	Code        string
	DeployOrder int32
	DeployedAt  time.Time
	PackageName string
}

// ── Deployments ──
func (q *Queries) SaveDeployment(ctx context.Context, arg SaveDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, saveDeployment,
		arg.Source,
		arg.Code,
		arg.DeployOrder,
		arg.DeployedAt,
		arg.PackageName,
	)
	return err
}

const saveInstalledPlugin = `-- name: SaveInstalledPlugin :exec

INSERT INTO installed_plugins (name, owner, version, binary_path, manifest, installed_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (owner, name) DO UPDATE SET
    version = EXCLUDED.version,
    binary_path = EXCLUDED.binary_path,
    manifest = EXCLUDED.manifest,
    installed_at = EXCLUDED.installed_at
`

type SaveInstalledPluginParams struct {
	Name        string
	Owner       string
	Version     string
	BinaryPath  string
	Manifest    string
	InstalledAt time.Time
}

// ── Installed Plugins ──
func (q *Queries) SaveInstalledPlugin(ctx context.Context, arg SaveInstalledPluginParams) error {
	_, err := q.db.ExecContext(ctx, saveInstalledPlugin,
		arg.Name,
		arg.Owner,
		arg.Version,
		arg.BinaryPath,
		arg.Manifest,
		arg.InstalledAt,
	)
	return err
}

const saveRunningPlugin = `-- name: SaveRunningPlugin :exec

INSERT INTO running_plugins (name, owner, version, binary_path, env, config, start_order, started_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (name) DO UPDATE SET
    owner = EXCLUDED.owner,
    version = EXCLUDED.version,
    binary_path = EXCLUDED.binary_path,
    env = EXCLUDED.env,
    config = EXCLUDED.config,
    start_order = EXCLUDED.start_order,
    started_at = EXCLUDED.started_at
`

type SaveRunningPluginParams struct {
	Name       string
	Owner      string
	Version    string
	BinaryPath string
	Env        string
	Config     string
	StartOrder int32
	StartedAt  time.Time
}

// ── Running Plugins ──
func (q *Queries) SaveRunningPlugin(ctx context.Context, arg SaveRunningPluginParams) error {
	_, err := q.db.ExecContext(ctx, saveRunningPlugin,
		arg.Name,
		arg.Owner,
		arg.Version,
		arg.BinaryPath,
		arg.Env,
		arg.Config,
		arg.StartOrder,
		arg.StartedAt,
	)
	return err
}

const saveSchedule = `-- name: SaveSchedule :exec

INSERT INTO schedules (id, expression, duration_ns, topic, payload, source, created_at, next_fire, one_time)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET
    expression = EXCLUDED.expression,
    duration_ns = EXCLUDED.duration_ns,
    topic = EXCLUDED.topic,
    payload = EXCLUDED.payload,
    source = EXCLUDED.source,
    created_at = EXCLUDED.created_at,
    next_fire = EXCLUDED.next_fire,
    one_time = EXCLUDED.one_time
`

type SaveScheduleParams struct {
	ID         string
	Expression string
	DurationNs int64
	Topic      string
	Payload    string
	Source     string
	CreatedAt  time.Time
	NextFire   time.Time
	OneTime    bool
}

// ── Schedules ──
func (q *Queries) SaveSchedule(ctx context.Context, arg SaveScheduleParams) error {
	_, err := q.db.ExecContext(ctx, saveSchedule,
		arg.ID,
		arg.Expression,
		arg.DurationNs,
		arg.Topic,
		arg.Payload,
		arg.Source,
		arg.CreatedAt,
		arg.NextFire,
		arg.OneTime,
	)
	return err
}
