// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: proto/plugin/v1/plugin.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BrainkitPluginService_Handshake_FullMethodName     = "/brainkit.plugin.v1.BrainkitPluginService/Handshake"
	BrainkitPluginService_Manifest_FullMethodName      = "/brainkit.plugin.v1.BrainkitPluginService/Manifest"
	BrainkitPluginService_MessageStream_FullMethodName = "/brainkit.plugin.v1.BrainkitPluginService/MessageStream"
	BrainkitPluginService_Health_FullMethodName        = "/brainkit.plugin.v1.BrainkitPluginService/Health"
)

// BrainkitPluginServiceClient is the client API for BrainkitPluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BrainkitPluginService is implemented by the PLUGIN process.
type BrainkitPluginServiceClient interface {
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	Manifest(ctx context.Context, in *ManifestRequest, opts ...grpc.CallOption) (*PluginManifest, error)
	MessageStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PluginMessage, PluginMessage], error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type brainkitPluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrainkitPluginServiceClient(cc grpc.ClientConnInterface) BrainkitPluginServiceClient {
	return &brainkitPluginServiceClient{cc}
}

func (c *brainkitPluginServiceClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, BrainkitPluginService_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainkitPluginServiceClient) Manifest(ctx context.Context, in *ManifestRequest, opts ...grpc.CallOption) (*PluginManifest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginManifest)
	err := c.cc.Invoke(ctx, BrainkitPluginService_Manifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainkitPluginServiceClient) MessageStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PluginMessage, PluginMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BrainkitPluginService_ServiceDesc.Streams[0], BrainkitPluginService_MessageStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PluginMessage, PluginMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrainkitPluginService_MessageStreamClient = grpc.BidiStreamingClient[PluginMessage, PluginMessage]

func (c *brainkitPluginServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, BrainkitPluginService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrainkitPluginServiceServer is the server API for BrainkitPluginService service.
// All implementations must embed UnimplementedBrainkitPluginServiceServer
// for forward compatibility.
//
// BrainkitPluginService is implemented by the PLUGIN process.
type BrainkitPluginServiceServer interface {
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	Manifest(context.Context, *ManifestRequest) (*PluginManifest, error)
	MessageStream(grpc.BidiStreamingServer[PluginMessage, PluginMessage]) error
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedBrainkitPluginServiceServer()
}

// UnimplementedBrainkitPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrainkitPluginServiceServer struct{}

func (UnimplementedBrainkitPluginServiceServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedBrainkitPluginServiceServer) Manifest(context.Context, *ManifestRequest) (*PluginManifest, error) {
	return nil, status.Error(codes.Unimplemented, "method Manifest not implemented")
}
func (UnimplementedBrainkitPluginServiceServer) MessageStream(grpc.BidiStreamingServer[PluginMessage, PluginMessage]) error {
	return status.Error(codes.Unimplemented, "method MessageStream not implemented")
}
func (UnimplementedBrainkitPluginServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedBrainkitPluginServiceServer) mustEmbedUnimplementedBrainkitPluginServiceServer() {}
func (UnimplementedBrainkitPluginServiceServer) testEmbeddedByValue()                               {}

// UnsafeBrainkitPluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrainkitPluginServiceServer will
// result in compilation errors.
type UnsafeBrainkitPluginServiceServer interface {
	mustEmbedUnimplementedBrainkitPluginServiceServer()
}

func RegisterBrainkitPluginServiceServer(s grpc.ServiceRegistrar, srv BrainkitPluginServiceServer) {
	// If the following call panics, it indicates UnimplementedBrainkitPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrainkitPluginService_ServiceDesc, srv)
}

func _BrainkitPluginService_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainkitPluginServiceServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainkitPluginService_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainkitPluginServiceServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainkitPluginService_Manifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainkitPluginServiceServer).Manifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainkitPluginService_Manifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainkitPluginServiceServer).Manifest(ctx, req.(*ManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainkitPluginService_MessageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BrainkitPluginServiceServer).MessageStream(&grpc.GenericServerStream[PluginMessage, PluginMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrainkitPluginService_MessageStreamServer = grpc.BidiStreamingServer[PluginMessage, PluginMessage]

func _BrainkitPluginService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainkitPluginServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainkitPluginService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainkitPluginServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BrainkitPluginService_ServiceDesc is the grpc.ServiceDesc for BrainkitPluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrainkitPluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "brainkit.plugin.v1.BrainkitPluginService",
	HandlerType: (*BrainkitPluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _BrainkitPluginService_Handshake_Handler,
		},
		{
			MethodName: "Manifest",
			Handler:    _BrainkitPluginService_Manifest_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _BrainkitPluginService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MessageStream",
			Handler:       _BrainkitPluginService_MessageStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/plugin/v1/plugin.proto",
}

const (
	BrainkitHostService_Handshake_FullMethodName     = "/brainkit.plugin.v1.BrainkitHostService/Handshake"
	BrainkitHostService_MessageStream_FullMethodName = "/brainkit.plugin.v1.BrainkitHostService/MessageStream"
)

// BrainkitHostServiceClient is the client API for BrainkitHostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BrainkitHostService is implemented by the KIT process.
type BrainkitHostServiceClient interface {
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	MessageStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PluginMessage, PluginMessage], error)
}

type brainkitHostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrainkitHostServiceClient(cc grpc.ClientConnInterface) BrainkitHostServiceClient {
	return &brainkitHostServiceClient{cc}
}

func (c *brainkitHostServiceClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, BrainkitHostService_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainkitHostServiceClient) MessageStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PluginMessage, PluginMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BrainkitHostService_ServiceDesc.Streams[0], BrainkitHostService_MessageStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PluginMessage, PluginMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrainkitHostService_MessageStreamClient = grpc.BidiStreamingClient[PluginMessage, PluginMessage]

// BrainkitHostServiceServer is the server API for BrainkitHostService service.
// All implementations must embed UnimplementedBrainkitHostServiceServer
// for forward compatibility.
//
// BrainkitHostService is implemented by the KIT process.
type BrainkitHostServiceServer interface {
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	MessageStream(grpc.BidiStreamingServer[PluginMessage, PluginMessage]) error
	mustEmbedUnimplementedBrainkitHostServiceServer()
}

// UnimplementedBrainkitHostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrainkitHostServiceServer struct{}

func (UnimplementedBrainkitHostServiceServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedBrainkitHostServiceServer) MessageStream(grpc.BidiStreamingServer[PluginMessage, PluginMessage]) error {
	return status.Error(codes.Unimplemented, "method MessageStream not implemented")
}
func (UnimplementedBrainkitHostServiceServer) mustEmbedUnimplementedBrainkitHostServiceServer() {}
func (UnimplementedBrainkitHostServiceServer) testEmbeddedByValue()                             {}

// UnsafeBrainkitHostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrainkitHostServiceServer will
// result in compilation errors.
type UnsafeBrainkitHostServiceServer interface {
	mustEmbedUnimplementedBrainkitHostServiceServer()
}

func RegisterBrainkitHostServiceServer(s grpc.ServiceRegistrar, srv BrainkitHostServiceServer) {
	// If the following call panics, it indicates UnimplementedBrainkitHostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrainkitHostService_ServiceDesc, srv)
}

func _BrainkitHostService_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainkitHostServiceServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainkitHostService_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainkitHostServiceServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainkitHostService_MessageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BrainkitHostServiceServer).MessageStream(&grpc.GenericServerStream[PluginMessage, PluginMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrainkitHostService_MessageStreamServer = grpc.BidiStreamingServer[PluginMessage, PluginMessage]

// BrainkitHostService_ServiceDesc is the grpc.ServiceDesc for BrainkitHostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrainkitHostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "brainkit.plugin.v1.BrainkitHostService",
	HandlerType: (*BrainkitHostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _BrainkitHostService_Handshake_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MessageStream",
			Handler:       _BrainkitHostService_MessageStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/plugin/v1/plugin.proto",
}
