// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: proto/plugin/v1/plugin.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BrainletPluginService_Handshake_FullMethodName     = "/brainkit.plugin.v1.BrainletPluginService/Handshake"
	BrainletPluginService_Manifest_FullMethodName      = "/brainkit.plugin.v1.BrainletPluginService/Manifest"
	BrainletPluginService_MessageStream_FullMethodName = "/brainkit.plugin.v1.BrainletPluginService/MessageStream"
	BrainletPluginService_Health_FullMethodName        = "/brainkit.plugin.v1.BrainletPluginService/Health"
)

// BrainletPluginServiceClient is the client API for BrainletPluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BrainletPluginService is implemented by the PLUGIN process.
type BrainletPluginServiceClient interface {
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	Manifest(ctx context.Context, in *ManifestRequest, opts ...grpc.CallOption) (*PluginManifest, error)
	MessageStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PluginMessage, PluginMessage], error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type brainletPluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrainletPluginServiceClient(cc grpc.ClientConnInterface) BrainletPluginServiceClient {
	return &brainletPluginServiceClient{cc}
}

func (c *brainletPluginServiceClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, BrainletPluginService_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainletPluginServiceClient) Manifest(ctx context.Context, in *ManifestRequest, opts ...grpc.CallOption) (*PluginManifest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginManifest)
	err := c.cc.Invoke(ctx, BrainletPluginService_Manifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainletPluginServiceClient) MessageStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PluginMessage, PluginMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BrainletPluginService_ServiceDesc.Streams[0], BrainletPluginService_MessageStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PluginMessage, PluginMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrainletPluginService_MessageStreamClient = grpc.BidiStreamingClient[PluginMessage, PluginMessage]

func (c *brainletPluginServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, BrainletPluginService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrainletPluginServiceServer is the server API for BrainletPluginService service.
// All implementations must embed UnimplementedBrainletPluginServiceServer
// for forward compatibility.
//
// BrainletPluginService is implemented by the PLUGIN process.
type BrainletPluginServiceServer interface {
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	Manifest(context.Context, *ManifestRequest) (*PluginManifest, error)
	MessageStream(grpc.BidiStreamingServer[PluginMessage, PluginMessage]) error
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedBrainletPluginServiceServer()
}

// UnimplementedBrainletPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrainletPluginServiceServer struct{}

func (UnimplementedBrainletPluginServiceServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedBrainletPluginServiceServer) Manifest(context.Context, *ManifestRequest) (*PluginManifest, error) {
	return nil, status.Error(codes.Unimplemented, "method Manifest not implemented")
}
func (UnimplementedBrainletPluginServiceServer) MessageStream(grpc.BidiStreamingServer[PluginMessage, PluginMessage]) error {
	return status.Error(codes.Unimplemented, "method MessageStream not implemented")
}
func (UnimplementedBrainletPluginServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedBrainletPluginServiceServer) mustEmbedUnimplementedBrainletPluginServiceServer() {}
func (UnimplementedBrainletPluginServiceServer) testEmbeddedByValue()                               {}

// UnsafeBrainletPluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrainletPluginServiceServer will
// result in compilation errors.
type UnsafeBrainletPluginServiceServer interface {
	mustEmbedUnimplementedBrainletPluginServiceServer()
}

func RegisterBrainletPluginServiceServer(s grpc.ServiceRegistrar, srv BrainletPluginServiceServer) {
	// If the following call panics, it indicates UnimplementedBrainletPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrainletPluginService_ServiceDesc, srv)
}

func _BrainletPluginService_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainletPluginServiceServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainletPluginService_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainletPluginServiceServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainletPluginService_Manifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainletPluginServiceServer).Manifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainletPluginService_Manifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainletPluginServiceServer).Manifest(ctx, req.(*ManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainletPluginService_MessageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BrainletPluginServiceServer).MessageStream(&grpc.GenericServerStream[PluginMessage, PluginMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrainletPluginService_MessageStreamServer = grpc.BidiStreamingServer[PluginMessage, PluginMessage]

func _BrainletPluginService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainletPluginServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainletPluginService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainletPluginServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BrainletPluginService_ServiceDesc is the grpc.ServiceDesc for BrainletPluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrainletPluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "brainkit.plugin.v1.BrainletPluginService",
	HandlerType: (*BrainletPluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _BrainletPluginService_Handshake_Handler,
		},
		{
			MethodName: "Manifest",
			Handler:    _BrainletPluginService_Manifest_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _BrainletPluginService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MessageStream",
			Handler:       _BrainletPluginService_MessageStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/plugin/v1/plugin.proto",
}

const (
	BrainletHostService_Handshake_FullMethodName     = "/brainkit.plugin.v1.BrainletHostService/Handshake"
	BrainletHostService_MessageStream_FullMethodName = "/brainkit.plugin.v1.BrainletHostService/MessageStream"
)

// BrainletHostServiceClient is the client API for BrainletHostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BrainletHostService is implemented by the KIT process.
type BrainletHostServiceClient interface {
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	MessageStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PluginMessage, PluginMessage], error)
}

type brainletHostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrainletHostServiceClient(cc grpc.ClientConnInterface) BrainletHostServiceClient {
	return &brainletHostServiceClient{cc}
}

func (c *brainletHostServiceClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, BrainletHostService_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brainletHostServiceClient) MessageStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PluginMessage, PluginMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BrainletHostService_ServiceDesc.Streams[0], BrainletHostService_MessageStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PluginMessage, PluginMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrainletHostService_MessageStreamClient = grpc.BidiStreamingClient[PluginMessage, PluginMessage]

// BrainletHostServiceServer is the server API for BrainletHostService service.
// All implementations must embed UnimplementedBrainletHostServiceServer
// for forward compatibility.
//
// BrainletHostService is implemented by the KIT process.
type BrainletHostServiceServer interface {
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	MessageStream(grpc.BidiStreamingServer[PluginMessage, PluginMessage]) error
	mustEmbedUnimplementedBrainletHostServiceServer()
}

// UnimplementedBrainletHostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrainletHostServiceServer struct{}

func (UnimplementedBrainletHostServiceServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedBrainletHostServiceServer) MessageStream(grpc.BidiStreamingServer[PluginMessage, PluginMessage]) error {
	return status.Error(codes.Unimplemented, "method MessageStream not implemented")
}
func (UnimplementedBrainletHostServiceServer) mustEmbedUnimplementedBrainletHostServiceServer() {}
func (UnimplementedBrainletHostServiceServer) testEmbeddedByValue()                             {}

// UnsafeBrainletHostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrainletHostServiceServer will
// result in compilation errors.
type UnsafeBrainletHostServiceServer interface {
	mustEmbedUnimplementedBrainletHostServiceServer()
}

func RegisterBrainletHostServiceServer(s grpc.ServiceRegistrar, srv BrainletHostServiceServer) {
	// If the following call panics, it indicates UnimplementedBrainletHostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrainletHostService_ServiceDesc, srv)
}

func _BrainletHostService_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrainletHostServiceServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrainletHostService_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrainletHostServiceServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrainletHostService_MessageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BrainletHostServiceServer).MessageStream(&grpc.GenericServerStream[PluginMessage, PluginMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrainletHostService_MessageStreamServer = grpc.BidiStreamingServer[PluginMessage, PluginMessage]

// BrainletHostService_ServiceDesc is the grpc.ServiceDesc for BrainletHostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrainletHostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "brainkit.plugin.v1.BrainletHostService",
	HandlerType: (*BrainletHostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _BrainletHostService_Handshake_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MessageStream",
			Handler:       _BrainletHostService_MessageStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/plugin/v1/plugin.proto",
}
