// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/plugin/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HandshakeRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HandshakeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type HandshakeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Accepted        bool                   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectionReason string                 `protobuf:"bytes,4,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HandshakeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HandshakeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HandshakeResponse) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

type ManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestRequest) Reset() {
	*x = ManifestRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestRequest) ProtoMessage() {}

func (x *ManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestRequest.ProtoReflect.Descriptor instead.
func (*ManifestRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

type PluginManifest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Name          string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                    `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tools         []*ToolDefinition         `protobuf:"bytes,4,rep,name=tools,proto3" json:"tools,omitempty"`
	Interceptors  []*InterceptorDefinition  `protobuf:"bytes,5,rep,name=interceptors,proto3" json:"interceptors,omitempty"`
	Events        []*EventDefinition        `protobuf:"bytes,6,rep,name=events,proto3" json:"events,omitempty"`
	Subscriptions []*SubscriptionDefinition `protobuf:"bytes,7,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	Agents        []*AgentDefinition        `protobuf:"bytes,8,rep,name=agents,proto3" json:"agents,omitempty"`
	Files         []*FileDefinition         `protobuf:"bytes,9,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginManifest) Reset() {
	*x = PluginManifest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginManifest) ProtoMessage() {}

func (x *PluginManifest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginManifest.ProtoReflect.Descriptor instead.
func (*PluginManifest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *PluginManifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginManifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginManifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginManifest) GetTools() []*ToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *PluginManifest) GetInterceptors() []*InterceptorDefinition {
	if x != nil {
		return x.Interceptors
	}
	return nil
}

func (x *PluginManifest) GetEvents() []*EventDefinition {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *PluginManifest) GetSubscriptions() []*SubscriptionDefinition {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *PluginManifest) GetAgents() []*AgentDefinition {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *PluginManifest) GetFiles() []*FileDefinition {
	if x != nil {
		return x.Files
	}
	return nil
}

type ToolDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	InputSchema   string                 `protobuf:"bytes,3,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	OutputSchema  string                 `protobuf:"bytes,4,opt,name=output_schema,json=outputSchema,proto3" json:"output_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetInputSchema() string {
	if x != nil {
		return x.InputSchema
	}
	return ""
}

func (x *ToolDefinition) GetOutputSchema() string {
	if x != nil {
		return x.OutputSchema
	}
	return ""
}

type InterceptorDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Priority      int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	TopicFilter   string                 `protobuf:"bytes,3,opt,name=topic_filter,json=topicFilter,proto3" json:"topic_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterceptorDefinition) Reset() {
	*x = InterceptorDefinition{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterceptorDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterceptorDefinition) ProtoMessage() {}

func (x *InterceptorDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterceptorDefinition.ProtoReflect.Descriptor instead.
func (*InterceptorDefinition) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *InterceptorDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InterceptorDefinition) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *InterceptorDefinition) GetTopicFilter() string {
	if x != nil {
		return x.TopicFilter
	}
	return ""
}

type EventDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Schema        string                 `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventDefinition) Reset() {
	*x = EventDefinition{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDefinition) ProtoMessage() {}

func (x *EventDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventDefinition.ProtoReflect.Descriptor instead.
func (*EventDefinition) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *EventDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventDefinition) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

type SubscriptionDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionDefinition) Reset() {
	*x = SubscriptionDefinition{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionDefinition) ProtoMessage() {}

func (x *SubscriptionDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionDefinition.ProtoReflect.Descriptor instead.
func (*SubscriptionDefinition) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *SubscriptionDefinition) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type AgentDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Tools         []string               `protobuf:"bytes,4,rep,name=tools,proto3" json:"tools,omitempty"`
	Instructions  string                 `protobuf:"bytes,5,opt,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentDefinition) Reset() {
	*x = AgentDefinition{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDefinition) ProtoMessage() {}

func (x *AgentDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDefinition.ProtoReflect.Descriptor instead.
func (*AgentDefinition) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *AgentDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentDefinition) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AgentDefinition) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *AgentDefinition) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

type FileDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDefinition) Reset() {
	*x = FileDefinition{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDefinition) ProtoMessage() {}

func (x *FileDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDefinition.ProtoReflect.Descriptor instead.
func (*FileDefinition) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *FileDefinition) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FileDefinition) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PluginMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	TraceId       string                 `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ReplyTo       string                 `protobuf:"bytes,6,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	Topic         string                 `protobuf:"bytes,7,opt,name=topic,proto3" json:"topic,omitempty"`
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	CallerId      string                 `protobuf:"bytes,9,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	Depth         int32                  `protobuf:"varint,10,opt,name=depth,proto3" json:"depth,omitempty"`
	Payload       []byte                 `protobuf:"bytes,11,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginMessage) Reset() {
	*x = PluginMessage{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMessage) ProtoMessage() {}

func (x *PluginMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMessage.ProtoReflect.Descriptor instead.
func (*PluginMessage) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *PluginMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PluginMessage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginMessage) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *PluginMessage) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *PluginMessage) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *PluginMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PluginMessage) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PluginMessage) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

func (x *PluginMessage) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *PluginMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PluginMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{11}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_proto_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/plugin/v1/plugin.proto\x12\x12brainkit.plugin.v1\"T\n" +
	"\x10HandshakeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\x88\x01\n" +
	"\x11HandshakeResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted\x12)\n" +
	"\x10rejection_reason\x18\x04 \x01(\tR\x0frejectionReason\"\x11\n" +
	"\x0fManifestRequest\"\xef\x03\n" +
	"\x0ePluginManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x128\n" +
	"\x05tools\x18\x04 \x03(\v2\".brainkit.plugin.v1.ToolDefinitionR\x05tools\x12M\n" +
	"\finterceptors\x18\x05 \x03(\v2).brainkit.plugin.v1.InterceptorDefinitionR\finterceptors\x12;\n" +
	"\x06events\x18\x06 \x03(\v2#.brainkit.plugin.v1.EventDefinitionR\x06events\x12P\n" +
	"\rsubscriptions\x18\a \x03(\v2*.brainkit.plugin.v1.SubscriptionDefinitionR\rsubscriptions\x12;\n" +
	"\x06agents\x18\b \x03(\v2#.brainkit.plugin.v1.AgentDefinitionR\x06agents\x128\n" +
	"\x05files\x18\t \x03(\v2\".brainkit.plugin.v1.FileDefinitionR\x05files\"\x94\x01\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\finput_schema\x18\x03 \x01(\tR\vinputSchema\x12#\n" +
	"\routput_schema\x18\x04 \x01(\tR\foutputSchemaJ\x04\b\x05\x10\x06\"j\n" +
	"\x15InterceptorDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x12!\n" +
	"\ftopic_filter\x18\x03 \x01(\tR\vtopicFilter\"=\n" +
	"\x0fEventDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\tR\x06schema\".\n" +
	"\x16SubscriptionDefinition\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"\x97\x01\n" +
	"\x0fAgentDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x14\n" +
	"\x05tools\x18\x04 \x03(\tR\x05tools\x12\"\n" +
	"\finstructions\x18\x05 \x01(\tR\finstructions\"R\n" +
	"\x0eFileDefinition\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\xa7\x03\n" +
	"\rPluginMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\tR\bparentId\x12\x19\n" +
	"\breply_to\x18\x06 \x01(\tR\areplyTo\x12\x14\n" +
	"\x05topic\x18\a \x01(\tR\x05topic\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x1b\n" +
	"\tcaller_id\x18\t \x01(\tR\bcallerId\x12\x14\n" +
	"\x05depth\x18\n" +
	" \x01(\x05R\x05depth\x12\x18\n" +
	"\apayload\x18\v \x01(\fR\apayload\x12K\n" +
	"\bmetadata\x18\f \x03(\v2/.brainkit.plugin.v1.PluginMessage.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0f\n" +
	"\rHealthRequest\"D\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xf2\x02\n" +
	"\x15BrainletPluginService\x12X\n" +
	"\tHandshake\x12$.brainkit.plugin.v1.HandshakeRequest\x1a%.brainkit.plugin.v1.HandshakeResponse\x12S\n" +
	"\bManifest\x12#.brainkit.plugin.v1.ManifestRequest\x1a\".brainkit.plugin.v1.PluginManifest\x12Y\n" +
	"\rMessageStream\x12!.brainkit.plugin.v1.PluginMessage\x1a!.brainkit.plugin.v1.PluginMessage(\x010\x01\x12O\n" +
	"\x06Health\x12!.brainkit.plugin.v1.HealthRequest\x1a\".brainkit.plugin.v1.HealthResponse2\xca\x01\n" +
	"\x13BrainletHostService\x12X\n" +
	"\tHandshake\x12$.brainkit.plugin.v1.HandshakeRequest\x1a%.brainkit.plugin.v1.HandshakeResponse\x12Y\n" +
	"\rMessageStream\x12!.brainkit.plugin.v1.PluginMessage\x1a!.brainkit.plugin.v1.PluginMessage(\x010\x01B7Z5github.com/brainlet/brainkit/proto/plugin/v1;pluginv1b\x06proto3"

var (
	file_proto_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_proto_plugin_v1_plugin_proto_rawDescData []byte
)

func file_proto_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_proto_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_proto_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugin_v1_plugin_proto_rawDesc), len(file_proto_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_proto_plugin_v1_plugin_proto_rawDescData
}

var file_proto_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_plugin_v1_plugin_proto_goTypes = []any{
	(*HandshakeRequest)(nil),       // 0: brainkit.plugin.v1.HandshakeRequest
	(*HandshakeResponse)(nil),      // 1: brainkit.plugin.v1.HandshakeResponse
	(*ManifestRequest)(nil),        // 2: brainkit.plugin.v1.ManifestRequest
	(*PluginManifest)(nil),         // 3: brainkit.plugin.v1.PluginManifest
	(*ToolDefinition)(nil),         // 4: brainkit.plugin.v1.ToolDefinition
	(*InterceptorDefinition)(nil),  // 5: brainkit.plugin.v1.InterceptorDefinition
	(*EventDefinition)(nil),        // 6: brainkit.plugin.v1.EventDefinition
	(*SubscriptionDefinition)(nil), // 7: brainkit.plugin.v1.SubscriptionDefinition
	(*AgentDefinition)(nil),        // 8: brainkit.plugin.v1.AgentDefinition
	(*FileDefinition)(nil),         // 9: brainkit.plugin.v1.FileDefinition
	(*PluginMessage)(nil),          // 10: brainkit.plugin.v1.PluginMessage
	(*HealthRequest)(nil),          // 11: brainkit.plugin.v1.HealthRequest
	(*HealthResponse)(nil),         // 12: brainkit.plugin.v1.HealthResponse
	nil,                            // 13: brainkit.plugin.v1.PluginMessage.MetadataEntry
}
var file_proto_plugin_v1_plugin_proto_depIdxs = []int32{
	4,  // 0: brainkit.plugin.v1.PluginManifest.tools:type_name -> brainkit.plugin.v1.ToolDefinition
	5,  // 1: brainkit.plugin.v1.PluginManifest.interceptors:type_name -> brainkit.plugin.v1.InterceptorDefinition
	6,  // 2: brainkit.plugin.v1.PluginManifest.events:type_name -> brainkit.plugin.v1.EventDefinition
	7,  // 3: brainkit.plugin.v1.PluginManifest.subscriptions:type_name -> brainkit.plugin.v1.SubscriptionDefinition
	8,  // 4: brainkit.plugin.v1.PluginManifest.agents:type_name -> brainkit.plugin.v1.AgentDefinition
	9,  // 5: brainkit.plugin.v1.PluginManifest.files:type_name -> brainkit.plugin.v1.FileDefinition
	13, // 6: brainkit.plugin.v1.PluginMessage.metadata:type_name -> brainkit.plugin.v1.PluginMessage.MetadataEntry
	0,  // 7: brainkit.plugin.v1.BrainletPluginService.Handshake:input_type -> brainkit.plugin.v1.HandshakeRequest
	2,  // 8: brainkit.plugin.v1.BrainletPluginService.Manifest:input_type -> brainkit.plugin.v1.ManifestRequest
	10, // 9: brainkit.plugin.v1.BrainletPluginService.MessageStream:input_type -> brainkit.plugin.v1.PluginMessage
	11, // 10: brainkit.plugin.v1.BrainletPluginService.Health:input_type -> brainkit.plugin.v1.HealthRequest
	0,  // 11: brainkit.plugin.v1.BrainletHostService.Handshake:input_type -> brainkit.plugin.v1.HandshakeRequest
	10, // 12: brainkit.plugin.v1.BrainletHostService.MessageStream:input_type -> brainkit.plugin.v1.PluginMessage
	1,  // 13: brainkit.plugin.v1.BrainletPluginService.Handshake:output_type -> brainkit.plugin.v1.HandshakeResponse
	3,  // 14: brainkit.plugin.v1.BrainletPluginService.Manifest:output_type -> brainkit.plugin.v1.PluginManifest
	10, // 15: brainkit.plugin.v1.BrainletPluginService.MessageStream:output_type -> brainkit.plugin.v1.PluginMessage
	12, // 16: brainkit.plugin.v1.BrainletPluginService.Health:output_type -> brainkit.plugin.v1.HealthResponse
	1,  // 17: brainkit.plugin.v1.BrainletHostService.Handshake:output_type -> brainkit.plugin.v1.HandshakeResponse
	10, // 18: brainkit.plugin.v1.BrainletHostService.MessageStream:output_type -> brainkit.plugin.v1.PluginMessage
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_plugin_v1_plugin_proto_init() }
func file_proto_plugin_v1_plugin_proto_init() {
	if File_proto_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugin_v1_plugin_proto_rawDesc), len(file_proto_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_proto_plugin_v1_plugin_proto_depIdxs,
		MessageInfos:      file_proto_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_proto_plugin_v1_plugin_proto = out.File
	file_proto_plugin_v1_plugin_proto_goTypes = nil
	file_proto_plugin_v1_plugin_proto_depIdxs = nil
}
