// sdkgen generates typed wrappers from Brainkit message package types.
//
// The output file (default ./sdk/typed_gen.go) contains wrappers in the
// scanned message package:
//   - Publish{Name}(rt, ctx, msg, opts...) (PublishResult, error)
//   - Subscribe{Name}Resp(rt, ctx, topic, handler) (func(), error)
//   - Call{Name}(rt, ctx, msg, opts...) (Resp, error)
//   - Emit{Name}(rt, ctx, msg) error  — events
//   - Subscribe{Name}(rt, ctx, topic, handler) (func(), error)
//
// Each sync wrapper is a thin delegate to sdk.Call[Msg, Resp] that removes the
// type-parameter guessing. Only emitted for Msg types with a matching Resp.
//
// Usage:
//
//	go run ./cmd/sdkgen/ -messages ./sdk -out ./sdk/typed_gen.go
//	go run ./cmd/sdkgen/ -messages ./modules/health -out ./modules/health/typed_gen.go
package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type msgType struct {
	Name     string // e.g. "ToolCallMsg"
	BaseName string // e.g. "ToolCall"
	RespName string // e.g. "ToolCallResp" (empty if no response)
	IsEvent  bool
}

func main() {
	messagesDir := flag.String("messages", "./sdk", "path to message package")
	outFile := flag.String("out", "./sdk/typed_gen.go", "typed wrappers output path")
	outPackage := flag.String("package", "", "output package name; default is the package found in -messages")
	flag.Parse()

	packageName, types, err := scanMessages(*messagesDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "scan: %v\n", err)
		os.Exit(1)
	}
	if *outPackage != "" {
		packageName = *outPackage
	}

	if err := generate(*outFile, packageName, types); err != nil {
		fmt.Fprintf(os.Stderr, "generate: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("generated async wrappers → %s (%d types)\n", *outFile, len(types))

	calls := 0
	for _, mt := range types {
		if !mt.IsEvent && mt.RespName != "" {
			calls++
		}
	}
	fmt.Printf("generated sync Call wrappers in %s (%d pairs)\n", *outFile, calls)
}

func scanMessages(dir string) (string, []msgType, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		// Skip generated and test files to avoid stale references and external
		// test packages.
		return fi.Name() != "typed_gen.go" && !strings.HasSuffix(fi.Name(), "_test.go")
	}, 0)
	if err != nil {
		return "", nil, fmt.Errorf("parse %s: %w", dir, err)
	}
	if len(pkgs) != 1 {
		names := make([]string, 0, len(pkgs))
		for name := range pkgs {
			names = append(names, name)
		}
		sort.Strings(names)
		return "", nil, fmt.Errorf("expected one package in %s, found %s", dir, strings.Join(names, ", "))
	}
	var packageName string
	for name := range pkgs {
		packageName = name
	}

	// Collect all type names and which ones have BusTopic()
	allTypes := map[string]bool{}
	hasBusTopic := map[string]bool{}

	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			// Collect type declarations
			for _, decl := range file.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					continue
				}
				for _, spec := range genDecl.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					allTypes[ts.Name.Name] = true
				}
			}

			// Check for BusTopic() method declarations
			for _, decl := range file.Decls {
				funcDecl, ok := decl.(*ast.FuncDecl)
				if !ok || funcDecl.Recv == nil || funcDecl.Name.Name != "BusTopic" {
					continue
				}
				// Get the receiver type name
				for _, field := range funcDecl.Recv.List {
					switch t := field.Type.(type) {
					case *ast.Ident:
						hasBusTopic[t.Name] = true
					case *ast.StarExpr:
						if ident, ok := t.X.(*ast.Ident); ok {
							hasBusTopic[ident.Name] = true
						}
					}
				}
			}
		}
	}

	var result []msgType

	// Find Msg types with BusTopic
	for name := range hasBusTopic {
		if name == "CustomMsg" || name == "CustomEvent" {
			continue // skip dynamic-topic types
		}

		if strings.HasSuffix(name, "Msg") {
			base := strings.TrimSuffix(name, "Msg")
			mt := msgType{
				Name:     name,
				BaseName: base,
			}
			// Check for matching Resp type
			respName := base + "Resp"
			if allTypes[respName] {
				mt.RespName = respName
			}
			result = append(result, mt)
		} else if strings.HasSuffix(name, "Event") {
			base := strings.TrimSuffix(name, "Event")
			result = append(result, msgType{
				Name:     name,
				BaseName: base,
				IsEvent:  true,
			})
		}
	}

	sort.Slice(result, func(i, j int) bool {
		return result[i].BaseName < result[j].BaseName
	})

	return packageName, result, nil
}

func generate(outPath, packageName string, types []msgType) error {
	if err := os.MkdirAll(filepath.Dir(outPath), 0755); err != nil {
		return err
	}
	if packageName == "" {
		return fmt.Errorf("output package name is required")
	}

	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit publish/subscribe/call/emit.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// The underlying generic publish/call patterns are unchanged. These wrappers
// just add type safety.
//
// Regenerate with cmd/sdkgen from this repository.
package %s

`, packageName)

	refs := sdkRefs{
		runtime:       "Runtime",
		callerRuntime: "CallerRuntime",
		publishOption: "PublishOption",
		publishResult: "PublishResult",
		callOption:    "CallOption",
		message:       "Message",
		publish:       "Publish",
		subscribeTo:   "SubscribeTo",
		call:          "Call",
		emit:          "Emit",
	}
	if len(types) > 0 && packageName == "sdk" {
		b.WriteString(`import "context"

`)
	} else if len(types) > 0 {
		b.WriteString(`import (
	"context"

	"github.com/brainlet/brainkit/sdk"
)

`)
		refs = sdkRefs{
			runtime:       "sdk.Runtime",
			callerRuntime: "sdk.CallerRuntime",
			publishOption: "sdk.PublishOption",
			publishResult: "sdk.PublishResult",
			callOption:    "sdk.CallOption",
			message:       "sdk.Message",
			publish:       "sdk.Publish",
			subscribeTo:   "sdk.SubscribeTo",
			call:          "sdk.Call",
			emit:          "sdk.Emit",
		}
	}

	// Generate Msg wrappers (Publish + Subscribe + Call)
	for _, mt := range types {
		if mt.IsEvent {
			continue
		}

		// Publish wrapper
		fmt.Fprintf(&b, "// Publish%s publishes a %s and returns routing info for the response.\n", mt.BaseName, mt.Name)
		fmt.Fprintf(&b, "func Publish%s(rt %s, ctx context.Context, msg %s, opts ...%s) (%s, error) {\n", mt.BaseName, refs.runtime, mt.Name, refs.publishOption, refs.publishResult)
		fmt.Fprintf(&b, "\treturn %s(rt, ctx, msg, opts...)\n", refs.publish)
		fmt.Fprintf(&b, "}\n\n")

		// Subscribe wrapper (only if Resp type exists)
		if mt.RespName != "" {
			fmt.Fprintf(&b, "// Subscribe%sResp subscribes to the response topic for a %s command.\n", mt.BaseName, mt.Name)
			fmt.Fprintf(&b, "func Subscribe%sResp(rt %s, ctx context.Context, topic string, handler func(%s, %s)) (func(), error) {\n", mt.BaseName, refs.runtime, mt.RespName, refs.message)
			fmt.Fprintf(&b, "\treturn %s[%s](rt, ctx, topic, handler)\n", refs.subscribeTo, mt.RespName)
			fmt.Fprintf(&b, "}\n\n")

			fmt.Fprintf(&b, "// Call%s issues a synchronous request-response Call for %s.\n", mt.BaseName, mt.Name)
			fmt.Fprintf(&b, "func Call%s(rt %s, ctx context.Context, msg %s, opts ...%s) (%s, error) {\n", mt.BaseName, refs.callerRuntime, mt.Name, refs.callOption, mt.RespName)
			fmt.Fprintf(&b, "\treturn %s[%s, %s](rt, ctx, msg, opts...)\n", refs.call, mt.Name, mt.RespName)
			fmt.Fprintf(&b, "}\n\n")
		}
	}

	// Generate Event wrappers (Emit + Subscribe)
	for _, mt := range types {
		if !mt.IsEvent {
			continue
		}

		// Emit wrapper
		fmt.Fprintf(&b, "// Emit%s fires a %s event (no response expected).\n", mt.BaseName, mt.Name)
		fmt.Fprintf(&b, "func Emit%s(rt %s, ctx context.Context, msg %s) error {\n", mt.BaseName, refs.runtime, mt.Name)
		fmt.Fprintf(&b, "\treturn %s(rt, ctx, msg)\n", refs.emit)
		fmt.Fprintf(&b, "}\n\n")

		// Subscribe wrapper
		fmt.Fprintf(&b, "// Subscribe%s listens for %s events.\n", mt.BaseName, mt.Name)
		fmt.Fprintf(&b, "func Subscribe%s(rt %s, ctx context.Context, topic string, handler func(%s, %s)) (func(), error) {\n", mt.BaseName, refs.runtime, mt.Name, refs.message)
		fmt.Fprintf(&b, "\treturn %s[%s](rt, ctx, topic, handler)\n", refs.subscribeTo, mt.Name)
		fmt.Fprintf(&b, "}\n\n")
	}

	return os.WriteFile(outPath, []byte(b.String()), 0644)
}

type sdkRefs struct {
	runtime       string
	callerRuntime string
	publishOption string
	publishResult string
	callOption    string
	message       string
	publish       string
	subscribeTo   string
	call          string
	emit          string
}
