// sdkgen generates typed wrappers from Brainkit message package types.
//
// The output file (default ./sdk/typed_gen.go) contains wrappers in the
// scanned message package:
//   - Call{Name}(rt, ctx, msg, opts...) (Resp, error)
//   - Call{Name}WithCaller(caller, ctx, msg, opts...) (Resp, error)
//   - Emit{Name}(rt, ctx, msg) error  — events
//   - Subscribe{Name}(rt, ctx, topic, handler) (func(), error)
//
// Each sync wrapper is a thin delegate to sdk.Call[Msg, Resp] or
// sdk.CallWithCaller[Msg, Resp] that removes the type-parameter guessing. Only
// emitted for Msg types with a matching Resp.
//
// Usage:
//
//	go run ./cmd/sdkgen/ -messages ./sdk -out ./sdk/typed_gen.go
//	go run ./cmd/sdkgen/ -messages ./modules/health -out ./modules/health/typed_gen.go
package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type msgType struct {
	Name     string // e.g. "ToolCallMsg"
	BaseName string // e.g. "ToolCall"
	RespName string // e.g. "ToolCallResp" (empty if no response)
	IsEvent  bool
}

func main() {
	messagesDir := flag.String("messages", "./sdk", "path to message package")
	outFile := flag.String("out", "./sdk/typed_gen.go", "typed wrappers output path")
	outPackage := flag.String("package", "", "output package name; default is the package found in -messages")
	flag.Parse()

	packageName, types, err := scanMessages(*messagesDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "scan: %v\n", err)
		os.Exit(1)
	}
	if *outPackage != "" {
		packageName = *outPackage
	}

	if err := generate(*outFile, packageName, types); err != nil {
		fmt.Fprintf(os.Stderr, "generate: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("generated typed wrappers → %s (%d types)\n", *outFile, len(types))

	calls := 0
	for _, mt := range types {
		if !mt.IsEvent && mt.RespName != "" {
			calls++
		}
	}
	fmt.Printf("generated sync Call wrappers in %s (%d pairs)\n", *outFile, calls)
}

func scanMessages(dir string) (string, []msgType, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		// Skip generated and test files to avoid stale references and external
		// test packages.
		return fi.Name() != "typed_gen.go" && !strings.HasSuffix(fi.Name(), "_test.go")
	}, 0)
	if err != nil {
		return "", nil, fmt.Errorf("parse %s: %w", dir, err)
	}
	if len(pkgs) != 1 {
		names := make([]string, 0, len(pkgs))
		for name := range pkgs {
			names = append(names, name)
		}
		sort.Strings(names)
		return "", nil, fmt.Errorf("expected one package in %s, found %s", dir, strings.Join(names, ", "))
	}
	var packageName string
	for name := range pkgs {
		packageName = name
	}

	// Collect all type names and which ones have BusTopic()
	allTypes := map[string]bool{}
	hasBusTopic := map[string]bool{}

	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			// Collect type declarations
			for _, decl := range file.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					continue
				}
				for _, spec := range genDecl.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					allTypes[ts.Name.Name] = true
				}
			}

			// Check for BusTopic() method declarations
			for _, decl := range file.Decls {
				funcDecl, ok := decl.(*ast.FuncDecl)
				if !ok || funcDecl.Recv == nil || funcDecl.Name.Name != "BusTopic" {
					continue
				}
				// Get the receiver type name
				for _, field := range funcDecl.Recv.List {
					switch t := field.Type.(type) {
					case *ast.Ident:
						hasBusTopic[t.Name] = true
					case *ast.StarExpr:
						if ident, ok := t.X.(*ast.Ident); ok {
							hasBusTopic[ident.Name] = true
						}
					}
				}
			}
		}
	}

	var result []msgType

	// Find Msg types with BusTopic
	for name := range hasBusTopic {
		if name == "CustomMsg" || name == "CustomEvent" {
			continue // skip dynamic-topic types
		}

		if strings.HasSuffix(name, "Msg") {
			base := strings.TrimSuffix(name, "Msg")
			mt := msgType{
				Name:     name,
				BaseName: base,
			}
			// Check for matching Resp type
			respName := base + "Resp"
			if allTypes[respName] {
				mt.RespName = respName
			}
			result = append(result, mt)
		} else if strings.HasSuffix(name, "Event") {
			base := strings.TrimSuffix(name, "Event")
			result = append(result, msgType{
				Name:     name,
				BaseName: base,
				IsEvent:  true,
			})
		}
	}

	sort.Slice(result, func(i, j int) bool {
		return result[i].BaseName < result[j].BaseName
	})

	return packageName, result, nil
}

func generate(outPath, packageName string, types []msgType) error {
	if err := os.MkdirAll(filepath.Dir(outPath), 0755); err != nil {
		return err
	}
	if packageName == "" {
		return fmt.Errorf("output package name is required")
	}

	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit call/emit/subscribe.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// Low-level publish/reply-topic helpers are intentionally not generated; use
// the generic SDK protocol primitives directly when testing transport behavior.
//
// Regenerate with cmd/sdkgen from this repository.
package %s

`, packageName)

	refs := sdkRefs{
		runtime:        "Runtime",
		callerRuntime:  "CallerRuntime",
		requestCaller:  "RequestCaller",
		callOption:     "CallOption",
		message:        "Message",
		subscribeTo:    "SubscribeTo",
		call:           "Call",
		callWithCaller: "CallWithCaller",
		emit:           "Emit",
	}
	moduleOutput := isModuleOutputPath(outPath)
	moduleCaller := moduleOutput && hasCallPairs(types)
	needsImports := hasGeneratedWrappers(types)
	if needsImports && packageName == "sdk" {
		b.WriteString(`import "context"

`)
	} else if needsImports {
		if moduleCaller {
			b.WriteString(`import (
	"context"

	bkmodule "github.com/brainlet/brainkit/module"
	"github.com/brainlet/brainkit/sdk"
)

`)
		} else {
			b.WriteString(`import (
	"context"

	"github.com/brainlet/brainkit/sdk"
)

`)
		}
		refs = sdkRefs{
			runtime:        "sdk.Runtime",
			callerRuntime:  "sdk.CallerRuntime",
			requestCaller:  "sdk.RequestCaller",
			callOption:     "sdk.CallOption",
			message:        "sdk.Message",
			subscribeTo:    "sdk.SubscribeTo",
			call:           "sdk.Call",
			callWithCaller: "sdk.CallWithCaller",
			emit:           "sdk.Emit",
		}
		if moduleCaller {
			refs.requestCaller = "bkmodule.RequestCaller"
		}
	}

	// Generate command wrappers (Call only). Low-level publish/reply-topic
	// helpers remain available through generic SDK primitives.
	for _, mt := range types {
		if mt.IsEvent || mt.RespName == "" {
			continue
		}

		fmt.Fprintf(&b, "// Call%s issues a synchronous request-response Call for %s.\n", mt.BaseName, mt.Name)
		fmt.Fprintf(&b, "func Call%s(rt %s, ctx context.Context, msg %s, opts ...%s) (%s, error) {\n", mt.BaseName, refs.callerRuntime, mt.Name, refs.callOption, mt.RespName)
		fmt.Fprintf(&b, "\treturn %s[%s, %s](rt, ctx, msg, opts...)\n", refs.call, mt.Name, mt.RespName)
		fmt.Fprintf(&b, "}\n\n")

		fmt.Fprintf(&b, "// Call%sWithCaller issues a synchronous request-response Call through a narrow RequestCaller.\n", mt.BaseName)
		fmt.Fprintf(&b, "func Call%sWithCaller(caller %s, ctx context.Context, msg %s, opts ...%s) (%s, error) {\n", mt.BaseName, refs.requestCaller, mt.Name, refs.callOption, mt.RespName)
		fmt.Fprintf(&b, "\treturn %s[%s, %s](caller, ctx, msg, opts...)\n", refs.callWithCaller, mt.Name, mt.RespName)
		fmt.Fprintf(&b, "}\n\n")
	}

	// Generate Event wrappers (Emit + Subscribe)
	for _, mt := range types {
		if !mt.IsEvent {
			continue
		}

		// Emit wrapper
		fmt.Fprintf(&b, "// Emit%s fires a %s event (no response expected).\n", mt.BaseName, mt.Name)
		fmt.Fprintf(&b, "func Emit%s(rt %s, ctx context.Context, msg %s) error {\n", mt.BaseName, refs.runtime, mt.Name)
		fmt.Fprintf(&b, "\treturn %s(rt, ctx, msg)\n", refs.emit)
		fmt.Fprintf(&b, "}\n\n")

		// Subscribe wrapper
		fmt.Fprintf(&b, "// Subscribe%s listens for %s events.\n", mt.BaseName, mt.Name)
		fmt.Fprintf(&b, "func Subscribe%s(rt %s, ctx context.Context, topic string, handler func(%s, %s)) (func(), error) {\n", mt.BaseName, refs.runtime, mt.Name, refs.message)
		fmt.Fprintf(&b, "\treturn %s[%s](rt, ctx, topic, handler)\n", refs.subscribeTo, mt.Name)
		fmt.Fprintf(&b, "}\n\n")
	}

	return os.WriteFile(outPath, []byte(b.String()), 0644)
}

type sdkRefs struct {
	runtime        string
	callerRuntime  string
	requestCaller  string
	callOption     string
	message        string
	subscribeTo    string
	call           string
	callWithCaller string
	emit           string
}

func isModuleOutputPath(outPath string) bool {
	path := filepath.ToSlash(filepath.Clean(outPath))
	for _, part := range strings.Split(path, "/") {
		if part == "modules" {
			return true
		}
	}
	return false
}

func hasGeneratedWrappers(types []msgType) bool {
	for _, mt := range types {
		if mt.IsEvent || mt.RespName != "" {
			return true
		}
	}
	return false
}

func hasCallPairs(types []msgType) bool {
	for _, mt := range types {
		if !mt.IsEvent && mt.RespName != "" {
			return true
		}
	}
	return false
}
