// sdkgen generates typed wrappers from sdk message types.
//
// Two output files:
//
//  1. `-out` (default ./sdk/typed_gen.go) — async wrappers in
//     package sdk:
//       - Publish{Name}(rt, ctx, msg, opts...) (PublishResult, error)
//       - Subscribe{Name}Resp(rt, ctx, topic, handler) (func(), error)
//       - Emit{Name}(rt, ctx, msg) error  — events
//       - Subscribe{Name}(rt, ctx, topic, handler) (func(), error)
//
//  2. `-call-out` (default ./call_gen.go) — sync Call wrappers in
//     package brainkit:
//       - Call{Name}(k, ctx, msg, opts...) (Resp, error)
//
// Each sync wrapper is a thin delegate to brainkit.Call[Msg, Resp]
// that removes the type-parameter guessing. Only emitted for Msg
// types with a matching Resp.
//
// Usage:
//
//	go run ./cmd/sdkgen/ -messages ./sdk -out ./sdk/typed_gen.go -call-out ./call_gen.go
package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type msgType struct {
	Name     string // e.g. "ToolCallMsg"
	BaseName string // e.g. "ToolCall"
	RespName string // e.g. "ToolCallResp" (empty if no response)
	IsEvent  bool
}

func main() {
	messagesDir := flag.String("messages", "./sdk", "path to sdk package")
	outFile := flag.String("out", "./sdk/typed_gen.go", "async wrappers output path (package sdk)")
	callOutFile := flag.String("call-out", "./call_gen.go", "sync Call wrappers output path (package brainkit); empty to skip")
	flag.Parse()

	types, err := scanMessages(*messagesDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "scan: %v\n", err)
		os.Exit(1)
	}

	if err := generate(*outFile, types); err != nil {
		fmt.Fprintf(os.Stderr, "generate: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("generated async wrappers → %s (%d types)\n", *outFile, len(types))

	if *callOutFile != "" {
		calls, err := generateCallWrappers(*callOutFile, types)
		if err != nil {
			fmt.Fprintf(os.Stderr, "generate call: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("generated sync Call wrappers → %s (%d pairs)\n", *callOutFile, calls)
	}
}

func scanMessages(dir string) ([]msgType, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		// Skip the generated file itself to avoid stale references
		return fi.Name() != "typed_gen.go"
	}, 0)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", dir, err)
	}

	// Collect all type names and which ones have BusTopic()
	allTypes := map[string]bool{}
	hasBusTopic := map[string]bool{}

	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			// Collect type declarations
			for _, decl := range file.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					continue
				}
				for _, spec := range genDecl.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					allTypes[ts.Name.Name] = true
				}
			}

			// Check for BusTopic() method declarations
			for _, decl := range file.Decls {
				funcDecl, ok := decl.(*ast.FuncDecl)
				if !ok || funcDecl.Recv == nil || funcDecl.Name.Name != "BusTopic" {
					continue
				}
				// Get the receiver type name
				for _, field := range funcDecl.Recv.List {
					switch t := field.Type.(type) {
					case *ast.Ident:
						hasBusTopic[t.Name] = true
					case *ast.StarExpr:
						if ident, ok := t.X.(*ast.Ident); ok {
							hasBusTopic[ident.Name] = true
						}
					}
				}
			}
		}
	}

	var result []msgType

	// Find Msg types with BusTopic
	for name := range hasBusTopic {
		if name == "CustomMsg" || name == "CustomEvent" {
			continue // skip dynamic-topic types
		}

		if strings.HasSuffix(name, "Msg") {
			base := strings.TrimSuffix(name, "Msg")
			mt := msgType{
				Name:     name,
				BaseName: base,
			}
			// Check for matching Resp type
			respName := base + "Resp"
			if allTypes[respName] {
				mt.RespName = respName
			}
			result = append(result, mt)
		} else if strings.HasSuffix(name, "Event") {
			base := strings.TrimSuffix(name, "Event")
			result = append(result, msgType{
				Name:     name,
				BaseName: base,
				IsEvent:  true,
			})
		}
	}

	sort.Slice(result, func(i, j int) bool {
		return result[i].BaseName < result[j].BaseName
	})

	return result, nil
}

func generate(outPath string, types []msgType) error {
	if err := os.MkdirAll(filepath.Dir(outPath), 0755); err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString(`// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for sdk.Publish/SubscribeTo/Emit.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// The underlying async pub/sub pattern is unchanged — callers still manage
// channels, select, and timeouts. These wrappers just add type safety.
//
// Regenerate: go run ./cmd/sdkgen/ -messages ./sdk -out ./sdk/typed_gen.go
package sdk

import "context"

`)

	// Generate Msg wrappers (Publish + Subscribe)
	for _, mt := range types {
		if mt.IsEvent {
			continue
		}

		// Publish wrapper
		fmt.Fprintf(&b, "// Publish%s publishes a %s and returns routing info for the response.\n", mt.BaseName, mt.Name)
		fmt.Fprintf(&b, "func Publish%s(rt Runtime, ctx context.Context, msg %s, opts ...PublishOption) (PublishResult, error) {\n", mt.BaseName, mt.Name)
		fmt.Fprintf(&b, "\treturn Publish(rt, ctx, msg, opts...)\n")
		fmt.Fprintf(&b, "}\n\n")

		// Subscribe wrapper (only if Resp type exists)
		if mt.RespName != "" {
			fmt.Fprintf(&b, "// Subscribe%sResp subscribes to the response topic for a %s command.\n", mt.BaseName, mt.Name)
			fmt.Fprintf(&b, "func Subscribe%sResp(rt Runtime, ctx context.Context, topic string, handler func(%s, Message)) (func(), error) {\n", mt.BaseName, mt.RespName)
			fmt.Fprintf(&b, "\treturn SubscribeTo[%s](rt, ctx, topic, handler)\n", mt.RespName)
			fmt.Fprintf(&b, "}\n\n")
		}
	}

	// Generate Event wrappers (Emit + Subscribe)
	for _, mt := range types {
		if !mt.IsEvent {
			continue
		}

		// Emit wrapper
		fmt.Fprintf(&b, "// Emit%s fires a %s event (no response expected).\n", mt.BaseName, mt.Name)
		fmt.Fprintf(&b, "func Emit%s(rt Runtime, ctx context.Context, msg %s) error {\n", mt.BaseName, mt.Name)
		fmt.Fprintf(&b, "\treturn Emit(rt, ctx, msg)\n")
		fmt.Fprintf(&b, "}\n\n")

		// Subscribe wrapper
		fmt.Fprintf(&b, "// Subscribe%s listens for %s events.\n", mt.BaseName, mt.Name)
		fmt.Fprintf(&b, "func Subscribe%s(rt Runtime, ctx context.Context, topic string, handler func(%s, Message)) (func(), error) {\n", mt.BaseName, mt.Name)
		fmt.Fprintf(&b, "\treturn SubscribeTo[%s](rt, ctx, topic, handler)\n", mt.Name)
		fmt.Fprintf(&b, "}\n\n")
	}

	return os.WriteFile(outPath, []byte(b.String()), 0644)
}

// generateCallWrappers emits synchronous brainkit.Call wrappers at
// the repo root. One wrapper per Msg→Resp pair; events are skipped.
// Returns the number of wrappers written.
func generateCallWrappers(outPath string, types []msgType) (int, error) {
	if err := os.MkdirAll(filepath.Dir(outPath), 0755); err != nil {
		return 0, err
	}

	var b strings.Builder
	b.WriteString(`// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Synchronous Call wrappers — one per sdk.Msg/sdk.Resp pair — that
// remove the type-parameter guessing from brainkit.Call.
//
// Instead of:
//
//	resp, err := brainkit.Call[sdk.ToolCallMsg, sdk.ToolCallResp](k, ctx, msg)
//
// write:
//
//	resp, err := brainkit.CallToolCall(k, ctx, msg)
//
// The underlying generic stays exported for advanced uses. These
// wrappers just saturate the type parameters mechanically.
//
// Regenerate: go run ./cmd/sdkgen/ -messages ./sdk -out ./sdk/typed_gen.go -call-out ./call_gen.go
package brainkit

import (
	"context"

	"github.com/brainlet/brainkit/sdk"
)

`)

	count := 0
	for _, mt := range types {
		if mt.IsEvent || mt.RespName == "" {
			continue
		}
		fmt.Fprintf(&b, "// Call%s issues a synchronous request→response Call for %s and\n", mt.BaseName, mt.Name)
		fmt.Fprintf(&b, "// returns the decoded %s. Equivalent to\n", mt.RespName)
		fmt.Fprintf(&b, "// Call[sdk.%s, sdk.%s] with the types saturated.\n", mt.Name, mt.RespName)
		fmt.Fprintf(&b, "func Call%s(k *Kit, ctx context.Context, msg sdk.%s, opts ...CallOption) (sdk.%s, error) {\n", mt.BaseName, mt.Name, mt.RespName)
		fmt.Fprintf(&b, "\treturn Call[sdk.%s, sdk.%s](k, ctx, msg, opts...)\n", mt.Name, mt.RespName)
		fmt.Fprintf(&b, "}\n\n")
		count++
	}

	return count, os.WriteFile(outPath, []byte(b.String()), 0644)
}
