// Ported from: packages/ai/src/error/no-object-generated-error.ts
package aierror

const noObjectGeneratedErrorName = "AI_NoObjectGeneratedError"
const noObjectGeneratedErrorMarker = "vercel.ai.error." + noObjectGeneratedErrorName

// NoObjectGeneratedError is returned when no object could be generated.
// This can have several causes:
//   - The model failed to generate a response.
//   - The model generated a response that could not be parsed.
//   - The model generated a response that could not be validated against the schema.
type NoObjectGeneratedError struct {
	AISDKError

	// Text is the text that was generated by the model. This can be the raw text
	// or the tool call text, depending on the model.
	Text *string

	// Response is the response metadata.
	Response *LanguageModelResponseMetadata

	// Usage is the usage of the model.
	Usage *LanguageModelUsage

	// FinishReason is the reason why the model finished generating a response.
	FinishReason *FinishReason
}

// NoObjectGeneratedErrorOptions are the options for creating a NoObjectGeneratedError.
type NoObjectGeneratedErrorOptions struct {
	// Message overrides the default error message. Optional.
	Message string
	// Cause is the underlying error. Optional.
	Cause error
	// Text is the text generated by the model. Optional.
	Text *string
	// Response is the response metadata.
	Response *LanguageModelResponseMetadata
	// Usage is the usage of the model.
	Usage *LanguageModelUsage
	// FinishReason is the reason why the model finished generating.
	FinishReason *FinishReason
}

// NewNoObjectGeneratedError creates a new NoObjectGeneratedError.
func NewNoObjectGeneratedError(opts NoObjectGeneratedErrorOptions) *NoObjectGeneratedError {
	message := opts.Message
	if message == "" {
		message = "No object generated."
	}

	return &NoObjectGeneratedError{
		AISDKError: AISDKError{
			Name:    noObjectGeneratedErrorName,
			Message: message,
			Cause:   opts.Cause,
		},
		Text:         opts.Text,
		Response:     opts.Response,
		Usage:        opts.Usage,
		FinishReason: opts.FinishReason,
	}
}

// IsNoObjectGeneratedError checks whether the given error is a NoObjectGeneratedError.
func IsNoObjectGeneratedError(err error) bool {
	_, ok := err.(*NoObjectGeneratedError)
	return ok
}
