// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit call/emit/subscribe.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// Low-level publish/reply-topic helpers are intentionally not generated; use
// the generic SDK protocol primitives directly when testing transport behavior.
//
// Regenerate with cmd/sdkgen from this repository.
package packagemsg

import (
	"context"

	bkmodule "github.com/brainlet/brainkit/module"
	"github.com/brainlet/brainkit/sdk"
)

// CallPackageDeploy issues a synchronous request-response Call for PackageDeployMsg.
func CallPackageDeploy(rt sdk.CallerRuntime, ctx context.Context, msg PackageDeployMsg, opts ...sdk.CallOption) (PackageDeployResp, error) {
	return sdk.Call[PackageDeployMsg, PackageDeployResp](rt, ctx, msg, opts...)
}

// CallPackageDeployWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallPackageDeployWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg PackageDeployMsg, opts ...sdk.CallOption) (PackageDeployResp, error) {
	return sdk.CallWithCaller[PackageDeployMsg, PackageDeployResp](caller, ctx, msg, opts...)
}

// CallPackageDeployInfo issues a synchronous request-response Call for PackageDeployInfoMsg.
func CallPackageDeployInfo(rt sdk.CallerRuntime, ctx context.Context, msg PackageDeployInfoMsg, opts ...sdk.CallOption) (PackageDeployInfoResp, error) {
	return sdk.Call[PackageDeployInfoMsg, PackageDeployInfoResp](rt, ctx, msg, opts...)
}

// CallPackageDeployInfoWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallPackageDeployInfoWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg PackageDeployInfoMsg, opts ...sdk.CallOption) (PackageDeployInfoResp, error) {
	return sdk.CallWithCaller[PackageDeployInfoMsg, PackageDeployInfoResp](caller, ctx, msg, opts...)
}

// CallPackageListDeployed issues a synchronous request-response Call for PackageListDeployedMsg.
func CallPackageListDeployed(rt sdk.CallerRuntime, ctx context.Context, msg PackageListDeployedMsg, opts ...sdk.CallOption) (PackageListDeployedResp, error) {
	return sdk.Call[PackageListDeployedMsg, PackageListDeployedResp](rt, ctx, msg, opts...)
}

// CallPackageListDeployedWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallPackageListDeployedWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg PackageListDeployedMsg, opts ...sdk.CallOption) (PackageListDeployedResp, error) {
	return sdk.CallWithCaller[PackageListDeployedMsg, PackageListDeployedResp](caller, ctx, msg, opts...)
}

// CallPackageTeardown issues a synchronous request-response Call for PackageTeardownMsg.
func CallPackageTeardown(rt sdk.CallerRuntime, ctx context.Context, msg PackageTeardownMsg, opts ...sdk.CallOption) (PackageTeardownResp, error) {
	return sdk.Call[PackageTeardownMsg, PackageTeardownResp](rt, ctx, msg, opts...)
}

// CallPackageTeardownWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallPackageTeardownWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg PackageTeardownMsg, opts ...sdk.CallOption) (PackageTeardownResp, error) {
	return sdk.CallWithCaller[PackageTeardownMsg, PackageTeardownResp](caller, ctx, msg, opts...)
}

