// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit publish/subscribe/call/emit.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// The underlying generic publish/call patterns are unchanged. These wrappers
// just add type safety.
//
// Regenerate with cmd/sdkgen from this repository.
package packagemsg

import (
	"context"

	"github.com/brainlet/brainkit/sdk"
)

// PublishPackageDeploy publishes a PackageDeployMsg and returns routing info for the response.
func PublishPackageDeploy(rt sdk.Runtime, ctx context.Context, msg PackageDeployMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribePackageDeployResp subscribes to the response topic for a PackageDeployMsg command.
func SubscribePackageDeployResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(PackageDeployResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[PackageDeployResp](rt, ctx, topic, handler)
}

// CallPackageDeploy issues a synchronous request-response Call for PackageDeployMsg.
func CallPackageDeploy(rt sdk.CallerRuntime, ctx context.Context, msg PackageDeployMsg, opts ...sdk.CallOption) (PackageDeployResp, error) {
	return sdk.Call[PackageDeployMsg, PackageDeployResp](rt, ctx, msg, opts...)
}

// PublishPackageDeployInfo publishes a PackageDeployInfoMsg and returns routing info for the response.
func PublishPackageDeployInfo(rt sdk.Runtime, ctx context.Context, msg PackageDeployInfoMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribePackageDeployInfoResp subscribes to the response topic for a PackageDeployInfoMsg command.
func SubscribePackageDeployInfoResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(PackageDeployInfoResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[PackageDeployInfoResp](rt, ctx, topic, handler)
}

// CallPackageDeployInfo issues a synchronous request-response Call for PackageDeployInfoMsg.
func CallPackageDeployInfo(rt sdk.CallerRuntime, ctx context.Context, msg PackageDeployInfoMsg, opts ...sdk.CallOption) (PackageDeployInfoResp, error) {
	return sdk.Call[PackageDeployInfoMsg, PackageDeployInfoResp](rt, ctx, msg, opts...)
}

// PublishPackageListDeployed publishes a PackageListDeployedMsg and returns routing info for the response.
func PublishPackageListDeployed(rt sdk.Runtime, ctx context.Context, msg PackageListDeployedMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribePackageListDeployedResp subscribes to the response topic for a PackageListDeployedMsg command.
func SubscribePackageListDeployedResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(PackageListDeployedResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[PackageListDeployedResp](rt, ctx, topic, handler)
}

// CallPackageListDeployed issues a synchronous request-response Call for PackageListDeployedMsg.
func CallPackageListDeployed(rt sdk.CallerRuntime, ctx context.Context, msg PackageListDeployedMsg, opts ...sdk.CallOption) (PackageListDeployedResp, error) {
	return sdk.Call[PackageListDeployedMsg, PackageListDeployedResp](rt, ctx, msg, opts...)
}

// PublishPackageTeardown publishes a PackageTeardownMsg and returns routing info for the response.
func PublishPackageTeardown(rt sdk.Runtime, ctx context.Context, msg PackageTeardownMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribePackageTeardownResp subscribes to the response topic for a PackageTeardownMsg command.
func SubscribePackageTeardownResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(PackageTeardownResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[PackageTeardownResp](rt, ctx, topic, handler)
}

// CallPackageTeardown issues a synchronous request-response Call for PackageTeardownMsg.
func CallPackageTeardown(rt sdk.CallerRuntime, ctx context.Context, msg PackageTeardownMsg, opts ...sdk.CallOption) (PackageTeardownResp, error) {
	return sdk.Call[PackageTeardownMsg, PackageTeardownResp](rt, ctx, msg, opts...)
}

