// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit publish/subscribe/call/emit.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// The underlying generic publish/call patterns are unchanged. These wrappers
// just add type safety.
//
// Regenerate with cmd/sdkgen from this repository.
package schedulemsg

import (
	"context"

	"github.com/brainlet/brainkit/sdk"
)

// PublishScheduleCancel publishes a ScheduleCancelMsg and returns routing info for the response.
func PublishScheduleCancel(rt sdk.Runtime, ctx context.Context, msg ScheduleCancelMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeScheduleCancelResp subscribes to the response topic for a ScheduleCancelMsg command.
func SubscribeScheduleCancelResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(ScheduleCancelResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[ScheduleCancelResp](rt, ctx, topic, handler)
}

// CallScheduleCancel issues a synchronous request-response Call for ScheduleCancelMsg.
func CallScheduleCancel(rt sdk.CallerRuntime, ctx context.Context, msg ScheduleCancelMsg, opts ...sdk.CallOption) (ScheduleCancelResp, error) {
	return sdk.Call[ScheduleCancelMsg, ScheduleCancelResp](rt, ctx, msg, opts...)
}

// PublishScheduleCreate publishes a ScheduleCreateMsg and returns routing info for the response.
func PublishScheduleCreate(rt sdk.Runtime, ctx context.Context, msg ScheduleCreateMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeScheduleCreateResp subscribes to the response topic for a ScheduleCreateMsg command.
func SubscribeScheduleCreateResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(ScheduleCreateResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[ScheduleCreateResp](rt, ctx, topic, handler)
}

// CallScheduleCreate issues a synchronous request-response Call for ScheduleCreateMsg.
func CallScheduleCreate(rt sdk.CallerRuntime, ctx context.Context, msg ScheduleCreateMsg, opts ...sdk.CallOption) (ScheduleCreateResp, error) {
	return sdk.Call[ScheduleCreateMsg, ScheduleCreateResp](rt, ctx, msg, opts...)
}

// PublishScheduleList publishes a ScheduleListMsg and returns routing info for the response.
func PublishScheduleList(rt sdk.Runtime, ctx context.Context, msg ScheduleListMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeScheduleListResp subscribes to the response topic for a ScheduleListMsg command.
func SubscribeScheduleListResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(ScheduleListResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[ScheduleListResp](rt, ctx, topic, handler)
}

// CallScheduleList issues a synchronous request-response Call for ScheduleListMsg.
func CallScheduleList(rt sdk.CallerRuntime, ctx context.Context, msg ScheduleListMsg, opts ...sdk.CallOption) (ScheduleListResp, error) {
	return sdk.Call[ScheduleListMsg, ScheduleListResp](rt, ctx, msg, opts...)
}

