// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit call/emit/subscribe.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// Low-level publish/reply-topic helpers are intentionally not generated; use
// the generic SDK protocol primitives directly when testing transport behavior.
//
// Regenerate with cmd/sdkgen from this repository.
package schedulemsg

import (
	"context"

	bkmodule "github.com/brainlet/brainkit/module"
	"github.com/brainlet/brainkit/sdk"
)

// CallScheduleCancel issues a synchronous request-response Call for ScheduleCancelMsg.
func CallScheduleCancel(rt sdk.CallerRuntime, ctx context.Context, msg ScheduleCancelMsg, opts ...sdk.CallOption) (ScheduleCancelResp, error) {
	return sdk.Call[ScheduleCancelMsg, ScheduleCancelResp](rt, ctx, msg, opts...)
}

// CallScheduleCancelWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallScheduleCancelWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg ScheduleCancelMsg, opts ...sdk.CallOption) (ScheduleCancelResp, error) {
	return sdk.CallWithCaller[ScheduleCancelMsg, ScheduleCancelResp](caller, ctx, msg, opts...)
}

// CallScheduleCreate issues a synchronous request-response Call for ScheduleCreateMsg.
func CallScheduleCreate(rt sdk.CallerRuntime, ctx context.Context, msg ScheduleCreateMsg, opts ...sdk.CallOption) (ScheduleCreateResp, error) {
	return sdk.Call[ScheduleCreateMsg, ScheduleCreateResp](rt, ctx, msg, opts...)
}

// CallScheduleCreateWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallScheduleCreateWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg ScheduleCreateMsg, opts ...sdk.CallOption) (ScheduleCreateResp, error) {
	return sdk.CallWithCaller[ScheduleCreateMsg, ScheduleCreateResp](caller, ctx, msg, opts...)
}

// CallScheduleList issues a synchronous request-response Call for ScheduleListMsg.
func CallScheduleList(rt sdk.CallerRuntime, ctx context.Context, msg ScheduleListMsg, opts ...sdk.CallOption) (ScheduleListResp, error) {
	return sdk.Call[ScheduleListMsg, ScheduleListResp](rt, ctx, msg, opts...)
}

// CallScheduleListWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallScheduleListWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg ScheduleListMsg, opts ...sdk.CallOption) (ScheduleListResp, error) {
	return sdk.CallWithCaller[ScheduleListMsg, ScheduleListResp](caller, ctx, msg, opts...)
}

