// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit publish/subscribe/call/emit.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// The underlying generic publish/call patterns are unchanged. These wrappers
// just add type safety.
//
// Regenerate with cmd/sdkgen from this repository.
package systemmsg

import (
	"context"

	"github.com/brainlet/brainkit/sdk"
)

// EmitHandlerExhausted fires a HandlerExhaustedEvent event (no response expected).
func EmitHandlerExhausted(rt sdk.Runtime, ctx context.Context, msg HandlerExhaustedEvent) error {
	return sdk.Emit(rt, ctx, msg)
}

// SubscribeHandlerExhausted listens for HandlerExhaustedEvent events.
func SubscribeHandlerExhausted(rt sdk.Runtime, ctx context.Context, topic string, handler func(HandlerExhaustedEvent, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[HandlerExhaustedEvent](rt, ctx, topic, handler)
}

// EmitHandlerFailed fires a HandlerFailedEvent event (no response expected).
func EmitHandlerFailed(rt sdk.Runtime, ctx context.Context, msg HandlerFailedEvent) error {
	return sdk.Emit(rt, ctx, msg)
}

// SubscribeHandlerFailed listens for HandlerFailedEvent events.
func SubscribeHandlerFailed(rt sdk.Runtime, ctx context.Context, topic string, handler func(HandlerFailedEvent, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[HandlerFailedEvent](rt, ctx, topic, handler)
}

// EmitKitDeployed fires a KitDeployedEvent event (no response expected).
func EmitKitDeployed(rt sdk.Runtime, ctx context.Context, msg KitDeployedEvent) error {
	return sdk.Emit(rt, ctx, msg)
}

// SubscribeKitDeployed listens for KitDeployedEvent events.
func SubscribeKitDeployed(rt sdk.Runtime, ctx context.Context, topic string, handler func(KitDeployedEvent, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[KitDeployedEvent](rt, ctx, topic, handler)
}

// EmitKitTeardowned fires a KitTeardownedEvent event (no response expected).
func EmitKitTeardowned(rt sdk.Runtime, ctx context.Context, msg KitTeardownedEvent) error {
	return sdk.Emit(rt, ctx, msg)
}

// SubscribeKitTeardowned listens for KitTeardownedEvent events.
func SubscribeKitTeardowned(rt sdk.Runtime, ctx context.Context, topic string, handler func(KitTeardownedEvent, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[KitTeardownedEvent](rt, ctx, topic, handler)
}

