// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit publish/subscribe/call/emit.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// The underlying generic publish/call patterns are unchanged. These wrappers
// just add type safety.
//
// Regenerate with cmd/sdkgen from this repository.
package testingmsg

import (
	"context"

	"github.com/brainlet/brainkit/sdk"
)

// PublishTestRun publishes a TestRunMsg and returns routing info for the response.
func PublishTestRun(rt sdk.Runtime, ctx context.Context, msg TestRunMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeTestRunResp subscribes to the response topic for a TestRunMsg command.
func SubscribeTestRunResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(TestRunResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[TestRunResp](rt, ctx, topic, handler)
}

// CallTestRun issues a synchronous request-response Call for TestRunMsg.
func CallTestRun(rt sdk.CallerRuntime, ctx context.Context, msg TestRunMsg, opts ...sdk.CallOption) (TestRunResp, error) {
	return sdk.Call[TestRunMsg, TestRunResp](rt, ctx, msg, opts...)
}

