// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit call/emit/subscribe.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// Low-level publish/reply-topic helpers are intentionally not generated; use
// the generic SDK protocol primitives directly when testing transport behavior.
//
// Regenerate with cmd/sdkgen from this repository.
package testingmsg

import (
	"context"

	bkmodule "github.com/brainlet/brainkit/module"
	"github.com/brainlet/brainkit/sdk"
)

// CallTestRun issues a synchronous request-response Call for TestRunMsg.
func CallTestRun(rt sdk.CallerRuntime, ctx context.Context, msg TestRunMsg, opts ...sdk.CallOption) (TestRunResp, error) {
	return sdk.Call[TestRunMsg, TestRunResp](rt, ctx, msg, opts...)
}

// CallTestRunWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallTestRunWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg TestRunMsg, opts ...sdk.CallOption) (TestRunResp, error) {
	return sdk.CallWithCaller[TestRunMsg, TestRunResp](caller, ctx, msg, opts...)
}

