// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit call/emit/subscribe.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// Low-level publish/reply-topic helpers are intentionally not generated; use
// the generic SDK protocol primitives directly when testing transport behavior.
//
// Regenerate with cmd/sdkgen from this repository.
package secretmsg

import (
	"context"

	bkmodule "github.com/brainlet/brainkit/module"
	"github.com/brainlet/brainkit/sdk"
)

// CallSecretsDelete issues a synchronous request-response Call for SecretsDeleteMsg.
func CallSecretsDelete(rt sdk.CallerRuntime, ctx context.Context, msg SecretsDeleteMsg, opts ...sdk.CallOption) (SecretsDeleteResp, error) {
	return sdk.Call[SecretsDeleteMsg, SecretsDeleteResp](rt, ctx, msg, opts...)
}

// CallSecretsDeleteWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallSecretsDeleteWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg SecretsDeleteMsg, opts ...sdk.CallOption) (SecretsDeleteResp, error) {
	return sdk.CallWithCaller[SecretsDeleteMsg, SecretsDeleteResp](caller, ctx, msg, opts...)
}

// CallSecretsGet issues a synchronous request-response Call for SecretsGetMsg.
func CallSecretsGet(rt sdk.CallerRuntime, ctx context.Context, msg SecretsGetMsg, opts ...sdk.CallOption) (SecretsGetResp, error) {
	return sdk.Call[SecretsGetMsg, SecretsGetResp](rt, ctx, msg, opts...)
}

// CallSecretsGetWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallSecretsGetWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg SecretsGetMsg, opts ...sdk.CallOption) (SecretsGetResp, error) {
	return sdk.CallWithCaller[SecretsGetMsg, SecretsGetResp](caller, ctx, msg, opts...)
}

// CallSecretsList issues a synchronous request-response Call for SecretsListMsg.
func CallSecretsList(rt sdk.CallerRuntime, ctx context.Context, msg SecretsListMsg, opts ...sdk.CallOption) (SecretsListResp, error) {
	return sdk.Call[SecretsListMsg, SecretsListResp](rt, ctx, msg, opts...)
}

// CallSecretsListWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallSecretsListWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg SecretsListMsg, opts ...sdk.CallOption) (SecretsListResp, error) {
	return sdk.CallWithCaller[SecretsListMsg, SecretsListResp](caller, ctx, msg, opts...)
}

// CallSecretsRotate issues a synchronous request-response Call for SecretsRotateMsg.
func CallSecretsRotate(rt sdk.CallerRuntime, ctx context.Context, msg SecretsRotateMsg, opts ...sdk.CallOption) (SecretsRotateResp, error) {
	return sdk.Call[SecretsRotateMsg, SecretsRotateResp](rt, ctx, msg, opts...)
}

// CallSecretsRotateWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallSecretsRotateWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg SecretsRotateMsg, opts ...sdk.CallOption) (SecretsRotateResp, error) {
	return sdk.CallWithCaller[SecretsRotateMsg, SecretsRotateResp](caller, ctx, msg, opts...)
}

// CallSecretsSet issues a synchronous request-response Call for SecretsSetMsg.
func CallSecretsSet(rt sdk.CallerRuntime, ctx context.Context, msg SecretsSetMsg, opts ...sdk.CallOption) (SecretsSetResp, error) {
	return sdk.Call[SecretsSetMsg, SecretsSetResp](rt, ctx, msg, opts...)
}

// CallSecretsSetWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallSecretsSetWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg SecretsSetMsg, opts ...sdk.CallOption) (SecretsSetResp, error) {
	return sdk.CallWithCaller[SecretsSetMsg, SecretsSetResp](caller, ctx, msg, opts...)
}

// EmitSecretsAccessed fires a SecretsAccessedEvent event (no response expected).
func EmitSecretsAccessed(rt sdk.Runtime, ctx context.Context, msg SecretsAccessedEvent) error {
	return sdk.Emit(rt, ctx, msg)
}

// SubscribeSecretsAccessed listens for SecretsAccessedEvent events.
func SubscribeSecretsAccessed(rt sdk.Runtime, ctx context.Context, topic string, handler func(SecretsAccessedEvent, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[SecretsAccessedEvent](rt, ctx, topic, handler)
}

// EmitSecretsDeleted fires a SecretsDeletedEvent event (no response expected).
func EmitSecretsDeleted(rt sdk.Runtime, ctx context.Context, msg SecretsDeletedEvent) error {
	return sdk.Emit(rt, ctx, msg)
}

// SubscribeSecretsDeleted listens for SecretsDeletedEvent events.
func SubscribeSecretsDeleted(rt sdk.Runtime, ctx context.Context, topic string, handler func(SecretsDeletedEvent, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[SecretsDeletedEvent](rt, ctx, topic, handler)
}

// EmitSecretsRotated fires a SecretsRotatedEvent event (no response expected).
func EmitSecretsRotated(rt sdk.Runtime, ctx context.Context, msg SecretsRotatedEvent) error {
	return sdk.Emit(rt, ctx, msg)
}

// SubscribeSecretsRotated listens for SecretsRotatedEvent events.
func SubscribeSecretsRotated(rt sdk.Runtime, ctx context.Context, topic string, handler func(SecretsRotatedEvent, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[SecretsRotatedEvent](rt, ctx, topic, handler)
}

// EmitSecretsStored fires a SecretsStoredEvent event (no response expected).
func EmitSecretsStored(rt sdk.Runtime, ctx context.Context, msg SecretsStoredEvent) error {
	return sdk.Emit(rt, ctx, msg)
}

// SubscribeSecretsStored listens for SecretsStoredEvent events.
func SubscribeSecretsStored(rt sdk.Runtime, ctx context.Context, topic string, handler func(SecretsStoredEvent, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[SecretsStoredEvent](rt, ctx, topic, handler)
}

