// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit publish/subscribe/call/emit.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// The underlying generic publish/call patterns are unchanged. These wrappers
// just add type safety.
//
// Regenerate with cmd/sdkgen from this repository.
package secretmsg

import (
	"context"

	"github.com/brainlet/brainkit/sdk"
)

// PublishSecretsDelete publishes a SecretsDeleteMsg and returns routing info for the response.
func PublishSecretsDelete(rt sdk.Runtime, ctx context.Context, msg SecretsDeleteMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeSecretsDeleteResp subscribes to the response topic for a SecretsDeleteMsg command.
func SubscribeSecretsDeleteResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(SecretsDeleteResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[SecretsDeleteResp](rt, ctx, topic, handler)
}

// CallSecretsDelete issues a synchronous request-response Call for SecretsDeleteMsg.
func CallSecretsDelete(rt sdk.CallerRuntime, ctx context.Context, msg SecretsDeleteMsg, opts ...sdk.CallOption) (SecretsDeleteResp, error) {
	return sdk.Call[SecretsDeleteMsg, SecretsDeleteResp](rt, ctx, msg, opts...)
}

// PublishSecretsGet publishes a SecretsGetMsg and returns routing info for the response.
func PublishSecretsGet(rt sdk.Runtime, ctx context.Context, msg SecretsGetMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeSecretsGetResp subscribes to the response topic for a SecretsGetMsg command.
func SubscribeSecretsGetResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(SecretsGetResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[SecretsGetResp](rt, ctx, topic, handler)
}

// CallSecretsGet issues a synchronous request-response Call for SecretsGetMsg.
func CallSecretsGet(rt sdk.CallerRuntime, ctx context.Context, msg SecretsGetMsg, opts ...sdk.CallOption) (SecretsGetResp, error) {
	return sdk.Call[SecretsGetMsg, SecretsGetResp](rt, ctx, msg, opts...)
}

// PublishSecretsList publishes a SecretsListMsg and returns routing info for the response.
func PublishSecretsList(rt sdk.Runtime, ctx context.Context, msg SecretsListMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeSecretsListResp subscribes to the response topic for a SecretsListMsg command.
func SubscribeSecretsListResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(SecretsListResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[SecretsListResp](rt, ctx, topic, handler)
}

// CallSecretsList issues a synchronous request-response Call for SecretsListMsg.
func CallSecretsList(rt sdk.CallerRuntime, ctx context.Context, msg SecretsListMsg, opts ...sdk.CallOption) (SecretsListResp, error) {
	return sdk.Call[SecretsListMsg, SecretsListResp](rt, ctx, msg, opts...)
}

// PublishSecretsRotate publishes a SecretsRotateMsg and returns routing info for the response.
func PublishSecretsRotate(rt sdk.Runtime, ctx context.Context, msg SecretsRotateMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeSecretsRotateResp subscribes to the response topic for a SecretsRotateMsg command.
func SubscribeSecretsRotateResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(SecretsRotateResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[SecretsRotateResp](rt, ctx, topic, handler)
}

// CallSecretsRotate issues a synchronous request-response Call for SecretsRotateMsg.
func CallSecretsRotate(rt sdk.CallerRuntime, ctx context.Context, msg SecretsRotateMsg, opts ...sdk.CallOption) (SecretsRotateResp, error) {
	return sdk.Call[SecretsRotateMsg, SecretsRotateResp](rt, ctx, msg, opts...)
}

// PublishSecretsSet publishes a SecretsSetMsg and returns routing info for the response.
func PublishSecretsSet(rt sdk.Runtime, ctx context.Context, msg SecretsSetMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeSecretsSetResp subscribes to the response topic for a SecretsSetMsg command.
func SubscribeSecretsSetResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(SecretsSetResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[SecretsSetResp](rt, ctx, topic, handler)
}

// CallSecretsSet issues a synchronous request-response Call for SecretsSetMsg.
func CallSecretsSet(rt sdk.CallerRuntime, ctx context.Context, msg SecretsSetMsg, opts ...sdk.CallOption) (SecretsSetResp, error) {
	return sdk.Call[SecretsSetMsg, SecretsSetResp](rt, ctx, msg, opts...)
}

// EmitSecretsAccessed fires a SecretsAccessedEvent event (no response expected).
func EmitSecretsAccessed(rt sdk.Runtime, ctx context.Context, msg SecretsAccessedEvent) error {
	return sdk.Emit(rt, ctx, msg)
}

// SubscribeSecretsAccessed listens for SecretsAccessedEvent events.
func SubscribeSecretsAccessed(rt sdk.Runtime, ctx context.Context, topic string, handler func(SecretsAccessedEvent, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[SecretsAccessedEvent](rt, ctx, topic, handler)
}

// EmitSecretsDeleted fires a SecretsDeletedEvent event (no response expected).
func EmitSecretsDeleted(rt sdk.Runtime, ctx context.Context, msg SecretsDeletedEvent) error {
	return sdk.Emit(rt, ctx, msg)
}

// SubscribeSecretsDeleted listens for SecretsDeletedEvent events.
func SubscribeSecretsDeleted(rt sdk.Runtime, ctx context.Context, topic string, handler func(SecretsDeletedEvent, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[SecretsDeletedEvent](rt, ctx, topic, handler)
}

// EmitSecretsRotated fires a SecretsRotatedEvent event (no response expected).
func EmitSecretsRotated(rt sdk.Runtime, ctx context.Context, msg SecretsRotatedEvent) error {
	return sdk.Emit(rt, ctx, msg)
}

// SubscribeSecretsRotated listens for SecretsRotatedEvent events.
func SubscribeSecretsRotated(rt sdk.Runtime, ctx context.Context, topic string, handler func(SecretsRotatedEvent, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[SecretsRotatedEvent](rt, ctx, topic, handler)
}

// EmitSecretsStored fires a SecretsStoredEvent event (no response expected).
func EmitSecretsStored(rt sdk.Runtime, ctx context.Context, msg SecretsStoredEvent) error {
	return sdk.Emit(rt, ctx, msg)
}

// SubscribeSecretsStored listens for SecretsStoredEvent events.
func SubscribeSecretsStored(rt sdk.Runtime, ctx context.Context, topic string, handler func(SecretsStoredEvent, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[SecretsStoredEvent](rt, ctx, topic, handler)
}

