// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit publish/subscribe/call/emit.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// The underlying generic publish/call patterns are unchanged. These wrappers
// just add type safety.
//
// Regenerate with cmd/sdkgen from this repository.
package topology

import (
	"context"

	"github.com/brainlet/brainkit/sdk"
)

// PublishPeersList publishes a PeersListMsg and returns routing info for the response.
func PublishPeersList(rt sdk.Runtime, ctx context.Context, msg PeersListMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribePeersListResp subscribes to the response topic for a PeersListMsg command.
func SubscribePeersListResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(PeersListResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[PeersListResp](rt, ctx, topic, handler)
}

// CallPeersList issues a synchronous request-response Call for PeersListMsg.
func CallPeersList(rt sdk.CallerRuntime, ctx context.Context, msg PeersListMsg, opts ...sdk.CallOption) (PeersListResp, error) {
	return sdk.Call[PeersListMsg, PeersListResp](rt, ctx, msg, opts...)
}

// PublishPeersResolve publishes a PeersResolveMsg and returns routing info for the response.
func PublishPeersResolve(rt sdk.Runtime, ctx context.Context, msg PeersResolveMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribePeersResolveResp subscribes to the response topic for a PeersResolveMsg command.
func SubscribePeersResolveResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(PeersResolveResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[PeersResolveResp](rt, ctx, topic, handler)
}

// CallPeersResolve issues a synchronous request-response Call for PeersResolveMsg.
func CallPeersResolve(rt sdk.CallerRuntime, ctx context.Context, msg PeersResolveMsg, opts ...sdk.CallOption) (PeersResolveResp, error) {
	return sdk.Call[PeersResolveMsg, PeersResolveResp](rt, ctx, msg, opts...)
}

