// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit call/emit/subscribe.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// Low-level publish/reply-topic helpers are intentionally not generated; use
// the generic SDK protocol primitives directly when testing transport behavior.
//
// Regenerate with cmd/sdkgen from this repository.
package topology

import (
	"context"

	bkmodule "github.com/brainlet/brainkit/module"
	"github.com/brainlet/brainkit/sdk"
)

// CallPeersList issues a synchronous request-response Call for PeersListMsg.
func CallPeersList(rt sdk.CallerRuntime, ctx context.Context, msg PeersListMsg, opts ...sdk.CallOption) (PeersListResp, error) {
	return sdk.Call[PeersListMsg, PeersListResp](rt, ctx, msg, opts...)
}

// CallPeersListWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallPeersListWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg PeersListMsg, opts ...sdk.CallOption) (PeersListResp, error) {
	return sdk.CallWithCaller[PeersListMsg, PeersListResp](caller, ctx, msg, opts...)
}

// CallPeersResolve issues a synchronous request-response Call for PeersResolveMsg.
func CallPeersResolve(rt sdk.CallerRuntime, ctx context.Context, msg PeersResolveMsg, opts ...sdk.CallOption) (PeersResolveResp, error) {
	return sdk.Call[PeersResolveMsg, PeersResolveResp](rt, ctx, msg, opts...)
}

// CallPeersResolveWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallPeersResolveWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg PeersResolveMsg, opts ...sdk.CallOption) (PeersResolveResp, error) {
	return sdk.CallWithCaller[PeersResolveMsg, PeersResolveResp](caller, ctx, msg, opts...)
}

