// Ported from: packages/core/src/loop/network/validation.ts
//
// Network Completion Scorers
//
// Completion checks are MastraScorers that return 0 (failed) or 1 (passed).
// This unifies completion checking with the evaluation system.
package network

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"sync"
	"time"
)

// ---------------------------------------------------------------------------
// Stub types for packages not yet ported
// ---------------------------------------------------------------------------

// MastraScorer is a stub for ../../evals/base.MastraScorer.
// Stub: real type is a struct (not interface) with Config, Source, steps, etc.
// Network uses an interface with ID/Name/Run methods. Shape mismatch (struct vs interface).
type MastraScorer interface {
	ID() string
	Name() string
	Run(ctx context.Context, input ScorerRunInput) (*ScorerRunResult, error)
}

// ScorerRunInput is the input to a MastraScorer.Run call.
type ScorerRunInput struct {
	RunID          string `json:"runId"`
	Input          any    `json:"input"`
	Output         any    `json:"output"`
	RequestContext any    `json:"requestContext,omitempty"`
}

// ScorerRunResult is the raw result from a MastraScorer.
type ScorerRunResult struct {
	Score  float64 `json:"score"`
	Reason string  `json:"reason,omitempty"`
}

// ChunkFrom type and ChunkFromNetwork constant are defined in network.go.

// ---------------------------------------------------------------------------
// Core Types
// ---------------------------------------------------------------------------

// CompletionContext is the runtime context passed to completion scoring.
// Available via run.input when using a completion scorer.
type CompletionContext struct {
	// Iteration is the current iteration number (1-based).
	Iteration int `json:"iteration"`
	// MaxIterations is the maximum iterations allowed.
	MaxIterations int `json:"maxIterations,omitempty"`
	// Messages is all messages in the conversation thread.
	Messages []MastraDBMessage `json:"messages"`
	// OriginalTask is the original task/prompt that started this network run.
	OriginalTask string `json:"originalTask"`
	// SelectedPrimitive is which primitive was selected this iteration.
	SelectedPrimitive SelectedPrimitiveInfo `json:"selectedPrimitive"`
	// PrimitivePrompt is the prompt/input sent to the selected primitive.
	PrimitivePrompt string `json:"primitivePrompt"`
	// PrimitiveResult is the result from the primitive execution.
	PrimitiveResult string `json:"primitiveResult"`
	// NetworkName is the name of the network/routing agent.
	NetworkName string `json:"networkName"`
	// RunID is the ID of the current run.
	RunID string `json:"runId"`
	// ThreadID is the current thread ID (if using memory).
	ThreadID string `json:"threadId,omitempty"`
	// ResourceID is the resource ID (if using memory).
	ResourceID string `json:"resourceId,omitempty"`
	// CustomContext is custom context from the request.
	CustomContext map[string]any `json:"customContext,omitempty"`
}

// SelectedPrimitiveInfo describes which primitive was selected for an iteration.
type SelectedPrimitiveInfo struct {
	ID   string `json:"id"`
	Type string `json:"type"` // "agent" | "workflow" | "tool" | "none"
}

// ScorerResult is the result of running a single scorer.
// Scorers evaluate pass/fail; they don't generate the final result.
type ScorerResult struct {
	// Score is the score (0 = failed, 1 = passed).
	Score float64 `json:"score"`
	// Passed indicates whether this scorer passed (score == 1).
	Passed bool `json:"passed"`
	// Reason from the scorer (why it passed/failed).
	Reason string `json:"reason,omitempty"`
	// ScorerID is the scorer's identifier.
	ScorerID string `json:"scorerId"`
	// ScorerName is the scorer's display name.
	ScorerName string `json:"scorerName"`
	// Duration in milliseconds.
	Duration int64 `json:"duration"`
	// FinalResult generated by the scorer (if any).
	FinalResult string `json:"finalResult,omitempty"`
}

// CompletionConfig configures network completion.
type CompletionConfig struct {
	// Scorers to run to determine if the task is complete.
	// Each scorer should return 0 (not complete) or 1 (complete).
	Scorers []MastraScorer `json:"-"`
	// Strategy is how to combine scorer results:
	//   "all" — All scorers must pass (score = 1) (default)
	//   "any" — At least one scorer must pass
	Strategy string `json:"strategy,omitempty"`
	// Timeout is the maximum time for all scorers (ms).
	// Default: 600000 (10 minutes).
	Timeout int `json:"timeout,omitempty"`
	// Parallel controls whether scorers run in parallel. Default: true.
	Parallel *bool `json:"parallel,omitempty"`
	// OnComplete is called after scorers run with results.
	OnComplete func(result CompletionRunResult) error `json:"-"`
	// SuppressFeedback suppresses the completion feedback message from being
	// saved to memory. When true, the "#### Completion Check Results" message
	// will not be persisted. Default: false.
	SuppressFeedback bool `json:"suppressFeedback,omitempty"`
}

// CompletionRunResult is the result of running completion checks.
type CompletionRunResult struct {
	// Complete indicates whether the task is complete (based on strategy).
	Complete bool `json:"complete"`
	// CompletionReason is the reason for completion/failure.
	CompletionReason string `json:"completionReason,omitempty"`
	// Scorers contains individual scorer results.
	Scorers []ScorerResult `json:"scorers"`
	// TotalDuration is the total duration of all checks in milliseconds.
	TotalDuration int64 `json:"totalDuration"`
	// TimedOut indicates whether checks timed out.
	TimedOut bool `json:"timedOut"`
}

// Legacy type aliases for backwards compatibility.
type CheckContext = CompletionContext           // Deprecated: Use CompletionContext.
type NetworkValidationConfig = CompletionConfig // Deprecated: Use CompletionConfig.
type CheckRunResult = CompletionRunResult       // Deprecated: Use CompletionRunResult.
type ValidationRunResult = CompletionRunResult  // Deprecated: Use CompletionRunResult.

// ---------------------------------------------------------------------------
// Scorer Runner
// ---------------------------------------------------------------------------

// runSingleScorer runs a single scorer and returns the result.
func runSingleScorer(ctx context.Context, scorer MastraScorer, compCtx CompletionContext) ScorerResult {
	start := time.Now()

	result, err := scorer.Run(ctx, ScorerRunInput{
		RunID:          compCtx.RunID,
		Input:          compCtx,
		Output:         compCtx.PrimitiveResult,
		RequestContext: compCtx.CustomContext,
	})

	if err != nil {
		return ScorerResult{
			Score:      0,
			Passed:     false,
			Reason:     fmt.Sprintf("Scorer threw an error: %s", err.Error()),
			ScorerID:   scorer.ID(),
			ScorerName: scorerName(scorer),
			Duration:   time.Since(start).Milliseconds(),
		}
	}

	score := float64(0)
	if result != nil {
		score = result.Score
	}
	reason := ""
	if result != nil {
		reason = result.Reason
	}

	return ScorerResult{
		Score:      score,
		Passed:     score == 1,
		Reason:     reason,
		ScorerID:   scorer.ID(),
		ScorerName: scorerName(scorer),
		Duration:   time.Since(start).Milliseconds(),
	}
}

func scorerName(s MastraScorer) string {
	if n := s.Name(); n != "" {
		return n
	}
	return s.ID()
}

// CompletionScorerOptions configures how scorers are run.
type CompletionScorerOptions struct {
	Strategy string // "all" | "any"
	Parallel bool
	Timeout  int // milliseconds
}

// RunCompletionScorers runs all completion scorers according to the configuration.
func RunCompletionScorers(
	ctx context.Context,
	scorers []MastraScorer,
	compCtx CompletionContext,
	options *CompletionScorerOptions,
) CompletionRunResult {
	strategy := "all"
	parallel := true
	timeout := 600000

	if options != nil {
		if options.Strategy != "" {
			strategy = options.Strategy
		}
		parallel = options.Parallel
		if options.Timeout > 0 {
			timeout = options.Timeout
		}
	}

	startTime := time.Now()
	var results []ScorerResult
	timedOut := false

	timeoutCtx, cancel := context.WithTimeout(ctx, time.Duration(timeout)*time.Millisecond)
	defer cancel()

	if parallel {
		type indexedResult struct {
			idx    int
			result ScorerResult
		}
		ch := make(chan indexedResult, len(scorers))
		var wg sync.WaitGroup

		for i, scorer := range scorers {
			wg.Add(1)
			go func(idx int, s MastraScorer) {
				defer wg.Done()
				r := runSingleScorer(timeoutCtx, s, compCtx)
				ch <- indexedResult{idx: idx, result: r}
			}(i, scorer)
		}

		// Wait for all goroutines in a separate goroutine
		go func() {
			wg.Wait()
			close(ch)
		}()

		collected := make([]ScorerResult, len(scorers))
		collectedCount := 0
		for ir := range ch {
			collected[ir.idx] = ir.result
			collectedCount++
		}

		// Check if context timed out
		if timeoutCtx.Err() != nil {
			timedOut = true
		}

		for i := 0; i < collectedCount; i++ {
			results = append(results, collected[i])
		}
	} else {
		for _, scorer := range scorers {
			if time.Since(startTime).Milliseconds() > int64(timeout) {
				timedOut = true
				break
			}

			result := runSingleScorer(timeoutCtx, scorer, compCtx)
			results = append(results, result)

			// Short-circuit
			if strategy == "all" && !result.Passed {
				break
			}
			if strategy == "any" && result.Passed {
				break
			}
		}
	}

	complete := false
	if strategy == "all" {
		complete = len(results) == len(scorers)
		if complete {
			for _, r := range results {
				if !r.Passed {
					complete = false
					break
				}
			}
		}
	} else {
		for _, r := range results {
			if r.Passed {
				complete = true
				break
			}
		}
	}

	// Get reason from first passing scorer (or first failing if none passed)
	var completionReason string
	for _, r := range results {
		if r.Passed {
			completionReason = r.Reason
			break
		}
	}
	if completionReason == "" && len(results) > 0 {
		completionReason = results[0].Reason
	}

	return CompletionRunResult{
		Complete:         complete,
		CompletionReason: completionReason,
		Scorers:          results,
		TotalDuration:    time.Since(startTime).Milliseconds(),
		TimedOut:         timedOut,
	}
}

// RunChecks is a legacy alias for RunCompletionScorers.
// Deprecated: Use RunCompletionScorers instead.
func RunChecks(
	ctx context.Context,
	scorers []MastraScorer,
	compCtx CompletionContext,
	options *CompletionScorerOptions,
) CompletionRunResult {
	return RunCompletionScorers(ctx, scorers, compCtx, options)
}

// RunValidation is a legacy alias that runs scorers from a CompletionConfig.
// Deprecated: Use RunCompletionScorers instead.
func RunValidation(
	ctx context.Context,
	config CompletionConfig,
	compCtx CompletionContext,
) (CompletionRunResult, error) {
	parallel := true
	if config.Parallel != nil {
		parallel = *config.Parallel
	}
	result := RunCompletionScorers(ctx, config.Scorers, compCtx, &CompletionScorerOptions{
		Strategy: config.Strategy,
		Parallel: parallel,
		Timeout:  config.Timeout,
	})
	if config.OnComplete != nil {
		if err := config.OnComplete(result); err != nil {
			return result, err
		}
	}
	return result, nil
}

// ---------------------------------------------------------------------------
// Feedback Formatting
// ---------------------------------------------------------------------------

// FormatCompletionFeedback formats scorer results into a message for the LLM.
func FormatCompletionFeedback(result CompletionRunResult, maxIterationReached bool) string {
	var b strings.Builder

	b.WriteString("#### Completion Check Results\n")
	b.WriteString("\n")
	if result.Complete {
		b.WriteString("Overall: COMPLETE\n")
	} else {
		b.WriteString("Overall: NOT COMPLETE\n")
	}
	fmt.Fprintf(&b, "Duration: %dms\n", result.TotalDuration)
	if result.TimedOut {
		b.WriteString("WARNING: Scoring timed out\n")
	}
	b.WriteString("\n")

	for _, scorer := range result.Scorers {
		fmt.Fprintf(&b, "###### %s (%s)\n", scorer.ScorerName, scorer.ScorerID)
		passStr := "FAILED"
		if scorer.Passed {
			passStr = "PASSED"
		}
		fmt.Fprintf(&b, "Score: %g %s\n", scorer.Score, passStr)
		if scorer.Reason != "" {
			fmt.Fprintf(&b, "Reason: %s\n", scorer.Reason)
		}
		b.WriteString("\n")
	}

	if result.Complete {
		b.WriteString("\n\nThe task is complete.")
	} else if maxIterationReached {
		b.WriteString("\n\nMax iterations reached.")
	} else {
		b.WriteString("\n\nWill continue working on the task.")
	}

	return b.String()
}

// FormatCheckFeedback is a legacy alias for FormatCompletionFeedback.
// Deprecated: Use FormatCompletionFeedback instead.
var FormatCheckFeedback = FormatCompletionFeedback

// FormatValidationFeedback is a legacy alias for FormatCompletionFeedback.
// Deprecated: Use FormatCompletionFeedback instead.
var FormatValidationFeedback = FormatCompletionFeedback

// ---------------------------------------------------------------------------
// Default LLM Completion Scorer
// ---------------------------------------------------------------------------

// RunDefaultCompletionCheck runs the default LLM completion check.
// It evaluates "is this done?" and does NOT generate the final result.
//
// This is an internal function used by the network loop when no scorers
// are configured. It streams a structured output call to the agent with a
// completion prompt and returns pass/fail based on the response.
func RunDefaultCompletionCheck(
	ctx context.Context,
	agent Agent,
	compCtx CompletionContext,
	streamContext *StreamContext,
) (*ScorerResult, error) {
	start := time.Now()

	// Build compact list of completed primitives from network messages.
	var completedPrimitives []string
	for _, m := range compCtx.Messages {
		for _, part := range m.Content.Parts {
			if part.Type == "text" && strings.Contains(part.Text, `"isNetwork":true`) {
				var parsed map[string]any
				if err := json.Unmarshal([]byte(part.Text), &parsed); err == nil {
					if isNet, ok := parsed["isNetwork"].(bool); ok && isNet {
						pType, _ := parsed["primitiveType"].(string)
						pID, _ := parsed["primitiveId"].(string)
						completedPrimitives = append(completedPrimitives, fmt.Sprintf("%s %q", pType, pID))
					}
				}
			}
		}
	}

	completedSection := ""
	if len(completedPrimitives) > 0 {
		completedSection = "\n\nPrimitives already executed: " + strings.Join(completedPrimitives, ", ")
	}

	primitiveResultJSON, _ := json.Marshal(compCtx.PrimitiveResult)

	completionPrompt := fmt.Sprintf(`
    The %s %s has contributed to the task.
    This is the result: %s

    %s

    You need to evaluate if the task is complete. Pay very close attention to the SYSTEM INSTRUCTIONS for when the task is considered complete.
    Only return true if the task is complete according to the system instructions.
    Original task: %s

    If no primitive (type = 'none'), the task is complete because we can't run any primitive to further task completion.

    Also, if the %s %s has declined the tool call in its response, then the task is complete as the primitive tool-call was declined by the user.

    IMPORTANT: If the above result is from an AGENT PRIMITIVE and it is a suitable final result itself considering the original task, then finalResult should be an empty string or undefined.

    If the task is complete and the result is not from an AGENT PRIMITIVE, always generate a finalResult.
    IF the task is complete and the result is from an AGENT PRIMITIVE, but the AGENT PRIMITIVE response is not comprehensive enough to accomplish the user's original task, then generate a finalResult.

    IMPORTANT: The generated finalResult should not be the exact primitive result. You should craft a comprehensive response based on the message history.
    The finalResult field should be written in natural language.

    You must return this JSON shape:
    {
      "isComplete": boolean,
      "completionReason": string,
      "finalResult": string,
    }
  `, compCtx.SelectedPrimitive.Type, compCtx.SelectedPrimitive.ID,
		string(primitiveResultJSON),
		completedSection,
		compCtx.OriginalTask,
		compCtx.SelectedPrimitive.Type, compCtx.SelectedPrimitive.ID,
	)

	// Call the agent with structured output.
	stream, err := agent.Stream(ctx, completionPrompt, map[string]any{
		"maxSteps": 1,
		"structuredOutput": map[string]any{
			"schema": "default-completion-schema",
		},
	})
	if err != nil {
		return &ScorerResult{
			Score:      0,
			Passed:     false,
			Reason:     fmt.Sprintf("LLM completion check failed: %s", err.Error()),
			ScorerID:   "default-completion",
			ScorerName: "Default LLM Completion",
			Duration:   time.Since(start).Milliseconds(),
		}, nil
	}

	// Consume the stream.
	for range stream.FullStream {
		// Consume chunks.
	}

	// Parse the structured output.
	var output map[string]any
	if stream.Object != nil {
		if m, ok := stream.Object.(map[string]any); ok {
			output = m
		}
	}

	isComplete := false
	completionReason := ""
	finalResult := ""

	if output != nil {
		if ic, ok := output["isComplete"].(bool); ok {
			isComplete = ic
		}
		if cr, ok := output["completionReason"].(string); ok {
			completionReason = cr
		}
		if fr, ok := output["finalResult"].(string); ok {
			finalResult = fr
		}
	}

	score := float64(0)
	if isComplete {
		score = 1
	}

	return &ScorerResult{
		Score:       score,
		Passed:      isComplete,
		Reason:      completionReason,
		FinalResult: finalResult,
		ScorerID:    "default-completion",
		ScorerName:  "Default LLM Completion",
		Duration:    time.Since(start).Milliseconds(),
	}, nil
}

// StreamContext holds streaming context for completion check output.
type StreamContext struct {
	Writer interface {
		Write(chunk any) error
	}
	StepID string
	RunID  string
}

// ---------------------------------------------------------------------------
// Final Result Generation
// ---------------------------------------------------------------------------

// StructuredFinalResult is the result type for structured final result generation.
type StructuredFinalResult struct {
	// Text result (for backward compatibility).
	Text string `json:"text,omitempty"`
	// Object is the structured object result when user schema is provided.
	Object any `json:"object,omitempty"`
}

// GenerateFinalResult generates and streams the final result after custom
// scorers have passed. Unlike RunDefaultCompletionCheck, this doesn't evaluate
// completion -- it only generates the result.
func GenerateFinalResult(
	ctx context.Context,
	agent Agent,
	compCtx CompletionContext,
	streamContext *StreamContext,
) (string, error) {
	primitiveResultJSON, _ := json.Marshal(compCtx.PrimitiveResult)

	prompt := fmt.Sprintf(`
    The task has been completed successfully.
    Original task: %s

    The %s %s produced this result:
    %s

    IMPORTANT: If the above result is from an AGENT PRIMITIVE and it is a suitable final result itself considering the original task, then finalResult should be an empty string or undefined.
    You should evaluate if the above result is comprehensive enough to accomplish the user's original task.
    Otherwise, generate the finalResult object. If the result is not from an AGENT PRIMITIVE, always generate a finalResult.

    The generated finalResult should not be the exact primitive result. You should craft a comprehensive response based on the message history.
    The response should be written in natural language.

    Return JSON:
    {
      "finalResult": string,
    }
  `, compCtx.OriginalTask,
		compCtx.SelectedPrimitive.Type, compCtx.SelectedPrimitive.ID,
		string(primitiveResultJSON),
	)

	stream, err := agent.Stream(ctx, prompt, map[string]any{
		"maxSteps": 1,
		"structuredOutput": map[string]any{
			"schema": "final-result-schema",
		},
	})
	if err != nil {
		return "", fmt.Errorf("generate final result: %w", err)
	}

	// Consume the stream.
	for range stream.FullStream {
		// Consume chunks.
	}

	// Parse the structured output.
	if stream.Object != nil {
		if m, ok := stream.Object.(map[string]any); ok {
			if fr, ok := m["finalResult"].(string); ok {
				return fr, nil
			}
		}
	}

	return "", nil
}

// GenerateStructuredFinalResult generates a structured final result using
// the user-provided schema. Called when the network has structuredOutput
// option configured.
func GenerateStructuredFinalResult(
	ctx context.Context,
	agent Agent,
	compCtx CompletionContext,
	structuredOutputOptions StructuredOutputOptions,
	streamContext *StreamContext,
) (*StructuredFinalResult, error) {
	primitiveResultJSON, _ := json.Marshal(compCtx.PrimitiveResult)

	prompt := fmt.Sprintf(`
    The task has been completed successfully.
    Original task: %s

    The %s %s produced this result:
    %s

    Based on the task and result above, generate a structured response according to the provided schema.
    Use the conversation history and primitive results to craft the response.
  `, compCtx.OriginalTask,
		compCtx.SelectedPrimitive.Type, compCtx.SelectedPrimitive.ID,
		string(primitiveResultJSON),
	)

	stream, err := agent.Stream(ctx, prompt, map[string]any{
		"maxSteps":         1,
		"structuredOutput": structuredOutputOptions,
	})
	if err != nil {
		return nil, fmt.Errorf("generate structured final result: %w", err)
	}

	// Consume the stream.
	for range stream.FullStream {
		// Consume chunks.
	}

	// Parse the structured output.
	var finalObject any
	if stream.Object != nil {
		finalObject = stream.Object
	}

	var text string
	if finalObject != nil {
		b, _ := json.Marshal(finalObject)
		text = string(b)
	}

	return &StructuredFinalResult{
		Text:   text,
		Object: finalObject,
	}, nil
}

// ---------------------------------------------------------------------------
// Stream Completion Scoring
// ---------------------------------------------------------------------------

// StreamCompletionContext is the runtime context passed to stream/generate
// completion scoring. A simplified version of CompletionContext for
// tool-based supervisor patterns.
type StreamCompletionContext struct {
	// Iteration is the current iteration number (1-based).
	Iteration int `json:"iteration"`
	// MaxIterations is the maximum iterations allowed (maxSteps).
	MaxIterations int `json:"maxIterations,omitempty"`
	// OriginalTask is the original user message/task that started this execution.
	OriginalTask string `json:"originalTask"`
	// CurrentText is the current output text from the LLM.
	CurrentText string `json:"currentText"`
	// ToolCalls made in this iteration.
	ToolCalls []ToolCallInfo `json:"toolCalls"`
	// ToolResults from this iteration.
	ToolResults []ToolResultInfo `json:"toolResults"`
	// RunID is the ID of the current run.
	RunID string `json:"runId"`
	// ThreadID is the current thread ID (if using memory).
	ThreadID string `json:"threadId,omitempty"`
	// ResourceID is the resource ID (if using memory).
	ResourceID string `json:"resourceId,omitempty"`
	// AgentID is the agent identifier.
	AgentID string `json:"agentId,omitempty"`
	// AgentName is the agent's display name.
	AgentName string `json:"agentName,omitempty"`
	// CustomContext is custom context from the request.
	CustomContext map[string]any `json:"customContext,omitempty"`
	// Messages is the full message list.
	Messages []MastraDBMessage `json:"messages"`
}

// ToolCallInfo describes a tool call made during an iteration.
type ToolCallInfo struct {
	Name string         `json:"name"`
	Args map[string]any `json:"args"`
}

// ToolResultInfo describes a tool result from an iteration.
type ToolResultInfo struct {
	Name   string `json:"name"`
	Result any    `json:"result"`
}

// RunStreamCompletionScorers runs completion scorers for stream/generate
// execution. It adapts StreamCompletionContext to work with existing scorers.
func RunStreamCompletionScorers(
	ctx context.Context,
	scorers []MastraScorer,
	sCtx StreamCompletionContext,
	options *CompletionScorerOptions,
) CompletionRunResult {
	// Adapt StreamCompletionContext to CompletionContext for scorer compatibility
	adaptedCtx := CompletionContext{
		Iteration:     sCtx.Iteration,
		MaxIterations: sCtx.MaxIterations,
		Messages:      sCtx.Messages,
		OriginalTask:  sCtx.OriginalTask,
		SelectedPrimitive: SelectedPrimitiveInfo{
			ID:   "stream",
			Type: "agent",
		},
		PrimitivePrompt: sCtx.OriginalTask,
		PrimitiveResult: sCtx.CurrentText,
		NetworkName:     sCtx.AgentName,
		RunID:           sCtx.RunID,
		ThreadID:        sCtx.ThreadID,
		ResourceID:      sCtx.ResourceID,
		CustomContext: map[string]any{
			"toolCalls":   sCtx.ToolCalls,
			"toolResults": sCtx.ToolResults,
			"agentId":     sCtx.AgentID,
			"agentName":   sCtx.AgentName,
		},
	}

	if adaptedCtx.NetworkName == "" {
		adaptedCtx.NetworkName = sCtx.AgentID
	}
	if adaptedCtx.NetworkName == "" {
		adaptedCtx.NetworkName = "stream"
	}

	// Merge caller's custom context
	if sCtx.CustomContext != nil {
		for k, v := range sCtx.CustomContext {
			adaptedCtx.CustomContext[k] = v
		}
	}

	return RunCompletionScorers(ctx, scorers, adaptedCtx, options)
}

// FormatStreamCompletionFeedback formats stream completion feedback for the LLM.
// Similar to FormatCompletionFeedback but tailored for stream context.
func FormatStreamCompletionFeedback(result CompletionRunResult, maxIterationReached bool) string {
	var b strings.Builder

	b.WriteString("#### Completion Check Results\n")
	b.WriteString("\n")
	if result.Complete {
		b.WriteString("Overall: COMPLETE\n")
	} else {
		b.WriteString("Overall: NOT COMPLETE\n")
	}
	fmt.Fprintf(&b, "Duration: %dms\n", result.TotalDuration)
	if result.TimedOut {
		b.WriteString("WARNING: Scoring timed out\n")
	}
	b.WriteString("\n")

	for _, scorer := range result.Scorers {
		fmt.Fprintf(&b, "**%s** (%s)\n", scorer.ScorerName, scorer.ScorerID)
		passStr := "FAILED"
		if scorer.Passed {
			passStr = "PASSED"
		}
		fmt.Fprintf(&b, "Score: %g %s\n", scorer.Score, passStr)
		if scorer.Reason != "" {
			fmt.Fprintf(&b, "Reason: %s\n", scorer.Reason)
		}
		b.WriteString("\n")
	}

	if result.Complete {
		b.WriteString("The task is complete.")
	} else if maxIterationReached {
		b.WriteString("Max iterations reached.")
	} else {
		b.WriteString("The task is not yet complete. Please continue working based on the feedback above.")
	}

	return b.String()
}
