// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit call/emit/subscribe.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// Low-level publish/reply-topic helpers are intentionally not generated; use
// the generic SDK protocol primitives directly when testing transport behavior.
//
// Regenerate with cmd/sdkgen from this repository.
package referencemsg

import (
	"context"

	bkmodule "github.com/brainlet/brainkit/module"
	"github.com/brainlet/brainkit/sdk"
)

// CallKitReference issues a synchronous request-response Call for KitReferenceMsg.
func CallKitReference(rt sdk.CallerRuntime, ctx context.Context, msg KitReferenceMsg, opts ...sdk.CallOption) (KitReferenceResp, error) {
	return sdk.Call[KitReferenceMsg, KitReferenceResp](rt, ctx, msg, opts...)
}

// CallKitReferenceWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallKitReferenceWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg KitReferenceMsg, opts ...sdk.CallOption) (KitReferenceResp, error) {
	return sdk.CallWithCaller[KitReferenceMsg, KitReferenceResp](caller, ctx, msg, opts...)
}

// CallKitReferenceList issues a synchronous request-response Call for KitReferenceListMsg.
func CallKitReferenceList(rt sdk.CallerRuntime, ctx context.Context, msg KitReferenceListMsg, opts ...sdk.CallOption) (KitReferenceListResp, error) {
	return sdk.Call[KitReferenceListMsg, KitReferenceListResp](rt, ctx, msg, opts...)
}

// CallKitReferenceListWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallKitReferenceListWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg KitReferenceListMsg, opts ...sdk.CallOption) (KitReferenceListResp, error) {
	return sdk.CallWithCaller[KitReferenceListMsg, KitReferenceListResp](caller, ctx, msg, opts...)
}

