// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit publish/subscribe/call/emit.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// The underlying generic publish/call patterns are unchanged. These wrappers
// just add type safety.
//
// Regenerate with cmd/sdkgen from this repository.
package referencemsg

import (
	"context"

	"github.com/brainlet/brainkit/sdk"
)

// PublishKitReference publishes a KitReferenceMsg and returns routing info for the response.
func PublishKitReference(rt sdk.Runtime, ctx context.Context, msg KitReferenceMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeKitReferenceResp subscribes to the response topic for a KitReferenceMsg command.
func SubscribeKitReferenceResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(KitReferenceResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[KitReferenceResp](rt, ctx, topic, handler)
}

// CallKitReference issues a synchronous request-response Call for KitReferenceMsg.
func CallKitReference(rt sdk.CallerRuntime, ctx context.Context, msg KitReferenceMsg, opts ...sdk.CallOption) (KitReferenceResp, error) {
	return sdk.Call[KitReferenceMsg, KitReferenceResp](rt, ctx, msg, opts...)
}

// PublishKitReferenceList publishes a KitReferenceListMsg and returns routing info for the response.
func PublishKitReferenceList(rt sdk.Runtime, ctx context.Context, msg KitReferenceListMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeKitReferenceListResp subscribes to the response topic for a KitReferenceListMsg command.
func SubscribeKitReferenceListResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(KitReferenceListResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[KitReferenceListResp](rt, ctx, topic, handler)
}

// CallKitReferenceList issues a synchronous request-response Call for KitReferenceListMsg.
func CallKitReferenceList(rt sdk.CallerRuntime, ctx context.Context, msg KitReferenceListMsg, opts ...sdk.CallOption) (KitReferenceListResp, error) {
	return sdk.Call[KitReferenceListMsg, KitReferenceListResp](rt, ctx, msg, opts...)
}

