// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitegen

type AuditEvent struct {
	ID        string
	Timestamp string
	Category  string
	EventType string
	Source    string
	RuntimeID string
	Namespace string
	Data      string
	Duration  int64
	ErrorMsg  string
}

type Deployment struct {
	Source      string
	Code        string
	DeployOrder int64
	DeployedAt  string
	PackageName string
	Role        string
}

type InstalledPlugin struct {
	Name        string
	Owner       string
	Version     string
	BinaryPath  string
	Manifest    string
	InstalledAt string
}

type RunningPlugin struct {
	Name       string
	Owner      string
	Version    string
	BinaryPath string
	Env        string
	Config     string
	StartOrder int64
	StartedAt  string
	Role       string
}

type Schedule struct {
	ID         string
	Expression string
	DurationNs int64
	Topic      string
	Payload    string
	Source     string
	CreatedAt  string
	NextFire   string
	OneTime    int64
}

type ScheduleFire struct {
	ScheduleID string
	FireTime   string
	ClaimedAt  string
}
