// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries_kit.sql

package sqlitegen

import (
	"context"
)

const claimScheduleFire = `-- name: ClaimScheduleFire :exec
es WHERE id = ?;


INSERT OR IGNORE INTO schedule_fires (schedule_id, fire_time, clai
`

type ClaimScheduleFireParams struct {
	ScheduleID string
	FireTime   string
	ClaimedAt  string
}

// ── Schedule Fires (deduplication) ──
func (q *Queries) ClaimScheduleFire(ctx context.Context, arg ClaimScheduleFireParams) error {
	_, err := q.db.ExecContext(ctx, claimScheduleFire, arg.ScheduleID, arg.FireTime, arg.ClaimedAt)
	return err
}

const deleteDeployment = `-- name: DeleteDeployment :exec
rce = ?;

DELETE FROM deployments WHERE so
`

func (q *Queries) DeleteDeployment(ctx context.Context, source string) error {
	_, err := q.db.ExecContext(ctx, deleteDeployment, source)
	return err
}

const deleteInstalledPlugin = `-- name: DeleteInstalledPlugin :exec
alled_at
FROM installed_plugins;

DELETE FROM
`

func (q *Queries) DeleteInstalledPlugin(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteInstalledPlugin, name)
	return err
}

const deleteRunningPlugin = `-- name: DeleteRunningPlugin :exec
OM running_plugins ORDER BY start_order;

DE
`

func (q *Queries) DeleteRunningPlugin(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteRunningPlugin, name)
	return err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
FROM schedules;

DELETE FROM schedu
`

func (q *Queries) DeleteSchedule(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSchedule, id)
	return err
}

const loadDeployment = `-- name: LoadDeployment :one
y_order;

SELECT source, code, deploy_order, deployed_at, package_name, role
FROM deployments WHERE so
`

func (q *Queries) LoadDeployment(ctx context.Context, source string) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, loadDeployment, source)
	var i Deployment
	err := row.Scan(
		&i.Source,
		&i.Code,
		&i.DeployOrder,
		&i.DeployedAt,
		&i.PackageName,
		&i.Role,
	)
	return i, err
}

const loadDeployments = `-- name: LoadDeployments :many
, ?, ?);

SELECT source, code, deploy_order, deployed_at, package_name, role
FROM deployments ORDER BY depl
`

func (q *Queries) LoadDeployments(ctx context.Context) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, loadDeployments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.Source,
			&i.Code,
			&i.DeployOrder,
			&i.DeployedAt,
			&i.PackageName,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadInstalledPlugins = `-- name: LoadInstalledPlugins :many
d_at)
VALUES (?, ?, ?, ?, ?, ?);

SELECT name, owner, version, binary_path, manifest, ins
`

func (q *Queries) LoadInstalledPlugins(ctx context.Context) ([]InstalledPlugin, error) {
	rows, err := q.db.QueryContext(ctx, loadInstalledPlugins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstalledPlugin{}
	for rows.Next() {
		var i InstalledPlugin
		if err := rows.Scan(
			&i.Name,
			&i.Owner,
			&i.Version,
			&i.BinaryPath,
			&i.Manifest,
			&i.InstalledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadRunningPlugins = `-- name: LoadRunningPlugins :many
ole)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);

SELECT name, owner, version, binary_path, env, config, start_order, started_at, role
F
`

func (q *Queries) LoadRunningPlugins(ctx context.Context) ([]RunningPlugin, error) {
	rows, err := q.db.QueryContext(ctx, loadRunningPlugins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunningPlugin{}
	for rows.Next() {
		var i RunningPlugin
		if err := rows.Scan(
			&i.Name,
			&i.Owner,
			&i.Version,
			&i.BinaryPath,
			&i.Env,
			&i.Config,
			&i.StartOrder,
			&i.StartedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadSchedules = `-- name: LoadSchedules :many
?, ?, ?, ?, ?);

SELECT id, expression, duration_ns, topic, payload, source, created_at, next_fire, one_tim
`

func (q *Queries) LoadSchedules(ctx context.Context) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, loadSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.Expression,
			&i.DurationNs,
			&i.Topic,
			&i.Payload,
			&i.Source,
			&i.CreatedAt,
			&i.NextFire,
			&i.OneTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveDeployment = `-- name: SaveDeployment :exec

INSERT OR REPLACE INTO deployments (source, code, deploy_order, deployed_at, package_name, role)
VALUES (?, ?, ?,
`

type SaveDeploymentParams struct {
	Source      string
	Code        string
	DeployOrder int64
	DeployedAt  string
	PackageName string
	Role        string
}

// ── Deployments ──
func (q *Queries) SaveDeployment(ctx context.Context, arg SaveDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, saveDeployment,
		arg.Source,
		arg.Code,
		arg.DeployOrder,
		arg.DeployedAt,
		arg.PackageName,
		arg.Role,
	)
	return err
}

const saveInstalledPlugin = `-- name: SaveInstalledPlugin :exec
ed_at)
VALUES (?, ?, ?);


INSERT OR REPLACE INTO installed_plugins (name, owner, version, binary_path, manifest, install
`

type SaveInstalledPluginParams struct {
	Name        string
	Owner       string
	Version     string
	BinaryPath  string
	Manifest    string
	InstalledAt string
}

// ── Installed Plugins ──
func (q *Queries) SaveInstalledPlugin(ctx context.Context, arg SaveInstalledPluginParams) error {
	_, err := q.db.ExecContext(ctx, saveInstalledPlugin,
		arg.Name,
		arg.Owner,
		arg.Version,
		arg.BinaryPath,
		arg.Manifest,
		arg.InstalledAt,
	)
	return err
}

const saveRunningPlugin = `-- name: SaveRunningPlugin :exec
nstalled_plugins WHERE name = ?;


INSERT OR REPLACE INTO running_plugins (name, owner, version, binary_path, env, config, start_order, started_at,
`

type SaveRunningPluginParams struct {
	Name       string
	Owner      string
	Version    string
	BinaryPath string
	Env        string
	Config     string
	StartOrder int64
	StartedAt  string
	Role       string
}

// ── Running Plugins ──
func (q *Queries) SaveRunningPlugin(ctx context.Context, arg SaveRunningPluginParams) error {
	_, err := q.db.ExecContext(ctx, saveRunningPlugin,
		arg.Name,
		arg.Owner,
		arg.Version,
		arg.BinaryPath,
		arg.Env,
		arg.Config,
		arg.StartOrder,
		arg.StartedAt,
		arg.Role,
	)
	return err
}

const saveSchedule = `-- name: SaveSchedule :exec
rce = ?;


INSERT OR REPLACE INTO schedules (id, expression, duration_ns, topic, payload, source, created_at, next_fire, one_time)
VALUES (?, ?, ?, ?
`

type SaveScheduleParams struct {
	ID         string
	Expression string
	DurationNs int64
	Topic      string
	Payload    string
	Source     string
	CreatedAt  string
	NextFire   string
	OneTime    int64
}

// ── Schedules ──
func (q *Queries) SaveSchedule(ctx context.Context, arg SaveScheduleParams) error {
	_, err := q.db.ExecContext(ctx, saveSchedule,
		arg.ID,
		arg.Expression,
		arg.DurationNs,
		arg.Topic,
		arg.Payload,
		arg.Source,
		arg.CreatedAt,
		arg.NextFire,
		arg.OneTime,
	)
	return err
}
