// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries_audit.sql

package sqlitegen

import (
	"context"
)

const countAuditEvents = `-- name: CountAuditEvents :one
LIMIT ?;

SELECT COUNT(*) FROM audi
`

func (q *Queries) CountAuditEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditEventsByCategory = `-- name: CountAuditEventsByCategory :many
_events;

SELECT category, COUNT(*) AS cnt FROM audit_events GROUP BY
`

type CountAuditEventsByCategoryRow struct {
	Category string
	Cnt      int64
}

func (q *Queries) CountAuditEventsByCategory(ctx context.Context) ([]CountAuditEventsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, countAuditEventsByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAuditEventsByCategoryRow{}
	for rows.Next() {
		var i CountAuditEventsByCategoryRow
		if err := rows.Scan(&i.Category, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAuditEvents = `-- name: PruneAuditEvents :exec
ategory;

DELETE FROM audit_events WHERE times
`

func (q *Queries) PruneAuditEvents(ctx context.Context, timestamp string) error {
	_, err := q.db.ExecContext(ctx, pruneAuditEvents, timestamp)
	return err
}

const queryAuditEventsAll = `-- name: QueryAuditEventsAll :many
LIMIT ?;

SELECT id, timestamp, category, event_type, source, runtime_id, namespace, data, duration, error_msg
FROM audit_events ORDER BY timestamp DESC
`

func (q *Queries) QueryAuditEventsAll(ctx context.Context, limit int64) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, queryAuditEventsAll, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Category,
			&i.EventType,
			&i.Source,
			&i.RuntimeID,
			&i.Namespace,
			&i.Data,
			&i.Duration,
			&i.ErrorMsg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryAuditEventsByCategory = `-- name: QueryAuditEventsByCategory :many
, ?, ?);

SELECT id, timestamp, category, event_type, source, runtime_id, namespace, data, duration, error_msg
FROM audit_events WHERE category = ? ORDER BY timestamp DESC
`

type QueryAuditEventsByCategoryParams struct {
	Category string
	Limit    int64
}

func (q *Queries) QueryAuditEventsByCategory(ctx context.Context, arg QueryAuditEventsByCategoryParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, queryAuditEventsByCategory, arg.Category, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Category,
			&i.EventType,
			&i.Source,
			&i.RuntimeID,
			&i.Namespace,
			&i.Data,
			&i.Duration,
			&i.ErrorMsg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryAuditEventsBySource = `-- name: QueryAuditEventsBySource :many
LIMIT ?;

SELECT id, timestamp, category, event_type, source, runtime_id, namespace, data, duration, error_msg
FROM audit_events WHERE source = ? ORDER BY timestamp DESC
`

type QueryAuditEventsBySourceParams struct {
	Source string
	Limit  int64
}

func (q *Queries) QueryAuditEventsBySource(ctx context.Context, arg QueryAuditEventsBySourceParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, queryAuditEventsBySource, arg.Source, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Category,
			&i.EventType,
			&i.Source,
			&i.RuntimeID,
			&i.Namespace,
			&i.Data,
			&i.Duration,
			&i.ErrorMsg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryAuditEventsByType = `-- name: QueryAuditEventsByType :many
LIMIT ?;

SELECT id, timestamp, category, event_type, source, runtime_id, namespace, data, duration, error_msg
FROM audit_events WHERE event_type = ? ORDER BY timestamp DESC
`

type QueryAuditEventsByTypeParams struct {
	EventType string
	Limit     int64
}

func (q *Queries) QueryAuditEventsByType(ctx context.Context, arg QueryAuditEventsByTypeParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, queryAuditEventsByType, arg.EventType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Category,
			&i.EventType,
			&i.Source,
			&i.RuntimeID,
			&i.Namespace,
			&i.Data,
			&i.Duration,
			&i.ErrorMsg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryAuditEventsSince = `-- name: QueryAuditEventsSince :many
LIMIT ?;

SELECT id, timestamp, category, event_type, source, runtime_id, namespace, data, duration, error_msg
FROM audit_events WHERE timestamp >= ? ORDER BY timestamp DESC
`

type QueryAuditEventsSinceParams struct {
	Timestamp string
	Limit     int64
}

func (q *Queries) QueryAuditEventsSince(ctx context.Context, arg QueryAuditEventsSinceParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, queryAuditEventsSince, arg.Timestamp, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Category,
			&i.EventType,
			&i.Source,
			&i.RuntimeID,
			&i.Namespace,
			&i.Data,
			&i.Duration,
			&i.ErrorMsg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAuditEvent = `-- name: RecordAuditEvent :exec

INSERT INTO audit_events (id, timestamp, category, event_type, source, runtime_id, namespace, data, duration, error_msg)
VALUES (?, ?, ?, ?, ?, ?, ?,
`

type RecordAuditEventParams struct {
	ID        string
	Timestamp string
	Category  string
	EventType string
	Source    string
	RuntimeID string
	Namespace string
	Data      string
	Duration  int64
	ErrorMsg  string
}

// ── Audit Events ──
func (q *Queries) RecordAuditEvent(ctx context.Context, arg RecordAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, recordAuditEvent,
		arg.ID,
		arg.Timestamp,
		arg.Category,
		arg.EventType,
		arg.Source,
		arg.RuntimeID,
		arg.Namespace,
		arg.Data,
		arg.Duration,
		arg.ErrorMsg,
	)
	return err
}
