// Code generated by codegen/sdkgen. DO NOT EDIT.
//
// Typed wrappers for sdk.Publish/SubscribeTo/Emit.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// The underlying async pub/sub pattern is unchanged — callers still manage
// channels, select, and timeouts. These wrappers just add type safety.
//
// Regenerate: go run ./codegen/sdkgen/ -messages ./sdk/messages -out ./sdk/typed_gen.go
package sdk

import (
	"context"

	"github.com/brainlet/brainkit/sdk/messages"
)

// PublishAgentDiscover publishes a AgentDiscoverMsg and returns routing info for the response.
func PublishAgentDiscover(rt Runtime, ctx context.Context, msg messages.AgentDiscoverMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeAgentDiscoverResp subscribes to the response topic for a AgentDiscoverMsg command.
func SubscribeAgentDiscoverResp(rt Runtime, ctx context.Context, topic string, handler func(messages.AgentDiscoverResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.AgentDiscoverResp](rt, ctx, topic, handler)
}

// PublishAgentGetStatus publishes a AgentGetStatusMsg and returns routing info for the response.
func PublishAgentGetStatus(rt Runtime, ctx context.Context, msg messages.AgentGetStatusMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeAgentGetStatusResp subscribes to the response topic for a AgentGetStatusMsg command.
func SubscribeAgentGetStatusResp(rt Runtime, ctx context.Context, topic string, handler func(messages.AgentGetStatusResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.AgentGetStatusResp](rt, ctx, topic, handler)
}

// PublishAgentList publishes a AgentListMsg and returns routing info for the response.
func PublishAgentList(rt Runtime, ctx context.Context, msg messages.AgentListMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeAgentListResp subscribes to the response topic for a AgentListMsg command.
func SubscribeAgentListResp(rt Runtime, ctx context.Context, topic string, handler func(messages.AgentListResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.AgentListResp](rt, ctx, topic, handler)
}

// PublishAgentSetStatus publishes a AgentSetStatusMsg and returns routing info for the response.
func PublishAgentSetStatus(rt Runtime, ctx context.Context, msg messages.AgentSetStatusMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeAgentSetStatusResp subscribes to the response topic for a AgentSetStatusMsg command.
func SubscribeAgentSetStatusResp(rt Runtime, ctx context.Context, topic string, handler func(messages.AgentSetStatusResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.AgentSetStatusResp](rt, ctx, topic, handler)
}

// PublishGatewayRouteAdd publishes a GatewayRouteAddMsg and returns routing info for the response.
func PublishGatewayRouteAdd(rt Runtime, ctx context.Context, msg messages.GatewayRouteAddMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeGatewayRouteAddResp subscribes to the response topic for a GatewayRouteAddMsg command.
func SubscribeGatewayRouteAddResp(rt Runtime, ctx context.Context, topic string, handler func(messages.GatewayRouteAddResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.GatewayRouteAddResp](rt, ctx, topic, handler)
}

// PublishGatewayRouteList publishes a GatewayRouteListMsg and returns routing info for the response.
func PublishGatewayRouteList(rt Runtime, ctx context.Context, msg messages.GatewayRouteListMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeGatewayRouteListResp subscribes to the response topic for a GatewayRouteListMsg command.
func SubscribeGatewayRouteListResp(rt Runtime, ctx context.Context, topic string, handler func(messages.GatewayRouteListResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.GatewayRouteListResp](rt, ctx, topic, handler)
}

// PublishGatewayRouteRemove publishes a GatewayRouteRemoveMsg and returns routing info for the response.
func PublishGatewayRouteRemove(rt Runtime, ctx context.Context, msg messages.GatewayRouteRemoveMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeGatewayRouteRemoveResp subscribes to the response topic for a GatewayRouteRemoveMsg command.
func SubscribeGatewayRouteRemoveResp(rt Runtime, ctx context.Context, topic string, handler func(messages.GatewayRouteRemoveResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.GatewayRouteRemoveResp](rt, ctx, topic, handler)
}

// PublishGatewayStatus publishes a GatewayStatusMsg and returns routing info for the response.
func PublishGatewayStatus(rt Runtime, ctx context.Context, msg messages.GatewayStatusMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeGatewayStatusResp subscribes to the response topic for a GatewayStatusMsg command.
func SubscribeGatewayStatusResp(rt Runtime, ctx context.Context, topic string, handler func(messages.GatewayStatusResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.GatewayStatusResp](rt, ctx, topic, handler)
}

// PublishKitDeploy publishes a KitDeployMsg and returns routing info for the response.
func PublishKitDeploy(rt Runtime, ctx context.Context, msg messages.KitDeployMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeKitDeployResp subscribes to the response topic for a KitDeployMsg command.
func SubscribeKitDeployResp(rt Runtime, ctx context.Context, topic string, handler func(messages.KitDeployResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.KitDeployResp](rt, ctx, topic, handler)
}

// PublishKitDeployFile publishes a KitDeployFileMsg and returns routing info for the response.
func PublishKitDeployFile(rt Runtime, ctx context.Context, msg messages.KitDeployFileMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// PublishKitEval publishes a KitEvalMsg and returns routing info for the response.
func PublishKitEval(rt Runtime, ctx context.Context, msg messages.KitEvalMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeKitEvalResp subscribes to the response topic for a KitEvalMsg command.
func SubscribeKitEvalResp(rt Runtime, ctx context.Context, topic string, handler func(messages.KitEvalResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.KitEvalResp](rt, ctx, topic, handler)
}

// PublishKitHealth publishes a KitHealthMsg and returns routing info for the response.
func PublishKitHealth(rt Runtime, ctx context.Context, msg messages.KitHealthMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeKitHealthResp subscribes to the response topic for a KitHealthMsg command.
func SubscribeKitHealthResp(rt Runtime, ctx context.Context, topic string, handler func(messages.KitHealthResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.KitHealthResp](rt, ctx, topic, handler)
}

// PublishKitList publishes a KitListMsg and returns routing info for the response.
func PublishKitList(rt Runtime, ctx context.Context, msg messages.KitListMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeKitListResp subscribes to the response topic for a KitListMsg command.
func SubscribeKitListResp(rt Runtime, ctx context.Context, topic string, handler func(messages.KitListResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.KitListResp](rt, ctx, topic, handler)
}

// PublishKitRedeploy publishes a KitRedeployMsg and returns routing info for the response.
func PublishKitRedeploy(rt Runtime, ctx context.Context, msg messages.KitRedeployMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeKitRedeployResp subscribes to the response topic for a KitRedeployMsg command.
func SubscribeKitRedeployResp(rt Runtime, ctx context.Context, topic string, handler func(messages.KitRedeployResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.KitRedeployResp](rt, ctx, topic, handler)
}

// PublishKitSend publishes a KitSendMsg and returns routing info for the response.
func PublishKitSend(rt Runtime, ctx context.Context, msg messages.KitSendMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeKitSendResp subscribes to the response topic for a KitSendMsg command.
func SubscribeKitSendResp(rt Runtime, ctx context.Context, topic string, handler func(messages.KitSendResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.KitSendResp](rt, ctx, topic, handler)
}

// PublishKitTeardown publishes a KitTeardownMsg and returns routing info for the response.
func PublishKitTeardown(rt Runtime, ctx context.Context, msg messages.KitTeardownMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeKitTeardownResp subscribes to the response topic for a KitTeardownMsg command.
func SubscribeKitTeardownResp(rt Runtime, ctx context.Context, topic string, handler func(messages.KitTeardownResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.KitTeardownResp](rt, ctx, topic, handler)
}

// PublishMcpCallTool publishes a McpCallToolMsg and returns routing info for the response.
func PublishMcpCallTool(rt Runtime, ctx context.Context, msg messages.McpCallToolMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeMcpCallToolResp subscribes to the response topic for a McpCallToolMsg command.
func SubscribeMcpCallToolResp(rt Runtime, ctx context.Context, topic string, handler func(messages.McpCallToolResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.McpCallToolResp](rt, ctx, topic, handler)
}

// PublishMcpListTools publishes a McpListToolsMsg and returns routing info for the response.
func PublishMcpListTools(rt Runtime, ctx context.Context, msg messages.McpListToolsMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeMcpListToolsResp subscribes to the response topic for a McpListToolsMsg command.
func SubscribeMcpListToolsResp(rt Runtime, ctx context.Context, topic string, handler func(messages.McpListToolsResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.McpListToolsResp](rt, ctx, topic, handler)
}

// PublishMetricsGet publishes a MetricsGetMsg and returns routing info for the response.
func PublishMetricsGet(rt Runtime, ctx context.Context, msg messages.MetricsGetMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeMetricsGetResp subscribes to the response topic for a MetricsGetMsg command.
func SubscribeMetricsGetResp(rt Runtime, ctx context.Context, topic string, handler func(messages.MetricsGetResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.MetricsGetResp](rt, ctx, topic, handler)
}

// PublishPackageDeploy publishes a PackageDeployMsg and returns routing info for the response.
func PublishPackageDeploy(rt Runtime, ctx context.Context, msg messages.PackageDeployMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePackageDeployResp subscribes to the response topic for a PackageDeployMsg command.
func SubscribePackageDeployResp(rt Runtime, ctx context.Context, topic string, handler func(messages.PackageDeployResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PackageDeployResp](rt, ctx, topic, handler)
}

// PublishPackageDeployInfo publishes a PackageDeployInfoMsg and returns routing info for the response.
func PublishPackageDeployInfo(rt Runtime, ctx context.Context, msg messages.PackageDeployInfoMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePackageDeployInfoResp subscribes to the response topic for a PackageDeployInfoMsg command.
func SubscribePackageDeployInfoResp(rt Runtime, ctx context.Context, topic string, handler func(messages.PackageDeployInfoResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PackageDeployInfoResp](rt, ctx, topic, handler)
}

// PublishPackageListDeployed publishes a PackageListDeployedMsg and returns routing info for the response.
func PublishPackageListDeployed(rt Runtime, ctx context.Context, msg messages.PackageListDeployedMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePackageListDeployedResp subscribes to the response topic for a PackageListDeployedMsg command.
func SubscribePackageListDeployedResp(rt Runtime, ctx context.Context, topic string, handler func(messages.PackageListDeployedResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PackageListDeployedResp](rt, ctx, topic, handler)
}

// PublishPackageRedeploy publishes a PackageRedeployMsg and returns routing info for the response.
func PublishPackageRedeploy(rt Runtime, ctx context.Context, msg messages.PackageRedeployMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePackageRedeployResp subscribes to the response topic for a PackageRedeployMsg command.
func SubscribePackageRedeployResp(rt Runtime, ctx context.Context, topic string, handler func(messages.PackageRedeployResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PackageRedeployResp](rt, ctx, topic, handler)
}

// PublishPackageTeardown publishes a PackageTeardownMsg and returns routing info for the response.
func PublishPackageTeardown(rt Runtime, ctx context.Context, msg messages.PackageTeardownMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePackageTeardownResp subscribes to the response topic for a PackageTeardownMsg command.
func SubscribePackageTeardownResp(rt Runtime, ctx context.Context, topic string, handler func(messages.PackageTeardownResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PackageTeardownResp](rt, ctx, topic, handler)
}

// PublishPackagesInfo publishes a PackagesInfoMsg and returns routing info for the response.
func PublishPackagesInfo(rt Runtime, ctx context.Context, msg messages.PackagesInfoMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePackagesInfoResp subscribes to the response topic for a PackagesInfoMsg command.
func SubscribePackagesInfoResp(rt Runtime, ctx context.Context, topic string, handler func(messages.PackagesInfoResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PackagesInfoResp](rt, ctx, topic, handler)
}

// PublishPackagesInstall publishes a PackagesInstallMsg and returns routing info for the response.
func PublishPackagesInstall(rt Runtime, ctx context.Context, msg messages.PackagesInstallMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePackagesInstallResp subscribes to the response topic for a PackagesInstallMsg command.
func SubscribePackagesInstallResp(rt Runtime, ctx context.Context, topic string, handler func(messages.PackagesInstallResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PackagesInstallResp](rt, ctx, topic, handler)
}

// PublishPackagesList publishes a PackagesListMsg and returns routing info for the response.
func PublishPackagesList(rt Runtime, ctx context.Context, msg messages.PackagesListMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePackagesListResp subscribes to the response topic for a PackagesListMsg command.
func SubscribePackagesListResp(rt Runtime, ctx context.Context, topic string, handler func(messages.PackagesListResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PackagesListResp](rt, ctx, topic, handler)
}

// PublishPackagesRemove publishes a PackagesRemoveMsg and returns routing info for the response.
func PublishPackagesRemove(rt Runtime, ctx context.Context, msg messages.PackagesRemoveMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePackagesRemoveResp subscribes to the response topic for a PackagesRemoveMsg command.
func SubscribePackagesRemoveResp(rt Runtime, ctx context.Context, topic string, handler func(messages.PackagesRemoveResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PackagesRemoveResp](rt, ctx, topic, handler)
}

// PublishPackagesSearch publishes a PackagesSearchMsg and returns routing info for the response.
func PublishPackagesSearch(rt Runtime, ctx context.Context, msg messages.PackagesSearchMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePackagesSearchResp subscribes to the response topic for a PackagesSearchMsg command.
func SubscribePackagesSearchResp(rt Runtime, ctx context.Context, topic string, handler func(messages.PackagesSearchResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PackagesSearchResp](rt, ctx, topic, handler)
}

// PublishPackagesUpdate publishes a PackagesUpdateMsg and returns routing info for the response.
func PublishPackagesUpdate(rt Runtime, ctx context.Context, msg messages.PackagesUpdateMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePackagesUpdateResp subscribes to the response topic for a PackagesUpdateMsg command.
func SubscribePackagesUpdateResp(rt Runtime, ctx context.Context, topic string, handler func(messages.PackagesUpdateResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PackagesUpdateResp](rt, ctx, topic, handler)
}

// PublishPeersList publishes a PeersListMsg and returns routing info for the response.
func PublishPeersList(rt Runtime, ctx context.Context, msg messages.PeersListMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePeersListResp subscribes to the response topic for a PeersListMsg command.
func SubscribePeersListResp(rt Runtime, ctx context.Context, topic string, handler func(messages.PeersListResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PeersListResp](rt, ctx, topic, handler)
}

// PublishPeersResolve publishes a PeersResolveMsg and returns routing info for the response.
func PublishPeersResolve(rt Runtime, ctx context.Context, msg messages.PeersResolveMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePeersResolveResp subscribes to the response topic for a PeersResolveMsg command.
func SubscribePeersResolveResp(rt Runtime, ctx context.Context, topic string, handler func(messages.PeersResolveResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PeersResolveResp](rt, ctx, topic, handler)
}

// PublishPluginListRunning publishes a PluginListRunningMsg and returns routing info for the response.
func PublishPluginListRunning(rt Runtime, ctx context.Context, msg messages.PluginListRunningMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePluginListRunningResp subscribes to the response topic for a PluginListRunningMsg command.
func SubscribePluginListRunningResp(rt Runtime, ctx context.Context, topic string, handler func(messages.PluginListRunningResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PluginListRunningResp](rt, ctx, topic, handler)
}

// PublishPluginManifest publishes a PluginManifestMsg and returns routing info for the response.
func PublishPluginManifest(rt Runtime, ctx context.Context, msg messages.PluginManifestMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePluginManifestResp subscribes to the response topic for a PluginManifestMsg command.
func SubscribePluginManifestResp(rt Runtime, ctx context.Context, topic string, handler func(messages.PluginManifestResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PluginManifestResp](rt, ctx, topic, handler)
}

// PublishPluginRestart publishes a PluginRestartMsg and returns routing info for the response.
func PublishPluginRestart(rt Runtime, ctx context.Context, msg messages.PluginRestartMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePluginRestartResp subscribes to the response topic for a PluginRestartMsg command.
func SubscribePluginRestartResp(rt Runtime, ctx context.Context, topic string, handler func(messages.PluginRestartResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PluginRestartResp](rt, ctx, topic, handler)
}

// PublishPluginStart publishes a PluginStartMsg and returns routing info for the response.
func PublishPluginStart(rt Runtime, ctx context.Context, msg messages.PluginStartMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePluginStartResp subscribes to the response topic for a PluginStartMsg command.
func SubscribePluginStartResp(rt Runtime, ctx context.Context, topic string, handler func(messages.PluginStartResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PluginStartResp](rt, ctx, topic, handler)
}

// PublishPluginStateGet publishes a PluginStateGetMsg and returns routing info for the response.
func PublishPluginStateGet(rt Runtime, ctx context.Context, msg messages.PluginStateGetMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePluginStateGetResp subscribes to the response topic for a PluginStateGetMsg command.
func SubscribePluginStateGetResp(rt Runtime, ctx context.Context, topic string, handler func(messages.PluginStateGetResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PluginStateGetResp](rt, ctx, topic, handler)
}

// PublishPluginStateSet publishes a PluginStateSetMsg and returns routing info for the response.
func PublishPluginStateSet(rt Runtime, ctx context.Context, msg messages.PluginStateSetMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePluginStateSetResp subscribes to the response topic for a PluginStateSetMsg command.
func SubscribePluginStateSetResp(rt Runtime, ctx context.Context, topic string, handler func(messages.PluginStateSetResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PluginStateSetResp](rt, ctx, topic, handler)
}

// PublishPluginStatus publishes a PluginStatusMsg and returns routing info for the response.
func PublishPluginStatus(rt Runtime, ctx context.Context, msg messages.PluginStatusMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePluginStatusResp subscribes to the response topic for a PluginStatusMsg command.
func SubscribePluginStatusResp(rt Runtime, ctx context.Context, topic string, handler func(messages.PluginStatusResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PluginStatusResp](rt, ctx, topic, handler)
}

// PublishPluginStop publishes a PluginStopMsg and returns routing info for the response.
func PublishPluginStop(rt Runtime, ctx context.Context, msg messages.PluginStopMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePluginStopResp subscribes to the response topic for a PluginStopMsg command.
func SubscribePluginStopResp(rt Runtime, ctx context.Context, topic string, handler func(messages.PluginStopResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PluginStopResp](rt, ctx, topic, handler)
}

// PublishRBACAssign publishes a RBACAssignMsg and returns routing info for the response.
func PublishRBACAssign(rt Runtime, ctx context.Context, msg messages.RBACAssignMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeRBACAssignResp subscribes to the response topic for a RBACAssignMsg command.
func SubscribeRBACAssignResp(rt Runtime, ctx context.Context, topic string, handler func(messages.RBACAssignResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.RBACAssignResp](rt, ctx, topic, handler)
}

// PublishRBACList publishes a RBACListMsg and returns routing info for the response.
func PublishRBACList(rt Runtime, ctx context.Context, msg messages.RBACListMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeRBACListResp subscribes to the response topic for a RBACListMsg command.
func SubscribeRBACListResp(rt Runtime, ctx context.Context, topic string, handler func(messages.RBACListResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.RBACListResp](rt, ctx, topic, handler)
}

// PublishRBACRevoke publishes a RBACRevokeMsg and returns routing info for the response.
func PublishRBACRevoke(rt Runtime, ctx context.Context, msg messages.RBACRevokeMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeRBACRevokeResp subscribes to the response topic for a RBACRevokeMsg command.
func SubscribeRBACRevokeResp(rt Runtime, ctx context.Context, topic string, handler func(messages.RBACRevokeResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.RBACRevokeResp](rt, ctx, topic, handler)
}

// PublishRBACRoles publishes a RBACRolesMsg and returns routing info for the response.
func PublishRBACRoles(rt Runtime, ctx context.Context, msg messages.RBACRolesMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeRBACRolesResp subscribes to the response topic for a RBACRolesMsg command.
func SubscribeRBACRolesResp(rt Runtime, ctx context.Context, topic string, handler func(messages.RBACRolesResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.RBACRolesResp](rt, ctx, topic, handler)
}

// PublishRegistryHas publishes a RegistryHasMsg and returns routing info for the response.
func PublishRegistryHas(rt Runtime, ctx context.Context, msg messages.RegistryHasMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeRegistryHasResp subscribes to the response topic for a RegistryHasMsg command.
func SubscribeRegistryHasResp(rt Runtime, ctx context.Context, topic string, handler func(messages.RegistryHasResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.RegistryHasResp](rt, ctx, topic, handler)
}

// PublishRegistryList publishes a RegistryListMsg and returns routing info for the response.
func PublishRegistryList(rt Runtime, ctx context.Context, msg messages.RegistryListMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeRegistryListResp subscribes to the response topic for a RegistryListMsg command.
func SubscribeRegistryListResp(rt Runtime, ctx context.Context, topic string, handler func(messages.RegistryListResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.RegistryListResp](rt, ctx, topic, handler)
}

// PublishRegistryResolve publishes a RegistryResolveMsg and returns routing info for the response.
func PublishRegistryResolve(rt Runtime, ctx context.Context, msg messages.RegistryResolveMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeRegistryResolveResp subscribes to the response topic for a RegistryResolveMsg command.
func SubscribeRegistryResolveResp(rt Runtime, ctx context.Context, topic string, handler func(messages.RegistryResolveResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.RegistryResolveResp](rt, ctx, topic, handler)
}

// PublishSecretsDelete publishes a SecretsDeleteMsg and returns routing info for the response.
func PublishSecretsDelete(rt Runtime, ctx context.Context, msg messages.SecretsDeleteMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeSecretsDeleteResp subscribes to the response topic for a SecretsDeleteMsg command.
func SubscribeSecretsDeleteResp(rt Runtime, ctx context.Context, topic string, handler func(messages.SecretsDeleteResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.SecretsDeleteResp](rt, ctx, topic, handler)
}

// PublishSecretsGet publishes a SecretsGetMsg and returns routing info for the response.
func PublishSecretsGet(rt Runtime, ctx context.Context, msg messages.SecretsGetMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeSecretsGetResp subscribes to the response topic for a SecretsGetMsg command.
func SubscribeSecretsGetResp(rt Runtime, ctx context.Context, topic string, handler func(messages.SecretsGetResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.SecretsGetResp](rt, ctx, topic, handler)
}

// PublishSecretsList publishes a SecretsListMsg and returns routing info for the response.
func PublishSecretsList(rt Runtime, ctx context.Context, msg messages.SecretsListMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeSecretsListResp subscribes to the response topic for a SecretsListMsg command.
func SubscribeSecretsListResp(rt Runtime, ctx context.Context, topic string, handler func(messages.SecretsListResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.SecretsListResp](rt, ctx, topic, handler)
}

// PublishSecretsRotate publishes a SecretsRotateMsg and returns routing info for the response.
func PublishSecretsRotate(rt Runtime, ctx context.Context, msg messages.SecretsRotateMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeSecretsRotateResp subscribes to the response topic for a SecretsRotateMsg command.
func SubscribeSecretsRotateResp(rt Runtime, ctx context.Context, topic string, handler func(messages.SecretsRotateResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.SecretsRotateResp](rt, ctx, topic, handler)
}

// PublishSecretsSet publishes a SecretsSetMsg and returns routing info for the response.
func PublishSecretsSet(rt Runtime, ctx context.Context, msg messages.SecretsSetMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeSecretsSetResp subscribes to the response topic for a SecretsSetMsg command.
func SubscribeSecretsSetResp(rt Runtime, ctx context.Context, topic string, handler func(messages.SecretsSetResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.SecretsSetResp](rt, ctx, topic, handler)
}

// PublishTestRun publishes a TestRunMsg and returns routing info for the response.
func PublishTestRun(rt Runtime, ctx context.Context, msg messages.TestRunMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeTestRunResp subscribes to the response topic for a TestRunMsg command.
func SubscribeTestRunResp(rt Runtime, ctx context.Context, topic string, handler func(messages.TestRunResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.TestRunResp](rt, ctx, topic, handler)
}

// PublishToolCall publishes a ToolCallMsg and returns routing info for the response.
func PublishToolCall(rt Runtime, ctx context.Context, msg messages.ToolCallMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeToolCallResp subscribes to the response topic for a ToolCallMsg command.
func SubscribeToolCallResp(rt Runtime, ctx context.Context, topic string, handler func(messages.ToolCallResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.ToolCallResp](rt, ctx, topic, handler)
}

// PublishToolList publishes a ToolListMsg and returns routing info for the response.
func PublishToolList(rt Runtime, ctx context.Context, msg messages.ToolListMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeToolListResp subscribes to the response topic for a ToolListMsg command.
func SubscribeToolListResp(rt Runtime, ctx context.Context, topic string, handler func(messages.ToolListResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.ToolListResp](rt, ctx, topic, handler)
}

// PublishToolResolve publishes a ToolResolveMsg and returns routing info for the response.
func PublishToolResolve(rt Runtime, ctx context.Context, msg messages.ToolResolveMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeToolResolveResp subscribes to the response topic for a ToolResolveMsg command.
func SubscribeToolResolveResp(rt Runtime, ctx context.Context, topic string, handler func(messages.ToolResolveResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.ToolResolveResp](rt, ctx, topic, handler)
}

// PublishTraceGet publishes a TraceGetMsg and returns routing info for the response.
func PublishTraceGet(rt Runtime, ctx context.Context, msg messages.TraceGetMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeTraceGetResp subscribes to the response topic for a TraceGetMsg command.
func SubscribeTraceGetResp(rt Runtime, ctx context.Context, topic string, handler func(messages.TraceGetResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.TraceGetResp](rt, ctx, topic, handler)
}

// PublishTraceList publishes a TraceListMsg and returns routing info for the response.
func PublishTraceList(rt Runtime, ctx context.Context, msg messages.TraceListMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeTraceListResp subscribes to the response topic for a TraceListMsg command.
func SubscribeTraceListResp(rt Runtime, ctx context.Context, topic string, handler func(messages.TraceListResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.TraceListResp](rt, ctx, topic, handler)
}

// PublishWorkflowCancel publishes a WorkflowCancelMsg and returns routing info for the response.
func PublishWorkflowCancel(rt Runtime, ctx context.Context, msg messages.WorkflowCancelMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeWorkflowCancelResp subscribes to the response topic for a WorkflowCancelMsg command.
func SubscribeWorkflowCancelResp(rt Runtime, ctx context.Context, topic string, handler func(messages.WorkflowCancelResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.WorkflowCancelResp](rt, ctx, topic, handler)
}

// PublishWorkflowList publishes a WorkflowListMsg and returns routing info for the response.
func PublishWorkflowList(rt Runtime, ctx context.Context, msg messages.WorkflowListMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeWorkflowListResp subscribes to the response topic for a WorkflowListMsg command.
func SubscribeWorkflowListResp(rt Runtime, ctx context.Context, topic string, handler func(messages.WorkflowListResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.WorkflowListResp](rt, ctx, topic, handler)
}

// PublishWorkflowRestart publishes a WorkflowRestartMsg and returns routing info for the response.
func PublishWorkflowRestart(rt Runtime, ctx context.Context, msg messages.WorkflowRestartMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeWorkflowRestartResp subscribes to the response topic for a WorkflowRestartMsg command.
func SubscribeWorkflowRestartResp(rt Runtime, ctx context.Context, topic string, handler func(messages.WorkflowRestartResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.WorkflowRestartResp](rt, ctx, topic, handler)
}

// PublishWorkflowResume publishes a WorkflowResumeMsg and returns routing info for the response.
func PublishWorkflowResume(rt Runtime, ctx context.Context, msg messages.WorkflowResumeMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeWorkflowResumeResp subscribes to the response topic for a WorkflowResumeMsg command.
func SubscribeWorkflowResumeResp(rt Runtime, ctx context.Context, topic string, handler func(messages.WorkflowResumeResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.WorkflowResumeResp](rt, ctx, topic, handler)
}

// PublishWorkflowRuns publishes a WorkflowRunsMsg and returns routing info for the response.
func PublishWorkflowRuns(rt Runtime, ctx context.Context, msg messages.WorkflowRunsMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeWorkflowRunsResp subscribes to the response topic for a WorkflowRunsMsg command.
func SubscribeWorkflowRunsResp(rt Runtime, ctx context.Context, topic string, handler func(messages.WorkflowRunsResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.WorkflowRunsResp](rt, ctx, topic, handler)
}

// PublishWorkflowStart publishes a WorkflowStartMsg and returns routing info for the response.
func PublishWorkflowStart(rt Runtime, ctx context.Context, msg messages.WorkflowStartMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeWorkflowStartResp subscribes to the response topic for a WorkflowStartMsg command.
func SubscribeWorkflowStartResp(rt Runtime, ctx context.Context, topic string, handler func(messages.WorkflowStartResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.WorkflowStartResp](rt, ctx, topic, handler)
}

// PublishWorkflowStartAsync publishes a WorkflowStartAsyncMsg and returns routing info for the response.
func PublishWorkflowStartAsync(rt Runtime, ctx context.Context, msg messages.WorkflowStartAsyncMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeWorkflowStartAsyncResp subscribes to the response topic for a WorkflowStartAsyncMsg command.
func SubscribeWorkflowStartAsyncResp(rt Runtime, ctx context.Context, topic string, handler func(messages.WorkflowStartAsyncResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.WorkflowStartAsyncResp](rt, ctx, topic, handler)
}

// PublishWorkflowStatus publishes a WorkflowStatusMsg and returns routing info for the response.
func PublishWorkflowStatus(rt Runtime, ctx context.Context, msg messages.WorkflowStatusMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeWorkflowStatusResp subscribes to the response topic for a WorkflowStatusMsg command.
func SubscribeWorkflowStatusResp(rt Runtime, ctx context.Context, topic string, handler func(messages.WorkflowStatusResp, messages.Message)) (func(), error) {
	return SubscribeTo[messages.WorkflowStatusResp](rt, ctx, topic, handler)
}

// EmitHandlerExhausted fires a HandlerExhaustedEvent event (no response expected).
func EmitHandlerExhausted(rt Runtime, ctx context.Context, msg messages.HandlerExhaustedEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribeHandlerExhausted listens for HandlerExhaustedEvent events.
func SubscribeHandlerExhausted(rt Runtime, ctx context.Context, topic string, handler func(messages.HandlerExhaustedEvent, messages.Message)) (func(), error) {
	return SubscribeTo[messages.HandlerExhaustedEvent](rt, ctx, topic, handler)
}

// EmitHandlerFailed fires a HandlerFailedEvent event (no response expected).
func EmitHandlerFailed(rt Runtime, ctx context.Context, msg messages.HandlerFailedEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribeHandlerFailed listens for HandlerFailedEvent events.
func SubscribeHandlerFailed(rt Runtime, ctx context.Context, topic string, handler func(messages.HandlerFailedEvent, messages.Message)) (func(), error) {
	return SubscribeTo[messages.HandlerFailedEvent](rt, ctx, topic, handler)
}

// EmitKitDeployed fires a KitDeployedEvent event (no response expected).
func EmitKitDeployed(rt Runtime, ctx context.Context, msg messages.KitDeployedEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribeKitDeployed listens for KitDeployedEvent events.
func SubscribeKitDeployed(rt Runtime, ctx context.Context, topic string, handler func(messages.KitDeployedEvent, messages.Message)) (func(), error) {
	return SubscribeTo[messages.KitDeployedEvent](rt, ctx, topic, handler)
}

// EmitKitTeardowned fires a KitTeardownedEvent event (no response expected).
func EmitKitTeardowned(rt Runtime, ctx context.Context, msg messages.KitTeardownedEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribeKitTeardowned listens for KitTeardownedEvent events.
func SubscribeKitTeardowned(rt Runtime, ctx context.Context, topic string, handler func(messages.KitTeardownedEvent, messages.Message)) (func(), error) {
	return SubscribeTo[messages.KitTeardownedEvent](rt, ctx, topic, handler)
}

// EmitPermissionDenied fires a PermissionDeniedEvent event (no response expected).
func EmitPermissionDenied(rt Runtime, ctx context.Context, msg messages.PermissionDeniedEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribePermissionDenied listens for PermissionDeniedEvent events.
func SubscribePermissionDenied(rt Runtime, ctx context.Context, topic string, handler func(messages.PermissionDeniedEvent, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PermissionDeniedEvent](rt, ctx, topic, handler)
}

// EmitPluginRegistered fires a PluginRegisteredEvent event (no response expected).
func EmitPluginRegistered(rt Runtime, ctx context.Context, msg messages.PluginRegisteredEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribePluginRegistered listens for PluginRegisteredEvent events.
func SubscribePluginRegistered(rt Runtime, ctx context.Context, topic string, handler func(messages.PluginRegisteredEvent, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PluginRegisteredEvent](rt, ctx, topic, handler)
}

// EmitPluginStarted fires a PluginStartedEvent event (no response expected).
func EmitPluginStarted(rt Runtime, ctx context.Context, msg messages.PluginStartedEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribePluginStarted listens for PluginStartedEvent events.
func SubscribePluginStarted(rt Runtime, ctx context.Context, topic string, handler func(messages.PluginStartedEvent, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PluginStartedEvent](rt, ctx, topic, handler)
}

// EmitPluginStopped fires a PluginStoppedEvent event (no response expected).
func EmitPluginStopped(rt Runtime, ctx context.Context, msg messages.PluginStoppedEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribePluginStopped listens for PluginStoppedEvent events.
func SubscribePluginStopped(rt Runtime, ctx context.Context, topic string, handler func(messages.PluginStoppedEvent, messages.Message)) (func(), error) {
	return SubscribeTo[messages.PluginStoppedEvent](rt, ctx, topic, handler)
}

// EmitReplyDenied fires a ReplyDeniedEvent event (no response expected).
func EmitReplyDenied(rt Runtime, ctx context.Context, msg messages.ReplyDeniedEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribeReplyDenied listens for ReplyDeniedEvent events.
func SubscribeReplyDenied(rt Runtime, ctx context.Context, topic string, handler func(messages.ReplyDeniedEvent, messages.Message)) (func(), error) {
	return SubscribeTo[messages.ReplyDeniedEvent](rt, ctx, topic, handler)
}

// EmitSecretsAccessed fires a SecretsAccessedEvent event (no response expected).
func EmitSecretsAccessed(rt Runtime, ctx context.Context, msg messages.SecretsAccessedEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribeSecretsAccessed listens for SecretsAccessedEvent events.
func SubscribeSecretsAccessed(rt Runtime, ctx context.Context, topic string, handler func(messages.SecretsAccessedEvent, messages.Message)) (func(), error) {
	return SubscribeTo[messages.SecretsAccessedEvent](rt, ctx, topic, handler)
}

// EmitSecretsDeleted fires a SecretsDeletedEvent event (no response expected).
func EmitSecretsDeleted(rt Runtime, ctx context.Context, msg messages.SecretsDeletedEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribeSecretsDeleted listens for SecretsDeletedEvent events.
func SubscribeSecretsDeleted(rt Runtime, ctx context.Context, topic string, handler func(messages.SecretsDeletedEvent, messages.Message)) (func(), error) {
	return SubscribeTo[messages.SecretsDeletedEvent](rt, ctx, topic, handler)
}

// EmitSecretsRotated fires a SecretsRotatedEvent event (no response expected).
func EmitSecretsRotated(rt Runtime, ctx context.Context, msg messages.SecretsRotatedEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribeSecretsRotated listens for SecretsRotatedEvent events.
func SubscribeSecretsRotated(rt Runtime, ctx context.Context, topic string, handler func(messages.SecretsRotatedEvent, messages.Message)) (func(), error) {
	return SubscribeTo[messages.SecretsRotatedEvent](rt, ctx, topic, handler)
}

// EmitSecretsStored fires a SecretsStoredEvent event (no response expected).
func EmitSecretsStored(rt Runtime, ctx context.Context, msg messages.SecretsStoredEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribeSecretsStored listens for SecretsStoredEvent events.
func SubscribeSecretsStored(rt Runtime, ctx context.Context, topic string, handler func(messages.SecretsStoredEvent, messages.Message)) (func(), error) {
	return SubscribeTo[messages.SecretsStoredEvent](rt, ctx, topic, handler)
}

