// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for sdk.Publish/SubscribeTo/Emit.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// The underlying async pub/sub pattern is unchanged — callers still manage
// channels, select, and timeouts. These wrappers just add type safety.
//
// Regenerate: go run ./cmd/sdkgen/ -messages ./sdk -out ./sdk/typed_gen.go
package sdk

import "context"

// PublishAgentDiscover publishes a AgentDiscoverMsg and returns routing info for the response.
func PublishAgentDiscover(rt Runtime, ctx context.Context, msg AgentDiscoverMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeAgentDiscoverResp subscribes to the response topic for a AgentDiscoverMsg command.
func SubscribeAgentDiscoverResp(rt Runtime, ctx context.Context, topic string, handler func(AgentDiscoverResp, Message)) (func(), error) {
	return SubscribeTo[AgentDiscoverResp](rt, ctx, topic, handler)
}

// PublishAgentGetStatus publishes a AgentGetStatusMsg and returns routing info for the response.
func PublishAgentGetStatus(rt Runtime, ctx context.Context, msg AgentGetStatusMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeAgentGetStatusResp subscribes to the response topic for a AgentGetStatusMsg command.
func SubscribeAgentGetStatusResp(rt Runtime, ctx context.Context, topic string, handler func(AgentGetStatusResp, Message)) (func(), error) {
	return SubscribeTo[AgentGetStatusResp](rt, ctx, topic, handler)
}

// PublishAgentList publishes a AgentListMsg and returns routing info for the response.
func PublishAgentList(rt Runtime, ctx context.Context, msg AgentListMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeAgentListResp subscribes to the response topic for a AgentListMsg command.
func SubscribeAgentListResp(rt Runtime, ctx context.Context, topic string, handler func(AgentListResp, Message)) (func(), error) {
	return SubscribeTo[AgentListResp](rt, ctx, topic, handler)
}

// PublishAgentSetStatus publishes a AgentSetStatusMsg and returns routing info for the response.
func PublishAgentSetStatus(rt Runtime, ctx context.Context, msg AgentSetStatusMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeAgentSetStatusResp subscribes to the response topic for a AgentSetStatusMsg command.
func SubscribeAgentSetStatusResp(rt Runtime, ctx context.Context, topic string, handler func(AgentSetStatusResp, Message)) (func(), error) {
	return SubscribeTo[AgentSetStatusResp](rt, ctx, topic, handler)
}

// PublishClusterPeers publishes a ClusterPeersMsg and returns routing info for the response.
func PublishClusterPeers(rt Runtime, ctx context.Context, msg ClusterPeersMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeClusterPeersResp subscribes to the response topic for a ClusterPeersMsg command.
func SubscribeClusterPeersResp(rt Runtime, ctx context.Context, topic string, handler func(ClusterPeersResp, Message)) (func(), error) {
	return SubscribeTo[ClusterPeersResp](rt, ctx, topic, handler)
}

// PublishGatewayRouteAdd publishes a GatewayRouteAddMsg and returns routing info for the response.
func PublishGatewayRouteAdd(rt Runtime, ctx context.Context, msg GatewayRouteAddMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeGatewayRouteAddResp subscribes to the response topic for a GatewayRouteAddMsg command.
func SubscribeGatewayRouteAddResp(rt Runtime, ctx context.Context, topic string, handler func(GatewayRouteAddResp, Message)) (func(), error) {
	return SubscribeTo[GatewayRouteAddResp](rt, ctx, topic, handler)
}

// PublishGatewayRouteList publishes a GatewayRouteListMsg and returns routing info for the response.
func PublishGatewayRouteList(rt Runtime, ctx context.Context, msg GatewayRouteListMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeGatewayRouteListResp subscribes to the response topic for a GatewayRouteListMsg command.
func SubscribeGatewayRouteListResp(rt Runtime, ctx context.Context, topic string, handler func(GatewayRouteListResp, Message)) (func(), error) {
	return SubscribeTo[GatewayRouteListResp](rt, ctx, topic, handler)
}

// PublishGatewayRouteRemove publishes a GatewayRouteRemoveMsg and returns routing info for the response.
func PublishGatewayRouteRemove(rt Runtime, ctx context.Context, msg GatewayRouteRemoveMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeGatewayRouteRemoveResp subscribes to the response topic for a GatewayRouteRemoveMsg command.
func SubscribeGatewayRouteRemoveResp(rt Runtime, ctx context.Context, topic string, handler func(GatewayRouteRemoveResp, Message)) (func(), error) {
	return SubscribeTo[GatewayRouteRemoveResp](rt, ctx, topic, handler)
}

// PublishGatewayStatus publishes a GatewayStatusMsg and returns routing info for the response.
func PublishGatewayStatus(rt Runtime, ctx context.Context, msg GatewayStatusMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeGatewayStatusResp subscribes to the response topic for a GatewayStatusMsg command.
func SubscribeGatewayStatusResp(rt Runtime, ctx context.Context, topic string, handler func(GatewayStatusResp, Message)) (func(), error) {
	return SubscribeTo[GatewayStatusResp](rt, ctx, topic, handler)
}

// PublishKitDeploy publishes a KitDeployMsg and returns routing info for the response.
func PublishKitDeploy(rt Runtime, ctx context.Context, msg KitDeployMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeKitDeployResp subscribes to the response topic for a KitDeployMsg command.
func SubscribeKitDeployResp(rt Runtime, ctx context.Context, topic string, handler func(KitDeployResp, Message)) (func(), error) {
	return SubscribeTo[KitDeployResp](rt, ctx, topic, handler)
}

// PublishKitDeployFile publishes a KitDeployFileMsg and returns routing info for the response.
func PublishKitDeployFile(rt Runtime, ctx context.Context, msg KitDeployFileMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// PublishKitEval publishes a KitEvalMsg and returns routing info for the response.
func PublishKitEval(rt Runtime, ctx context.Context, msg KitEvalMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeKitEvalResp subscribes to the response topic for a KitEvalMsg command.
func SubscribeKitEvalResp(rt Runtime, ctx context.Context, topic string, handler func(KitEvalResp, Message)) (func(), error) {
	return SubscribeTo[KitEvalResp](rt, ctx, topic, handler)
}

// PublishKitEvalModule publishes a KitEvalModuleMsg and returns routing info for the response.
func PublishKitEvalModule(rt Runtime, ctx context.Context, msg KitEvalModuleMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeKitEvalModuleResp subscribes to the response topic for a KitEvalModuleMsg command.
func SubscribeKitEvalModuleResp(rt Runtime, ctx context.Context, topic string, handler func(KitEvalModuleResp, Message)) (func(), error) {
	return SubscribeTo[KitEvalModuleResp](rt, ctx, topic, handler)
}

// PublishKitEvalTS publishes a KitEvalTSMsg and returns routing info for the response.
func PublishKitEvalTS(rt Runtime, ctx context.Context, msg KitEvalTSMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeKitEvalTSResp subscribes to the response topic for a KitEvalTSMsg command.
func SubscribeKitEvalTSResp(rt Runtime, ctx context.Context, topic string, handler func(KitEvalTSResp, Message)) (func(), error) {
	return SubscribeTo[KitEvalTSResp](rt, ctx, topic, handler)
}

// PublishKitHealth publishes a KitHealthMsg and returns routing info for the response.
func PublishKitHealth(rt Runtime, ctx context.Context, msg KitHealthMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeKitHealthResp subscribes to the response topic for a KitHealthMsg command.
func SubscribeKitHealthResp(rt Runtime, ctx context.Context, topic string, handler func(KitHealthResp, Message)) (func(), error) {
	return SubscribeTo[KitHealthResp](rt, ctx, topic, handler)
}

// PublishKitList publishes a KitListMsg and returns routing info for the response.
func PublishKitList(rt Runtime, ctx context.Context, msg KitListMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeKitListResp subscribes to the response topic for a KitListMsg command.
func SubscribeKitListResp(rt Runtime, ctx context.Context, topic string, handler func(KitListResp, Message)) (func(), error) {
	return SubscribeTo[KitListResp](rt, ctx, topic, handler)
}

// PublishKitRedeploy publishes a KitRedeployMsg and returns routing info for the response.
func PublishKitRedeploy(rt Runtime, ctx context.Context, msg KitRedeployMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeKitRedeployResp subscribes to the response topic for a KitRedeployMsg command.
func SubscribeKitRedeployResp(rt Runtime, ctx context.Context, topic string, handler func(KitRedeployResp, Message)) (func(), error) {
	return SubscribeTo[KitRedeployResp](rt, ctx, topic, handler)
}

// PublishKitSend publishes a KitSendMsg and returns routing info for the response.
func PublishKitSend(rt Runtime, ctx context.Context, msg KitSendMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeKitSendResp subscribes to the response topic for a KitSendMsg command.
func SubscribeKitSendResp(rt Runtime, ctx context.Context, topic string, handler func(KitSendResp, Message)) (func(), error) {
	return SubscribeTo[KitSendResp](rt, ctx, topic, handler)
}

// PublishKitSetDraining publishes a KitSetDrainingMsg and returns routing info for the response.
func PublishKitSetDraining(rt Runtime, ctx context.Context, msg KitSetDrainingMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeKitSetDrainingResp subscribes to the response topic for a KitSetDrainingMsg command.
func SubscribeKitSetDrainingResp(rt Runtime, ctx context.Context, topic string, handler func(KitSetDrainingResp, Message)) (func(), error) {
	return SubscribeTo[KitSetDrainingResp](rt, ctx, topic, handler)
}

// PublishKitTeardown publishes a KitTeardownMsg and returns routing info for the response.
func PublishKitTeardown(rt Runtime, ctx context.Context, msg KitTeardownMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeKitTeardownResp subscribes to the response topic for a KitTeardownMsg command.
func SubscribeKitTeardownResp(rt Runtime, ctx context.Context, topic string, handler func(KitTeardownResp, Message)) (func(), error) {
	return SubscribeTo[KitTeardownResp](rt, ctx, topic, handler)
}

// PublishMcpCallTool publishes a McpCallToolMsg and returns routing info for the response.
func PublishMcpCallTool(rt Runtime, ctx context.Context, msg McpCallToolMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeMcpCallToolResp subscribes to the response topic for a McpCallToolMsg command.
func SubscribeMcpCallToolResp(rt Runtime, ctx context.Context, topic string, handler func(McpCallToolResp, Message)) (func(), error) {
	return SubscribeTo[McpCallToolResp](rt, ctx, topic, handler)
}

// PublishMcpListTools publishes a McpListToolsMsg and returns routing info for the response.
func PublishMcpListTools(rt Runtime, ctx context.Context, msg McpListToolsMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeMcpListToolsResp subscribes to the response topic for a McpListToolsMsg command.
func SubscribeMcpListToolsResp(rt Runtime, ctx context.Context, topic string, handler func(McpListToolsResp, Message)) (func(), error) {
	return SubscribeTo[McpListToolsResp](rt, ctx, topic, handler)
}

// PublishMetricsGet publishes a MetricsGetMsg and returns routing info for the response.
func PublishMetricsGet(rt Runtime, ctx context.Context, msg MetricsGetMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeMetricsGetResp subscribes to the response topic for a MetricsGetMsg command.
func SubscribeMetricsGetResp(rt Runtime, ctx context.Context, topic string, handler func(MetricsGetResp, Message)) (func(), error) {
	return SubscribeTo[MetricsGetResp](rt, ctx, topic, handler)
}

// PublishPackageDeploy publishes a PackageDeployMsg and returns routing info for the response.
func PublishPackageDeploy(rt Runtime, ctx context.Context, msg PackageDeployMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePackageDeployResp subscribes to the response topic for a PackageDeployMsg command.
func SubscribePackageDeployResp(rt Runtime, ctx context.Context, topic string, handler func(PackageDeployResp, Message)) (func(), error) {
	return SubscribeTo[PackageDeployResp](rt, ctx, topic, handler)
}

// PublishPackageDeployInfo publishes a PackageDeployInfoMsg and returns routing info for the response.
func PublishPackageDeployInfo(rt Runtime, ctx context.Context, msg PackageDeployInfoMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePackageDeployInfoResp subscribes to the response topic for a PackageDeployInfoMsg command.
func SubscribePackageDeployInfoResp(rt Runtime, ctx context.Context, topic string, handler func(PackageDeployInfoResp, Message)) (func(), error) {
	return SubscribeTo[PackageDeployInfoResp](rt, ctx, topic, handler)
}

// PublishPackageListDeployed publishes a PackageListDeployedMsg and returns routing info for the response.
func PublishPackageListDeployed(rt Runtime, ctx context.Context, msg PackageListDeployedMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePackageListDeployedResp subscribes to the response topic for a PackageListDeployedMsg command.
func SubscribePackageListDeployedResp(rt Runtime, ctx context.Context, topic string, handler func(PackageListDeployedResp, Message)) (func(), error) {
	return SubscribeTo[PackageListDeployedResp](rt, ctx, topic, handler)
}

// PublishPackageTeardown publishes a PackageTeardownMsg and returns routing info for the response.
func PublishPackageTeardown(rt Runtime, ctx context.Context, msg PackageTeardownMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePackageTeardownResp subscribes to the response topic for a PackageTeardownMsg command.
func SubscribePackageTeardownResp(rt Runtime, ctx context.Context, topic string, handler func(PackageTeardownResp, Message)) (func(), error) {
	return SubscribeTo[PackageTeardownResp](rt, ctx, topic, handler)
}

// PublishPackagesInfo publishes a PackagesInfoMsg and returns routing info for the response.
func PublishPackagesInfo(rt Runtime, ctx context.Context, msg PackagesInfoMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePackagesInfoResp subscribes to the response topic for a PackagesInfoMsg command.
func SubscribePackagesInfoResp(rt Runtime, ctx context.Context, topic string, handler func(PackagesInfoResp, Message)) (func(), error) {
	return SubscribeTo[PackagesInfoResp](rt, ctx, topic, handler)
}

// PublishPackagesInstall publishes a PackagesInstallMsg and returns routing info for the response.
func PublishPackagesInstall(rt Runtime, ctx context.Context, msg PackagesInstallMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePackagesInstallResp subscribes to the response topic for a PackagesInstallMsg command.
func SubscribePackagesInstallResp(rt Runtime, ctx context.Context, topic string, handler func(PackagesInstallResp, Message)) (func(), error) {
	return SubscribeTo[PackagesInstallResp](rt, ctx, topic, handler)
}

// PublishPackagesList publishes a PackagesListMsg and returns routing info for the response.
func PublishPackagesList(rt Runtime, ctx context.Context, msg PackagesListMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePackagesListResp subscribes to the response topic for a PackagesListMsg command.
func SubscribePackagesListResp(rt Runtime, ctx context.Context, topic string, handler func(PackagesListResp, Message)) (func(), error) {
	return SubscribeTo[PackagesListResp](rt, ctx, topic, handler)
}

// PublishPackagesRemove publishes a PackagesRemoveMsg and returns routing info for the response.
func PublishPackagesRemove(rt Runtime, ctx context.Context, msg PackagesRemoveMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePackagesRemoveResp subscribes to the response topic for a PackagesRemoveMsg command.
func SubscribePackagesRemoveResp(rt Runtime, ctx context.Context, topic string, handler func(PackagesRemoveResp, Message)) (func(), error) {
	return SubscribeTo[PackagesRemoveResp](rt, ctx, topic, handler)
}

// PublishPackagesSearch publishes a PackagesSearchMsg and returns routing info for the response.
func PublishPackagesSearch(rt Runtime, ctx context.Context, msg PackagesSearchMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePackagesSearchResp subscribes to the response topic for a PackagesSearchMsg command.
func SubscribePackagesSearchResp(rt Runtime, ctx context.Context, topic string, handler func(PackagesSearchResp, Message)) (func(), error) {
	return SubscribeTo[PackagesSearchResp](rt, ctx, topic, handler)
}

// PublishPackagesUpdate publishes a PackagesUpdateMsg and returns routing info for the response.
func PublishPackagesUpdate(rt Runtime, ctx context.Context, msg PackagesUpdateMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePackagesUpdateResp subscribes to the response topic for a PackagesUpdateMsg command.
func SubscribePackagesUpdateResp(rt Runtime, ctx context.Context, topic string, handler func(PackagesUpdateResp, Message)) (func(), error) {
	return SubscribeTo[PackagesUpdateResp](rt, ctx, topic, handler)
}

// PublishPeersList publishes a PeersListMsg and returns routing info for the response.
func PublishPeersList(rt Runtime, ctx context.Context, msg PeersListMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePeersListResp subscribes to the response topic for a PeersListMsg command.
func SubscribePeersListResp(rt Runtime, ctx context.Context, topic string, handler func(PeersListResp, Message)) (func(), error) {
	return SubscribeTo[PeersListResp](rt, ctx, topic, handler)
}

// PublishPeersResolve publishes a PeersResolveMsg and returns routing info for the response.
func PublishPeersResolve(rt Runtime, ctx context.Context, msg PeersResolveMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePeersResolveResp subscribes to the response topic for a PeersResolveMsg command.
func SubscribePeersResolveResp(rt Runtime, ctx context.Context, topic string, handler func(PeersResolveResp, Message)) (func(), error) {
	return SubscribeTo[PeersResolveResp](rt, ctx, topic, handler)
}

// PublishPluginListRunning publishes a PluginListRunningMsg and returns routing info for the response.
func PublishPluginListRunning(rt Runtime, ctx context.Context, msg PluginListRunningMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePluginListRunningResp subscribes to the response topic for a PluginListRunningMsg command.
func SubscribePluginListRunningResp(rt Runtime, ctx context.Context, topic string, handler func(PluginListRunningResp, Message)) (func(), error) {
	return SubscribeTo[PluginListRunningResp](rt, ctx, topic, handler)
}

// PublishPluginManifest publishes a PluginManifestMsg and returns routing info for the response.
func PublishPluginManifest(rt Runtime, ctx context.Context, msg PluginManifestMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePluginManifestResp subscribes to the response topic for a PluginManifestMsg command.
func SubscribePluginManifestResp(rt Runtime, ctx context.Context, topic string, handler func(PluginManifestResp, Message)) (func(), error) {
	return SubscribeTo[PluginManifestResp](rt, ctx, topic, handler)
}

// PublishPluginRestart publishes a PluginRestartMsg and returns routing info for the response.
func PublishPluginRestart(rt Runtime, ctx context.Context, msg PluginRestartMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePluginRestartResp subscribes to the response topic for a PluginRestartMsg command.
func SubscribePluginRestartResp(rt Runtime, ctx context.Context, topic string, handler func(PluginRestartResp, Message)) (func(), error) {
	return SubscribeTo[PluginRestartResp](rt, ctx, topic, handler)
}

// PublishPluginStart publishes a PluginStartMsg and returns routing info for the response.
func PublishPluginStart(rt Runtime, ctx context.Context, msg PluginStartMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePluginStartResp subscribes to the response topic for a PluginStartMsg command.
func SubscribePluginStartResp(rt Runtime, ctx context.Context, topic string, handler func(PluginStartResp, Message)) (func(), error) {
	return SubscribeTo[PluginStartResp](rt, ctx, topic, handler)
}

// PublishPluginStateGet publishes a PluginStateGetMsg and returns routing info for the response.
func PublishPluginStateGet(rt Runtime, ctx context.Context, msg PluginStateGetMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePluginStateGetResp subscribes to the response topic for a PluginStateGetMsg command.
func SubscribePluginStateGetResp(rt Runtime, ctx context.Context, topic string, handler func(PluginStateGetResp, Message)) (func(), error) {
	return SubscribeTo[PluginStateGetResp](rt, ctx, topic, handler)
}

// PublishPluginStateSet publishes a PluginStateSetMsg and returns routing info for the response.
func PublishPluginStateSet(rt Runtime, ctx context.Context, msg PluginStateSetMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePluginStateSetResp subscribes to the response topic for a PluginStateSetMsg command.
func SubscribePluginStateSetResp(rt Runtime, ctx context.Context, topic string, handler func(PluginStateSetResp, Message)) (func(), error) {
	return SubscribeTo[PluginStateSetResp](rt, ctx, topic, handler)
}

// PublishPluginStatus publishes a PluginStatusMsg and returns routing info for the response.
func PublishPluginStatus(rt Runtime, ctx context.Context, msg PluginStatusMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePluginStatusResp subscribes to the response topic for a PluginStatusMsg command.
func SubscribePluginStatusResp(rt Runtime, ctx context.Context, topic string, handler func(PluginStatusResp, Message)) (func(), error) {
	return SubscribeTo[PluginStatusResp](rt, ctx, topic, handler)
}

// PublishPluginStop publishes a PluginStopMsg and returns routing info for the response.
func PublishPluginStop(rt Runtime, ctx context.Context, msg PluginStopMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribePluginStopResp subscribes to the response topic for a PluginStopMsg command.
func SubscribePluginStopResp(rt Runtime, ctx context.Context, topic string, handler func(PluginStopResp, Message)) (func(), error) {
	return SubscribeTo[PluginStopResp](rt, ctx, topic, handler)
}

// PublishProviderAdd publishes a ProviderAddMsg and returns routing info for the response.
func PublishProviderAdd(rt Runtime, ctx context.Context, msg ProviderAddMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeProviderAddResp subscribes to the response topic for a ProviderAddMsg command.
func SubscribeProviderAddResp(rt Runtime, ctx context.Context, topic string, handler func(ProviderAddResp, Message)) (func(), error) {
	return SubscribeTo[ProviderAddResp](rt, ctx, topic, handler)
}

// PublishProviderRemove publishes a ProviderRemoveMsg and returns routing info for the response.
func PublishProviderRemove(rt Runtime, ctx context.Context, msg ProviderRemoveMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeProviderRemoveResp subscribes to the response topic for a ProviderRemoveMsg command.
func SubscribeProviderRemoveResp(rt Runtime, ctx context.Context, topic string, handler func(ProviderRemoveResp, Message)) (func(), error) {
	return SubscribeTo[ProviderRemoveResp](rt, ctx, topic, handler)
}

// PublishRBACAssign publishes a RBACAssignMsg and returns routing info for the response.
func PublishRBACAssign(rt Runtime, ctx context.Context, msg RBACAssignMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeRBACAssignResp subscribes to the response topic for a RBACAssignMsg command.
func SubscribeRBACAssignResp(rt Runtime, ctx context.Context, topic string, handler func(RBACAssignResp, Message)) (func(), error) {
	return SubscribeTo[RBACAssignResp](rt, ctx, topic, handler)
}

// PublishRBACList publishes a RBACListMsg and returns routing info for the response.
func PublishRBACList(rt Runtime, ctx context.Context, msg RBACListMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeRBACListResp subscribes to the response topic for a RBACListMsg command.
func SubscribeRBACListResp(rt Runtime, ctx context.Context, topic string, handler func(RBACListResp, Message)) (func(), error) {
	return SubscribeTo[RBACListResp](rt, ctx, topic, handler)
}

// PublishRBACRevoke publishes a RBACRevokeMsg and returns routing info for the response.
func PublishRBACRevoke(rt Runtime, ctx context.Context, msg RBACRevokeMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeRBACRevokeResp subscribes to the response topic for a RBACRevokeMsg command.
func SubscribeRBACRevokeResp(rt Runtime, ctx context.Context, topic string, handler func(RBACRevokeResp, Message)) (func(), error) {
	return SubscribeTo[RBACRevokeResp](rt, ctx, topic, handler)
}

// PublishRBACRoles publishes a RBACRolesMsg and returns routing info for the response.
func PublishRBACRoles(rt Runtime, ctx context.Context, msg RBACRolesMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeRBACRolesResp subscribes to the response topic for a RBACRolesMsg command.
func SubscribeRBACRolesResp(rt Runtime, ctx context.Context, topic string, handler func(RBACRolesResp, Message)) (func(), error) {
	return SubscribeTo[RBACRolesResp](rt, ctx, topic, handler)
}

// PublishRegistryHas publishes a RegistryHasMsg and returns routing info for the response.
func PublishRegistryHas(rt Runtime, ctx context.Context, msg RegistryHasMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeRegistryHasResp subscribes to the response topic for a RegistryHasMsg command.
func SubscribeRegistryHasResp(rt Runtime, ctx context.Context, topic string, handler func(RegistryHasResp, Message)) (func(), error) {
	return SubscribeTo[RegistryHasResp](rt, ctx, topic, handler)
}

// PublishRegistryList publishes a RegistryListMsg and returns routing info for the response.
func PublishRegistryList(rt Runtime, ctx context.Context, msg RegistryListMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeRegistryListResp subscribes to the response topic for a RegistryListMsg command.
func SubscribeRegistryListResp(rt Runtime, ctx context.Context, topic string, handler func(RegistryListResp, Message)) (func(), error) {
	return SubscribeTo[RegistryListResp](rt, ctx, topic, handler)
}

// PublishRegistryResolve publishes a RegistryResolveMsg and returns routing info for the response.
func PublishRegistryResolve(rt Runtime, ctx context.Context, msg RegistryResolveMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeRegistryResolveResp subscribes to the response topic for a RegistryResolveMsg command.
func SubscribeRegistryResolveResp(rt Runtime, ctx context.Context, topic string, handler func(RegistryResolveResp, Message)) (func(), error) {
	return SubscribeTo[RegistryResolveResp](rt, ctx, topic, handler)
}

// PublishScheduleCancel publishes a ScheduleCancelMsg and returns routing info for the response.
func PublishScheduleCancel(rt Runtime, ctx context.Context, msg ScheduleCancelMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeScheduleCancelResp subscribes to the response topic for a ScheduleCancelMsg command.
func SubscribeScheduleCancelResp(rt Runtime, ctx context.Context, topic string, handler func(ScheduleCancelResp, Message)) (func(), error) {
	return SubscribeTo[ScheduleCancelResp](rt, ctx, topic, handler)
}

// PublishScheduleCreate publishes a ScheduleCreateMsg and returns routing info for the response.
func PublishScheduleCreate(rt Runtime, ctx context.Context, msg ScheduleCreateMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeScheduleCreateResp subscribes to the response topic for a ScheduleCreateMsg command.
func SubscribeScheduleCreateResp(rt Runtime, ctx context.Context, topic string, handler func(ScheduleCreateResp, Message)) (func(), error) {
	return SubscribeTo[ScheduleCreateResp](rt, ctx, topic, handler)
}

// PublishScheduleList publishes a ScheduleListMsg and returns routing info for the response.
func PublishScheduleList(rt Runtime, ctx context.Context, msg ScheduleListMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeScheduleListResp subscribes to the response topic for a ScheduleListMsg command.
func SubscribeScheduleListResp(rt Runtime, ctx context.Context, topic string, handler func(ScheduleListResp, Message)) (func(), error) {
	return SubscribeTo[ScheduleListResp](rt, ctx, topic, handler)
}

// PublishSecretsDelete publishes a SecretsDeleteMsg and returns routing info for the response.
func PublishSecretsDelete(rt Runtime, ctx context.Context, msg SecretsDeleteMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeSecretsDeleteResp subscribes to the response topic for a SecretsDeleteMsg command.
func SubscribeSecretsDeleteResp(rt Runtime, ctx context.Context, topic string, handler func(SecretsDeleteResp, Message)) (func(), error) {
	return SubscribeTo[SecretsDeleteResp](rt, ctx, topic, handler)
}

// PublishSecretsGet publishes a SecretsGetMsg and returns routing info for the response.
func PublishSecretsGet(rt Runtime, ctx context.Context, msg SecretsGetMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeSecretsGetResp subscribes to the response topic for a SecretsGetMsg command.
func SubscribeSecretsGetResp(rt Runtime, ctx context.Context, topic string, handler func(SecretsGetResp, Message)) (func(), error) {
	return SubscribeTo[SecretsGetResp](rt, ctx, topic, handler)
}

// PublishSecretsList publishes a SecretsListMsg and returns routing info for the response.
func PublishSecretsList(rt Runtime, ctx context.Context, msg SecretsListMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeSecretsListResp subscribes to the response topic for a SecretsListMsg command.
func SubscribeSecretsListResp(rt Runtime, ctx context.Context, topic string, handler func(SecretsListResp, Message)) (func(), error) {
	return SubscribeTo[SecretsListResp](rt, ctx, topic, handler)
}

// PublishSecretsRotate publishes a SecretsRotateMsg and returns routing info for the response.
func PublishSecretsRotate(rt Runtime, ctx context.Context, msg SecretsRotateMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeSecretsRotateResp subscribes to the response topic for a SecretsRotateMsg command.
func SubscribeSecretsRotateResp(rt Runtime, ctx context.Context, topic string, handler func(SecretsRotateResp, Message)) (func(), error) {
	return SubscribeTo[SecretsRotateResp](rt, ctx, topic, handler)
}

// PublishSecretsSet publishes a SecretsSetMsg and returns routing info for the response.
func PublishSecretsSet(rt Runtime, ctx context.Context, msg SecretsSetMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeSecretsSetResp subscribes to the response topic for a SecretsSetMsg command.
func SubscribeSecretsSetResp(rt Runtime, ctx context.Context, topic string, handler func(SecretsSetResp, Message)) (func(), error) {
	return SubscribeTo[SecretsSetResp](rt, ctx, topic, handler)
}

// PublishStorageAdd publishes a StorageAddMsg and returns routing info for the response.
func PublishStorageAdd(rt Runtime, ctx context.Context, msg StorageAddMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeStorageAddResp subscribes to the response topic for a StorageAddMsg command.
func SubscribeStorageAddResp(rt Runtime, ctx context.Context, topic string, handler func(StorageAddResp, Message)) (func(), error) {
	return SubscribeTo[StorageAddResp](rt, ctx, topic, handler)
}

// PublishStorageRemove publishes a StorageRemoveMsg and returns routing info for the response.
func PublishStorageRemove(rt Runtime, ctx context.Context, msg StorageRemoveMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeStorageRemoveResp subscribes to the response topic for a StorageRemoveMsg command.
func SubscribeStorageRemoveResp(rt Runtime, ctx context.Context, topic string, handler func(StorageRemoveResp, Message)) (func(), error) {
	return SubscribeTo[StorageRemoveResp](rt, ctx, topic, handler)
}

// PublishTestRun publishes a TestRunMsg and returns routing info for the response.
func PublishTestRun(rt Runtime, ctx context.Context, msg TestRunMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeTestRunResp subscribes to the response topic for a TestRunMsg command.
func SubscribeTestRunResp(rt Runtime, ctx context.Context, topic string, handler func(TestRunResp, Message)) (func(), error) {
	return SubscribeTo[TestRunResp](rt, ctx, topic, handler)
}

// PublishToolCall publishes a ToolCallMsg and returns routing info for the response.
func PublishToolCall(rt Runtime, ctx context.Context, msg ToolCallMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeToolCallResp subscribes to the response topic for a ToolCallMsg command.
func SubscribeToolCallResp(rt Runtime, ctx context.Context, topic string, handler func(ToolCallResp, Message)) (func(), error) {
	return SubscribeTo[ToolCallResp](rt, ctx, topic, handler)
}

// PublishToolList publishes a ToolListMsg and returns routing info for the response.
func PublishToolList(rt Runtime, ctx context.Context, msg ToolListMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeToolListResp subscribes to the response topic for a ToolListMsg command.
func SubscribeToolListResp(rt Runtime, ctx context.Context, topic string, handler func(ToolListResp, Message)) (func(), error) {
	return SubscribeTo[ToolListResp](rt, ctx, topic, handler)
}

// PublishToolResolve publishes a ToolResolveMsg and returns routing info for the response.
func PublishToolResolve(rt Runtime, ctx context.Context, msg ToolResolveMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeToolResolveResp subscribes to the response topic for a ToolResolveMsg command.
func SubscribeToolResolveResp(rt Runtime, ctx context.Context, topic string, handler func(ToolResolveResp, Message)) (func(), error) {
	return SubscribeTo[ToolResolveResp](rt, ctx, topic, handler)
}

// PublishTraceGet publishes a TraceGetMsg and returns routing info for the response.
func PublishTraceGet(rt Runtime, ctx context.Context, msg TraceGetMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeTraceGetResp subscribes to the response topic for a TraceGetMsg command.
func SubscribeTraceGetResp(rt Runtime, ctx context.Context, topic string, handler func(TraceGetResp, Message)) (func(), error) {
	return SubscribeTo[TraceGetResp](rt, ctx, topic, handler)
}

// PublishTraceList publishes a TraceListMsg and returns routing info for the response.
func PublishTraceList(rt Runtime, ctx context.Context, msg TraceListMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeTraceListResp subscribes to the response topic for a TraceListMsg command.
func SubscribeTraceListResp(rt Runtime, ctx context.Context, topic string, handler func(TraceListResp, Message)) (func(), error) {
	return SubscribeTo[TraceListResp](rt, ctx, topic, handler)
}

// PublishVectorAdd publishes a VectorAddMsg and returns routing info for the response.
func PublishVectorAdd(rt Runtime, ctx context.Context, msg VectorAddMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeVectorAddResp subscribes to the response topic for a VectorAddMsg command.
func SubscribeVectorAddResp(rt Runtime, ctx context.Context, topic string, handler func(VectorAddResp, Message)) (func(), error) {
	return SubscribeTo[VectorAddResp](rt, ctx, topic, handler)
}

// PublishVectorRemove publishes a VectorRemoveMsg and returns routing info for the response.
func PublishVectorRemove(rt Runtime, ctx context.Context, msg VectorRemoveMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeVectorRemoveResp subscribes to the response topic for a VectorRemoveMsg command.
func SubscribeVectorRemoveResp(rt Runtime, ctx context.Context, topic string, handler func(VectorRemoveResp, Message)) (func(), error) {
	return SubscribeTo[VectorRemoveResp](rt, ctx, topic, handler)
}

// PublishWorkflowCancel publishes a WorkflowCancelMsg and returns routing info for the response.
func PublishWorkflowCancel(rt Runtime, ctx context.Context, msg WorkflowCancelMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeWorkflowCancelResp subscribes to the response topic for a WorkflowCancelMsg command.
func SubscribeWorkflowCancelResp(rt Runtime, ctx context.Context, topic string, handler func(WorkflowCancelResp, Message)) (func(), error) {
	return SubscribeTo[WorkflowCancelResp](rt, ctx, topic, handler)
}

// PublishWorkflowList publishes a WorkflowListMsg and returns routing info for the response.
func PublishWorkflowList(rt Runtime, ctx context.Context, msg WorkflowListMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeWorkflowListResp subscribes to the response topic for a WorkflowListMsg command.
func SubscribeWorkflowListResp(rt Runtime, ctx context.Context, topic string, handler func(WorkflowListResp, Message)) (func(), error) {
	return SubscribeTo[WorkflowListResp](rt, ctx, topic, handler)
}

// PublishWorkflowRestart publishes a WorkflowRestartMsg and returns routing info for the response.
func PublishWorkflowRestart(rt Runtime, ctx context.Context, msg WorkflowRestartMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeWorkflowRestartResp subscribes to the response topic for a WorkflowRestartMsg command.
func SubscribeWorkflowRestartResp(rt Runtime, ctx context.Context, topic string, handler func(WorkflowRestartResp, Message)) (func(), error) {
	return SubscribeTo[WorkflowRestartResp](rt, ctx, topic, handler)
}

// PublishWorkflowResume publishes a WorkflowResumeMsg and returns routing info for the response.
func PublishWorkflowResume(rt Runtime, ctx context.Context, msg WorkflowResumeMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeWorkflowResumeResp subscribes to the response topic for a WorkflowResumeMsg command.
func SubscribeWorkflowResumeResp(rt Runtime, ctx context.Context, topic string, handler func(WorkflowResumeResp, Message)) (func(), error) {
	return SubscribeTo[WorkflowResumeResp](rt, ctx, topic, handler)
}

// PublishWorkflowRuns publishes a WorkflowRunsMsg and returns routing info for the response.
func PublishWorkflowRuns(rt Runtime, ctx context.Context, msg WorkflowRunsMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeWorkflowRunsResp subscribes to the response topic for a WorkflowRunsMsg command.
func SubscribeWorkflowRunsResp(rt Runtime, ctx context.Context, topic string, handler func(WorkflowRunsResp, Message)) (func(), error) {
	return SubscribeTo[WorkflowRunsResp](rt, ctx, topic, handler)
}

// PublishWorkflowStart publishes a WorkflowStartMsg and returns routing info for the response.
func PublishWorkflowStart(rt Runtime, ctx context.Context, msg WorkflowStartMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeWorkflowStartResp subscribes to the response topic for a WorkflowStartMsg command.
func SubscribeWorkflowStartResp(rt Runtime, ctx context.Context, topic string, handler func(WorkflowStartResp, Message)) (func(), error) {
	return SubscribeTo[WorkflowStartResp](rt, ctx, topic, handler)
}

// PublishWorkflowStartAsync publishes a WorkflowStartAsyncMsg and returns routing info for the response.
func PublishWorkflowStartAsync(rt Runtime, ctx context.Context, msg WorkflowStartAsyncMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeWorkflowStartAsyncResp subscribes to the response topic for a WorkflowStartAsyncMsg command.
func SubscribeWorkflowStartAsyncResp(rt Runtime, ctx context.Context, topic string, handler func(WorkflowStartAsyncResp, Message)) (func(), error) {
	return SubscribeTo[WorkflowStartAsyncResp](rt, ctx, topic, handler)
}

// PublishWorkflowStatus publishes a WorkflowStatusMsg and returns routing info for the response.
func PublishWorkflowStatus(rt Runtime, ctx context.Context, msg WorkflowStatusMsg, opts ...PublishOption) (PublishResult, error) {
	return Publish(rt, ctx, msg, opts...)
}

// SubscribeWorkflowStatusResp subscribes to the response topic for a WorkflowStatusMsg command.
func SubscribeWorkflowStatusResp(rt Runtime, ctx context.Context, topic string, handler func(WorkflowStatusResp, Message)) (func(), error) {
	return SubscribeTo[WorkflowStatusResp](rt, ctx, topic, handler)
}

// EmitHandlerExhausted fires a HandlerExhaustedEvent event (no response expected).
func EmitHandlerExhausted(rt Runtime, ctx context.Context, msg HandlerExhaustedEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribeHandlerExhausted listens for HandlerExhaustedEvent events.
func SubscribeHandlerExhausted(rt Runtime, ctx context.Context, topic string, handler func(HandlerExhaustedEvent, Message)) (func(), error) {
	return SubscribeTo[HandlerExhaustedEvent](rt, ctx, topic, handler)
}

// EmitHandlerFailed fires a HandlerFailedEvent event (no response expected).
func EmitHandlerFailed(rt Runtime, ctx context.Context, msg HandlerFailedEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribeHandlerFailed listens for HandlerFailedEvent events.
func SubscribeHandlerFailed(rt Runtime, ctx context.Context, topic string, handler func(HandlerFailedEvent, Message)) (func(), error) {
	return SubscribeTo[HandlerFailedEvent](rt, ctx, topic, handler)
}

// EmitKitDeployed fires a KitDeployedEvent event (no response expected).
func EmitKitDeployed(rt Runtime, ctx context.Context, msg KitDeployedEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribeKitDeployed listens for KitDeployedEvent events.
func SubscribeKitDeployed(rt Runtime, ctx context.Context, topic string, handler func(KitDeployedEvent, Message)) (func(), error) {
	return SubscribeTo[KitDeployedEvent](rt, ctx, topic, handler)
}

// EmitKitTeardowned fires a KitTeardownedEvent event (no response expected).
func EmitKitTeardowned(rt Runtime, ctx context.Context, msg KitTeardownedEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribeKitTeardowned listens for KitTeardownedEvent events.
func SubscribeKitTeardowned(rt Runtime, ctx context.Context, topic string, handler func(KitTeardownedEvent, Message)) (func(), error) {
	return SubscribeTo[KitTeardownedEvent](rt, ctx, topic, handler)
}

// EmitPermissionDenied fires a PermissionDeniedEvent event (no response expected).
func EmitPermissionDenied(rt Runtime, ctx context.Context, msg PermissionDeniedEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribePermissionDenied listens for PermissionDeniedEvent events.
func SubscribePermissionDenied(rt Runtime, ctx context.Context, topic string, handler func(PermissionDeniedEvent, Message)) (func(), error) {
	return SubscribeTo[PermissionDeniedEvent](rt, ctx, topic, handler)
}

// EmitPluginRegistered fires a PluginRegisteredEvent event (no response expected).
func EmitPluginRegistered(rt Runtime, ctx context.Context, msg PluginRegisteredEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribePluginRegistered listens for PluginRegisteredEvent events.
func SubscribePluginRegistered(rt Runtime, ctx context.Context, topic string, handler func(PluginRegisteredEvent, Message)) (func(), error) {
	return SubscribeTo[PluginRegisteredEvent](rt, ctx, topic, handler)
}

// EmitPluginStarted fires a PluginStartedEvent event (no response expected).
func EmitPluginStarted(rt Runtime, ctx context.Context, msg PluginStartedEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribePluginStarted listens for PluginStartedEvent events.
func SubscribePluginStarted(rt Runtime, ctx context.Context, topic string, handler func(PluginStartedEvent, Message)) (func(), error) {
	return SubscribeTo[PluginStartedEvent](rt, ctx, topic, handler)
}

// EmitPluginStopped fires a PluginStoppedEvent event (no response expected).
func EmitPluginStopped(rt Runtime, ctx context.Context, msg PluginStoppedEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribePluginStopped listens for PluginStoppedEvent events.
func SubscribePluginStopped(rt Runtime, ctx context.Context, topic string, handler func(PluginStoppedEvent, Message)) (func(), error) {
	return SubscribeTo[PluginStoppedEvent](rt, ctx, topic, handler)
}

// EmitReplyDenied fires a ReplyDeniedEvent event (no response expected).
func EmitReplyDenied(rt Runtime, ctx context.Context, msg ReplyDeniedEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribeReplyDenied listens for ReplyDeniedEvent events.
func SubscribeReplyDenied(rt Runtime, ctx context.Context, topic string, handler func(ReplyDeniedEvent, Message)) (func(), error) {
	return SubscribeTo[ReplyDeniedEvent](rt, ctx, topic, handler)
}

// EmitSecretsAccessed fires a SecretsAccessedEvent event (no response expected).
func EmitSecretsAccessed(rt Runtime, ctx context.Context, msg SecretsAccessedEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribeSecretsAccessed listens for SecretsAccessedEvent events.
func SubscribeSecretsAccessed(rt Runtime, ctx context.Context, topic string, handler func(SecretsAccessedEvent, Message)) (func(), error) {
	return SubscribeTo[SecretsAccessedEvent](rt, ctx, topic, handler)
}

// EmitSecretsDeleted fires a SecretsDeletedEvent event (no response expected).
func EmitSecretsDeleted(rt Runtime, ctx context.Context, msg SecretsDeletedEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribeSecretsDeleted listens for SecretsDeletedEvent events.
func SubscribeSecretsDeleted(rt Runtime, ctx context.Context, topic string, handler func(SecretsDeletedEvent, Message)) (func(), error) {
	return SubscribeTo[SecretsDeletedEvent](rt, ctx, topic, handler)
}

// EmitSecretsRotated fires a SecretsRotatedEvent event (no response expected).
func EmitSecretsRotated(rt Runtime, ctx context.Context, msg SecretsRotatedEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribeSecretsRotated listens for SecretsRotatedEvent events.
func SubscribeSecretsRotated(rt Runtime, ctx context.Context, topic string, handler func(SecretsRotatedEvent, Message)) (func(), error) {
	return SubscribeTo[SecretsRotatedEvent](rt, ctx, topic, handler)
}

// EmitSecretsStored fires a SecretsStoredEvent event (no response expected).
func EmitSecretsStored(rt Runtime, ctx context.Context, msg SecretsStoredEvent) error {
	return Emit(rt, ctx, msg)
}

// SubscribeSecretsStored listens for SecretsStoredEvent events.
func SubscribeSecretsStored(rt Runtime, ctx context.Context, topic string, handler func(SecretsStoredEvent, Message)) (func(), error) {
	return SubscribeTo[SecretsStoredEvent](rt, ctx, topic, handler)
}

