// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit call/emit/subscribe.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// Low-level publish/reply-topic helpers are intentionally not generated; use
// the generic SDK protocol primitives directly when testing transport behavior.
//
// Regenerate with cmd/sdkgen from this repository.
package health

import (
	"context"

	bkmodule "github.com/brainlet/brainkit/module"
	"github.com/brainlet/brainkit/sdk"
)

// CallKitHealth issues a synchronous request-response Call for KitHealthMsg.
func CallKitHealth(rt sdk.CallerRuntime, ctx context.Context, msg KitHealthMsg, opts ...sdk.CallOption) (KitHealthResp, error) {
	return sdk.Call[KitHealthMsg, KitHealthResp](rt, ctx, msg, opts...)
}

// CallKitHealthWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallKitHealthWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg KitHealthMsg, opts ...sdk.CallOption) (KitHealthResp, error) {
	return sdk.CallWithCaller[KitHealthMsg, KitHealthResp](caller, ctx, msg, opts...)
}

