// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit publish/subscribe/call/emit.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// The underlying generic publish/call patterns are unchanged. These wrappers
// just add type safety.
//
// Regenerate with cmd/sdkgen from this repository.
package health

import (
	"context"

	"github.com/brainlet/brainkit/sdk"
)

// PublishKitHealth publishes a KitHealthMsg and returns routing info for the response.
func PublishKitHealth(rt sdk.Runtime, ctx context.Context, msg KitHealthMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeKitHealthResp subscribes to the response topic for a KitHealthMsg command.
func SubscribeKitHealthResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(KitHealthResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[KitHealthResp](rt, ctx, topic, handler)
}

// CallKitHealth issues a synchronous request-response Call for KitHealthMsg.
func CallKitHealth(rt sdk.CallerRuntime, ctx context.Context, msg KitHealthMsg, opts ...sdk.CallOption) (KitHealthResp, error) {
	return sdk.Call[KitHealthMsg, KitHealthResp](rt, ctx, msg, opts...)
}

