// Ported from: packages/ai/src/generate-text/generated-file.ts
package generatetext

import (
	"encoding/base64"
	"sync"
)

// GeneratedFile represents a file generated by the model.
type GeneratedFile interface {
	// Base64 returns the file as a base64 encoded string.
	Base64() string

	// Uint8Array returns the file as a byte slice.
	Bytes() []byte

	// MediaType returns the IANA media type of the file.
	GetMediaType() string
}

// DefaultGeneratedFile implements GeneratedFile with lazy conversion and caching.
type DefaultGeneratedFile struct {
	base64Data *string
	bytesData  []byte
	mediaType  string
	mu         sync.Mutex
}

// NewDefaultGeneratedFile creates a new DefaultGeneratedFile.
// data can be a string (base64) or []byte.
func NewDefaultGeneratedFile(data interface{}, mediaType string) *DefaultGeneratedFile {
	f := &DefaultGeneratedFile{mediaType: mediaType}
	switch d := data.(type) {
	case string:
		f.base64Data = &d
	case []byte:
		f.bytesData = d
	}
	return f
}

// Base64 returns the file as a base64 encoded string, converting from bytes if needed.
func (f *DefaultGeneratedFile) Base64() string {
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.base64Data == nil {
		encoded := base64.StdEncoding.EncodeToString(f.bytesData)
		f.base64Data = &encoded
	}
	return *f.base64Data
}

// Bytes returns the file as a byte slice, converting from base64 if needed.
func (f *DefaultGeneratedFile) Bytes() []byte {
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.bytesData == nil && f.base64Data != nil {
		decoded, err := base64.StdEncoding.DecodeString(*f.base64Data)
		if err == nil {
			f.bytesData = decoded
		}
	}
	return f.bytesData
}

// GetMediaType returns the IANA media type of the file.
func (f *DefaultGeneratedFile) GetMediaType() string {
	return f.mediaType
}

// DefaultGeneratedFileWithType extends DefaultGeneratedFile with a Type field.
type DefaultGeneratedFileWithType struct {
	*DefaultGeneratedFile
	// Type is always "file".
	Type string
}

// NewDefaultGeneratedFileWithType creates a new DefaultGeneratedFileWithType.
func NewDefaultGeneratedFileWithType(data interface{}, mediaType string) *DefaultGeneratedFileWithType {
	return &DefaultGeneratedFileWithType{
		DefaultGeneratedFile: NewDefaultGeneratedFile(data, mediaType),
		Type:                 "file",
	}
}
