// Ported from: packages/openai/src/tool/code-interpreter.ts
package openai

// CodeInterpreterInput is the input schema for the code_interpreter tool.
type CodeInterpreterInput struct {
	// Code is the code to run, or nil if not available.
	Code *string `json:"code,omitempty"`

	// ContainerID is the ID of the container used to run the code.
	ContainerID string `json:"containerId"`
}

// CodeInterpreterOutputItem represents a single output from the code interpreter.
type CodeInterpreterOutputItem struct {
	// Type is either "logs" or "image".
	Type string `json:"type"`

	// Logs is the logs output (when Type is "logs").
	Logs string `json:"logs,omitempty"`

	// URL is the image URL (when Type is "image").
	URL string `json:"url,omitempty"`
}

// CodeInterpreterOutput is the output schema for the code_interpreter tool.
type CodeInterpreterOutput struct {
	// Outputs are the outputs generated by the code interpreter.
	Outputs []CodeInterpreterOutputItem `json:"outputs,omitempty"`
}

// CodeInterpreterArgs contains configuration options for the code_interpreter tool.
type CodeInterpreterArgs struct {
	// Container is the code interpreter container.
	// Can be a container ID string or a struct with file IDs.
	Container interface{} `json:"container,omitempty"`
}

// CodeInterpreterContainerConfig represents a container configuration with file IDs.
type CodeInterpreterContainerConfig struct {
	// FileIDs are uploaded file IDs to make available to the code.
	FileIDs []string `json:"fileIds,omitempty"`
}

// CodeInterpreterToolID is the provider tool ID for code_interpreter.
const CodeInterpreterToolID = "openai.code_interpreter"

// NewCodeInterpreterTool creates a provider tool configuration for the code_interpreter tool.
func NewCodeInterpreterTool(args *CodeInterpreterArgs) map[string]interface{} {
	result := map[string]interface{}{
		"type": "provider",
		"id":   CodeInterpreterToolID,
	}
	if args != nil && args.Container != nil {
		result["container"] = args.Container
	}
	return result
}
