// Ported from: packages/openai/src/tool/apply-patch.ts
package openai

// ApplyPatchOperation represents a file operation for the apply_patch tool.
type ApplyPatchOperation struct {
	// Type is the operation type: "create_file", "delete_file", or "update_file".
	Type string `json:"type"`

	// Path of the file relative to the workspace root.
	Path string `json:"path"`

	// Diff is the unified diff content to apply (for create_file and update_file).
	Diff string `json:"diff,omitempty"`
}

// ApplyPatchInput is the input schema for the apply_patch tool.
type ApplyPatchInput struct {
	// CallID is the unique ID of the apply patch tool call generated by the model.
	CallID string `json:"callId"`

	// Operation is the specific create, delete, or update instruction.
	Operation ApplyPatchOperation `json:"operation"`
}

// ApplyPatchOutput is the output schema for the apply_patch tool.
type ApplyPatchOutput struct {
	// Status is the status of the apply patch tool call output.
	// "completed" or "failed".
	Status string `json:"status"`

	// Output is optional human-readable log text from the apply patch tool.
	Output string `json:"output,omitempty"`
}

// ApplyPatchToolID is the provider tool ID for apply_patch.
const ApplyPatchToolID = "openai.apply_patch"

// NewApplyPatchTool creates a provider tool configuration for the apply_patch tool.
// The apply_patch tool lets GPT-5.1 create, update, and delete files in your
// codebase using structured diffs.
func NewApplyPatchTool() map[string]interface{} {
	return map[string]interface{}{
		"type": "provider",
		"id":   ApplyPatchToolID,
	}
}
