// Ported from: packages/provider-utils/src/types/content-part.ts
package providerutils

// TextPart represents text content in a prompt.
type TextPart struct {
	Type            string          `json:"type"` // "text"
	Text            string          `json:"text"`
	ProviderOptions ProviderOptions `json:"providerOptions,omitempty"`
}

// ImagePart represents image content in a prompt.
type ImagePart struct {
	Type            string          `json:"type"` // "image"
	Image           interface{}     `json:"image"` // DataContent or URL string
	MediaType       string          `json:"mediaType,omitempty"`
	ProviderOptions ProviderOptions `json:"providerOptions,omitempty"`
}

// FilePart represents file content in a prompt.
type FilePart struct {
	Type            string          `json:"type"` // "file"
	Data            interface{}     `json:"data"` // DataContent or URL string
	Filename        string          `json:"filename,omitempty"`
	MediaType       string          `json:"mediaType"`
	ProviderOptions ProviderOptions `json:"providerOptions,omitempty"`
}

// ReasoningPart represents reasoning content in a prompt.
type ReasoningPart struct {
	Type            string          `json:"type"` // "reasoning"
	Text            string          `json:"text"`
	ProviderOptions ProviderOptions `json:"providerOptions,omitempty"`
}

// ToolCallPart represents a tool call content part (usually generated by the AI model).
type ToolCallPart struct {
	Type             string          `json:"type"` // "tool-call"
	ToolCallID       string          `json:"toolCallId"`
	ToolName         string          `json:"toolName"`
	Input            interface{}     `json:"input"`
	ProviderOptions  ProviderOptions `json:"providerOptions,omitempty"`
	ProviderExecuted bool            `json:"providerExecuted,omitempty"`
}

// ToolResultPart represents a tool result content part.
type ToolResultPart struct {
	Type            string           `json:"type"` // "tool-result"
	ToolCallID      string           `json:"toolCallId"`
	ToolName        string           `json:"toolName"`
	Output          ToolResultOutput `json:"output"`
	ProviderOptions ProviderOptions  `json:"providerOptions,omitempty"`
}

// ToolResultOutput represents the output of a tool result.
// Type can be: "text", "json", "execution-denied", "error-text", "error-json", "content".
type ToolResultOutput struct {
	Type            string          `json:"type"`
	Value           interface{}     `json:"value,omitempty"`
	Reason          string          `json:"reason,omitempty"`
	ProviderOptions ProviderOptions `json:"providerOptions,omitempty"`
}

// ToolResultContentItem represents an item in a "content" type ToolResultOutput.
type ToolResultContentItem struct {
	Type            string          `json:"type"` // "text", "media", "file-data", "file-url", "file-id", "image-data", "image-url", "image-file-id", "custom"
	Text            string          `json:"text,omitempty"`
	Data            string          `json:"data,omitempty"`
	MediaType       string          `json:"mediaType,omitempty"`
	Filename        string          `json:"filename,omitempty"`
	URL             string          `json:"url,omitempty"`
	FileID          interface{}     `json:"fileId,omitempty"` // string or map[string]string
	ProviderOptions ProviderOptions `json:"providerOptions,omitempty"`
}
