// binaryen_shim.js — module resolution glue for the esbuild bundle.
// Code generated by gen-bridge. DO NOT EDIT.
//
// All _Binaryen* functions are registered as globals by Go's RegisterBinaryenBridge().
// This shim routes binaryen.X to globalThis.X via a Proxy.

(function() {
  if (typeof self === "undefined") globalThis.self = globalThis;
  if (typeof global === "undefined") globalThis.global = globalThis;

  var binaryenProxy = new Proxy({}, {
    get: function(target, prop) {
      if (typeof prop === "string" && typeof globalThis[prop] !== "undefined") {
        return globalThis[prop];
      }
      // Return a stub function for any unregistered property.
      return function() { return 0; };
    },
    has: function(target, prop) {
      return true; // Claim all properties exist to prevent destructuring failures.
    }
  });

  globalThis.binaryen = binaryenProxy;

  if (typeof globalThis.require === "undefined") {
    globalThis.require = function(name) {
      if (name === "binaryen") return globalThis.binaryen;
      throw new Error("Cannot require module: " + name);
    };
  }
})();
