package asembed

import "github.com/fastschema/qjs"

func registerOpcodeImpls(ctx *qjs.Context, lm *LinearMemory) {
	// Unary ops
	ctx.SetFunc("_BinaryenClzInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoClzInt32()) })
	ctx.SetFunc("_BinaryenCtzInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoCtzInt32()) })
	ctx.SetFunc("_BinaryenPopcntInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoPopcntInt32()) })
	ctx.SetFunc("_BinaryenNegFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoNegFloat32()) })
	ctx.SetFunc("_BinaryenAbsFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoAbsFloat32()) })
	ctx.SetFunc("_BinaryenCeilFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoCeilFloat32()) })
	ctx.SetFunc("_BinaryenFloorFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoFloorFloat32()) })
	ctx.SetFunc("_BinaryenTruncFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoTruncFloat32()) })
	ctx.SetFunc("_BinaryenNearestFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoNearestFloat32()) })
	ctx.SetFunc("_BinaryenSqrtFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoSqrtFloat32()) })
	ctx.SetFunc("_BinaryenEqZInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoEqZInt32()) })
	ctx.SetFunc("_BinaryenClzInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoClzInt64()) })
	ctx.SetFunc("_BinaryenCtzInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoCtzInt64()) })
	ctx.SetFunc("_BinaryenPopcntInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoPopcntInt64()) })
	ctx.SetFunc("_BinaryenNegFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoNegFloat64()) })
	ctx.SetFunc("_BinaryenAbsFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoAbsFloat64()) })
	ctx.SetFunc("_BinaryenCeilFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoCeilFloat64()) })
	ctx.SetFunc("_BinaryenFloorFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoFloorFloat64()) })
	ctx.SetFunc("_BinaryenTruncFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoTruncFloat64()) })
	ctx.SetFunc("_BinaryenNearestFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoNearestFloat64()) })
	ctx.SetFunc("_BinaryenSqrtFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoSqrtFloat64()) })
	ctx.SetFunc("_BinaryenEqZInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoEqZInt64()) })

	// Binary ops - i32
	ctx.SetFunc("_BinaryenAddInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoAddInt32()) })
	ctx.SetFunc("_BinaryenSubInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoSubInt32()) })
	ctx.SetFunc("_BinaryenMulInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoMulInt32()) })
	ctx.SetFunc("_BinaryenDivSInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoDivSInt32()) })
	ctx.SetFunc("_BinaryenDivUInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoDivUInt32()) })
	ctx.SetFunc("_BinaryenRemSInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoRemSInt32()) })
	ctx.SetFunc("_BinaryenRemUInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoRemUInt32()) })
	ctx.SetFunc("_BinaryenAndInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoAndInt32()) })
	ctx.SetFunc("_BinaryenOrInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoOrInt32()) })
	ctx.SetFunc("_BinaryenXorInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoXorInt32()) })
	ctx.SetFunc("_BinaryenShlInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoShlInt32()) })
	ctx.SetFunc("_BinaryenShrSInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoShrSInt32()) })
	ctx.SetFunc("_BinaryenShrUInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoShrUInt32()) })
	ctx.SetFunc("_BinaryenRotLInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoRotLInt32()) })
	ctx.SetFunc("_BinaryenRotRInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoRotRInt32()) })
	ctx.SetFunc("_BinaryenEqInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoEqInt32()) })
	ctx.SetFunc("_BinaryenNeInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoNeInt32()) })
	ctx.SetFunc("_BinaryenLtSInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoLtSInt32()) })
	ctx.SetFunc("_BinaryenLtUInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoLtUInt32()) })
	ctx.SetFunc("_BinaryenLeSInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoLeSInt32()) })
	ctx.SetFunc("_BinaryenLeUInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoLeUInt32()) })
	ctx.SetFunc("_BinaryenGtSInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoGtSInt32()) })
	ctx.SetFunc("_BinaryenGtUInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoGtUInt32()) })
	ctx.SetFunc("_BinaryenGeSInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoGeSInt32()) })
	ctx.SetFunc("_BinaryenGeUInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoGeUInt32()) })

	// Binary ops - i64
	ctx.SetFunc("_BinaryenAddInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoAddInt64()) })
	ctx.SetFunc("_BinaryenSubInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoSubInt64()) })
	ctx.SetFunc("_BinaryenMulInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoMulInt64()) })
	ctx.SetFunc("_BinaryenDivSInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoDivSInt64()) })
	ctx.SetFunc("_BinaryenDivUInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoDivUInt64()) })
	ctx.SetFunc("_BinaryenRemSInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoRemSInt64()) })
	ctx.SetFunc("_BinaryenRemUInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoRemUInt64()) })
	ctx.SetFunc("_BinaryenAndInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoAndInt64()) })
	ctx.SetFunc("_BinaryenOrInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoOrInt64()) })
	ctx.SetFunc("_BinaryenXorInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoXorInt64()) })
	ctx.SetFunc("_BinaryenShlInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoShlInt64()) })
	ctx.SetFunc("_BinaryenShrSInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoShrSInt64()) })
	ctx.SetFunc("_BinaryenShrUInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoShrUInt64()) })
	ctx.SetFunc("_BinaryenRotLInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoRotLInt64()) })
	ctx.SetFunc("_BinaryenRotRInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoRotRInt64()) })
	ctx.SetFunc("_BinaryenEqInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoEqInt64()) })
	ctx.SetFunc("_BinaryenNeInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoNeInt64()) })
	ctx.SetFunc("_BinaryenLtSInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoLtSInt64()) })
	ctx.SetFunc("_BinaryenLtUInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoLtUInt64()) })
	ctx.SetFunc("_BinaryenLeSInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoLeSInt64()) })
	ctx.SetFunc("_BinaryenLeUInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoLeUInt64()) })
	ctx.SetFunc("_BinaryenGtSInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoGtSInt64()) })
	ctx.SetFunc("_BinaryenGtUInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoGtUInt64()) })
	ctx.SetFunc("_BinaryenGeSInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoGeSInt64()) })
	ctx.SetFunc("_BinaryenGeUInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoGeUInt64()) })

	// Binary ops - f32
	ctx.SetFunc("_BinaryenAddFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoAddFloat32()) })
	ctx.SetFunc("_BinaryenSubFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoSubFloat32()) })
	ctx.SetFunc("_BinaryenMulFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoMulFloat32()) })
	ctx.SetFunc("_BinaryenDivFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoDivFloat32()) })
	ctx.SetFunc("_BinaryenCopySignFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoCopySignFloat32()) })
	ctx.SetFunc("_BinaryenMinFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoMinFloat32()) })
	ctx.SetFunc("_BinaryenMaxFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoMaxFloat32()) })
	ctx.SetFunc("_BinaryenEqFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoEqFloat32()) })
	ctx.SetFunc("_BinaryenNeFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoNeFloat32()) })
	ctx.SetFunc("_BinaryenLtFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoLtFloat32()) })
	ctx.SetFunc("_BinaryenLeFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoLeFloat32()) })
	ctx.SetFunc("_BinaryenGtFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoGtFloat32()) })
	ctx.SetFunc("_BinaryenGeFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoGeFloat32()) })

	// Binary ops - f64
	ctx.SetFunc("_BinaryenAddFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoAddFloat64()) })
	ctx.SetFunc("_BinaryenSubFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoSubFloat64()) })
	ctx.SetFunc("_BinaryenMulFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoMulFloat64()) })
	ctx.SetFunc("_BinaryenDivFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoDivFloat64()) })
	ctx.SetFunc("_BinaryenCopySignFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoCopySignFloat64()) })
	ctx.SetFunc("_BinaryenMinFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoMinFloat64()) })
	ctx.SetFunc("_BinaryenMaxFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoMaxFloat64()) })
	ctx.SetFunc("_BinaryenEqFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoEqFloat64()) })
	ctx.SetFunc("_BinaryenNeFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoNeFloat64()) })
	ctx.SetFunc("_BinaryenLtFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoLtFloat64()) })
	ctx.SetFunc("_BinaryenLeFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoLeFloat64()) })
	ctx.SetFunc("_BinaryenGtFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoGtFloat64()) })
	ctx.SetFunc("_BinaryenGeFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoGeFloat64()) })

	// Conversion ops
	ctx.SetFunc("_BinaryenTruncSFloat32ToInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoTruncSFloat32ToInt32()) })
	ctx.SetFunc("_BinaryenTruncSFloat32ToInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoTruncSFloat32ToInt64()) })
	ctx.SetFunc("_BinaryenTruncUFloat32ToInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoTruncUFloat32ToInt32()) })
	ctx.SetFunc("_BinaryenTruncUFloat32ToInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoTruncUFloat32ToInt64()) })
	ctx.SetFunc("_BinaryenTruncSFloat64ToInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoTruncSFloat64ToInt32()) })
	ctx.SetFunc("_BinaryenTruncSFloat64ToInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoTruncSFloat64ToInt64()) })
	ctx.SetFunc("_BinaryenTruncUFloat64ToInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoTruncUFloat64ToInt32()) })
	ctx.SetFunc("_BinaryenTruncUFloat64ToInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoTruncUFloat64ToInt64()) })
	ctx.SetFunc("_BinaryenReinterpretFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoReinterpretFloat32()) })
	ctx.SetFunc("_BinaryenReinterpretFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoReinterpretFloat64()) })
	ctx.SetFunc("_BinaryenConvertSInt32ToFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoConvertSInt32ToFloat32()) })
	ctx.SetFunc("_BinaryenConvertSInt32ToFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoConvertSInt32ToFloat64()) })
	ctx.SetFunc("_BinaryenConvertUInt32ToFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoConvertUInt32ToFloat32()) })
	ctx.SetFunc("_BinaryenConvertUInt32ToFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoConvertUInt32ToFloat64()) })
	ctx.SetFunc("_BinaryenConvertSInt64ToFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoConvertSInt64ToFloat32()) })
	ctx.SetFunc("_BinaryenConvertSInt64ToFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoConvertSInt64ToFloat64()) })
	ctx.SetFunc("_BinaryenConvertUInt64ToFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoConvertUInt64ToFloat32()) })
	ctx.SetFunc("_BinaryenConvertUInt64ToFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoConvertUInt64ToFloat64()) })
	ctx.SetFunc("_BinaryenPromoteFloat32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoPromoteFloat32()) })
	ctx.SetFunc("_BinaryenDemoteFloat64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoDemoteFloat64()) })
	ctx.SetFunc("_BinaryenReinterpretInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoReinterpretInt32()) })
	ctx.SetFunc("_BinaryenReinterpretInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoReinterpretInt64()) })
	ctx.SetFunc("_BinaryenExtendSInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoExtendSInt32()) })
	ctx.SetFunc("_BinaryenExtendUInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoExtendUInt32()) })
	ctx.SetFunc("_BinaryenWrapInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoWrapInt64()) })
	ctx.SetFunc("_BinaryenTruncSatSFloat32ToInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoTruncSatSFloat32ToInt32()) })
	ctx.SetFunc("_BinaryenTruncSatSFloat32ToInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoTruncSatSFloat32ToInt64()) })
	ctx.SetFunc("_BinaryenTruncSatUFloat32ToInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoTruncSatUFloat32ToInt32()) })
	ctx.SetFunc("_BinaryenTruncSatUFloat32ToInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoTruncSatUFloat32ToInt64()) })
	ctx.SetFunc("_BinaryenTruncSatSFloat64ToInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoTruncSatSFloat64ToInt32()) })
	ctx.SetFunc("_BinaryenTruncSatSFloat64ToInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoTruncSatSFloat64ToInt64()) })
	ctx.SetFunc("_BinaryenTruncSatUFloat64ToInt32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoTruncSatUFloat64ToInt32()) })
	ctx.SetFunc("_BinaryenTruncSatUFloat64ToInt64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoTruncSatUFloat64ToInt64()) })

	// Sign extension
	ctx.SetFunc("_BinaryenExtendS8Int32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoExtendS8Int32()) })
	ctx.SetFunc("_BinaryenExtendS16Int32", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoExtendS16Int32()) })
	ctx.SetFunc("_BinaryenExtendS8Int64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoExtendS8Int64()) })
	ctx.SetFunc("_BinaryenExtendS16Int64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoExtendS16Int64()) })
	ctx.SetFunc("_BinaryenExtendS32Int64", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoExtendS32Int64()) })

	// GC/ref ops
	ctx.SetFunc("_BinaryenBrOnCast", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoBrOnCast()) })
	ctx.SetFunc("_BinaryenBrOnCastFail", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoBrOnCastFail()) })
	ctx.SetFunc("_BinaryenRefAsNonNull", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoRefAsNonNull()) })
	ctx.SetFunc("_BinaryenRefAsExternInternalize", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoRefAsExternInternalize()) })
	ctx.SetFunc("_BinaryenRefAsExternExternalize", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoRefAsExternExternalize()) })

	// String ops
	ctx.SetFunc("_BinaryenStringNewLossyUTF8Array", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoStringNewLossyUTF8Array()) })
	ctx.SetFunc("_BinaryenStringNewWTF16Array", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoStringNewWTF16Array()) })
	ctx.SetFunc("_BinaryenStringNewFromCodePoint", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoStringNewFromCodePoint()) })
	ctx.SetFunc("_BinaryenStringMeasureUTF8", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoStringMeasureUTF8()) })
	ctx.SetFunc("_BinaryenStringMeasureWTF16", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoStringMeasureWTF16()) })
	ctx.SetFunc("_BinaryenStringEncodeLossyUTF8Array", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoStringEncodeLossyUTF8Array()) })
	ctx.SetFunc("_BinaryenStringEncodeWTF16Array", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoStringEncodeWTF16Array()) })
	ctx.SetFunc("_BinaryenStringEqEqual", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoStringEqEqual()) })
	ctx.SetFunc("_BinaryenStringEqCompare", func(this *qjs.This) (*qjs.Value, error) { return retI32(this.Context(), cgoStringEqCompare()) })

	// Packed types
	ctx.SetFunc("_BinaryenPackedTypeNotPacked", func(this *qjs.This) (*qjs.Value, error) { return retU32(this.Context(), cgoPackedTypeNotPacked()) })
	ctx.SetFunc("_BinaryenPackedTypeInt8", func(this *qjs.This) (*qjs.Value, error) { return retU32(this.Context(), cgoPackedTypeInt8()) })
	ctx.SetFunc("_BinaryenPackedTypeInt16", func(this *qjs.This) (*qjs.Value, error) { return retU32(this.Context(), cgoPackedTypeInt16()) })

	// Side effects
	ctx.SetFunc("_BinaryenSideEffectNone", func(this *qjs.This) (*qjs.Value, error) { return retU32(this.Context(), cgoSideEffectsNone()) })
	ctx.SetFunc("_BinaryenSideEffectAny", func(this *qjs.This) (*qjs.Value, error) { return retU32(this.Context(), cgoSideEffectsAny()) })
}

func registerFeatureImpls(ctx *qjs.Context, lm *LinearMemory) {
	ctx.SetFunc("_BinaryenFeatureAll", func(this *qjs.This) (*qjs.Value, error) { return retU32(this.Context(), cgoFeatureAll()) })
	ctx.SetFunc("_BinaryenFeatureMVP", func(this *qjs.This) (*qjs.Value, error) { return retU32(this.Context(), cgoFeatureMVP()) })
	ctx.SetFunc("_BinaryenFeatureAtomics", func(this *qjs.This) (*qjs.Value, error) { return retU32(this.Context(), cgoFeatureAtomics()) })
	ctx.SetFunc("_BinaryenFeatureBulkMemory", func(this *qjs.This) (*qjs.Value, error) { return retU32(this.Context(), cgoFeatureBulkMemory()) })
	ctx.SetFunc("_BinaryenFeatureMutableGlobals", func(this *qjs.This) (*qjs.Value, error) { return retU32(this.Context(), cgoFeatureMutableGlobals()) })
	ctx.SetFunc("_BinaryenFeatureNontrappingFPToInt", func(this *qjs.This) (*qjs.Value, error) { return retU32(this.Context(), cgoFeatureNontrappingFPToInt()) })
	ctx.SetFunc("_BinaryenFeatureSignExt", func(this *qjs.This) (*qjs.Value, error) { return retU32(this.Context(), cgoFeatureSignExt()) })
	ctx.SetFunc("_BinaryenFeatureSIMD128", func(this *qjs.This) (*qjs.Value, error) { return retU32(this.Context(), cgoFeatureSIMD128()) })
	ctx.SetFunc("_BinaryenFeatureExceptionHandling", func(this *qjs.This) (*qjs.Value, error) { return retU32(this.Context(), cgoFeatureExceptionHandling()) })
	ctx.SetFunc("_BinaryenFeatureTailCall", func(this *qjs.This) (*qjs.Value, error) { return retU32(this.Context(), cgoFeatureTailCall()) })
	ctx.SetFunc("_BinaryenFeatureReferenceTypes", func(this *qjs.This) (*qjs.Value, error) { return retU32(this.Context(), cgoFeatureReferenceTypes()) })
	ctx.SetFunc("_BinaryenFeatureMultivalue", func(this *qjs.This) (*qjs.Value, error) { return retU32(this.Context(), cgoFeatureMultivalue()) })
	ctx.SetFunc("_BinaryenFeatureGC", func(this *qjs.This) (*qjs.Value, error) { return retU32(this.Context(), cgoFeatureGC()) })
	ctx.SetFunc("_BinaryenFeatureMemory64", func(this *qjs.This) (*qjs.Value, error) { return retU32(this.Context(), cgoFeatureMemory64()) })
	ctx.SetFunc("_BinaryenFeatureStrings", func(this *qjs.This) (*qjs.Value, error) { return retU32(this.Context(), cgoFeatureStrings()) })
	ctx.SetFunc("_BinaryenFeatureMultiMemory", func(this *qjs.This) (*qjs.Value, error) { return retU32(this.Context(), cgoFeatureMultiMemory()) })
}

func registerExprIdImpls(ctx *qjs.Context, lm *LinearMemory) {
	ctx.SetFunc("_BinaryenInvalidId", func(this *qjs.This) (*qjs.Value, error) { return retI(this.Context(), cgoInvalidId()) })
	ctx.SetFunc("_BinaryenNopId", func(this *qjs.This) (*qjs.Value, error) { return retI(this.Context(), cgoNopId()) })
	ctx.SetFunc("_BinaryenBlockId", func(this *qjs.This) (*qjs.Value, error) { return retI(this.Context(), cgoBlockId()) })
	ctx.SetFunc("_BinaryenIfId", func(this *qjs.This) (*qjs.Value, error) { return retI(this.Context(), cgoIfId()) })
	ctx.SetFunc("_BinaryenLoopId", func(this *qjs.This) (*qjs.Value, error) { return retI(this.Context(), cgoLoopId()) })
	ctx.SetFunc("_BinaryenBreakId", func(this *qjs.This) (*qjs.Value, error) { return retI(this.Context(), cgoBreakId()) })
	ctx.SetFunc("_BinaryenSwitchId", func(this *qjs.This) (*qjs.Value, error) { return retI(this.Context(), cgoSwitchId()) })
	ctx.SetFunc("_BinaryenCallId", func(this *qjs.This) (*qjs.Value, error) { return retI(this.Context(), cgoCallId()) })
	ctx.SetFunc("_BinaryenCallIndirectId", func(this *qjs.This) (*qjs.Value, error) { return retI(this.Context(), cgoCallIndirectId()) })
	ctx.SetFunc("_BinaryenLocalGetId", func(this *qjs.This) (*qjs.Value, error) { return retI(this.Context(), cgoLocalGetId()) })
	ctx.SetFunc("_BinaryenLocalSetId", func(this *qjs.This) (*qjs.Value, error) { return retI(this.Context(), cgoLocalSetId()) })
	ctx.SetFunc("_BinaryenGlobalGetId", func(this *qjs.This) (*qjs.Value, error) { return retI(this.Context(), cgoGlobalGetId()) })
	ctx.SetFunc("_BinaryenGlobalSetId", func(this *qjs.This) (*qjs.Value, error) { return retI(this.Context(), cgoGlobalSetId()) })
	ctx.SetFunc("_BinaryenLoadId", func(this *qjs.This) (*qjs.Value, error) { return retI(this.Context(), cgoLoadId()) })
	ctx.SetFunc("_BinaryenStoreId", func(this *qjs.This) (*qjs.Value, error) { return retI(this.Context(), cgoStoreId()) })
	ctx.SetFunc("_BinaryenConstId", func(this *qjs.This) (*qjs.Value, error) { return retI(this.Context(), cgoConstId()) })
	ctx.SetFunc("_BinaryenUnaryId", func(this *qjs.This) (*qjs.Value, error) { return retI(this.Context(), cgoUnaryId()) })
	ctx.SetFunc("_BinaryenBinaryId", func(this *qjs.This) (*qjs.Value, error) { return retI(this.Context(), cgoBinaryId()) })
	ctx.SetFunc("_BinaryenSelectId", func(this *qjs.This) (*qjs.Value, error) { return retI(this.Context(), cgoSelectId()) })
	ctx.SetFunc("_BinaryenDropId", func(this *qjs.This) (*qjs.Value, error) { return retI(this.Context(), cgoDropId()) })
	ctx.SetFunc("_BinaryenReturnId", func(this *qjs.This) (*qjs.Value, error) { return retI(this.Context(), cgoReturnId()) })
	ctx.SetFunc("_BinaryenMemorySizeId", func(this *qjs.This) (*qjs.Value, error) { return retI(this.Context(), cgoMemorySizeId()) })
	ctx.SetFunc("_BinaryenMemoryGrowId", func(this *qjs.This) (*qjs.Value, error) { return retI(this.Context(), cgoMemoryGrowId()) })
	ctx.SetFunc("_BinaryenUnreachableId", func(this *qjs.This) (*qjs.Value, error) { return retI(this.Context(), cgoUnreachableId()) })
}
