package asembed

import quickjs "github.com/buke/quickjs-go"

func registerOpcodeImpls(ctx *quickjs.Context, lm *LinearMemory) {
	// Unary ops
	setFunc(ctx, "_BinaryenClzInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoClzInt32()) })
	setFunc(ctx, "_BinaryenCtzInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoCtzInt32()) })
	setFunc(ctx, "_BinaryenPopcntInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoPopcntInt32()) })
	setFunc(ctx, "_BinaryenNegFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoNegFloat32()) })
	setFunc(ctx, "_BinaryenAbsFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoAbsFloat32()) })
	setFunc(ctx, "_BinaryenCeilFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoCeilFloat32()) })
	setFunc(ctx, "_BinaryenFloorFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoFloorFloat32()) })
	setFunc(ctx, "_BinaryenTruncFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoTruncFloat32()) })
	setFunc(ctx, "_BinaryenNearestFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoNearestFloat32()) })
	setFunc(ctx, "_BinaryenSqrtFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoSqrtFloat32()) })
	setFunc(ctx, "_BinaryenEqZInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoEqZInt32()) })
	setFunc(ctx, "_BinaryenClzInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoClzInt64()) })
	setFunc(ctx, "_BinaryenCtzInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoCtzInt64()) })
	setFunc(ctx, "_BinaryenPopcntInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoPopcntInt64()) })
	setFunc(ctx, "_BinaryenNegFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoNegFloat64()) })
	setFunc(ctx, "_BinaryenAbsFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoAbsFloat64()) })
	setFunc(ctx, "_BinaryenCeilFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoCeilFloat64()) })
	setFunc(ctx, "_BinaryenFloorFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoFloorFloat64()) })
	setFunc(ctx, "_BinaryenTruncFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoTruncFloat64()) })
	setFunc(ctx, "_BinaryenNearestFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoNearestFloat64()) })
	setFunc(ctx, "_BinaryenSqrtFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoSqrtFloat64()) })
	setFunc(ctx, "_BinaryenEqZInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoEqZInt64()) })

	// Binary ops - i32
	setFunc(ctx, "_BinaryenAddInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoAddInt32()) })
	setFunc(ctx, "_BinaryenSubInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoSubInt32()) })
	setFunc(ctx, "_BinaryenMulInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoMulInt32()) })
	setFunc(ctx, "_BinaryenDivSInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoDivSInt32()) })
	setFunc(ctx, "_BinaryenDivUInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoDivUInt32()) })
	setFunc(ctx, "_BinaryenRemSInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoRemSInt32()) })
	setFunc(ctx, "_BinaryenRemUInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoRemUInt32()) })
	setFunc(ctx, "_BinaryenAndInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoAndInt32()) })
	setFunc(ctx, "_BinaryenOrInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoOrInt32()) })
	setFunc(ctx, "_BinaryenXorInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoXorInt32()) })
	setFunc(ctx, "_BinaryenShlInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoShlInt32()) })
	setFunc(ctx, "_BinaryenShrSInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoShrSInt32()) })
	setFunc(ctx, "_BinaryenShrUInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoShrUInt32()) })
	setFunc(ctx, "_BinaryenRotLInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoRotLInt32()) })
	setFunc(ctx, "_BinaryenRotRInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoRotRInt32()) })
	setFunc(ctx, "_BinaryenEqInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoEqInt32()) })
	setFunc(ctx, "_BinaryenNeInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoNeInt32()) })
	setFunc(ctx, "_BinaryenLtSInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoLtSInt32()) })
	setFunc(ctx, "_BinaryenLtUInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoLtUInt32()) })
	setFunc(ctx, "_BinaryenLeSInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoLeSInt32()) })
	setFunc(ctx, "_BinaryenLeUInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoLeUInt32()) })
	setFunc(ctx, "_BinaryenGtSInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoGtSInt32()) })
	setFunc(ctx, "_BinaryenGtUInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoGtUInt32()) })
	setFunc(ctx, "_BinaryenGeSInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoGeSInt32()) })
	setFunc(ctx, "_BinaryenGeUInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoGeUInt32()) })

	// Binary ops - i64
	setFunc(ctx, "_BinaryenAddInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoAddInt64()) })
	setFunc(ctx, "_BinaryenSubInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoSubInt64()) })
	setFunc(ctx, "_BinaryenMulInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoMulInt64()) })
	setFunc(ctx, "_BinaryenDivSInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoDivSInt64()) })
	setFunc(ctx, "_BinaryenDivUInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoDivUInt64()) })
	setFunc(ctx, "_BinaryenRemSInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoRemSInt64()) })
	setFunc(ctx, "_BinaryenRemUInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoRemUInt64()) })
	setFunc(ctx, "_BinaryenAndInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoAndInt64()) })
	setFunc(ctx, "_BinaryenOrInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoOrInt64()) })
	setFunc(ctx, "_BinaryenXorInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoXorInt64()) })
	setFunc(ctx, "_BinaryenShlInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoShlInt64()) })
	setFunc(ctx, "_BinaryenShrSInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoShrSInt64()) })
	setFunc(ctx, "_BinaryenShrUInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoShrUInt64()) })
	setFunc(ctx, "_BinaryenRotLInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoRotLInt64()) })
	setFunc(ctx, "_BinaryenRotRInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoRotRInt64()) })
	setFunc(ctx, "_BinaryenEqInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoEqInt64()) })
	setFunc(ctx, "_BinaryenNeInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoNeInt64()) })
	setFunc(ctx, "_BinaryenLtSInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoLtSInt64()) })
	setFunc(ctx, "_BinaryenLtUInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoLtUInt64()) })
	setFunc(ctx, "_BinaryenLeSInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoLeSInt64()) })
	setFunc(ctx, "_BinaryenLeUInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoLeUInt64()) })
	setFunc(ctx, "_BinaryenGtSInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoGtSInt64()) })
	setFunc(ctx, "_BinaryenGtUInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoGtUInt64()) })
	setFunc(ctx, "_BinaryenGeSInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoGeSInt64()) })
	setFunc(ctx, "_BinaryenGeUInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoGeUInt64()) })

	// Binary ops - f32
	setFunc(ctx, "_BinaryenAddFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoAddFloat32()) })
	setFunc(ctx, "_BinaryenSubFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoSubFloat32()) })
	setFunc(ctx, "_BinaryenMulFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoMulFloat32()) })
	setFunc(ctx, "_BinaryenDivFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoDivFloat32()) })
	setFunc(ctx, "_BinaryenCopySignFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoCopySignFloat32()) })
	setFunc(ctx, "_BinaryenMinFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoMinFloat32()) })
	setFunc(ctx, "_BinaryenMaxFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoMaxFloat32()) })
	setFunc(ctx, "_BinaryenEqFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoEqFloat32()) })
	setFunc(ctx, "_BinaryenNeFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoNeFloat32()) })
	setFunc(ctx, "_BinaryenLtFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoLtFloat32()) })
	setFunc(ctx, "_BinaryenLeFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoLeFloat32()) })
	setFunc(ctx, "_BinaryenGtFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoGtFloat32()) })
	setFunc(ctx, "_BinaryenGeFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoGeFloat32()) })

	// Binary ops - f64
	setFunc(ctx, "_BinaryenAddFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoAddFloat64()) })
	setFunc(ctx, "_BinaryenSubFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoSubFloat64()) })
	setFunc(ctx, "_BinaryenMulFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoMulFloat64()) })
	setFunc(ctx, "_BinaryenDivFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoDivFloat64()) })
	setFunc(ctx, "_BinaryenCopySignFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoCopySignFloat64()) })
	setFunc(ctx, "_BinaryenMinFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoMinFloat64()) })
	setFunc(ctx, "_BinaryenMaxFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoMaxFloat64()) })
	setFunc(ctx, "_BinaryenEqFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoEqFloat64()) })
	setFunc(ctx, "_BinaryenNeFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoNeFloat64()) })
	setFunc(ctx, "_BinaryenLtFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoLtFloat64()) })
	setFunc(ctx, "_BinaryenLeFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoLeFloat64()) })
	setFunc(ctx, "_BinaryenGtFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoGtFloat64()) })
	setFunc(ctx, "_BinaryenGeFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoGeFloat64()) })

	// Conversion ops
	setFunc(ctx, "_BinaryenTruncSFloat32ToInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoTruncSFloat32ToInt32()) })
	setFunc(ctx, "_BinaryenTruncSFloat32ToInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoTruncSFloat32ToInt64()) })
	setFunc(ctx, "_BinaryenTruncUFloat32ToInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoTruncUFloat32ToInt32()) })
	setFunc(ctx, "_BinaryenTruncUFloat32ToInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoTruncUFloat32ToInt64()) })
	setFunc(ctx, "_BinaryenTruncSFloat64ToInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoTruncSFloat64ToInt32()) })
	setFunc(ctx, "_BinaryenTruncSFloat64ToInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoTruncSFloat64ToInt64()) })
	setFunc(ctx, "_BinaryenTruncUFloat64ToInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoTruncUFloat64ToInt32()) })
	setFunc(ctx, "_BinaryenTruncUFloat64ToInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoTruncUFloat64ToInt64()) })
	setFunc(ctx, "_BinaryenReinterpretFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoReinterpretFloat32()) })
	setFunc(ctx, "_BinaryenReinterpretFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoReinterpretFloat64()) })
	setFunc(ctx, "_BinaryenConvertSInt32ToFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoConvertSInt32ToFloat32()) })
	setFunc(ctx, "_BinaryenConvertSInt32ToFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoConvertSInt32ToFloat64()) })
	setFunc(ctx, "_BinaryenConvertUInt32ToFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoConvertUInt32ToFloat32()) })
	setFunc(ctx, "_BinaryenConvertUInt32ToFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoConvertUInt32ToFloat64()) })
	setFunc(ctx, "_BinaryenConvertSInt64ToFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoConvertSInt64ToFloat32()) })
	setFunc(ctx, "_BinaryenConvertSInt64ToFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoConvertSInt64ToFloat64()) })
	setFunc(ctx, "_BinaryenConvertUInt64ToFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoConvertUInt64ToFloat32()) })
	setFunc(ctx, "_BinaryenConvertUInt64ToFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoConvertUInt64ToFloat64()) })
	setFunc(ctx, "_BinaryenPromoteFloat32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoPromoteFloat32()) })
	setFunc(ctx, "_BinaryenDemoteFloat64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoDemoteFloat64()) })
	setFunc(ctx, "_BinaryenReinterpretInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoReinterpretInt32()) })
	setFunc(ctx, "_BinaryenReinterpretInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoReinterpretInt64()) })
	setFunc(ctx, "_BinaryenExtendSInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoExtendSInt32()) })
	setFunc(ctx, "_BinaryenExtendUInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoExtendUInt32()) })
	setFunc(ctx, "_BinaryenWrapInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoWrapInt64()) })
	setFunc(ctx, "_BinaryenTruncSatSFloat32ToInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoTruncSatSFloat32ToInt32()) })
	setFunc(ctx, "_BinaryenTruncSatSFloat32ToInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoTruncSatSFloat32ToInt64()) })
	setFunc(ctx, "_BinaryenTruncSatUFloat32ToInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoTruncSatUFloat32ToInt32()) })
	setFunc(ctx, "_BinaryenTruncSatUFloat32ToInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoTruncSatUFloat32ToInt64()) })
	setFunc(ctx, "_BinaryenTruncSatSFloat64ToInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoTruncSatSFloat64ToInt32()) })
	setFunc(ctx, "_BinaryenTruncSatSFloat64ToInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoTruncSatSFloat64ToInt64()) })
	setFunc(ctx, "_BinaryenTruncSatUFloat64ToInt32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoTruncSatUFloat64ToInt32()) })
	setFunc(ctx, "_BinaryenTruncSatUFloat64ToInt64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoTruncSatUFloat64ToInt64()) })

	// Sign extension
	setFunc(ctx, "_BinaryenExtendS8Int32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoExtendS8Int32()) })
	setFunc(ctx, "_BinaryenExtendS16Int32", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoExtendS16Int32()) })
	setFunc(ctx, "_BinaryenExtendS8Int64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoExtendS8Int64()) })
	setFunc(ctx, "_BinaryenExtendS16Int64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoExtendS16Int64()) })
	setFunc(ctx, "_BinaryenExtendS32Int64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoExtendS32Int64()) })

	// GC/ref ops
	setFunc(ctx, "_BinaryenBrOnCast", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoBrOnCast()) })
	setFunc(ctx, "_BinaryenBrOnCastFail", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoBrOnCastFail()) })
	setFunc(ctx, "_BinaryenRefAsNonNull", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoRefAsNonNull()) })
	setFunc(ctx, "_BinaryenRefAsExternInternalize", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoRefAsExternInternalize()) })
	setFunc(ctx, "_BinaryenRefAsExternExternalize", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoRefAsExternExternalize()) })

	// String ops
	setFunc(ctx, "_BinaryenStringNewLossyUTF8Array", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoStringNewLossyUTF8Array()) })
	setFunc(ctx, "_BinaryenStringNewWTF16Array", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoStringNewWTF16Array()) })
	setFunc(ctx, "_BinaryenStringNewFromCodePoint", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoStringNewFromCodePoint()) })
	setFunc(ctx, "_BinaryenStringMeasureUTF8", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoStringMeasureUTF8()) })
	setFunc(ctx, "_BinaryenStringMeasureWTF16", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoStringMeasureWTF16()) })
	setFunc(ctx, "_BinaryenStringEncodeLossyUTF8Array", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoStringEncodeLossyUTF8Array()) })
	setFunc(ctx, "_BinaryenStringEncodeWTF16Array", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoStringEncodeWTF16Array()) })
	setFunc(ctx, "_BinaryenStringEqEqual", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoStringEqEqual()) })
	setFunc(ctx, "_BinaryenStringEqCompare", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI32(c, cgoStringEqCompare()) })

	// Packed types
	setFunc(ctx, "_BinaryenPackedTypeNotPacked", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retU32(c, cgoPackedTypeNotPacked()) })
	setFunc(ctx, "_BinaryenPackedTypeInt8", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retU32(c, cgoPackedTypeInt8()) })
	setFunc(ctx, "_BinaryenPackedTypeInt16", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retU32(c, cgoPackedTypeInt16()) })

	// Side effects
	setFunc(ctx, "_BinaryenSideEffectNone", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retU32(c, cgoSideEffectsNone()) })
	setFunc(ctx, "_BinaryenSideEffectAny", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retU32(c, cgoSideEffectsAny()) })
}

func registerFeatureImpls(ctx *quickjs.Context, lm *LinearMemory) {
	setFunc(ctx, "_BinaryenFeatureAll", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retU32(c, cgoFeatureAll()) })
	setFunc(ctx, "_BinaryenFeatureMVP", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retU32(c, cgoFeatureMVP()) })
	setFunc(ctx, "_BinaryenFeatureAtomics", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retU32(c, cgoFeatureAtomics()) })
	setFunc(ctx, "_BinaryenFeatureBulkMemory", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retU32(c, cgoFeatureBulkMemory()) })
	setFunc(ctx, "_BinaryenFeatureMutableGlobals", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retU32(c, cgoFeatureMutableGlobals()) })
	setFunc(ctx, "_BinaryenFeatureNontrappingFPToInt", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retU32(c, cgoFeatureNontrappingFPToInt()) })
	setFunc(ctx, "_BinaryenFeatureSignExt", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retU32(c, cgoFeatureSignExt()) })
	setFunc(ctx, "_BinaryenFeatureSIMD128", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retU32(c, cgoFeatureSIMD128()) })
	setFunc(ctx, "_BinaryenFeatureExceptionHandling", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retU32(c, cgoFeatureExceptionHandling()) })
	setFunc(ctx, "_BinaryenFeatureTailCall", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retU32(c, cgoFeatureTailCall()) })
	setFunc(ctx, "_BinaryenFeatureReferenceTypes", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retU32(c, cgoFeatureReferenceTypes()) })
	setFunc(ctx, "_BinaryenFeatureMultivalue", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retU32(c, cgoFeatureMultivalue()) })
	setFunc(ctx, "_BinaryenFeatureGC", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retU32(c, cgoFeatureGC()) })
	setFunc(ctx, "_BinaryenFeatureMemory64", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retU32(c, cgoFeatureMemory64()) })
	setFunc(ctx, "_BinaryenFeatureStrings", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retU32(c, cgoFeatureStrings()) })
	setFunc(ctx, "_BinaryenFeatureMultiMemory", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retU32(c, cgoFeatureMultiMemory()) })
}

func registerExprIdImpls(ctx *quickjs.Context, lm *LinearMemory) {
	setFunc(ctx, "_BinaryenInvalidId", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI(c, cgoInvalidId()) })
	setFunc(ctx, "_BinaryenNopId", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI(c, cgoNopId()) })
	setFunc(ctx, "_BinaryenBlockId", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI(c, cgoBlockId()) })
	setFunc(ctx, "_BinaryenIfId", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI(c, cgoIfId()) })
	setFunc(ctx, "_BinaryenLoopId", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI(c, cgoLoopId()) })
	setFunc(ctx, "_BinaryenBreakId", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI(c, cgoBreakId()) })
	setFunc(ctx, "_BinaryenSwitchId", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI(c, cgoSwitchId()) })
	setFunc(ctx, "_BinaryenCallId", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI(c, cgoCallId()) })
	setFunc(ctx, "_BinaryenCallIndirectId", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI(c, cgoCallIndirectId()) })
	setFunc(ctx, "_BinaryenLocalGetId", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI(c, cgoLocalGetId()) })
	setFunc(ctx, "_BinaryenLocalSetId", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI(c, cgoLocalSetId()) })
	setFunc(ctx, "_BinaryenGlobalGetId", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI(c, cgoGlobalGetId()) })
	setFunc(ctx, "_BinaryenGlobalSetId", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI(c, cgoGlobalSetId()) })
	setFunc(ctx, "_BinaryenLoadId", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI(c, cgoLoadId()) })
	setFunc(ctx, "_BinaryenStoreId", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI(c, cgoStoreId()) })
	setFunc(ctx, "_BinaryenConstId", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI(c, cgoConstId()) })
	setFunc(ctx, "_BinaryenUnaryId", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI(c, cgoUnaryId()) })
	setFunc(ctx, "_BinaryenBinaryId", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI(c, cgoBinaryId()) })
	setFunc(ctx, "_BinaryenSelectId", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI(c, cgoSelectId()) })
	setFunc(ctx, "_BinaryenDropId", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI(c, cgoDropId()) })
	setFunc(ctx, "_BinaryenReturnId", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI(c, cgoReturnId()) })
	setFunc(ctx, "_BinaryenMemorySizeId", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI(c, cgoMemorySizeId()) })
	setFunc(ctx, "_BinaryenMemoryGrowId", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI(c, cgoMemoryGrowId()) })
	setFunc(ctx, "_BinaryenUnreachableId", func(c *quickjs.Context, args []*quickjs.Value) *quickjs.Value { return retI(c, cgoUnreachableId()) })
}
