// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit call/emit/subscribe.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// Low-level publish/reply-topic helpers are intentionally not generated; use
// the generic SDK protocol primitives directly when testing transport behavior.
//
// Regenerate with cmd/sdkgen from this repository.
package registrymsg

import (
	"context"

	bkmodule "github.com/brainlet/brainkit/module"
	"github.com/brainlet/brainkit/sdk"
)

// CallProviderAdd issues a synchronous request-response Call for ProviderAddMsg.
func CallProviderAdd(rt sdk.CallerRuntime, ctx context.Context, msg ProviderAddMsg, opts ...sdk.CallOption) (ProviderAddResp, error) {
	return sdk.Call[ProviderAddMsg, ProviderAddResp](rt, ctx, msg, opts...)
}

// CallProviderAddWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallProviderAddWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg ProviderAddMsg, opts ...sdk.CallOption) (ProviderAddResp, error) {
	return sdk.CallWithCaller[ProviderAddMsg, ProviderAddResp](caller, ctx, msg, opts...)
}

// CallProviderRemove issues a synchronous request-response Call for ProviderRemoveMsg.
func CallProviderRemove(rt sdk.CallerRuntime, ctx context.Context, msg ProviderRemoveMsg, opts ...sdk.CallOption) (ProviderRemoveResp, error) {
	return sdk.Call[ProviderRemoveMsg, ProviderRemoveResp](rt, ctx, msg, opts...)
}

// CallProviderRemoveWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallProviderRemoveWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg ProviderRemoveMsg, opts ...sdk.CallOption) (ProviderRemoveResp, error) {
	return sdk.CallWithCaller[ProviderRemoveMsg, ProviderRemoveResp](caller, ctx, msg, opts...)
}

// CallRegistryHas issues a synchronous request-response Call for RegistryHasMsg.
func CallRegistryHas(rt sdk.CallerRuntime, ctx context.Context, msg RegistryHasMsg, opts ...sdk.CallOption) (RegistryHasResp, error) {
	return sdk.Call[RegistryHasMsg, RegistryHasResp](rt, ctx, msg, opts...)
}

// CallRegistryHasWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallRegistryHasWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg RegistryHasMsg, opts ...sdk.CallOption) (RegistryHasResp, error) {
	return sdk.CallWithCaller[RegistryHasMsg, RegistryHasResp](caller, ctx, msg, opts...)
}

// CallRegistryList issues a synchronous request-response Call for RegistryListMsg.
func CallRegistryList(rt sdk.CallerRuntime, ctx context.Context, msg RegistryListMsg, opts ...sdk.CallOption) (RegistryListResp, error) {
	return sdk.Call[RegistryListMsg, RegistryListResp](rt, ctx, msg, opts...)
}

// CallRegistryListWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallRegistryListWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg RegistryListMsg, opts ...sdk.CallOption) (RegistryListResp, error) {
	return sdk.CallWithCaller[RegistryListMsg, RegistryListResp](caller, ctx, msg, opts...)
}

// CallRegistryResolve issues a synchronous request-response Call for RegistryResolveMsg.
func CallRegistryResolve(rt sdk.CallerRuntime, ctx context.Context, msg RegistryResolveMsg, opts ...sdk.CallOption) (RegistryResolveResp, error) {
	return sdk.Call[RegistryResolveMsg, RegistryResolveResp](rt, ctx, msg, opts...)
}

// CallRegistryResolveWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallRegistryResolveWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg RegistryResolveMsg, opts ...sdk.CallOption) (RegistryResolveResp, error) {
	return sdk.CallWithCaller[RegistryResolveMsg, RegistryResolveResp](caller, ctx, msg, opts...)
}

// CallStorageAdd issues a synchronous request-response Call for StorageAddMsg.
func CallStorageAdd(rt sdk.CallerRuntime, ctx context.Context, msg StorageAddMsg, opts ...sdk.CallOption) (StorageAddResp, error) {
	return sdk.Call[StorageAddMsg, StorageAddResp](rt, ctx, msg, opts...)
}

// CallStorageAddWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallStorageAddWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg StorageAddMsg, opts ...sdk.CallOption) (StorageAddResp, error) {
	return sdk.CallWithCaller[StorageAddMsg, StorageAddResp](caller, ctx, msg, opts...)
}

// CallStorageRemove issues a synchronous request-response Call for StorageRemoveMsg.
func CallStorageRemove(rt sdk.CallerRuntime, ctx context.Context, msg StorageRemoveMsg, opts ...sdk.CallOption) (StorageRemoveResp, error) {
	return sdk.Call[StorageRemoveMsg, StorageRemoveResp](rt, ctx, msg, opts...)
}

// CallStorageRemoveWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallStorageRemoveWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg StorageRemoveMsg, opts ...sdk.CallOption) (StorageRemoveResp, error) {
	return sdk.CallWithCaller[StorageRemoveMsg, StorageRemoveResp](caller, ctx, msg, opts...)
}

// CallVectorAdd issues a synchronous request-response Call for VectorAddMsg.
func CallVectorAdd(rt sdk.CallerRuntime, ctx context.Context, msg VectorAddMsg, opts ...sdk.CallOption) (VectorAddResp, error) {
	return sdk.Call[VectorAddMsg, VectorAddResp](rt, ctx, msg, opts...)
}

// CallVectorAddWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallVectorAddWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg VectorAddMsg, opts ...sdk.CallOption) (VectorAddResp, error) {
	return sdk.CallWithCaller[VectorAddMsg, VectorAddResp](caller, ctx, msg, opts...)
}

// CallVectorRemove issues a synchronous request-response Call for VectorRemoveMsg.
func CallVectorRemove(rt sdk.CallerRuntime, ctx context.Context, msg VectorRemoveMsg, opts ...sdk.CallOption) (VectorRemoveResp, error) {
	return sdk.Call[VectorRemoveMsg, VectorRemoveResp](rt, ctx, msg, opts...)
}

// CallVectorRemoveWithCaller issues a synchronous request-response Call through a narrow RequestCaller.
func CallVectorRemoveWithCaller(caller bkmodule.RequestCaller, ctx context.Context, msg VectorRemoveMsg, opts ...sdk.CallOption) (VectorRemoveResp, error) {
	return sdk.CallWithCaller[VectorRemoveMsg, VectorRemoveResp](caller, ctx, msg, opts...)
}

