// Code generated by cmd/sdkgen. DO NOT EDIT.
//
// Typed wrappers for Brainkit publish/subscribe/call/emit.
// These handle the Msg→Resp type pairing so callers don't need to remember
// which response type matches which message type.
//
// The underlying generic publish/call patterns are unchanged. These wrappers
// just add type safety.
//
// Regenerate with cmd/sdkgen from this repository.
package registrymsg

import (
	"context"

	"github.com/brainlet/brainkit/sdk"
)

// PublishProviderAdd publishes a ProviderAddMsg and returns routing info for the response.
func PublishProviderAdd(rt sdk.Runtime, ctx context.Context, msg ProviderAddMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeProviderAddResp subscribes to the response topic for a ProviderAddMsg command.
func SubscribeProviderAddResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(ProviderAddResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[ProviderAddResp](rt, ctx, topic, handler)
}

// CallProviderAdd issues a synchronous request-response Call for ProviderAddMsg.
func CallProviderAdd(rt sdk.CallerRuntime, ctx context.Context, msg ProviderAddMsg, opts ...sdk.CallOption) (ProviderAddResp, error) {
	return sdk.Call[ProviderAddMsg, ProviderAddResp](rt, ctx, msg, opts...)
}

// PublishProviderRemove publishes a ProviderRemoveMsg and returns routing info for the response.
func PublishProviderRemove(rt sdk.Runtime, ctx context.Context, msg ProviderRemoveMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeProviderRemoveResp subscribes to the response topic for a ProviderRemoveMsg command.
func SubscribeProviderRemoveResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(ProviderRemoveResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[ProviderRemoveResp](rt, ctx, topic, handler)
}

// CallProviderRemove issues a synchronous request-response Call for ProviderRemoveMsg.
func CallProviderRemove(rt sdk.CallerRuntime, ctx context.Context, msg ProviderRemoveMsg, opts ...sdk.CallOption) (ProviderRemoveResp, error) {
	return sdk.Call[ProviderRemoveMsg, ProviderRemoveResp](rt, ctx, msg, opts...)
}

// PublishRegistryHas publishes a RegistryHasMsg and returns routing info for the response.
func PublishRegistryHas(rt sdk.Runtime, ctx context.Context, msg RegistryHasMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeRegistryHasResp subscribes to the response topic for a RegistryHasMsg command.
func SubscribeRegistryHasResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(RegistryHasResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[RegistryHasResp](rt, ctx, topic, handler)
}

// CallRegistryHas issues a synchronous request-response Call for RegistryHasMsg.
func CallRegistryHas(rt sdk.CallerRuntime, ctx context.Context, msg RegistryHasMsg, opts ...sdk.CallOption) (RegistryHasResp, error) {
	return sdk.Call[RegistryHasMsg, RegistryHasResp](rt, ctx, msg, opts...)
}

// PublishRegistryList publishes a RegistryListMsg and returns routing info for the response.
func PublishRegistryList(rt sdk.Runtime, ctx context.Context, msg RegistryListMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeRegistryListResp subscribes to the response topic for a RegistryListMsg command.
func SubscribeRegistryListResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(RegistryListResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[RegistryListResp](rt, ctx, topic, handler)
}

// CallRegistryList issues a synchronous request-response Call for RegistryListMsg.
func CallRegistryList(rt sdk.CallerRuntime, ctx context.Context, msg RegistryListMsg, opts ...sdk.CallOption) (RegistryListResp, error) {
	return sdk.Call[RegistryListMsg, RegistryListResp](rt, ctx, msg, opts...)
}

// PublishRegistryResolve publishes a RegistryResolveMsg and returns routing info for the response.
func PublishRegistryResolve(rt sdk.Runtime, ctx context.Context, msg RegistryResolveMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeRegistryResolveResp subscribes to the response topic for a RegistryResolveMsg command.
func SubscribeRegistryResolveResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(RegistryResolveResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[RegistryResolveResp](rt, ctx, topic, handler)
}

// CallRegistryResolve issues a synchronous request-response Call for RegistryResolveMsg.
func CallRegistryResolve(rt sdk.CallerRuntime, ctx context.Context, msg RegistryResolveMsg, opts ...sdk.CallOption) (RegistryResolveResp, error) {
	return sdk.Call[RegistryResolveMsg, RegistryResolveResp](rt, ctx, msg, opts...)
}

// PublishStorageAdd publishes a StorageAddMsg and returns routing info for the response.
func PublishStorageAdd(rt sdk.Runtime, ctx context.Context, msg StorageAddMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeStorageAddResp subscribes to the response topic for a StorageAddMsg command.
func SubscribeStorageAddResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(StorageAddResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[StorageAddResp](rt, ctx, topic, handler)
}

// CallStorageAdd issues a synchronous request-response Call for StorageAddMsg.
func CallStorageAdd(rt sdk.CallerRuntime, ctx context.Context, msg StorageAddMsg, opts ...sdk.CallOption) (StorageAddResp, error) {
	return sdk.Call[StorageAddMsg, StorageAddResp](rt, ctx, msg, opts...)
}

// PublishStorageRemove publishes a StorageRemoveMsg and returns routing info for the response.
func PublishStorageRemove(rt sdk.Runtime, ctx context.Context, msg StorageRemoveMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeStorageRemoveResp subscribes to the response topic for a StorageRemoveMsg command.
func SubscribeStorageRemoveResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(StorageRemoveResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[StorageRemoveResp](rt, ctx, topic, handler)
}

// CallStorageRemove issues a synchronous request-response Call for StorageRemoveMsg.
func CallStorageRemove(rt sdk.CallerRuntime, ctx context.Context, msg StorageRemoveMsg, opts ...sdk.CallOption) (StorageRemoveResp, error) {
	return sdk.Call[StorageRemoveMsg, StorageRemoveResp](rt, ctx, msg, opts...)
}

// PublishVectorAdd publishes a VectorAddMsg and returns routing info for the response.
func PublishVectorAdd(rt sdk.Runtime, ctx context.Context, msg VectorAddMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeVectorAddResp subscribes to the response topic for a VectorAddMsg command.
func SubscribeVectorAddResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(VectorAddResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[VectorAddResp](rt, ctx, topic, handler)
}

// CallVectorAdd issues a synchronous request-response Call for VectorAddMsg.
func CallVectorAdd(rt sdk.CallerRuntime, ctx context.Context, msg VectorAddMsg, opts ...sdk.CallOption) (VectorAddResp, error) {
	return sdk.Call[VectorAddMsg, VectorAddResp](rt, ctx, msg, opts...)
}

// PublishVectorRemove publishes a VectorRemoveMsg and returns routing info for the response.
func PublishVectorRemove(rt sdk.Runtime, ctx context.Context, msg VectorRemoveMsg, opts ...sdk.PublishOption) (sdk.PublishResult, error) {
	return sdk.Publish(rt, ctx, msg, opts...)
}

// SubscribeVectorRemoveResp subscribes to the response topic for a VectorRemoveMsg command.
func SubscribeVectorRemoveResp(rt sdk.Runtime, ctx context.Context, topic string, handler func(VectorRemoveResp, sdk.Message)) (func(), error) {
	return sdk.SubscribeTo[VectorRemoveResp](rt, ctx, topic, handler)
}

// CallVectorRemove issues a synchronous request-response Call for VectorRemoveMsg.
func CallVectorRemove(rt sdk.CallerRuntime, ctx context.Context, msg VectorRemoveMsg, opts ...sdk.CallOption) (VectorRemoveResp, error) {
	return sdk.Call[VectorRemoveMsg, VectorRemoveResp](rt, ctx, msg, opts...)
}

